yast/yast-storage-ng

README.md

For a preview, see https://github.com/ancorgs/yast-storage-ng/tree/readme

README: badges and more accurate description

---

src/lib/storage/planned_volumes_list.rb

To make this easier
```ruby
def needed_partitions
volumes = super
volumes << efi_volume if efi_partition_needed?
volumes
end
```

Add push (<<) method to PlannedVolumesList

---

src/lib/storage/boot_requirements_strategies/base.rb
src/lib/storage/planned_volume.rb
src/lib/storage/planned_volumes_list.rb
src/lib/storage/proposal.rb
src/lib/storage/proposal/partition_creator.rb
src/lib/storage/proposal/volumes_generator.rb
test/boot_requirements_checker_test.rb
test/planned_volumes_list_test.rb
test/proposal/partition_creator_test.rb

Missing documentation and tests.
Now the previous (already merged) PR should make more sense. The plan is that some volumes can request to be in a particular disk (the only use-case now is that they request to be in `settings.root_device`).

Missing parts of new algorithm

---

doc/boot-partition.md

LoPAPR is basically a modernized CHRP

added reference to LoPAPR spec

---

src/lib/storage/boot_requirements_strategies/uefi.rb
src/lib/storage/disk_analyzer.rb
src/lib/storage/planned_volume.rb
src/lib/storage/proposal/devicegraph_generator.rb
src/lib/storage/proposal/partition_creator.rb
src/lib/storage/proposal/space_maker.rb
src/lib/storage/proposal/volumes_generator.rb
test/boot_requirements_checker_test.rb
test/data/output/multi-linux-pc-sep-home.yml
test/data/output/multi-linux-pc.yml
test/data/output/windows-linux-multiboot-pc-sep-home.yml
test/data/output/windows-linux-multiboot-pc.yml
test/proposal/partition_creator_test.rb
test/proposal/space_maker_test.rb
test/proposal/volumes_generator_test.rb
test/proposal_test.rb
test/storage_helpers.rb

General mechanism to reuse partitions including working scenarios with swap and EFI.

Reusing partitions

---

src/examples/boot_req_checker_demo.rb
src/lib/storage/boot_requirements_checker.rb
src/lib/storage/boot_requirements_strategies/base.rb
src/lib/storage/boot_requirements_strategies/legacy.rb
src/lib/storage/disk_analyzer.rb
src/lib/storage/patches.rb
src/lib/storage/proposal.rb
src/lib/storage/refinements.rb
src/lib/storage/refinements/disk.rb
test/boot_requirements_checker_test.rb

- I had to add #device_by_name to DiskAnalyzer to get the root device object
- there's still the unsolved problem where to create the partition table for a blank disk

implement legacy strategy

---

src/lib/storage/free_disk_space.rb
src/lib/storage/planned_volumes_list.rb
src/lib/storage/proposal.rb
src/lib/storage/proposal/assigned_space.rb
src/lib/storage/proposal/devicegraph_generator.rb
src/lib/storage/proposal/partition_creator.rb
src/lib/storage/proposal/settings.rb
src/lib/storage/proposal/space_distribution.rb
src/lib/storage/proposal/space_maker.rb
src/lib/storage/yaml_writer.rb
test/data/devicegraphs/multi-linux-pc.yml
test/data/devicegraphs/output/multi-linux-pc-sep-home.yml
test/data/devicegraphs/space_22_used_extended.yml
test/data/devicegraphs/spaces_2_10_two_disks.yml
test/data/devicegraphs/spaces_3_8_two_disks.yml
test/data/devicegraphs/spaces_4_4.yml
test/data/devicegraphs/spaces_5_1_two_disks.yml
test/data/devicegraphs/spaces_5_3.yml
test/data/devicegraphs/spaces_5_3_extended.yml
test/data/devicegraphs/spaces_5_3_used_extended.yml
test/data/devicegraphs/spaces_5_3_used_extended_alt.yml
test/data/devicegraphs/spaces_5_6_8_10.yml
test/proposal/partition_creator_test.rb
test/proposal/space_distribution_test.rb
test/proposal/space_maker_test.rb
test/proposal_test.rb
test/support/storage_helpers.rb

This closes #51 
This includes a working implementation of the idea sketched in #51. With tests for many situations including all kind of crazy combinations of extended and primary partitions.
There are still some TODOs about updating documentation of some methods.
We need to rethink SpaceMaker a little bit to make it slightly smarter. After that, we definitely need to rethink its unit tests.
It would also be nice to add more and better unit tests for DevicegraphGenerator... but we need to stop at some point. :smile: 
It's recommended to review it by individual commits. Taking a look to the tests for the new/changed classes in advance to checking the code can also be useful.

Working code to use multiple spaces

---

src/lib/storage/free_disk_space.rb
test/data/devicegraphs/double-windows-pc.yml
test/data/devicegraphs/space_22.yml
test/data/devicegraphs/space_22_extended.yml
test/data/devicegraphs/space_22_used_extended.yml
test/data/devicegraphs/swaps.yml
test/proposal/partition_creator_test.rb
test/proposal_test.rb

This substitutes #65 now that new_new_libstorage is already merged into master

 More fixes for the alignment pull request

---

src/lib/storage/proposal/space_maker.rb
test/data/devicegraphs/multi-linux-pc.yml
test/data/devicegraphs/output/multi-linux-pc-sep-home.yml
test/data/devicegraphs/output/multi-linux-pc.yml
test/proposal/space_maker_test.rb

* It honors volume's disk restrictions (don't waste time freeing space in the wrong disk)
* It tries to resize Windows partitions before deleting them
* Much better tests

Smarter SpaceMaker with enhanced tests 

---

src/lib/storage/planned_volumes_list.rb
src/lib/storage/proposal/space_distribution.rb
test/proposal/space_maker_test.rb

Hijacking the pull request to also include some PlannedVolumesList details I had in mind.

Ensure stable sorting when comparing space distributions

---

doc/boot-requirements.md
rakelib/doc_bootspecs.rake
src/tools/md_formatter.rb

- added rspec formatter creating markdown
- added rake task creating boot requirements as MD file

automatically create boot requirements document

---

.rubocop.yml
src/lib/expert_partitioner/dialogs/create_partition.rb
src/lib/expert_partitioner/main_dialog.rb
src/lib/expert_partitioner/tab_views/lvm_vg/lvm_lvs.rb
src/lib/expert_partitioner/tree.rb
src/lib/expert_partitioner/tree_views/all.rb
src/lib/expert_partitioner/tree_views/bcache.rb
src/lib/expert_partitioner/tree_views/bcache_cset.rb
src/lib/expert_partitioner/tree_views/bcache_csets.rb
src/lib/expert_partitioner/tree_views/bcaches.rb
src/lib/expert_partitioner/tree_views/luks.rb
src/lib/expert_partitioner/tree_views/lukses.rb
src/lib/storage/extensions.rb

This is still tech preview code.

- show more information for lvm lv, luks and bcache

---

.gitignore
src/lib/storage/yaml_writer.rb
test/yaml_writer_test.rb

For https://trello.com/c/PeiZJJrd/338-3-yast2-storage-ng-lvm-support-yaml-reader-writer.

- added support for lvm in yaml writer

---

src/lib/storage/abstract_device_factory.rb
src/lib/storage/fake_device_factory.rb
test/fake_device_factory_test.rb

For https://trello.com/c/PeiZJJrd/338-3-yast2-storage-ng-lvm-support-yaml-reader-writer.

- added support for lvm in yaml reader

---

doc/fake-devicegraphs-yaml-format.md

For https://trello.com/c/PeiZJJrd/338-3-yast2-storage-ng-lvm-support-yaml-reader-writer.

- document LVM syntax

---

doc/installer-hacks.md

Documents https://github.com/yast/yast-installation/pull/412

Document shortcuts taken in inst_system_analysis and to get Travis green

---

src/clients/inst_disk_proposal.rb

For https://trello.com/c/9Uj9DmG6/384-3-storageng-installation-storage-proposal.

- added new minimalistic inst_disk_proposal client

---

src/clients/inst_disk_proposal.rb
src/lib/y2storage/dialogs/inst_disk_proposal.rb
test/dialogs/inst_disk_proposal_test.rb
test/spec_helper.rb

And use InstallationDialog instead of a completely custom client.

Move inst_disk_proposal to y2storage and add unit test

---

doc/installer-hacks.md

To be merged after https://github.com/yast/yast-country/pull/90

Updated installer-hacks.md

---

doc/status.md

For https://trello.com/c/iucPgxKI/443-2-get-the-documentation-back-on-par-with-current-status.

- filled status

---

src/lib/y2storage/proposal/space_maker.rb
test/proposal/space_maker_test.rb

- Adapted to nested logical partitions in libstorage-ng
- Extended partitions are now deleted if left empty
- Fixed an existing bug (deleting extending and leaving logical)
Replaces #103

SpaceMaker: proper management of extended partitions

---

doc/installer-hacks.md

For https://trello.com/c/NQ524dss/459-8-storageng-bootloader-proposal-efi.

- documented changes in yast2-installation

---

package/yast2-storage-ng.changes
src/lib/y2storage/clients/inst_prepdisk.rb
test/clients/inst_prepdisk_test.rb

For https://trello.com/c/NQ524dss/459-8-storageng-bootloader-proposal-efi.

- mount special filesystems in target during installation

---

doc/installer-hacks.md

For https://trello.com/c/NQ524dss/459-8-storageng-bootloader-proposal-efi.

- documented shortcuts

---

doc/software-requirements.md

For https://trello.com/c/ZSnI5lF0/446-1-summarize-what-the-software-proposal-really-needs-from-storage.

- added requirements of yast2-packager

---

src/lib/y2storage/proposal/assigned_space.rb
src/lib/y2storage/proposal/space_distribution.rb
test/proposal/space_distribution_calculator_test.rb

Now it checks that things still make sense after calculating the number of logical partitions in each assigned space.

Proposal: improvement in SpaceDistribution

---

test/data/devicegraphs/output/windows-pc-mbr128-sep-home.yml
test/data/devicegraphs/output/windows-pc-mbr128.yml
test/data/devicegraphs/output/windows-pc-mbr256-lvm-sep-home.yml
test/data/devicegraphs/output/windows-pc-mbr256-lvm.yml
test/data/devicegraphs/output/windows-pc-mbr256-sep-home.yml
test/data/devicegraphs/output/windows-pc-mbr256.yml
test/data/devicegraphs/windows-pc-mbr128.yml
test/data/devicegraphs/windows-pc-mbr256.yml
test/proposal_test.rb

Proves that the proposal creates boot partitions when needed (not needed nowadays in most cases)

More cases (unusual MBR gap sizes) in proposal_test

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/devices_lists/base.rb
src/lib/y2storage/devices_lists/filesystems_list.rb
src/lib/y2storage/devices_lists/free_disk_spaces_list.rb
src/lib/y2storage/devices_lists/lvm_lvs_list.rb
src/lib/y2storage/devices_lists/lvm_pvs_list.rb
src/lib/y2storage/devices_lists/lvm_vgs_list.rb
src/lib/y2storage/devices_lists/partitions_list.rb
src/lib/y2storage/refinements/disk.rb
test/devices_list_test.rb

This improves the current query API to allow yast2-bootloader to get all the requested information for legacy boot... and beyond!

Improved API for other modules

---

src/lib/y2storage/proposal/assigned_space.rb
src/lib/y2storage/proposal/space_distribution.rb
src/lib/y2storage/proposal/space_distribution_calculator.rb
src/lib/y2storage/proposal/space_maker.rb
test/proposal/space_distribution_calculator_test.rb
test/support/storage_helpers.rb

This remove unneeded stuff (like passing the devicegraph), distributes the responsibilities better (the AssignedSpace is responsible for calculating and caching its partition_type) and simplifies code.

Some refactoring in SpaceDistribution and friends

---

doc/fake-devicegraphs-yaml-format.md
src/lib/expert_partitioner/tab_views/disk/overview.rb
src/lib/expert_partitioner/tree_views/partition.rb
src/lib/y2storage/boot_requirements_strategies/legacy.rb
src/lib/y2storage/boot_requirements_strategies/prep.rb
src/lib/y2storage/boot_requirements_strategies/uefi.rb
src/lib/y2storage/disk_analyzer.rb
src/lib/y2storage/enum_mappings.rb
test/boot_requirements_checker_ppc_test.rb
test/boot_requirements_checker_x86_test.rb
test/support/proposed_partitions_examples.rb

Also for https://trello.com/c/Mqq4FiIa/485-5-storageng-handle-partition-ids-for-gpt.
Needs https://github.com/openSUSE/libstorage-ng/pull/174.

- adapted to new set of partition ids in libstorage-ng

---

test/data/devicegraphs/multi-linux-pc-gpt.yml
test/data/devicegraphs/output/multi-linux-pc-gpt-lvm-sep-home.yml
test/data/devicegraphs/output/multi-linux-pc-gpt-lvm.yml
test/data/devicegraphs/output/multi-linux-pc-gpt-sep-home.yml
test/data/devicegraphs/output/multi-linux-pc-gpt.yml
test/data/devicegraphs/output/windows-linux-lvm-pc-gpt-lvm-sep-home.yml
test/data/devicegraphs/output/windows-linux-lvm-pc-gpt-lvm.yml
test/data/devicegraphs/output/windows-linux-lvm-pc-gpt-sep-home.yml
test/data/devicegraphs/output/windows-linux-lvm-pc-gpt.yml
test/data/devicegraphs/output/windows-linux-multiboot-pc-gpt-lvm-sep-home.yml
test/data/devicegraphs/output/windows-linux-multiboot-pc-gpt-lvm.yml
test/data/devicegraphs/output/windows-linux-multiboot-pc-gpt-sep-home.yml
test/data/devicegraphs/output/windows-linux-multiboot-pc-gpt.yml
test/data/devicegraphs/output/windows-pc-gpt-lvm-sep-home.yml
test/data/devicegraphs/output/windows-pc-gpt-lvm.yml
test/data/devicegraphs/output/windows-pc-gpt-sep-home.yml
test/data/devicegraphs/output/windows-pc-gpt.yml
test/data/devicegraphs/windows-linux-lvm-pc-gpt.yml
test/data/devicegraphs/windows-linux-multiboot-pc-gpt.yml
test/data/devicegraphs/windows-pc-gpt.yml
test/proposal_test.rb
test/support/proposal_examples.rb

It includes small cleanup to avoid too much repetition in the tests, review by commit to see that.
Replaces #129

Added GPT scenarios to proposal_test.rb

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/fake_device_factory.rb
src/lib/y2storage/yaml_writer.rb
test/fake_device_factory_test.rb
test/yaml_writer_test.rb

Needed to resurrect the yast2-packager tests (currently commented in the storage-ng branch)

Add fstab_options to the YAML format

---

src/lib/y2storage/free_disk_space.rb
src/lib/y2storage/proposal/assigned_space.rb
src/lib/y2storage/proposal/partition_creator.rb
src/lib/y2storage/proposal/space_distribution.rb
src/lib/y2storage/refinements/disk.rb
test/data/devicegraphs/gpt_msdos_and_empty.yml
test/refinements/disk_test.rb

Reviewing by commit should be easier
Relevant for https://trello.com/c/2SZJ427h/454-3-proposalng-handle-empty-disk-properly

Handle free spaces in not partitioned disks

---

test/proposal/space_maker_test.rb

This fixes the unit tests that got broken with the changes in libstorage. Libstorage now re-numbers logical partition properly, so the name cannot be used to check whether a partition is still there in the devicegraph produced by SpaceMaker.

Fix unit tests (use sids instead of names)

---

doc/fake-devicegraphs-yaml-format.md
src/lib/y2storage/abstract_device_factory.rb
src/lib/y2storage/enum_mappings.rb
src/lib/y2storage/fake_device_factory.rb
test/fake_device_factory_test.rb

https://trello.com/c/Tt1a2Pu7/336-5-yast2-storage-ng-encrypted-lvm-proposal
- Added encryption layer to the YAML reader
- Added unit test for encryption in the YAML reader
- Added encryption to YAML documentation
- Added dependencies between subproducts to AbstractDeviceFactory so the order of file_system vs. encryption in a partition is handled automatically

Encryption in YAML reader

---

src/lib/y2storage/dialogs/guided_setup.rb
src/lib/y2storage/planned_volume.rb
src/lib/y2storage/proposal/devicegraph_generator.rb
src/lib/y2storage/proposal/encrypter.rb
src/lib/y2storage/proposal/lvm_helper.rb
src/lib/y2storage/proposal/partition_creator.rb
src/lib/y2storage/proposal/phys_vol_calculator.rb
src/lib/y2storage/proposal_settings.rb
src/lib/y2storage/secret_attributes.rb
test/data/devicegraphs/lvm-new-encrypted-pvs.yml
test/proposal/encrypter_test.rb
test/proposal/lvm_helper_test.rb
test/proposal/partition_creator_test.rb
test/proposal/space_distribution_calculator_test.rb
test/secret_attributes_test.rb

This includes working code and unit tests. So it should be ready to merge.
YAML-based scenarios to be added to `proposal_test.rb` to be written after #160 is merged.

Encrypted LVM proposal

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/devices_lists.rb
src/lib/y2storage/devices_lists/base.rb
src/lib/y2storage/devices_lists/disks_list.rb
src/lib/y2storage/devices_lists/encryptions_list.rb
src/lib/y2storage/devices_lists/filesystems_list.rb
src/lib/y2storage/devices_lists/formattable.rb
src/lib/y2storage/devices_lists/lvm_lvs_list.rb
src/lib/y2storage/devices_lists/lvm_pvs_list.rb
src/lib/y2storage/devices_lists/partitions_list.rb
src/lib/y2storage/fake_device_factory.rb
src/lib/y2storage/refinements/devicegraph_lists.rb
test/data/devicegraphs/complex-lvm-encrypt.yml
test/devices_list_test.rb

Needed to fix the current yast2-bootloader problems

Add encryption to the query interface

---

doc/fake-devicegraphs-yaml-format.md
src/lib/y2storage/enum_mappings.rb
src/lib/y2storage/used_storage_features.rb

Adapt to upcoming libstorage-ng change.

- removed unused enum value

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/enum_mappings.rb

Needed for https://trello.com/c/rf9jCXSW/519-5-storageng-upgrade-rootpart-rb-part-1

Mount by mapping

---

doc/old_and_new_proposal.md
package/yast2-storage-ng.changes
src/lib/y2storage/clients/inst_disk_proposal.rb
src/lib/y2storage/proposal_settings.rb
test/clients/inst_disk_proposal_test.rb
test/proposal_settings_test.rb

This implements the changes and documentation requested at https://trello.com/c/o9LkrKGc/525-3-read-setting-from-control-file

Read proposal setting from product features

---

doc/old_and_new_proposal.md

The last task of https://trello.com/c/o9LkrKGc/525-3-read-setting-from-control-file

Document a way to emulate the old proposal

---

src/lib/storage/patches.rb
src/lib/y2storage/boot_requirements_strategies/zipl.rb
test/boot_requirements_checker_s390_test.rb

Requires PR: https://github.com/openSUSE/libstorage-ng/pull/218

- adapted to enum changes in libstorage-ng

---

package/yast2-storage-ng.changes
src/lib/y2storage/clients/inst_prepdisk.rb
test/clients/inst_prepdisk_test.rb

PBI: https://trello.com/c/JrA9u4mp/531-2-adapt-inst-prepdisk-for-upgrade

Adapt prepdisk for update

---

Rakefile
doc/fake-devicegraphs-yaml-format.md
src/lib/y2storage/fake_device_factory.rb
src/lib/y2storage/planned_subvol.rb
src/lib/y2storage/planned_volume.rb
src/lib/y2storage/proposal/partition_creator.rb
src/lib/y2storage/proposal/volumes_generator.rb
src/lib/y2storage/proposal_settings.rb
src/lib/y2storage/yaml_writer.rb
test/planned_subvol_test.rb

https://trello.com/c/Zboq9Byg/495-5-storageng-proposal-propose-btrfs-subvolumes
Screenshot from integration test with DUD from this package on the latest StorageNG ISO:

Propose subvolumes (WIP)

---

src/lib/y2storage/clients/inst_prepdisk.rb
src/lib/y2storage/storage_manager.rb
test/clients/inst_prepdisk_test.rb
test/storage_manager_test.rb

Manually tested (apart from the existing unit tests)

inst_prepdisk: don't access libstorage directly

---

src/lib/y2storage/planned_volume.rb
test/support/proposal_context.rb

This fixes the test suite as well as the rubocop complaints.

Fixed rubocop complaint

---

src/lib/y2storage/boot_requirements_strategies/legacy.rb
src/lib/y2storage/boot_requirements_strategies/prep.rb
src/lib/y2storage/boot_requirements_strategies/uefi.rb
src/lib/y2storage/disk_analyzer.rb
src/lib/y2storage/proposal.rb
src/lib/y2storage/proposal/partition_killer.rb
src/lib/y2storage/proposal/space_maker.rb
src/lib/y2storage/proposal/volumes_generator.rb
test/boot_requirements_checker_ppc_test.rb
test/boot_requirements_checker_x86_test.rb
test/disk_analyzer_test.rb
test/proposal/space_maker_test.rb
test/proposal/volumes_generator_test.rb
test/support/boot_requirements_context.rb
test/support/proposal_context.rb

Refac DiskAnalyzer class

---

src/lib/y2storage/planned_subvol.rb
test/proposal_settings_test.rb

This should fix the current breakage in our openQA.
TDD style: first commit introduces unit tests for reading subvolumes and second one refactors and fix the method.

Correctly process duplicated subvolumes in control.xml

---

src/lib/y2storage/actiongraph.rb
src/lib/y2storage/blk_device.rb
src/lib/y2storage/btrfs_subvolume.rb
src/lib/y2storage/dasd.rb
src/lib/y2storage/devicegraph.rb
src/lib/y2storage/disk.rb
src/lib/y2storage/encryption.rb
src/lib/y2storage/filesystems/base.rb
src/lib/y2storage/filesystems/blk_filesystem.rb
src/lib/y2storage/filesystems/nfs.rb
src/lib/y2storage/mountable.rb
src/lib/y2storage/planned_subvol.rb
src/lib/y2storage/planned_volume.rb
src/lib/y2storage/proposal_settings.rb
src/lib/y2storage/storage_class_wrapper.rb
src/lib/y2storage/storage_manager.rb
src/lib/y2storage/used_storage_features.rb
src/lib/y2storage/yaml_writer.rb

Still to be improved, of course.

Some documentation for the wrapper classes

---

src/lib/y2storage/clients/inst_disk_proposal.rb
src/lib/y2storage/dialogs/guided_setup.rb
src/lib/y2storage/dialogs/guided_setup/base.rb
src/lib/y2storage/dialogs/guided_setup/select_disks.rb
src/lib/y2storage/dialogs/guided_setup/select_filesystem.rb
src/lib/y2storage/dialogs/guided_setup/select_root_disk.rb
src/lib/y2storage/dialogs/guided_setup/select_scheme.rb
src/lib/y2storage/dialogs/proposal.rb
src/lib/y2storage/disk_analyzer.rb
src/lib/y2storage/existing_filesystem.rb
src/lib/y2storage/filesystems/type.rb
test/data/control_files/root/control.xml
test/data/control_files/root/mnt1/control.xml
test/dialogs/guided_setup/select_disks_test.rb
test/dialogs/guided_setup/select_filesystem_test.rb
test/dialogs/guided_setup/select_root_disk_test.rb
test/dialogs/guided_setup/select_scheme_test.rb
test/dialogs/guided_setup_test.rb
test/disk_analyzer_test.rb
test/existing_filesystem_test.rb
test/support/guided_setup_context.rb

PBI: https://trello.com/c/crhdffWC/516-5-storageng-guided-setup
This PR replaces this old one: https://github.com/yast/yast-storage-ng/pull/193

Guided setup

---

src/lib/y2storage/clients/inst_disk_proposal.rb
src/lib/y2storage/dialogs/guided_setup.rb
src/lib/y2storage/storage_manager.rb
test/dialogs/guided_setup_test.rb
test/support/guided_setup_context.rb

Related to PBI https://trello.com/c/b5DSHXf5/567-2-storageng-guided-set-up-disable-unneeded-widgets

Add disk analyzer to storage manager

---

src/lib/y2storage/dialogs/guided_setup.rb
src/lib/y2storage/dialogs/guided_setup/base.rb
src/lib/y2storage/dialogs/guided_setup/select_disks.rb
src/lib/y2storage/dialogs/guided_setup/select_root_disk.rb
src/lib/y2storage/dialogs/guided_setup/select_scheme.rb
src/lib/y2storage/disk_analyzer.rb
test/dialogs/guided_setup/select_disks_test.rb
test/dialogs/guided_setup/select_root_disk_test.rb
test/dialogs/guided_setup_test.rb
test/support/guided_setup_context.rb

PBI: https://trello.com/c/b5DSHXf5/567-2-storageng-guided-set-up-disable-unneeded-widgets

Disable uneeded widgets

---

test/device_test.rb
test/fake_device_factory_test.rb

Needs https://github.com/openSUSE/libstorage-ng/pull/238.

- adapted to change in libstorage-ng

---

src/lib/y2storage/dialogs/guided_setup/select_scheme.rb

PBI https://trello.com/c/b5DSHXf5/567-2-storageng-guided-set-up-disable-unneeded-widgets

Set default yes to accept weak password

---

test/disk_analyzer_test.rb
test/proposal_settings_test.rb
test/support/proposal_context.rb

Fix current problems generating iso for other archs.

Fix tests that depend on arch

---

src/lib/y2storage/proposal.rb
src/lib/y2storage/proposal/devicegraph_generator.rb
src/lib/y2storage/proposal/exceptions.rb
src/lib/y2storage/proposal/space_maker.rb
src/lib/y2storage/proposal/volumes_generator.rb
src/lib/y2storage/proposal_settings.rb
test/data/devicegraphs/complex-lvm-encrypt.yml
test/data/devicegraphs/output/windows-linux-lvm-pc-gpt-lvm-sep-home.yml
test/data/devicegraphs/output/windows-linux-lvm-pc-gpt-lvm.yml
test/data/devicegraphs/output/windows-linux-lvm-pc-gpt-sep-home.yml
test/data/devicegraphs/output/windows-linux-lvm-pc-gpt.yml
test/data/devicegraphs/windows-linux-lvm-pc-gpt.yml
test/devicegraph_test.rb
test/devices_list_test.rb
test/proposal/space_maker_test.rb
test/proposal/volumes_generator_test.rb
test/proposal_test.rb

This implements the main functionality of
https://trello.com/c/PnqN8jgz/549-5-storageng-guided-set-up-apply-the-setting-what-to-do-with-existing-partitions
It should be way easier to review commit by commit.

Apply settings about what to do with existing partitions

---

src/lib/y2storage/dialogs/guided_setup/select_root_disk.rb
src/lib/y2storage/proposal_settings.rb
test/dialogs/guided_setup/select_root_disk_test.rb
test/support/guided_setup_context.rb

One of the last steps for completing https://trello.com/c/PnqN8jgz/549-5-storageng-guided-set-up-apply-the-setting-what-to-do-with-existing-partitions
Manual testing in a real installation still pending.

Guided setup: new proposal settings in the UI

---

src/lib/y2storage/device.rb
src/lib/y2storage/lvm_vg.rb
src/lib/y2storage/partition.rb

Doc for Device and Partition classes.
PBI https://trello.com/c/1gvNrbFQ/546-8-wrapper-based-api

Wrapper doc

---

src/lib/y2storage/device.rb
src/lib/y2storage/devicegraph.rb
src/lib/y2storage/proposal/space_maker.rb

Try to solve problem in openQA when disk has a Windows.
https://yast-openqa.suse.cz/tests/4939

Fix bug with resize info

---

src/lib/y2storage/boot_requirements_strategies/base.rb
src/lib/y2storage/boot_requirements_strategies/legacy.rb
src/lib/y2storage/boot_requirements_strategies/prep.rb
src/lib/y2storage/boot_requirements_strategies/uefi.rb
src/lib/y2storage/boot_requirements_strategies/zipl.rb
src/lib/y2storage/planned_volume.rb
src/lib/y2storage/planned_volumes_list.rb
src/lib/y2storage/proposal/lvm_helper.rb
src/lib/y2storage/proposal/partition_creator.rb
src/lib/y2storage/proposal/phys_vol_calculator.rb
src/lib/y2storage/proposal/space_distribution_calculator.rb
src/lib/y2storage/proposal/volumes_generator.rb
src/lib/y2storage/proposal_settings.rb
test/planned_volumes_list_test.rb
test/proposal/space_distribution_calculator_test.rb
test/proposal/volumes_generator_test.rb
test/proposal_settings_test.rb

PBI https://trello.com/c/1gvNrbFQ/546-8-wrapper-based-api

Rename disk size

---

src/lib/y2storage/callbacks/activate_callbacks.rb
src/lib/y2storage/storage_manager.rb

For https://trello.com/c/li8xjUAE/538-5-storageng-probe-inactive-luks.
Next step will be to implement popups for the callbacks but without any callbacks set no activation is done (not even for LVM) likely breaking tests.

- added dummy activate callbacks

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/scrconf/etc_mtab.scr

Please review the following changes:
* 0fe0a01 added SCR agent .etc.mtab

[Review] Request from 'schubi2' @ 'yast/yast-storage-ng/review_170504_scr_etc_mtab_agent'

---

test/devicegraph_test.rb

Avoid error with new version of libstorage-ng.

Improve actiongraph test

---

src/lib/y2storage/partition_tables.rb
src/lib/y2storage/partition_tables/base.rb
src/lib/y2storage/partition_tables/dasd.rb

For https://trello.com/c/dnsteUCS/503-8-libstorageng-dasd-devices.

- added wrapper for DASD partition table

---

package/yast2-storage-ng.spec
src/lib/y2storage.rb
src/lib/y2storage/actiongraph.rb
src/lib/y2storage/compound_action.rb
src/lib/y2storage/dialogs/proposal.rb
src/lib/y2storage/widgets/actions_summary.rb
test/dialogs/proposal_test.rb
test/widgets/actions_summary_test.rb

PBI: https://trello.com/c/WzeqWCX8/518-(5)-storageng%3A-simplified-summary

Compound actions

---

src/lib/y2storage/filesystems/type.rb

cf. https://github.com/yast/yast-update/pull/74
replaces https://github.com/yast/yast-storage-ng/pull/257

add root_ok? and home_ok? methods to Y2Storage::Filesystems::Type

---

package/yast2-storage-ng.changes

Changelog entry that was missing in #262 Since Iván is not here, I decided to merge the PR and add the entry afterwards.

Changelog entry

---

doc/installer-hacks.md

cf. https://github.com/yast/yast-installation/pull/574

documented yast2-installation temporary change

---

.gitignore
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/disk_size.rb
src/lib/y2storage/region.rb
test/disk_size_test.rb
test/region_test.rb
test/storage_manager_test.rb

This is useful in https://github.com/yast/yast-partitioner/pull/15

Added Y2Storage::Region #size, #cover?.

---

test/fake_dependencies/lib/y2partitioner/clients/main.rb
test/spec_helper.rb

alternative approach to https://github.com/yast/yast-storage-ng/pull/273

allow easy mocking clients from partitioner

---

src/lib/y2storage.rb
src/lib/y2storage/md.rb
src/lib/y2storage/md_level.rb
src/lib/y2storage/md_parity.rb
test/md_test.rb
test/support/storage_helpers.rb

For https://trello.com/c/JO6m3Nkf/561-3-libstorageng-md-raid-named-raid-array.

- added wrapper for Md class

---

package/yast2-storage-ng.changes
src/lib/y2storage/storage_manager.rb
test/storage_manager_test.rb

Added the missing RSpec tests.

Invalidate StorageManager caches on reprobing

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_proposal.rb
src/lib/y2storage/guided_proposal.rb

PBI: https://trello.com/c/B2Qv7y6d/639-5-storageng-proposal-adapt-to-the-situation.
Related to task "Use the same mechanism in level 1 and 2 of AutoYaST".

Improve autoyast proposal initializer

---

package/yast2-storage-ng.changes
src/lib/y2storage/autoinst_proposal.rb
src/lib/y2storage/guided_proposal.rb
src/lib/y2storage/proposal.rb
src/lib/y2storage/proposal/base.rb
test/autoinst_proposal_test.rb

Create a new class `Proposal::Base`.
PBI https://trello.com/c/B2Qv7y6d/639-5-storageng-proposal-adapt-to-the-situation.

Base proposal class

---

README.md

PBI: https://trello.com/c/B2Qv7y6d/639-5-storageng-proposal-adapt-to-the-situation.

Remove disk requirements from readme

---

src/lib/y2storage/clients/inst_disk_proposal.rb
test/clients/inst_disk_proposal_test.rb

PBI: https://trello.com/c/pol3pLNV/608-1-storageng-enter-the-expert-partitioner-from-installation.

Use expert partitioner

---

src/lib/y2storage/clients/partitions_proposal.rb
test/clients/partitions_proposal_test.rb

PBI: https://trello.com/c/pol3pLNV/608-1-storageng-enter-the-expert-partitioner-from-installation.
Task: (optional, to be replaced with workflow later) Possible to enter partitioner from summary (https://trello.com/c/Bf7k0xKs/601-storageng-showing-proposal-in-the-general-proposal-overview).

Summary expert partitioner

---

src/lib/y2storage/fake_device_factory.rb
src/lib/y2storage/free_disk_space.rb
src/lib/y2storage/partition_tables/base.rb
src/lib/y2storage/planned/assigned_space.rb
src/lib/y2storage/planned/has_size.rb
src/lib/y2storage/proposal/partition_creator.rb
src/lib/y2storage/proposal/partitions_distribution_calculator.rb
test/data/devicegraphs/alignment.yml
test/data/devicegraphs/empty_dasd_50GiB.yml
test/data/devicegraphs/output/s390_dasd_zipl-lvm-sep-home.yml
test/data/devicegraphs/output/s390_dasd_zipl-lvm.yml
test/data/devicegraphs/output/s390_dasd_zipl.yml
test/y2storage/fake_device_factory_test.rb
test/y2storage/partition_tables_test.rb
test/y2storage/planned/assigned_space_test.rb
test/y2storage/proposal/partition_creator_test.rb
test/y2storage/proposal/partitions_distribution_calculator_test.rb
test/y2storage/proposal_scenarios_s390_test.rb

WIP
PBI: https://trello.com/c/UBCLA6Qo/651-2-storageng-and-s-390-partitions-not-aligned.
This PR depends on https://github.com/openSUSE/libstorage-ng/pull/303.

Dasd alignment

---

src/lib/y2storage/planned/assigned_space.rb
test/y2storage/planned/assigned_space_test.rb

PBI: https://trello.com/c/UBCLA6Qo/651-2-storageng-and-s-390-partitions-not-aligned.

Improve AssignedSpace#enforced_last

---

.gitignore
doc/user-stories/expert-partitioner.md

PBI: https://trello.com/c/ZEkBVzkj/661-2-partitioner-specification-plain-partitions.

Add expert partitioner specs

---

package/yast2-storage-ng.changes
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/planned/can_be_formatted.rb
src/lib/y2storage/proposal/autoinst_devices_planner.rb
src/lib/y2storage/proposal/devices_planner.rb
src/lib/y2storage/proposal_settings.rb
src/lib/y2storage/subvol_specification.rb
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/autoinst_proposal_test.rb
test/y2storage/planned/can_be_encrypted_test.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb

See https://trello.com/c/r17ee67j/600-3-autoyast-ng-level-3-btrfs-subvolumes

Subvolumes in AutoYaST level 3

---

src/lib/y2partitioner/widgets/disk_bar_graph.rb
src/lib/y2storage/free_disk_space.rb
src/lib/y2storage/partition_tables/base.rb
src/lib/y2storage/partitionable.rb
src/lib/y2storage/proposal/partition_creator.rb
src/lib/y2storage/region.rb
test/spec_helper.rb
test/y2storage/disk_test.rb
test/y2storage/guided_proposal_test.rb
test/y2storage/partition_tables_test.rb
test/y2storage/region_test.rb

PBI: https://trello.com/c/yh9J6T5F/656-5-storageng-multipath-and-dm-raid-in-the-proposal.
Generate partitions with correct name.

Correct partition names

---

package/yast2-storage-ng.changes
src/lib/y2storage/callbacks/activate.rb
test/y2storage/callbacks/activate_test.rb

Popup to ask for multipath activation

---

doc/boot-partition.md

After some talk with Alex Graf, here's what I understood.

add boot partition layout section for raspberry pi

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/clients/main.rb
src/lib/y2storage/clients/inst_disk_proposal.rb
src/lib/y2storage/clients/inst_prepdisk.rb
src/lib/y2storage/clients/partitions_proposal.rb
src/lib/y2storage/device.rb
src/lib/y2storage/proposal/autoinst_drives_map.rb
src/lib/y2storage/proposal/base.rb
src/lib/y2storage/storage_manager.rb
test/spec_helper.rb
test/support/storage_helpers.rb
test/y2partitioner/test_helper.rb
test/y2partitioner/widgets/overview_test.rb
test/y2storage/blk_device_test.rb
test/y2storage/clients/inst_disk_proposal_test.rb
test/y2storage/clients/inst_prepdisk_test.rb
test/y2storage/clients/partitions_proposal_test.rb
test/y2storage/device_test.rb
test/y2storage/devicegraph_test.rb
test/y2storage/lvm_vg_test.rb
test/y2storage/proposal/autoinst_devices_creator_test.rb
test/y2storage/storage_manager_test.rb
test/y2storage/yaml_writer_test.rb

PBI: https://trello.com/c/BWtX9ccg/548-2-remove-refinements-patches-extensions-etc-from-yast-storage-ng.

Remove old API from StorageManager

---

src/lib/y2storage/md.rb
src/lib/y2storage/md_level.rb
test/data/devicegraphs/md2-devicegraph.xml
test/y2storage/md_test.rb

For https://trello.com/c/2tJ3LlpM/672-5-storageng-bios-raid-via-md-devices.

- adapted to libstorage-ng API change

---

src/lib/y2storage/storage_manager.rb

For https://trello.com/c/3UBgvs3w/646-3-libstorageng-deactivate-an-md-array-and-lvm-vgs.

- added wrapper for deactivate()

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/format_and_mount.rb
src/lib/y2partitioner/widgets/fstab_options.rb
src/lib/y2storage/filesystems/type.rb

- It seems that we bring it back to life :P, and it was already removed for new installations in SLE 12.
The fate was for upgrade but just realized working on it that we added again the option for installation.

Drop reiserfs (fate#323394)

---

test/y2partitioner/format_mount/base_test.rb

Fix bug in tests

---

doc/old_and_new_proposal.md

For easier review, take a look to the [rendered version of the document](https://github.com/ancorgs/yast-storage-ng/blob/3303b8b8f8e379c447a52681c70de901fa382071/doc/old_and_new_proposal.md)

First proposal of control.xml structure (to be refined)

---

doc/old_and_new_proposal.md

It's probably better to review using the rendered version of the document.
This presents the examples before the specification (with the corresponding adjustments to the text to reflect that and explain why) and introduces every example with a human-friendly description of the intention.

old_and_new_proposal.md: start with examples and use cases

---

doc/user-stories/expert-partitioner.md

PBI: https://trello.com/c/BQUekIB1/659-1-partitioner-specification-md-arrays.

Document RAID section of partitioner

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/filesystems/btrfs.rb
src/lib/y2storage/planned/can_be_formatted.rb
src/lib/y2storage/planned/can_be_mounted.rb
src/lib/y2storage/proposal/devices_planner.rb
src/lib/y2storage/storage_manager.rb
test/y2storage/clients/inst_prepdisk_test.rb
test/y2storage/proposal/devices_planner_test.rb
test/y2storage/proposal_subvol_test.rb
test/y2storage/storage_manager_test.rb

Last commit to cover the Guided proposal part of https://trello.com/c/ytK5Yoe4/554-5-storageng-installation-to-root-subvolume (the others are already merged)

Snapshots on proposal

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/proposal/autoinst_devices_planner.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb

Please review the following changes:
* 54c9021 AY: size handling without unit
* 3723df4 AY: size handling without unit

[Review] Request from 'schubi2' @ 'yast/yast-storage-ng/review_170905_autoyast_size'

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/format_mount/base.rb
src/lib/y2storage/filesystems/btrfs.rb
test/y2partitioner/format_mount/base_test.rb

Bug: https://bugzilla.suse.com/show_bug.cgi?id=1057405

Fix bug when formatting with expert partitioner

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/dialogs/partition_size.rb
test/y2partitioner/dialogs/partition_size_test.rb

Bug: https://bugzilla.suse.com/show_bug.cgi?id=1057049.

Fix partitioner bug creating partition with custom size

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/proposal/autoinst_devices_planner.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb

Please review the following changes:
* f7bdd4c AY: size is -auto-

[Review] Request from 'schubi2' @ 'yast/yast-storage-ng/review_170907_ay_size_auto'

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/planned/partitions_distribution.rb
src/lib/y2storage/proposal/space_maker.rb
test/data/devicegraphs/dasd_50GiB.yml
test/y2storage/proposal/space_maker_test.rb
test/y2storage/proposal_scenarios_s390_test.rb

https://trello.com/c/RgeK8HFG/719-sles15-p5-1058052-build-2111-paritioning-no-proposal-possible-cannot-continue

Fix proposal bug with DASD partition tables

---

doc/user-stories/expert-partitioner.md

PBI: https://trello.com/c/czaBKQ9V/660-1-partitioner-specification-lvm.

Add specs for LVM section of partitioner

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/clients/partitions_proposal.rb
test/y2storage/clients/partitions_proposal_test.rb

https://trello.com/c/s8sAvZrA/723-1-storageng-provide-the-simple-proposal
https://bugzilla.suse.com/show_bug.cgi?id=1058736
Test result:

Ported simple_mode proposal to storage-ng

---

doc/user-stories/expert-partitioner.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/sequences/edit_blk_device.rb
src/lib/y2partitioner/widgets/disk_page.rb
src/lib/y2partitioner/widgets/edit_blk_device_button.rb
src/lib/y2partitioner/widgets/format_and_mount.rb
src/lib/y2partitioner/widgets/lvm_lv_page.rb
src/lib/y2partitioner/widgets/lvm_vg_page.rb
src/lib/y2partitioner/widgets/md_raid_page.rb
src/lib/y2partitioner/widgets/md_raids_page.rb
src/lib/y2partitioner/widgets/partition_page.rb
test/y2partitioner/sequences/edit_blk_device_test.rb
test/y2partitioner/widgets/disk_page_test.rb
test/y2partitioner/widgets/edit_blk_device_button_test.rb
test/y2partitioner/widgets/format_and_mount_test.rb
test/y2partitioner/widgets/partition_page_test.rb

* Edit button for LVs and RAIDs
* Fixed mountpoint validation for swap
* Proper placing/aligning of some buttons

Several improvements in the expert partitioner

---

doc/old_and_new_proposal.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/partitioning_features.rb
src/lib/y2storage/proposal/devices_planner.rb
src/lib/y2storage/proposal_settings.rb
src/lib/y2storage/volume_specification.rb
test/support/guided_setup_context.rb
test/support/proposal_context.rb
test/y2partitioner/dialogs/main_test.rb
test/y2storage/autoinst_proposal_test.rb
test/y2storage/dialogs/guided_setup_test.rb
test/y2storage/proposal/devices_planner_test.rb
test/y2storage/proposal/space_maker_test.rb
test/y2storage/proposal_settings_test.rb
test/y2storage/volume_specification_test.rb

PBI: https://trello.com/c/I9K56rmD/566-5-allow-to-propose-a-data-partition-changes-in-the-proposal-logic

New format for proposal settings

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/drive_section.rb
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/clients/inst_prepdisk.rb
src/lib/y2storage/fake_device_factory.rb
src/lib/y2storage/planned/can_be_formatted.rb
src/lib/y2storage/planned/can_be_mounted.rb
src/lib/y2storage/proposal/autoinst_devices_planner.rb
src/lib/y2storage/proposal/autoinst_space_maker.rb
src/lib/y2storage/storage_manager.rb
test/data/devicegraphs/autoyast_drive_examples.yml
test/y2storage/autoinst_profile/drive_section_test.rb
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/fake_device_factory_test.rb
test/y2storage/proposal/autoinst_devices_creator_test.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb
test/y2storage/proposal/autoinst_space_maker_test.rb
test/y2storage/storage_manager_test.rb

It should fix [bsc#1061042](https://bugzilla.suse.com/show_bug.cgi?id=1061042).

Handling use, mkfs_options, fstopt and mountby elements

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/mountable.rb
src/lib/y2storage/partitioning_features.rb
src/lib/y2storage/planned/can_be_mounted.rb
src/lib/y2storage/planned/lvm_lv.rb
src/lib/y2storage/planned/partition.rb
src/lib/y2storage/proposal/devices_planner.rb
src/lib/y2storage/proposal/devices_planner_strategies.rb
src/lib/y2storage/proposal/devices_planner_strategies/base.rb
src/lib/y2storage/proposal/devices_planner_strategies/legacy.rb
src/lib/y2storage/proposal/devices_planner_strategies/ng.rb
src/lib/y2storage/volume_specification.rb
test/data/control_files/caasp.xml
test/data/devicegraphs/empty_hard_disk_15GiB.yml
test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB_caasp.yml
test/spec_helper.rb
test/support/devices_planner_context.rb
test/support/proposal_context.rb
test/y2storage/proposal/devices_planner_strategies/legacy_test.rb
test/y2storage/proposal/devices_planner_strategies/ng_test.rb
test/y2storage/proposal/devices_planner_test.rb
test/y2storage/proposal_scenarios_caasp_test.rb
test/y2storage/proposal_settings_test.rb

PBI: https://trello.com/c/I9K56rmD/566-5-allow-to-propose-a-data-partition-changes-in-the-proposal-logic
Implement logic for devices planner ng strategy.

Ng strategy for devices planner

---

src/lib/y2storage/proposal/devices_planner_strategies.rb
src/lib/y2storage/proposal/devices_planner_strategies/ng.rb
src/lib/y2storage/volume_specification.rb
test/support/proposal_context.rb
test/y2storage/proposal/devices_planner_strategies/legacy_test.rb
test/y2storage/proposal/devices_planner_strategies/ng_test.rb
test/y2storage/proposal/devices_planner_test.rb
test/y2storage/volume_specification_test.rb

PBI: https://trello.com/c/I9K56rmD/566-5-allow-to-propose-a-data-partition-changes-in-the-proposal-logic

Add support for fallback settings

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/planned/has_size.rb

https://bugzilla.suse.com/show_bug.cgi?id=1063392

Avoid endless loop while distributing extra space

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/volume_specification.rb

... and let users change their settings.
It's just irritating having the volumes defined in control.xml and seeing
they are not created.

have volumes proposed by default

---

test/data/devicegraphs/empty_dasd_50GiB.yml

Set the DASD format. A propoer value is required for various functions.

- set DASD format

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/filesystems/btrfs.rb
src/lib/y2storage/planned/can_be_formatted.rb
src/lib/y2storage/proposal/autoinst_devices_planner.rb
src/lib/y2storage/subvol_specification.rb
test/data/devicegraphs/autoyast_drive_examples.yml
test/data/devicegraphs/mixed_disks_btrfs.yml
test/y2partitioner/widgets/pages/btrfs_test.rb
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/filesystems/btrfs_test.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb
test/y2storage/subvol_specification_test.rb

Now subvolumes are cloned in a proper way.

Clone subvolumes properly

---

doc/boot-requirements.md

Updates the documentation after https://github.com/yast/yast-storage-ng/pull/399

Sync doc/boot-requirements with RSpec

---

doc/old_and_new_proposal.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/planned/lvm_lv.rb
src/lib/y2storage/proposal/devices_planner_strategies/base.rb
src/lib/y2storage/proposal/devices_planner_strategies/ng.rb
src/lib/y2storage/proposal/initial_strategies/ng.rb
src/lib/y2storage/volume_specification.rb
test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-root-docker-lvm.yml
test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-root-swap.yml
test/support/devices_planner_context.rb
test/support/proposal_context.rb
test/y2storage/planned/lvm_lv_test.rb
test/y2storage/proposal/autoinst_size_parser_test.rb
test/y2storage/proposal/initial_strategies/ng_test.rb
test/y2storage/proposal_scenarios_x86_test.rb
test/y2storage/volume_specification_test.rb

Part of PBI https://trello.com/c/I9K56rmD/566-5-allow-to-propose-a-data-partition-changes-in-the-proposal-logic

Fix new settings

---

doc/old_and_new_proposal.md
doc/user-stories/expert-partitioner.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/add_lvm_vg.rb
src/lib/y2partitioner/actions/add_partition.rb
src/lib/y2partitioner/actions/controllers/lvm_vg.rb
src/lib/y2partitioner/dialogs/lvm_vg.rb
src/lib/y2partitioner/widgets/device_button.rb
src/lib/y2partitioner/widgets/lvm_add_button.rb
src/lib/y2partitioner/widgets/md_add_button.rb
src/lib/y2partitioner/widgets/pages/disk.rb
src/lib/y2partitioner/widgets/pages/lvm_vg.rb
src/lib/y2partitioner/widgets/pages/md_raids.rb
src/lib/y2partitioner/widgets/partition_add_button.rb
src/lib/y2storage/disk_size.rb
test/y2partitioner/actions/add_lvm_vg_test.rb
test/y2partitioner/actions/controllers/lvm_vg_test.rb
test/y2partitioner/dialogs/lvm_vg_test.rb
test/y2partitioner/dialogs/md_test.rb
test/y2partitioner/widgets/blk_device_edit_button_test.rb
test/y2partitioner/widgets/lvm_add_button_test.rb
test/y2partitioner/widgets/md_add_button_test.rb
test/y2partitioner/widgets/pages/disk_test.rb
test/y2partitioner/widgets/pages/md_raids_test.rb
test/y2partitioner/widgets/partition_add_button_test.rb
test/y2storage/disk_size_test.rb

PBI: https://trello.com/c/CGjosZ0p/734-3-expert-partitioner-create-a-vg

Partitioner add vg

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/planned/assigned_space.rb
src/lib/y2storage/planned/partitions_distribution.rb
test/data/control_files/kvm-role-like.xml
test/data/devicegraphs/kvm_role_scenario.yml
test/data/devicegraphs/output/kvm_role_scenario.yml
test/data/devicegraphs/spaces_5_5_10.yml
test/y2storage/proposal/partitions_distribution_calculator_test.rb
test/y2storage/proposal_scenarios_kvm_role_test.rb

See https://hackweek.suse.com/projects/yast2-storage-ng-ensure-the-best-layout-is-proposed
Better review in a per-commit basis

Enhance criteria to choose the best partitions distribution 

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/blk_device.rb
src/lib/y2storage/devicegraph.rb
src/lib/y2storage/lvm_pv.rb
src/lib/y2storage/partitionable.rb
src/lib/y2storage/planned/device.rb
src/lib/y2storage/storage_class_wrapper.rb
src/lib/y2storage/storage_manager.rb
test/y2storage/devicegraph_test.rb

PBI: https://trello.com/c/IwsGnkli/770-improve-logging
See also https://hackweek.suse.com/16/projects/y2storage-wrapper-around-libstorage-ng-be-more-silent

Improve logs

---

doc/user-stories/expert-partitioner.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/add_lvm_lv.rb
src/lib/y2partitioner/actions/add_md.rb
src/lib/y2partitioner/actions/controllers/md.rb
src/lib/y2partitioner/actions/resize_md.rb
src/lib/y2partitioner/dialogs/md.rb
src/lib/y2partitioner/dialogs/md_options.rb
src/lib/y2partitioner/dialogs/md_resize.rb
src/lib/y2partitioner/widgets/device_button.rb
src/lib/y2partitioner/widgets/md_devices_selector.rb
test/y2partitioner/actions/controllers/md_test.rb
test/y2partitioner/actions/resize_md_test.rb
test/y2partitioner/dialogs/md_resize_test.rb
test/y2partitioner/dialogs/md_test.rb
test/y2partitioner/widgets/device_resize_button_test.rb
test/y2partitioner/widgets/md_devices_selector_test.rb
test/y2partitioner/widgets/pages/lvm_lv_test.rb
test/y2partitioner/widgets/pages/md_raid_test.rb
test/y2partitioner/widgets/pages/partition_test.rb
test/y2partitioner/widgets/partition_add_button_test.rb

PBI: https://trello.com/c/2xffkeJR/738-3-expert-partitioner-resize-md-raid

Partitioner: resize md

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/dasd.rb
src/lib/y2storage/devicegraph.rb
src/lib/y2storage/disk.rb
src/lib/y2storage/partition.rb
src/lib/y2storage/partitionable.rb
test/data/devicegraphs/autoyast_drive_examples.yml
test/support/storage_helpers.rb
test/y2storage/autoinst_profile/drive_section_test.rb
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/dasd_test.rb
test/y2storage/devicegraph_test.rb
test/y2storage/disk_test.rb
test/y2storage/partition_test.rb
test/y2storage/proposal/autoinst_drives_map_test.rb

Main pull request for https://trello.com/c/6szyiBWI/763-2-sle15-storage-ng-select-the-disk-to-use-consistently

Name-based stable sorting for (auto)installation

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/storage_manager.rb
test/y2storage/storage_manager_test.rb

Verified manually that it fixes https://bugzilla.suse.com/show_bug.cgi?id=1069671

Never try to copy staging into itself. Bug#1069671

---

src/lib/y2storage/device.rb
test/y2storage/device_test.rb

- Removed now obsolete unit test for detect_resize_info
- Added new unit test for can_resize?

Fixed unit tests

---

src/lib/y2partitioner/actions/resize_partition.rb
src/lib/y2partitioner/dialogs/partition_resize.rb
src/lib/y2partitioner/widgets/device_resize_button.rb
src/lib/y2partitioner/widgets/pages/disk.rb
src/lib/y2partitioner/widgets/pages/disks.rb
src/lib/y2partitioner/widgets/pages/partition.rb

Part of PBI: https://trello.com/c/qDcdjjBL/697-5-partitioner-plain-partitioning-resize

WIP: Resize partition

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/storage_manager.rb
test/y2storage/storage_manager_test.rb

* Related to https://github.com/yast/yast-autoinstallation/pull/375

Support for setting activation callbacks

---

src/lib/y2partitioner/dialogs/partition_resize.rb
src/lib/y2storage.rb
test/y2partitioner/dialogs/partition_resize_test.rb

Part of PBI: https://trello.com/c/qDcdjjBL/697-5-partitioner-plain-partitioning-resize

Add dialog tests

---

.codeclimate.yml
doc/user-stories/expert-partitioner.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/controllers/md.rb
src/lib/y2partitioner/widgets/devices_selection.rb
src/lib/y2partitioner/widgets/md_devices_selector.rb
src/lib/y2storage/md.rb
test/y2partitioner/actions/controllers/md_test.rb
test/y2partitioner/widgets/md_devices_selector_test.rb

See https://trello.com/c/jLmRRq39/732-3-storage-ng-devices-order-in-raid

Partitioner: sorting of devices in MD RAID

---

src/lib/y2partitioner/actions/resize_partition.rb
src/lib/y2storage.rb
src/lib/y2storage/align_type.rb
src/lib/y2storage/partition.rb
src/lib/y2storage/partition_tables/base.rb
test/y2partitioner/actions/resize_partition_test.rb
test/y2storage/partition_test.rb
test/y2storage/proposal_scenarios_s390_test.rb

Part of PBI: https://trello.com/c/qDcdjjBL/697-5-partitioner-plain-partitioning-resize

Alignment tests

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/boot_requirements_strategies/analyzer.rb
test/y2storage/boot_requirements_strategies/analyzer_test.rb

It should fix [bsc#1070621](https://bugzilla.suse.com/show_bug.cgi?id=1070621)

Fix boot partition detection

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/blk_device.rb
src/lib/y2storage/comparable_by_name.rb
src/lib/y2storage/device.rb
src/lib/y2storage/lvm_vg.rb
src/lib/y2storage/partition.rb
src/lib/y2storage/partitionable.rb
test/data/devicegraphs/sorting/disks_and_dasds1.yml
test/data/devicegraphs/sorting/disks_and_dasds2.yml
test/y2storage/blk_device_test.rb
test/y2storage/devicegraph_test.rb
test/y2storage/disk_test.rb
test/y2storage/lvm_vg_test.rb

Based on https://github.com/openSUSE/libstorage-ng/pull/400
Replaces https://github.com/yast/yast-storage-ng/pull/434 and #432

Use the improved Device.compare_by_name from libstorage-ng 

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/partition_id.rb
test/y2storage/autoinst_profile/partition_section_test.rb

DIAG is, AFAIS, in the same situation.

Fix ESP and other partition_id conversions

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
test/y2partitioner/widgets/overview_test.rb

See also https://github.com/yast/yast-yast2/pull/654

Storage depends on newer yast2.rpm (Pager#current_page made public)

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/blk_device_edit_button.rb
src/lib/y2partitioner/widgets/pages/disks.rb
src/lib/y2partitioner/widgets/partition_add_button.rb
test/y2partitioner/widgets/blk_device_edit_button_test.rb
test/y2partitioner/widgets/pages/disks_test.rb
test/y2partitioner/widgets/partition_add_button_test.rb

PBI: https://trello.com/c/kE0SSbi5/698-0-partitioner-plain-partitioning-hard-disks-overview-add-edit-buttons

Add buttons to Hard Disks view

---

src/lib/y2partitioner/actions/controllers/lvm_vg.rb
test/y2partitioner/actions/controllers/lvm_vg_test.rb

For https://github.com/yast/yast-storage-ng/issues/463.

- fixed typo

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/blk_device.rb
test/y2storage/blk_device_test.rb

This is part of https://trello.com/c/lOQcX484/806-bug-1073254-storage-ng-staginge-fails-to-test-upgrade-a-131-installation-to-tw
Depends on this other PR being merged before: https://github.com/openSUSE/libstorage-ng/pull/414

BlkDevice.find_by_any_name and improved documentation 

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec

For https://bugzilla.suse.com/show_bug.cgi?id=1073645.

- added obsoletes (bsc#1073645)

---

Rakefile
doc/user-stories/expert-partitioner.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/delete_lvm_vg.rb
src/lib/y2partitioner/widgets/device_delete_button.rb
src/lib/y2storage/device.rb
src/lib/y2storage/devicegraph.rb
src/lib/y2storage/filesystems/btrfs.rb
src/lib/y2storage/lvm_vg.rb
test/y2partitioner/actions/delete_lvm_vg_test.rb
test/y2partitioner/widgets/device_delete_button_test.rb
test/y2storage/devicegraph_test.rb

This implements https://trello.com/c/qu4XutJH/739-1-expert-partitioner-delete-a-vg
**Note:** It should be easier to review if done commit per commit.

Partitioner: action to delete an LVM VG

---

package/yast2-storage-ng.changes
src/lib/y2storage/partition_id.rb
test/y2storage/partition_id_test.rb

It fixes [bsc#1068087](https://bugzilla.suse.com/show_bug.cgi?id=1068087).

to_human_string do not raises an exception

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/proposal/devicegraph_generator.rb
test/data/devicegraphs/false-swaps.yml
test/y2storage/guided_proposal_test.rb

Fix for https://bugzilla.suse.com/show_bug.cgi?id=1071515
Includes regression test.

Avoid error caused by unformatted swap partitions

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/filesystems/btrfs.rb
test/data/devicegraphs/autoyast_drive_examples.yml
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/devicegraph_test.rb
test/y2storage/disk_test.rb
test/y2storage/filesystems/btrfs_test.rb
test/y2storage/partition_test.rb

Fixes [bsc#1076321](https://bugzilla.suse.com/show_bug.cgi?id=1076321) and [bsc#1076335](https://bugzilla.suse.com/show_bug.cgi?id=1076335).

Fix snapshots detection

---

package/yast2-storage-ng.changes
src/lib/y2partitioner/widgets/lvm_vg_devices_selector.rb

Part of PBI https://trello.com/c/dsn6CQmd/204-3-lvm-expert-partitioner-resize-a-vg.

Improve error message

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/delete_lvm_lv.rb
src/lib/y2partitioner/dialogs/blk_device_resize.rb
src/lib/y2storage/lvm_lv.rb
test/support/storage_helpers.rb
test/y2partitioner/actions/delete_lvm_lv_test.rb
test/y2partitioner/dialogs/blk_device_resize_test.rb
test/y2storage/lvm_lv_test.rb

PBI: https://trello.com/c/2F4R7E4p/207-1-lvm-expert-partitioner-delete-a-thin-provisioned-pool-and-volume
PBI: https://trello.com/c/6msuy7lb/206-2-lvm-expert-partitioner-resize-a-thin-provisioned-pool

Delete and resize lvm thin pools and volumes

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/clients/disk.rb

Together with https://github.com/openSUSE/packaging_rake_tasks/pull/45, this should fix https://bugzilla.suse.com/show_bug.cgi?id=1078900

Add a disk client as an alias for the partitioner one

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/proposal/autoinst_devices_creator.rb
src/lib/y2storage/proposal/lvm_creator.rb
src/lib/y2storage/proposal/md_creator.rb
test/y2storage/proposal/autoinst_devices_creator_test.rb
test/y2storage/proposal/lvm_creator_test.rb
test/y2storage/proposal/md_creator_test.rb

It should fix [bsc#1077277](https://bugzilla.suse.com/show_bug.cgi?id=1077277).

Reuse already existing (and even formatted) partitions as RAID or PV

---

doc/boot-requirements.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/boot_requirements_strategies/base.rb
src/lib/y2storage/boot_requirements_strategies/prep.rb
src/lib/y2storage/boot_requirements_strategies/uefi.rb
src/lib/y2storage/match_volume_spec.rb
test/data/devicegraphs/output/ppc_non_power_nv-lvm.yml
test/support/boot_requirements_uefi.rb
test/y2storage/boot_requirements_checker_ppc_test.rb
test/y2storage/boot_requirements_duplicate_test.rb
test/y2storage/boot_requirements_errors_test.rb
test/y2storage/proposal_scenarios_ppc_test.rb
test/y2storage/reusing_efi.rb

PBI: https://trello.com/c/qtgGEDBm/259-1-efi-weaken-the-expert-partition-checks

Fix sanity checks

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/hwinfo_reader.rb
test/data/hwinfo.txt
test/y2storage/hwinfo_reader_test.rb

Fixes [bsc#1080999](https://bugzilla.suse.com/show_bug.cgi?id=1080999).

Fix hwinfo parsing

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/callbacks/activate.rb
src/lib/y2storage/callbacks/probe.rb
src/lib/y2storage/storage_manager.rb

Minimal adaption to https://github.com/openSUSE/libstorage-ng/pull/475.

- adapted to callback improvements in libstorage-ng

---

package/yast2-storage-ng.changes
test/y2partitioner/widgets/pages/settings_test.rb
test/y2storage/storage_manager_test.rb
test/y2storage/sysconfig_storage_test.rb

Part of: https://trello.com/c/rsjOOfOt/66-3-partitioner-settings-mount-by

Avoid to write files in tests

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/edit_blk_device.rb
src/lib/y2partitioner/actions/resize_blk_device.rb
src/lib/y2storage/blk_device.rb
test/y2partitioner/actions/edit_blk_device_test.rb
test/y2partitioner/actions/resize_blk_device_test.rb
test/y2storage/blk_device_test.rb

PBI: https://trello.com/c/YYSoL44u/191-1-partitioner-prevent-editing-of-used-partitions

Prevent to modify used devices

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/controllers/lvm_vg.rb
test/y2partitioner/actions/controllers/lvm_vg_test.rb

[bsc#1077750](https://bugzilla.suse.com/show_bug.cgi?id=1077750)

Do not remove encryption when adding a device to an VG

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/callbacks/activate.rb
test/y2storage/callbacks/activate_test.rb

See https://github.com/openSUSE/libstorage-ng/pull/481.

- adapted to new activate callbacks in libstorage-ng

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/callbacks/activate.rb
src/lib/y2storage/hwinfo_reader.rb
test/data/hwinfo_bug1982536.txt
test/y2storage/callbacks/activate_test.rb
test/y2storage/hwinfo_reader_test.rb

See https://bugzilla.suse.com/show_bug.cgi?id=1082536
Bonus track: documentation and tests for changes introduced in #553

More robust parsing of hwinfo output (bsc#1082536) 

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/clone_disk.rb
src/lib/y2partitioner/actions/controllers/disk_device.rb
src/lib/y2partitioner/actions/delete_device.rb
src/lib/y2partitioner/actions/delete_disk.rb
src/lib/y2partitioner/actions/delete_lvm_lv.rb
src/lib/y2partitioner/actions/delete_lvm_vg.rb
src/lib/y2partitioner/actions/delete_md.rb
src/lib/y2partitioner/actions/delete_partition.rb
src/lib/y2partitioner/confirm_recursive_delete.rb
src/lib/y2partitioner/dialogs/disk_clone.rb
src/lib/y2partitioner/widgets/disk_expert_menu_button.rb
src/lib/y2storage/partitionable.rb
test/data/devicegraphs/mixed_disks_clone.yml
test/y2partitioner/actions/clone_disk_test.rb
test/y2partitioner/actions/controllers/disk_device_test.rb
test/y2partitioner/actions/delete_disk_test.rb
test/y2partitioner/actions/delete_lvm_lv_test.rb
test/y2partitioner/actions/delete_lvm_vg_test.rb
test/y2partitioner/actions/delete_md_test.rb
test/y2partitioner/actions/delete_partition_test.rb
test/y2partitioner/dialogs/disk_clone_test.rb
test/y2partitioner/dialogs/partition_type_test.rb
test/y2partitioner/widgets/disk_expert_menu_button_test.rb

PBI: https://trello.com/c/QYrAzDGf/67-3-storageng-expert-partitioner-allow-to-clone-a-disk

Clone disk

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/fstab_options.rb

https://trello.com/c/Sra3oujB/284-1-betasles15-p2-1066077-installer-default-swap-priority-differ-from-sles12

Use no swap prio, not 42

---

package/yast2-storage-ng.changes
src/lib/y2storage/autoinst_profile/drive_section.rb
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/autoinst_profile/partitioning_section.rb
src/lib/y2storage/autoinst_profile/raid_options_section.rb
src/lib/y2storage/filesystems/btrfs.rb
test/data/devicegraphs/autoyast_drive_examples.yml
test/data/devicegraphs/mixed_disks_btrfs.yml
test/y2partitioner/widgets/pages/btrfs_test.rb
test/y2storage/autoinst_profile/drive_section_test.rb
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/autoinst_profile/partitioning_section_test.rb
test/y2storage/autoinst_profile/raid_options_section_test.rb
test/y2storage/devicegraph_test.rb
test/y2storage/disk_test.rb
test/y2storage/filesystems/btrfs_test.rb
test/y2storage/partition_test.rb

This PR enables AutoYaST to export LVM configuration.

Export LVM and RAID

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/format_and_mount.rb

PBI: https://trello.com/c/r6sk4mQB/270-2-sles15-p2-1077868-storage-ng-expert-partitioner-has-several-issues-with-existing-partition-use

Allow to modify patition id

---

doc/old_and_new_proposal.md
test/data/control_files/volumes_ng/control.CAASP.xml

Add btrfs_read_only documentation

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/delete_device.rb
src/lib/y2partitioner/actions/delete_disk_device.rb
src/lib/y2partitioner/actions/delete_lvm_lv.rb
src/lib/y2partitioner/actions/delete_lvm_vg.rb
src/lib/y2partitioner/actions/delete_md.rb
src/lib/y2partitioner/actions/delete_partition.rb
src/lib/y2partitioner/confirm_recursive_delete.rb
src/lib/y2partitioner/widgets/device_delete_button.rb
src/lib/y2storage/boot_requirements_strategies/legacy.rb
src/lib/y2storage/partition.rb
test/y2partitioner/actions/delete_disk_device_test.rb
test/y2partitioner/actions/delete_lvm_lv_test.rb
test/y2partitioner/actions/delete_lvm_vg_test.rb
test/y2partitioner/actions/delete_md_test.rb
test/y2partitioner/actions/delete_partition_test.rb
test/y2partitioner/widgets/device_delete_button_test.rb
test/y2storage/partition_test.rb

PBI: https://trello.com/c/1AGO9Dkf/312-1-partitioner-work-with-implicit-partition-tables-s390

Partitioner works with implicit partition tables

---

package/yast2-storage-ng.changes
src/lib/y2storage/proposal/lvm_creator.rb
test/y2storage/proposal/lvm_creator_test.rb

See [bsc#1079369](https://bugzilla.suse.com/show_bug.cgi?id=1079369).

Fix space distribution on LVM VGs

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/proposal/partitions_distribution_calculator.rb

See [bsc#1085627](https://bugzilla.suse.com/show_bug.cgi?id=1085627).

Do not ignore small spaces when distributing space

---

package/yast2-storage-ng.changes
src/lib/y2partitioner/actions/controllers/filesystem.rb
src/lib/y2partitioner/actions/controllers/lvm_vg.rb
src/lib/y2partitioner/actions/controllers/md.rb
src/lib/y2partitioner/blk_device_restorer.rb
src/lib/y2partitioner/device_graphs.rb
test/data/devicegraphs/trivial_lvm_and_other_partitions.yml
test/y2partitioner/keep_original_filesystems_test.rb

See https://trello.com/c/DIOx0i1I/176-5-partitioner-prevent-data-loss-by-honoring-previous-state-when-editing

Avoid data loss in the partitioner

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/callbacks/activate.rb
test/y2storage/callbacks/activate_test.rb

First step for https://trello.com/c/T5rxuHfg/300-2-sles15-p1-1082542-build4731storage-ng-delete-lvmlv-failed-when-reinstall-on-encrypted-lvm

Honor LIBSTORAGE_MULTIPATH_AUTOSTART (for bsc#1082542)

---

package/yast2-storage-ng.changes
test/support/storage_helpers.rb

Part of PBI https://trello.com/c/jItiacnG/335-readd-system-wide-lock-in-libstorage-ng

Lock fix tests

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/callbacks/activate.rb
src/lib/y2storage/callbacks/libstorage_callback.rb
test/support/storage_helpers.rb
test/y2storage/callbacks/activate_test.rb
test/y2storage/callbacks/callbacks_examples.rb

Last step of https://trello.com/c/T5rxuHfg/300-2-sles15-p1-1082542-build4731storage-ng-delete-lvmlv-failed-when-reinstall-on-encrypted-lvm

Specific error for duplicate PVs

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/devicegraph.rb
src/lib/y2storage/storage_manager.rb
test/y2storage/devicegraph_test.rb

Fix for https://openqa.opensuse.org/tests/648323#step/upgrade_select/5

Ensure name lookups are done on raw_probed

---

package/yast2-storage-ng.changes
src/lib/y2partitioner/widgets/lvm_lv_attributes.rb
test/y2partitioner/widgets/lvm_lv_description_test.rb

Fixes [bsc#1087702](https://bugzilla.suse.com/show_bug.cgi?id=1087702).

Fix stripe_size call

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/controllers/filesystem.rb
src/lib/y2storage/filesystems/btrfs.rb
test/y2partitioner/actions/controllers/filesystem_test.rb
test/y2storage/filesystems/btrfs_test.rb

PBI: https://trello.com/c/wifz8OmW/341-2-sles15-p2-1087763-installer-doesnt-create-volumes-when-not-using-suggested-partitioning-scheme

Fix creation of default subvol

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/proposal/autoinst_devices_creator.rb
src/lib/y2storage/proposal/autoinst_devices_planner.rb
test/y2storage/proposal/autoinst_devices_creator_test.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb

Fixes [bsc#1081506](https://bugzilla.suse.com/show_bug.cgi?id=1081506).

AutoYaST partition_type support

---

doc/old_and_new_proposal.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/dialogs/main.rb
src/lib/y2storage/callbacks/initialize.rb
src/lib/y2storage/clients/inst_disk_proposal.rb
src/lib/y2storage/dialogs/guided_setup.rb
src/lib/y2storage/dialogs/guided_setup/select_filesystem/ng.rb
src/lib/y2storage/dialogs/guided_setup/select_scheme.rb
src/lib/y2storage/dialogs/proposal.rb
test/y2partitioner/dialogs/main_test.rb
test/y2storage/clients/inst_disk_proposal_test.rb
test/y2storage/dialogs/guided_setup/select_filesystem/ng_test.rb
test/y2storage/dialogs/guided_setup/select_scheme_test.rb
test/y2storage/dialogs/guided_setup_test.rb
test/y2storage/dialogs/proposal_test.rb

PBI: https://trello.com/c/nujLPA7G/342-2-sles15-p1-1087486-storage-ng-various-storage-ng-related-controlxml-parameters-not-working

Support missing settings

---

package/yast2-storage-ng.changes
src/lib/y2partitioner/ui_state.rb
src/lib/y2partitioner/widgets/pages/device_graph.rb
src/lib/y2partitioner/widgets/pages/lvm.rb
src/lib/y2partitioner/widgets/pages/md_raids.rb

Fix [bsc#1081571](https://bugzilla.suse.com/show_bug.cgi?id=1081571).

Fix i18n issues

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/clients/inst_disk_proposal.rb
src/clients/partitioner.rb
src/clients/partitioner_testing.rb
src/clients/partitions_proposal.rb
src/clients/storage_finish.rb
src/lib/y2partitioner/clients/main.rb
src/lib/y2partitioner/dialogs/main.rb
src/lib/y2partitioner/dialogs/summary.rb
src/lib/y2partitioner/widgets/pages/summary.rb
src/lib/y2partitioner/widgets/rescan_devices_button.rb
src/lib/y2partitioner/widgets/summary_text.rb
src/lib/y2storage/clients/inst_disk_proposal.rb
src/lib/y2storage/clients/partitions_proposal.rb
test/y2partitioner/clients/main_test.rb
test/y2partitioner/dialogs/main_test.rb
test/y2partitioner/dialogs/summary_test.rb
test/y2partitioner/widgets/rescan_devices_button_test.rb
test/y2partitioner/widgets/summary_text_test.rb
test/y2storage/clients/inst_disk_proposal_test.rb
test/y2storage/clients/partitions_proposal_test.rb

PBI: https://trello.com/c/VjBb7Jxy/347-0-sles15-p3-1086892-slex15loc-yastalllangsuntranslated-modify-the-disks-confirmation-pop-up-after-finishing-changes-in-expert-pa

Add partitioner confirmations

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/storage_manager.rb
test/y2storage/storage_manager_test.rb

replaces https://github.com/yast/yast-storage-ng/pull/621

Light probe

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/proposal/autoinst_devices_planner.rb
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb

* Fixes [bsc#1091669](https://bugzilla.suse.com/show_bug.cgi?id=1091669) and [bsc#1090095](https://bugzilla.suse.com/show_bug.cgi?id=1091669)
* Related to https://github.com/yast/yast-storage-ng/pull/627
* Trello cards: https://trello.com/c/xjlFsCBz and https://trello.com/c/nTbvDnuU/

Properly handle subvolumes/subvolumes_prefix

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/quit_partitioner.rb
src/lib/y2partitioner/device_graphs.rb
src/lib/y2partitioner/dialogs/base.rb
src/lib/y2partitioner/dialogs/blk_device_resize.rb
src/lib/y2partitioner/dialogs/encrypt_password.rb
src/lib/y2partitioner/dialogs/format_and_mount.rb
src/lib/y2partitioner/dialogs/lvm_lv_info.rb
src/lib/y2partitioner/dialogs/lvm_lv_size.rb
src/lib/y2partitioner/dialogs/lvm_vg.rb
src/lib/y2partitioner/dialogs/main.rb
src/lib/y2partitioner/dialogs/md.rb
src/lib/y2partitioner/dialogs/md_options.rb
src/lib/y2partitioner/dialogs/md_resize.rb
src/lib/y2partitioner/dialogs/partition_role.rb
src/lib/y2partitioner/dialogs/partition_size.rb
src/lib/y2partitioner/dialogs/partition_table_type.rb
src/lib/y2partitioner/dialogs/partition_type.rb
src/lib/y2partitioner/dialogs/popup.rb
src/lib/y2partitioner/dialogs/summary.rb
src/lib/y2partitioner/widgets/configure.rb
src/lib/y2partitioner/widgets/rescan_devices_button.rb
src/lib/y2storage/clients/inst_disk_proposal.rb
test/support/partitioner_reprobe_examples.rb
test/y2partitioner/actions/quit_partitioner_test.rb
test/y2partitioner/device_graphs_test.rb
test/y2partitioner/dialogs/main_test.rb
test/y2partitioner/dialogs/summary_test.rb
test/y2storage/clients/inst_disk_proposal_test.rb

PBI: https://trello.com/c/Lqos3IvN/238-2-partitioner-fix-abort-and-back-buttons
Manually tested.

Fix partitioner buttons

---

package/yast2-storage-ng.changes
src/lib/y2storage/callbacks/libstorage_callback.rb
src/lib/y2storage/md.rb
src/lib/y2storage/md_container.rb
src/lib/y2storage/md_member.rb
src/lib/y2storage/storage_env.rb
test/y2storage/md_container_test.rb
test/y2storage/md_member_test.rb
test/y2storage/md_test.rb

PBI: https://trello.com/c/z4eVEC6E/385-https-bugzillasusecom-showbugcgiid1092417

Allow to consider MDs as BIOS RAIDs

---

doc/user-stories/expert-partitioner.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/move_partition.rb
src/lib/y2partitioner/dialogs/partition_move.rb
src/lib/y2partitioner/dialogs/popup.rb
src/lib/y2partitioner/widgets/pages/disk.rb
src/lib/y2partitioner/widgets/pages/disks.rb
src/lib/y2partitioner/widgets/pages/partition.rb
src/lib/y2partitioner/widgets/partition_move_button.rb
test/y2partitioner/actions/move_partition_test.rb
test/y2partitioner/dialogs/partition_move_test.rb
test/y2partitioner/widgets/pages/disk_test.rb
test/y2partitioner/widgets/pages/disks_test.rb
test/y2partitioner/widgets/pages/partition_test.rb
test/y2partitioner/widgets/partition_move_button_test.rb

PBI: https://trello.com/c/CwguWHoI/174-5-partitioner-plain-partitioning-move

Move partitions

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/dialogs/btrfs_subvolume.rb
src/lib/y2storage/filesystems/btrfs.rb
test/y2partitioner/dialogs/btrfs_subvolume_test.rb
test/y2storage/filesystems/btrfs_test.rb

PBI: https://trello.com/c/KHSMmp19/392-sles15-p2p1-1067510-build3334storage-ng-partitioner-in-installed-system-add-snapshots-1-snapshot-prefix-to-the-subvolumes

Fix subvolume creation

---

.travis.yml
test/spec_helper.rb
test/y2storage/dump_manager_test.rb

Just merging #657 and #661 to `master`.

Merge SLE15 to master (DumpManager mock, parallel Travis)

---

.coveralls.yml
.gitignore
.rspec_parallel
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
test/spec_helper.rb

Just merging #663 to master.
You can see the speed up for unit tests at Travis:
- In the [previous build](https://travis-ci.org/yast/yast-storage-ng/builds/391281685) it took 4 min 53 sec
- In the [latest build](https://travis-ci.org/yast/yast-storage-ng/builds/391284699) with parallel_tests it took only 3 min 27 sec

Parallel tests master

---

package/yast2-storage-ng.spec

Sync master again

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/callbacks/libstorage_callback.rb
test/y2storage/callbacks/callbacks_examples.rb

Merge #675 (fixed callback crash) to master

---

Rakefile
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/controllers/fstabs.rb
src/lib/y2partitioner/dialogs/import_mount_points.rb
src/lib/y2partitioner/widgets/fstab_selector.rb
src/lib/y2storage/blk_device.rb
src/lib/y2storage/crypttab.rb
src/lib/y2storage/disk_analyzer.rb
src/lib/y2storage/encryption.rb
src/lib/y2storage/existing_filesystem.rb
src/lib/y2storage/simple_etc_fstab_entry.rb
test/y2partitioner/actions/controllers/fstabs_test.rb
test/y2partitioner/dialogs/import_mount_points_test.rb
test/y2storage/crypttab_test.rb
test/y2storage/devicegraph_test.rb
test/y2storage/disk_analyzer_test.rb
test/y2storage/encryption_test.rb
test/y2storage/existing_filesystem_test.rb
test/y2storage/simple_etc_fstab_entry_test.rb

PBI: https://trello.com/c/S2PrGCQz/388-ostumbleweed-p5-1094924-partition-imported-during-installation-would-all-be-formatted-by-default

Add format checkbox when importing mount points

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/desktop/disk.desktop

Please review the following changes:
* 021c05bb Merge remote-tracking branch 'origin/SLE-15-GA'
* 7d454be3 Added additional searchkeys to desktop file

[Review] Request from 'schubi2' @ 'yast/yast-storage-ng/review_180629_merged_with_sles15'

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/dialogs/partition_size.rb
test/y2partitioner/dialogs/partition_size_test.rb

See https://trello.com/c/WERj3HSs/146-3-sles15-p5-1097634-expert-partitioner-tries-to-create-primary-partition-inside-extended

Partitioner: offer only correct regions to create partitions 

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/dialogs/partition_size.rb
test/y2partitioner/dialogs/partition_size_test.rb

Merge to master of #690 
See https://trello.com/c/WERj3HSs/146-3-sles15-p5-1097634-expert-partitioner-tries-to-create-primary-partition-inside-extended

Merge into master: offer only correct regions to create partitions

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/drive_section.rb

It merges #695 and fixes (https://bugzilla.novell.com/show_bug.cgi?id=1103190)

Merge SLE-15-GA into master

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/add_partition.rb
src/lib/y2partitioner/actions/controllers/partition.rb
src/lib/y2partitioner/dialogs/partition_type.rb
test/y2partitioner/actions/add_partition_test.rb
test/y2partitioner/actions/controllers/partition_test.rb
test/y2partitioner/dialogs/partition_type_test.rb

https://trello.com/c/ewWzf3Vk
Probably not the best solution, so just provided a quick fix in order to check the problem

Skip partition type dialog when going back if it needs to be skipped

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/planned/can_be_formatted.rb
test/y2storage/planned/can_be_formatted_test.rb

Fixes [bsc#1104774](https://bugzilla.suse.com/show_bug.cgi?id=1104774).

Set mount_by option when reusing devices

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/planned.rb
src/lib/y2storage/planned/device.rb
src/lib/y2storage/planned/stray_blk_device.rb
src/lib/y2storage/proposal/autoinst_devices_creator.rb
src/lib/y2storage/proposal/autoinst_devices_planner.rb
src/lib/y2storage/proposal/autoinst_drives_map.rb
test/y2storage/autoinst_proposal_test.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb

This is the merge to the master branch of #711 See that PR for more info

Merge to master: process Xen virtual partitions from AutoYaST profiles

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/clients/partitions_proposal.rb
test/data/devicegraphs/empty_hard_disk_128MiB.yml
test/y2storage/clients/partitions_proposal_test.rb

Merge of PR#710 (SLE-15-GA) to master

Prevent nil:NilClass crash in Kubic if disk too small

---

doc/partitioner-checks.md

Maybe this should go to `master` only?

document (old) partitioner checks

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/md_description.rb

Companion to https://github.com/openSUSE/libstorage-ng/pull/554
for https://trello.com/c/8kPdHfZR

RAID attributes: include "Active: Yes/No"

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/md_description.rb
test/y2partitioner/actions/controllers/filesystem_test.rb

Merge two PRs to master (one of them fixing the build failure)

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/controllers/md.rb
test/y2partitioner/actions/controllers/md_test.rb

Refinement over https://trello.com/c/G8Or8z0z/211-3-full-disks-as-member-of-md since we refined the requirements a little bit more after some chat with @aschnell

Partitioner: do not offer RAID partitions to create another RAID

---

src/lib/y2storage/fake_device_factory.rb
src/lib/y2storage/yaml_writer.rb
test/data/devicegraphs/formatted_md.yml
test/data/devicegraphs/partitioned_md.yml
test/y2storage/fake_device_factory_test.rb
test/y2storage/yaml_writer_test.rb

Part of PBI https://trello.com/c/itizMqBG/274-5-partitions-in-raid

Yaml support for importing/exporting Md devices

---

test/y2storage/disk_analyzer_test.rb

This should fix the building issues on IBS https://build.suse.de/package/live_build_log/Devel:YaST:Head/yast2-storage-ng/SUSE_SLE-15-SP1_GA/s390x

Fix testsuite in non-windows architectures

---

src/lib/y2partitioner/actions/edit_blk_device.rb
src/lib/y2partitioner/actions/filesystem_steps.rb
src/lib/y2storage/blk_device.rb
test/y2partitioner/actions/edit_blk_device_test.rb
test/y2storage/blk_device_test.rb

Part of https://trello.com/c/5rrmzwKh/276-3-partitioner-unleash-the-beast

Fix some minor issues related to editing block devices

---

src/lib/y2storage/proposal/autoinst_devices_creator.rb
test/y2storage/proposal/autoinst_devices_creator_test.rb

This PR fixes the AutoYaST proposal so the devices to reuse are processed before creating new ones. This is useful when, for instance, we want to resize a partition. In such a case, it might happen that we have more (or less) space available for new partitions (or logical volumes).

Reuse devices first; reuse later

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec

Bump version and update changes file

---

src/lib/y2partitioner/widgets/pages/lvm_vg.rb

To fix the current build failure.

Add missing require

---

src/lib/y2storage/disk_analyzer.rb
src/lib/y2storage/guided_proposal.rb
src/lib/y2storage/partition.rb
src/lib/y2storage/proposal/devices_planner_strategies/base.rb
src/lib/y2storage/proposal/space_maker.rb
test/support/devices_planner_context.rb
test/support/storage_helpers.rb
test/y2storage/disk_analyzer_test.rb
test/y2storage/guided_proposal_test.rb
test/y2storage/partition_test.rb
test/y2storage/proposal/devices_planner_strategies/legacy_test.rb
test/y2storage/proposal/devices_planner_strategies/ng_test.rb
test/y2storage/proposal/space_maker_test.rb

Related to fate#326573 (see https://trello.com/c/atCIY5jT for detailed info) and [bug#1092417](https://bugzilla.novell.com/show_bug.cgi?id=1092417).
---
Initial proposal using the devicegraph from bsc#1092417 logs:
:file_cabinet:  [bug_1092417_devicegraph.xml.zip](https://github.com/yast/yast-storage-ng/files/2543109/bug_1092417_devicegraph.xml.zip)

Make the proposal work on top of existing MD RAIDs

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec

Forgotten in https://github.com/yast/yast-storage-ng/pull/791

Update version and changelog

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/proposal/space_maker.rb
src/lib/y2storage/proposal/space_maker_prospects.rb
src/lib/y2storage/proposal/space_maker_prospects/base.rb
src/lib/y2storage/proposal/space_maker_prospects/delete_partition.rb
src/lib/y2storage/proposal/space_maker_prospects/list.rb
src/lib/y2storage/proposal/space_maker_prospects/partition_prospect.rb
src/lib/y2storage/proposal/space_maker_prospects/resize_partition.rb
src/lib/y2storage/proposal/space_maker_prospects/wipe_disk.rb
test/data/devicegraphs/irst-windows-linux.yml
test/y2storage/proposal_irst_test.rb

Main PR for https://trello.com/c/DVQH3p2n/397-bug1057436-improve-confusing-spacemaker-strategy-fate325885-preserve-irst-partitions-in-guided-proposal
Review commit by commit.
Bonus: fixed 4 historical CodeClimate issues in SpaceMaker

SpaceMaker: IRST support + extract prospect actions to dedicated classes

---

test/y2partitioner/widgets/format_and_mount_test.rb

Related to PBI: https://trello.com/c/xra7ISEF/487-support-udf-filesystem-in-partitioner

Add unit tests

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/dialogs/btrfs_subvolume.rb
test/y2partitioner/dialogs/btrfs_subvolume_test.rb

PBI: https://trello.com/c/m7eAH7Dw/525-storage-subvolumes

Avoid unsafe characters for subvolumes path

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/existing_filesystem.rb
test/y2storage/existing_filesystem_test.rb

Part of PBI: https://trello.com/c/AzEDChwZ/520-issues-from-yast-audit-systemlog-backtickslog

Hardening execution of commands

---

src/lib/y2storage/planned/assigned_space.rb
src/lib/y2storage/proposal/partitions_distribution_calculator.rb
test/y2storage/proposal/partitions_distribution_calculator_test.rb

Final polishing for https://trello.com/c/gdXTlipJ/603-1-bug1121286-implement-better-calculation-of-resize-windows
As requested during the review of #822

Improve documentation and unit tests

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/callbacks/libstorage_callback.rb
test/y2storage/callbacks/callbacks_examples.rb

For https://bugzilla.suse.com/show_bug.cgi?id=1115807.

do not show hint for details button if button does not exist

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec

This is just the version and changelog entry that were missing at #835

Version and changelog missed at #835

---

package/yast2-storage-ng.changes

Cleanup for #800 (master), just like #817 does for #799 (SLE-15-GA).

Fix bug # for 4.1.32 changelog.

---

test/y2partitioner/actions/add_partition_test.rb

Failing test when accessing to a destroyed `Region` object.
- Related to https://github.com/yast/yast-storage-ng/pull/856
Avoid references to a `Region` susceptible to be destroyed by the Garbage Collector + C++ destructor.
NOTE: version was willfully not bumped. Another PR is coming, see https://github.com/yast/yast-storage-ng/pull/858.

Fix testsuite

---

doc/boot-partition-location.md
doc/boot-requirements.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/boot_requirements_strategies/legacy.rb
src/lib/y2storage/boot_requirements_strategies/prep.rb
src/lib/y2storage/boot_requirements_strategies/uefi.rb
test/support/boot_requirements_uefi.rb
test/support/proposed_partitions_examples.rb
test/y2storage/boot_requirements_checker_ppc_test.rb
test/y2storage/boot_requirements_checker_x86_test.rb
test/y2storage/guided_proposal_test.rb
test/y2storage/initial_guided_proposal_test.rb

The boot loader should be installed on the same disk that gets the operating system (root partition).
- Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1094927
- Scrum board: https://trello.com/c/zgu7Iq9V
Documentation adjusted and implemented according to doc.
- updated and added unit tests
- manual integration tests

document boot partition strategy

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_issues/list.rb
src/lib/y2storage/autoinst_profile/drive_section.rb
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/autoinst_profile/partitioning_section.rb
src/lib/y2storage/planned.rb
src/lib/y2storage/planned/devices_collection.rb
src/lib/y2storage/planned/md.rb
src/lib/y2storage/planned/nfs.rb
src/lib/y2storage/proposal/autoinst_devices_creator.rb
src/lib/y2storage/proposal/autoinst_devices_planner.rb
src/lib/y2storage/proposal/autoinst_drives_map.rb
src/lib/y2storage/proposal/autoinst_nfs_planner.rb
src/lib/y2storage/proposal/nfs_creator.rb
test/support/storage_helpers.rb
test/y2storage/autoinst_profile/drive_section_test.rb
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/autoinst_profile/partitioning_section_test.rb
test/y2storage/autoinst_proposal_nfs_test.rb
test/y2storage/planned/devices_collection_test.rb
test/y2storage/proposal/autoinst_devices_creator_test.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb
test/y2storage/proposal/autoinst_drives_map_test.rb
test/y2storage/proposal/autoinst_nfs_planner_test.rb
test/y2storage/proposal/nfs_creator_test.rb

Backporting PR https://github.com/yast/yast-storage-ng/pull/884.

Backport: Add support for NFS in AutoYaST

---

src/lib/y2storage/proposal/autoinst_nfs_planner.rb

See https://github.com/yast/yast-storage-ng/pull/890.

Merge SLE-15-SP1 branch

---

.cirrus.yml
.yardopts

Travis is sometimes too slow and does not support Docker builds directly (only running docker commands inside an Ubuntu VM).
Experimentally try another CI: https://cirrus-ci.com/

Added .cirrus.yml

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/initial_guided_proposal.rb
src/lib/y2storage/proposal/settings_generator/base.rb
src/lib/y2storage/proposal_settings.rb
test/y2storage/initial_guided_proposal_test.rb
test/y2storage/proposal/settings_generator/legacy_test.rb
test/y2storage/proposal/settings_generator/ng_test.rb
test/y2storage/proposal_settings_test.rb

Merge SLE-15-SP1

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/boot_requirements_checker.rb

See https://github.com/yast/yast-storage-ng/pull/892.

Merge SLE-15-GA

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/drive_section.rb
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/autoinst_profile/partitioning_section.rb
src/lib/y2storage/proposal/autoinst_devices_planner.rb
src/lib/y2storage/proposal/autoinst_nfs_planner.rb
test/y2storage/autoinst_profile/drive_section_test.rb
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/autoinst_profile/partitioning_section_test.rb
test/y2storage/autoinst_proposal_nfs_test.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb
test/y2storage/proposal/autoinst_nfs_planner_test.rb

Backporting https://github.com/yast/yast-storage-ng/pull/896.

Backport: Add support for NFS in Autoyast (new format)

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/pages/bcaches.rb

Some strings in the Partitioner are not being displayed in the correct language
- https://bugzilla.suse.com/show_bug.cgi?id=1126822
Merge the pull request #905 to master also.
For more details, see that pull request.

Merge #905 to master

---

README.md

README.md - Added Cirrus CI badge

---

doc/btrfs_in_partitioner.md

The documentation was incomplete (the exact labels to be introduced/changed were not explained) and outdated (we actually decided to take a different approach that does not imply modifying those dialogs).
Document updated
https://trello.com/c/Icti2ZBT/947-3-partitioner-editing-btrfs-filesystems

btrfs_in_partitioner.md: more details about edit devices

---

doc/multipath-setup.md

I needed to test YaST behavior with multipath disks and had no actual multipath hardware.
- https://bugzilla.suse.com/show_bug.cgi?id=1130988
- https://trello.com/c/gAJZHQuD
Eventually I figured out a way to simulate it with QEMU.

Setting up Virtual Multipath Hardware for Testing (bsc#1130988)

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/proposal_settings.rb

https://trello.com/c/tYqIvWA4
Not all ng proposal settings are logged, making it hard to debug issues in the guided proposal.
Log all relevant settings.
Tested manually

log all ng proposal settings

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/encryption_type.rb
test/y2storage/dialogs/proposal_exception_test.rb

The new enum value has to be handled, otherwise the test suite fails.

added translation for new EncryptionType::PLAIN

---

src/clients/partitioner.rb

I know that storage-ng can work on simulated hardware but I forget how to do it. When I look into the entry point (clients/partitioner.rb) it does not tell me.
Put a comment there reminding me how to do it
- Tested manually on 01-probed.xml from https://bugzilla.suse.com/attachment.cgi?id=803468&action=edit

Point to partitioner_testing

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/resize_info.rb

For https://trello.com/c/gzVGeo2J/1288-3-resizing-of-luks2.

Added translation for new enum value RB_PASSWORD_REQUIRED.

---

package/yast2-storage-ng.changes

For https://trello.com/c/gzVGeo2J/1288-3-resizing-of-luks2.

added newly created bugzilla number

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/encrypt_method_options.rb

Fixes [bsc#1154364](https://bugzilla.suse.com/show_bug.cgi?id=1154364).

Fix encryption widgets i18n

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/partitioning_section.rb
src/lib/y2storage/proposal/autoinst_devices_planner.rb
src/lib/y2storage/proposal/autoinst_drives_map.rb
test/y2storage/autoinst_profile/partitioning_section_test.rb
test/y2storage/proposal/autoinst_devices_planner_test.rb

 AutoYaST: CT_DMMULTIPATH handling (master)

---

doc/autoyast.md

Update AutoYaST and storage-ng documentation. See https://trello.com/c/SjtD2G62/1403-3-step-1-clarify-update-autoyast-documentation-regarding-storage.

AutoYaST documentation update

---

doc/autoyast.md

Removes the TODO items from the AutoYaST developer documentation.

Update AutoYaST developer documentation

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/help.rb
src/lib/y2partitioner/widgets/pages/nfs_mounts.rb
src/lib/y2partitioner/yast_nfs_client.rb
src/lib/y2storage/filesystems/legacy_nfs.rb
src/lib/y2storage/mount_point.rb
test/y2partitioner/widgets/pages/nfs_mounts_test.rb

Forward port https://github.com/yast/yast-storage-ng/pull/1021.

Improve integration of NFS client (forward port)

---

src/lib/y2partitioner/actions/resize_blk_device.rb

Improved recently added message.

improved message

---

test/y2storage/autoinst_proposal_test.rb

Minor RSpec description improvement.

Improve test description

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/storage_manager.rb
test/y2storage/storage_manager_test.rb

This merges the fix from #1074 into the master branch. See that pull request for details about the problem and the solution.
- Tested manually also in master

Refresh the system devicegraph when reprobing (bsc#1168325), master branch

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/callbacks/activate.rb
src/lib/y2storage/storage_env.rb
test/y2storage/callbacks/activate_test.rb
test/y2storage/storage_env_test.rb

PR https://github.com/yast/yast-storage-ng/pull/1077 for master.

allow to disable LUKS activation (bsc#1162545)

---

doc/old_and_new_proposal.md
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/clients/inst_disk_proposal.rb
src/lib/y2storage/dialogs/guided_setup.rb
src/lib/y2storage/dialogs/guided_setup/select_filesystem/ng.rb
src/lib/y2storage/dialogs/guided_setup/select_scheme.rb
test/data/control_files/bug_1078691.xml
test/data/control_files/volumes_ng/control.CAASP.xml
test/data/control_files/volumes_ng/control.SLE-like.xml
test/data/control_files/volumes_ng/control.SLE-with-data.xml
test/y2storage/clients/inst_disk_proposal_test.rb
test/y2storage/dialogs/guided_setup/select_filesystem/ng_test.rb
test/y2storage/dialogs/guided_setup/select_scheme_test.rb
test/y2storage/dialogs/guided_setup_test.rb

- https://bugzilla.suse.com/show_bug.cgi?id=1171423
- https://trello.com/c/BqWDHmp1
Remove obsolete `proposal_settings_editable` setting.

remove obsolete proposal_settings_editable

---

doc/partitioner_ui.md
doc/partitioner_ui/ideas/overview.md

We are collecting ideas for the UI of the partitioner at `doc/partitioner_ui.md`
This pull request adds another one.
For a more pleasant review, use the "view file" option on the markdown file.

New idea for partitioner_ui: overview tab

---

package/yast2-storage-ng.changes

See https://bugzilla.suse.com/show_bug.cgi?id=1172164.

added bug number for tools

---

doc/partitioner_ui.md
doc/partitioner_ui/ideas/grouped_techs.md

A new idea for the new Partitioner UI.

Proposal for Partitioner UI

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/storage_feature.rb

See https://github.com/yast/yast-storage-ng/pull/1107. Additionally handle UF_PMEM.

Bsc1172866

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_proposal.rb
src/lib/y2storage/proposal_settings.rb
test/y2storage/autoinst_proposal_test.rb
test/y2storage/proposal_settings_test.rb

See https://github.com/yast/yast-storage-ng/pull/1109.

AutoYaST delegates to initial proposal (forward-port to master)

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/planned/can_be_formatted.rb
test/y2storage/proposal_separate_vgs_test.rb

Merge of #1113 into master. See that pull request for details

Merge to master: detect subvolumes shadowed by a separate_vg (bug#1174475)

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_proposal.rb
src/lib/y2storage/proposal/base.rb
test/y2storage/autoinst_proposal_test.rb

Merge of #1115 into master. See that pull request for details

Merge to master: fix bug when AutoinstProposal find no devices (bsc#1174469) 

---

package/yast2-storage-ng.changes
src/lib/y2storage/proposal/autoinst_space_maker.rb

Merge #1118 into master. It adds a line to the changes log that was omitted in the original #1056 and it should have been added in the #1057.

Merge SLE-15-SP2 into master

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/format_and_mount.rb
test/y2partitioner/widgets/format_and_mount_test.rb

There is a code typo making to raise an exception:
* https://bugzilla.suse.com/show_bug.cgi?id=1181348
Typo fixed.

Partitioner: Fix code typo

---

doc/old_and_new_proposal.md

The documents about the storage proposal were messy because they were left in a state where they documented the transformation process from yast-storage into yast-storage-ng instead of focusing on the status quo.
1) The reference documentation of the control file (at the yast-installation repo) was still describing the old yast-storage format
2) The more detailed documentation in this repo was written as some kind of list of differences with the obsolete old format, instead of simply describing the present.
The solution comes in two pull requests: this one and https://github.com/yast/yast-installation/pull/909
This one updates the information regarding how the proposal works, removing a lot of information that has been moved to the general control file document (see the mentioned …

Update proposal documentation (bsc#1175098)

---

.github/workflows/ci.yml
Rakefile

Merges #1216 into master.

---

package/yast2-storage-ng.changes

Just fixes a typo in the changes file.

Fix a typo in the changes file

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec

See https://github.com/yast/yast-storage-ng/pull/1231.

Recommends libyui-qt-graph (backport to SLE-15-SP3)

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
test/y2storage/encryption_processes/secure_key_test.rb

adapt calling named parameters to ruby3

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec

Version and changelog

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/issues_reporter.rb
test/y2storage/issues_reporter_test.rb

Crash when reporting issue in TW due to new ruby.
- https://bugzilla.suse.com/show_bug.cgi?id=1194342
Adapt code.
- adapted unit test, so it failed without fix.

Issues reporter

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/configure_actions.rb
src/lib/y2partitioner/widgets/overview.rb
src/lib/y2partitioner/yast_nfs_client.rb
src/lib/y2storage/package_handler.rb
test/y2partitioner/actions/configure_actions_test.rb
test/y2partitioner/widgets/overview_test.rb
test/y2partitioner/widgets/pages/nfs_mounts_test.rb
test/y2storage/package_handler_test.rb

Adapt to `Package` and `PackageSystem` changes. See https://github.com/yast/yast-yast2/pull/1219 for further information.

Use `Package` instead of `PackageSystem`

---

test/y2partitioner/actions/edit_nfs_test.rb
test/y2partitioner/dialogs/nfs_test.rb
test/y2storage/filesystems/legacy_nfs_test.rb
test/y2storage/filesystems/nfs_test.rb

Continuation of #1283 (it adds the tests that were missing there)

Tests for the recent code

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/filesystems/blk_filesystem.rb
src/lib/y2storage/luks.rb
test/y2storage/filesystems/blk_filesystem_test.rb
test/y2storage/luks_test.rb

It merges #1291 & #1293 into SLE-15-SP3

Merge 'SLE-15-SP2' into 'SLE-15-SP3'

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/filesystems/blk_filesystem.rb
src/lib/y2storage/luks.rb
test/y2storage/filesystems/blk_filesystem_test.rb
test/y2storage/luks_test.rb

It merges #1292 into 'SLE-15-SP3'

Merge SLE-15-SP3 into SLE-15-SP4

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/filesystems/blk_filesystem.rb
src/lib/y2storage/luks.rb
test/y2storage/filesystems/blk_filesystem_test.rb
test/y2storage/luks_test.rb

It merges #1291 (description & info), #1292, #1293 (extends #1291), #1294 into master

Merge 'SLE-15-SP4' into 'master'

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/tmpfs_filesystems_table.rb

Not localized text in tmpfs widget
- https://bugzilla.suse.com/show_bug.cgi?id=1198192
mark for localization

Loc fix sp4

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/tmpfs_filesystems_table.rb

merge of https://github.com/yast/yast-storage-ng/pull/1299

Loc fix master

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/widgets/overview.rb
src/lib/y2storage/dialogs/proposal.rb
src/lib/y2storage/setup_checker.rb
src/lib/y2storage/setup_errors_presenter.rb
src/lib/y2storage/with_security_policies.rb
test/y2partitioner/widgets/overview_test.rb
test/y2storage/dialogs/proposal_test.rb
test/y2storage/setup_checker_test.rb
test/y2storage/setup_errors_presenter_test.rb

Merge security policies into `master`

Merge security policies into master

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/dialogs/guided_setup/select_scheme.rb

bsc#1209697 (master): fix widgets titles in the dialog to select a partitioning schema

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec

I forgot to include the corresponding changelong entry and version bump as part of #1327 
Add the missing bits so our CI effectively submits the fix to Tumbleweed.

Version and changelog for previous pull request

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/controllers/md.rb
src/lib/y2partitioner/dialogs/md_options.rb
src/lib/y2storage/autoinst_profile/raid_options_section.rb
src/lib/y2storage/md.rb
src/lib/y2storage/md_parity.rb
src/lib/y2storage/proposal/autoinst_md_planner.rb
test/y2partitioner/actions/controllers/md_test.rb
test/y2storage/autoinst_profile/raid_options_section_test.rb
test/y2storage/autoinst_proposal_md_test.rb

This is a merge to master of #1331. Check that pull request for details.

Fixes related to RAID parity and chunk size

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/dialogs/guided_setup/helpers/disk.rb
test/y2storage/dialogs/guided_setup/helpers/disk_test.rb

This is a merge to master of #1333. See that pull request for details

[Master] Guided Setup: display a hint for disks with sensible transports

---

.github/workflows/ci.yml
package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/encryption.rb
src/lib/y2storage/encryption_method/luks2.rb
src/lib/y2storage/planned/can_be_encrypted.rb
src/lib/y2storage/proposal/autoinst_drive_planner.rb
test/y2storage/autoinst_profile/partition_section_test.rb
test/y2storage/autoinst_proposal_encryption_test.rb

This is a merge of #1355 to the master branch. See the original pull request for details.
Bear in mind this is the first merge ever from SLE-15-SP6 into master in this repository.

AutoYaST (master): support for advanced LUKS(2) settings

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/raid_options_section.rb
src/lib/y2storage/md_level.rb

This is a merge to the SLE-15-SP6 branch of https://github.com/yast/yast-storage-ng/pull/1354.
That pull request was already tested, approved and verified to work by the reporter.
The corresponding merge to SLE-15-SP5 can be found at #1358.

Support probing of linear RAIDs (SP6)

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/autoinst_profile/raid_options_section.rb
src/lib/y2storage/md_level.rb

This is a merge to the master branch of #1354.
That pull request was already tested, approved and verified to work by the reporter.
The corresponding merges to SLE-15-SP5 and SLE-15-SP6 can be found at #1358 and #1359.

Support probing of linear RAIDs (master)

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2storage/proposal/lvm_helper.rb
src/lib/y2storage/proposal_settings.rb
src/lib/y2storage/storage_env.rb
test/y2storage/storage_env_test.rb

Followup of https://github.com/yast/yast-storage-ng/pull/1365

Merged sle15sp6

---

package/yast2-storage-ng.changes
package/yast2-storage-ng.spec
src/lib/y2partitioner/actions/controllers/encryption.rb
src/lib/y2storage/autoinst_profile/partition_section.rb
src/lib/y2storage/planned/can_be_encrypted.rb
src/lib/y2storage/proposal/autoinst_drive_planner.rb
test/y2storage/autoinst_proposal_encryption_test.rb

AutoYaST part of pervasive encryption (master)
