yast/yast-storage-ng

- README.md
- Rakefile
@aschnell maybe it would be a good idea to delete `home:aschnell:storage-redesign` to avoid future confusion.
> Adapted to new OBS location

- src/lib/storage/devices_list.rb
- src/lib/storage/disks_list.rb
- src/lib/storage/filesystems_list.rb
- src/lib/storage/free_disk_spaces_list.rb
- src/lib/storage/partitions_list.rb
- src/lib/storage/proposal/devicegraph_generator.rb
- src/lib/storage/proposal/partition_creator.rb
- src/lib/storage/proposal/settings.rb
- src/lib/storage/proposal/space_maker.rb
- src/lib/storage/refinements/devicegraph_lists.rb
- test/data/input/mixed_disks.yml
- test/devices_list_test.rb
- test/proposal/partition_creator_test.rb
- test/proposal/space_maker_test.rb
Inline documentation is still missing
Some usage examples
```ruby
using DevicegraphLists
disks = a_devicegraph.disks.with(name: ["/dev/sda", "/dev/sdb"])
a_devicegraph.partitions.map {|p| p.name } # ["/dev/sda1", "/dev/sdb1", "/dev/sdb2", "/dev/sdc1"]
disks.partitions.map {|p| p.name } # ["/dev/sda1", "/dev/sdb1", "/dev/sdb2"]
primary_parts = disks.partitions.with(type: ::Storage::PartitionType_PRIMARY)
a_device_graph.filesystems.to_a # all file systems in the devicegraph
disks.filesystems.to_a # Filesystems in the chosen disks
primary_parts.filesystems.to_a # fs in primary parts of chosen disks
partitioned_disks = a_devicegraph.disks.with { |disk| disk.partition_table }
partitioned_disks.filesystems.size
```
> Devices lists

- src/examples/boot_req_checker_demo.rb
- src/lib/storage/boot_requirements_checker.rb
- src/lib/storage/boot_requirements_strategies.rb
- src/lib/storage/boot_requirements_strategies/base.rb
- src/lib/storage/boot_requirements_strategies/default.rb
- src/lib/storage/boot_requirements_strategies/legacy.rb
- src/lib/storage/boot_requirements_strategies/prep.rb
- src/lib/storage/boot_requirements_strategies/uefi.rb
- src/lib/storage/boot_requirements_strategies/zipl.rb
- src/lib/storage/disk_analyzer.rb
- test/boot_requirements_checker_test.rb
- test/proposal_test.rb
Very important: this pull request assumes that code like this works with libstorage-ng-ruby
```ruby
arch = Yast::Storage::StorageManager.instance.arch
arch.efiboot?
arch.x86?
```
Currently it does not because the libstorage-ng bindings don't provide access to `::Storage::Arch`.
@aschnell, @shundhammer Can you please add it (I failed miserably).
> First RSpec tests (and other improvements) for the BootRequirementsChecker

- src/lib/storage/proposal.rb
- src/lib/storage/proposal/devicegraph_generator.rb
- src/lib/storage/proposal/exceptions.rb
- src/lib/storage/proposal/partition_creator.rb
- src/lib/storage/proposal/settings.rb
- src/lib/storage/proposal/space_maker.rb
- src/lib/storage/proposal/volumes_generator.rb
- test/data/output/multi-linux-pc-sep-home.yml
- test/data/output/multi-linux-pc.yml
- test/data/output/windows-linux-multiboot-pc-sep-home.yml
- test/data/output/windows-linux-multiboot-pc.yml
- test/data/output/windows-pc-sep-home.yml
- test/data/output/windows-pc.yml
- test/proposal/partition_creator_test.rb
- test/proposal/space_maker_test.rb
- test/proposal/volumes_generator_test.rb
* Allows the caller to decide where / (and related partitions) is going to be installed.
* Knowing the root_device in advance allows BootRequirementsChecker to properly do its job.
* If root_device and candidate_device are not provided, they are calculated in a new additional first step.
> Added root_device and candidate_devices to Proposal::Settings

- doc/boot-partition.md
- src/lib/storage/boot_requirements_strategies/prep.rb
- src/lib/storage/disk_analyzer.rb
- src/lib/storage/planned_volume.rb
- src/lib/storage/proposal/partition_creator.rb
- test/boot_requirements_checker_test.rb
IMPORTANT: it relies on a `::Storage::Arch#open_nv?` that is still not there
> Improvements and tests for PReP boot strategy

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/examples/boot_req_checker_demo.rb
- src/lib/y2storage/disk_analyzer.rb
- src/lib/y2storage/proposal.rb
- test/data/devicegraphs/gpt_and_msdos.yml
- test/disk_analyzer_test.rb
- test/proposal/space_maker_test.rb
- test/proposal_test.rb
Make DiskAnalyzer reusable in other contexts beyond partitioning proposal, since it includes quite some valuable logic (like checking for Windows partitions).
Here (https://github.com/yast/yast-country/pull/89#discussion_r80223751) we are discussing the exact code to check for Windows partitions in yast2-country. Checking for Windows implies:
- checking for the architecture (something that DiskAnalyzer does but our draft in yast2-country forgets)
- checking for the partition ID (DiskAnalyzer checks for 4 ids, our draft only NTFS)
- checking for a primary partition (only done by yast2-country)
- checking for the content of the filesystem
Obviously we should not have two pieces of code  to check that, and `DiskAnalyzer` looks like the perfect candidate to host the one and only code. We just …
> More reusable DiskAnalyzer

- test/data/devicegraphs/output/multi-linux-pc-sep-home.yml
- test/data/devicegraphs/output/multi-linux-pc.yml
- test/data/devicegraphs/output/windows-linux-multiboot-pc-sep-home.yml
- test/data/devicegraphs/output/windows-pc-sep-home.yml
- test/data/devicegraphs/output/windows-pc.yml
Adapt the tests to the fix introduced in https://github.com/openSUSE/libstorage-ng/pull/160
> libstorage-ng does not longer use id linux for extended partitions

- src/lib/y2storage/proposal/space_maker.rb
Without this, our image in OBS cannot perform the installation if there are previous partitions.
> SpaceMaker: workaround libstorage restriction

- package/yast2-storage-ng.changes
- src/lib/y2storage/devices_lists/lvm_lvs_list.rb
- src/lib/y2storage/devices_lists/lvm_pvs_list.rb
- src/lib/y2storage/devices_lists/lvm_vgs_list.rb
- src/lib/y2storage/refinements/devicegraph_lists.rb
- test/data/devicegraphs/lvm-two-vgs.yml
- test/devices_list_test.rb
Just to have the same query interface that we have for disks, partitions, etc. That is, for example
```ruby
vgs = devicegraph.volume_groups.with { |vg| vg.vg_name.starts_with?("system") }
vgs.lvs.with(lv_name: "swap")
```
> Devices list for LVM classes

- package/yast2-storage-ng.changes
- src/lib/y2storage.rb
- src/lib/y2storage/disk_analyzer.rb
- src/lib/y2storage/existing_filesystem.rb
- src/lib/y2storage/proposal/space_maker.rb
- test/existing_filesystem_test.rb
- test/proposal/space_maker_test.rb
When deleting a partition that holds a PV, it now also deletes all the other partitions in the same VG.
Rationale: when deleting a partition that holds a PV of a given VG, we are effectively killing the whole VG (not only implicitly, but even explicitly thanks to libstorage). It makes no sense to leave the other PVs alive. So let's reclaim all the space.
> Better management of LVM partitions in SpaceMaker

- src/lib/y2storage/subvol.rb
- test/subvol_test.rb
This is just a rough backport to ensure that feature isn't completely forgotten.
The glue code to put that into is still missing, as well as subvolumes in libstorage-ng.
> Backported fate#321737: Subvolumes configurable in control.xml

- src/lib/y2storage/proposal/assigned_space.rb
- src/lib/y2storage/proposal/partition_creator.rb
- src/lib/y2storage/proposal/space_distribution.rb
- src/lib/y2storage/proposal/space_distribution_calculator.rb
- src/lib/y2storage/proposal/space_maker.rb
- test/data/devicegraphs/output/windows-linux-lvm-pc-sep-home.yml
- test/data/devicegraphs/output/windows-linux-lvm-pc.yml
- test/data/devicegraphs/output/windows-linux-multiboot-pc-sep-home.yml
- test/data/devicegraphs/output/windows-pc-sep-home.yml
- test/data/devicegraphs/output/windows-pc.yml
- test/proposal/partition_creator_test.rb
- test/proposal/space_distribution_calculator_test.rb
replaces #114 
I found out that so far we have been creating partitions that were some MiBs smaller than planned in some situations. 
With these changes, when calculating a proposal we now take into account the overhead produced by creating logical partitions and count with it when resizing windows and when distributing the volumes into the spaces.
I also removed some "unlimited" from the YAML of the tests, to ensure we don't overlook the problem any more.
As bonus, SpaceDistribution now decides in advance which partitions should be logical, as a result, PartitionCreator does not longer creates extended partitions with just one logical inside.
> Proposal: logical partitions overhead (EBR)

- src/lib/y2storage/devices_lists/lvm_pvs_list.rb
- src/lib/y2storage/devices_lists/lvm_vgs_list.rb
- test/devices_list_test.rb
I forgot to add these during https://github.com/yast/yast-storage-ng/pull/120 and they are needed for https://github.com/yast/yast-bootloader/pull/384 to really work with LVM.
> More methods for DevicesLists

- src/lib/y2storage/proposal/partition_creator.rb
- test/data/devicegraphs/empty_hard_disk_gpt_50GiB.yml
- test/proposal/partition_creator_test.rb
Part of https://trello.com/c/okn67JXC/465-5-proposalng-be-able-to-make-a-proposal-when-gpt-part-table-exists
It also includes some extra tests to check the "fix the wrong GUID..." task.
Travis will probably fail in a first attempt. This depends on https://github.com/openSUSE/libstorage-ng/pull/176
> Do not set boot flag if not supported

- src/lib/y2storage/disk_size.rb
- src/lib/y2storage/yaml_writer.rb
- test/disk_size_test.rb
The fact that `DiskSize#to_s` returned imprecise numbers is unexpected and can be a problem for log-based debugging. Lines like these were actually logging imprecise information:
```ruby
log.info "This is a size: #{disk_size}"
log.info "Content of the volume: #{volume}"
```
This PR aims to make `to_s` more "programmer friendly" (a.k.a. precise). We still have `to_human_string` for user friendliness (although is not much used so far).
> Make DiskSize#to_s precise

- package/yast2-storage-ng.changes
- src/lib/y2storage/devices_lists/base.rb
- src/lib/y2storage/disk_size.rb
- src/lib/y2storage/planned_volumes_list.rb
- src/lib/y2storage/proposal/assigned_space.rb
- src/lib/y2storage/proposal/partition_creator.rb
- src/lib/y2storage/proposal/space_distribution_calculator.rb
- src/lib/y2storage/refinements/disk.rb
- test/data/devicegraphs/empty_hard_disk_gpt_25GiB.yml
- test/data/devicegraphs/output/multi-linux-pc-gpt-lvm-sep-home.yml
- test/data/devicegraphs/output/multi-linux-pc-gpt-sep-home.yml
- test/data/devicegraphs/output/windows-linux-lvm-pc-gpt-lvm-sep-home.yml
- test/data/devicegraphs/output/windows-linux-lvm-pc-gpt-sep-home.yml
- test/data/devicegraphs/output/windows-linux-multiboot-pc-gpt-lvm-sep-home.yml
- test/data/devicegraphs/output/windows-linux-multiboot-pc-gpt-sep-home.yml
- test/planned_volumes_list_test.rb
- test/proposal/partition_creator_test.rb
- test/proposal_test.rb
Correctly manage small partitions (like bios_boot) and the infamous 16.5KiB at the end of GPT partitions
Before this change, in GPT + legacy boot, the proposal wanted to create very small bios_boot but after creating other bigger partitions there was no suitable slot because we didn't round to min_grain. This prevent such situations (tests included).
This also reduce the number of produced gaps.
> Manage small partitions and GPT final space

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/devices_lists/disks_list.rb
- test/devices_list_test.rb
New method very similar to the old `Yast::Storage.GetDisk`, added to avoid repeating the same pattern in yast2-bootloader all over the code.
> DisksList#with_name_or_partition

- package/yast2-storage-ng.changes
- src/lib/y2storage/boot_requirements_strategies/legacy.rb
- src/lib/y2storage/disk_analyzer.rb
- test/data/devicegraphs/gpt_and_msdos.yml
- test/data/devicegraphs/output/empty_hard_disk_50GiB-lvm-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_50GiB-lvm.yml
- test/data/devicegraphs/output/empty_hard_disk_50GiB-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_50GiB.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-lvm-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-lvm.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB.yml
- test/data/devicegraphs/output/gpt_and_msdos-sda_root_device.yml
- test/data/devicegraphs/output/gpt_and_msdos-sdb_root_device.yml
- test/disk_analyzer_test.rb
- test/proposal_test.rb
- `Y2Storage::DiskAnalyzer` - distinguish disks with no MBR gap (0 bytes gap) from cases where the MBR gap is not applicable.
- This fixes the proposal for some LVM scenarios with legacy boot (new tests included)
> DiskAnalyzer: no MBR gap != MBR gap not applicable

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/expert_partitioner/main_dialog.rb
- src/lib/expert_partitioner/tab_views/view.rb
- src/lib/expert_partitioner/tree.rb
- src/lib/expert_partitioner/tree_views/view.rb
- src/lib/y2storage/clients/inst_prepdisk.rb
- src/lib/y2storage/dialogs/inst_disk_proposal.rb
- src/lib/y2storage/refinements/devicegraph.rb
- src/lib/y2storage/storage_manager.rb
- test/clients/inst_prepdisk_test.rb
- test/dialogs/inst_disk_proposal_test.rb
- test/proposal_test.rb
- test/storage_manager_test.rb
Installation tested manually. The change does not break anything new.
This makes `StorageManager`behave like a real singleton class (see details in the description of #141)
Also adds a `staging_revision` method to check for changes (needed for https://trello.com/c/rKVpR8ul/391-3-storageng-software-selection)
Created as a separate pull request (from #141, which was RFC) to keep the discussion focused.
> Make StorageManager a real singleton and add revision

- doc/fake-devicegraphs-yaml-format.md
- test/fake_device_factory_test.rb
- Doc update: Use `/dev/mapper/cr_xy` consistently everywhere
- More unit tests for reading YAML with encryption:
- Encryption on LVM PV level
- Encryption on LVM LV level
> YAML Reader Unit Tests

- src/lib/y2storage/disk_size.rb
- src/lib/y2storage/refinements/size_casts.rb
- test/disk_size_test.rb
PBI https://trello.com/c/o9LkrKGc/525-3-read-setting-from-control-file
Disk size values read from control file can be formatted as "10MB". 
This PR extends DiskSize#parse to allow IS units and without spaces.
> Allow IS units for disk size and without spaces

- src/lib/y2storage/planned_subvol.rb
- src/lib/y2storage/planned_volume.rb
- src/lib/y2storage/proposal/lvm_helper.rb
- src/lib/y2storage/proposal/partition_creator.rb
- src/lib/y2storage/proposal_settings.rb
- test/planned_volume_test.rb
- test/proposal/volumes_generator_test.rb
- Prepend the default subvolume name to the subvol name upon creation: `var/log` -> `@/var/log`
- Don't shadow other volumes with a subvolume: Don't propose a `@/home` subvol to be mounted at `/home` when another dedicated volume (partition, LVM LV) is created for `/home´
- More unit tests
> Subvol proposal

- src/lib/y2storage/blk_device.rb
- test/yaml_writer_test.rb
- Use new API in yaml-writer unit test
- Added alias for create_filesystem() which is more natural to use than create_blk_filesystem()
> Use new API in yaml-writer unit test

- src/lib/y2storage/dialogs/guided_setup.rb
- src/lib/y2storage/dialogs/guided_setup/select_disks.rb
- src/lib/y2storage/dialogs/guided_setup/select_filesystem.rb
- src/lib/y2storage/dialogs/guided_setup/select_scheme.rb
- test/dialogs/guided_setup_test.rb
- test/support/guided_setup_context.rb
Add some improvements suggested by UX expert.
* Skip first dialog when there is only one candidate disk.
* Align widgets.
PBI: https://trello.com/c/crhdffWC/516-5-storageng-guided-setup
> Guided setup improvements

- src/lib/y2storage/dialogs/guided_setup/select_scheme.rb
- test/dialogs/guided_setup/select_scheme_test.rb
Related to PBI https://trello.com/c/b5DSHXf5/567-2-storageng-guided-set-up-disable-unneeded-widgets
* Focus password field when encryption is selected.
* Improve password error message and allow to use a simple password.
> Usability fixes

- src/lib/y2storage/devicegraph.rb
- test/storage_manager_test.rb
Needed for https://trello.com/c/WAGRJLgv/542-5-libstorage-ng-support-of-alternative-device-naming-schemes.
> - pass storage object when creating devicegraph objects

- src/lib/y2storage/planned_volume.rb
- src/lib/y2storage/proposal/volumes_generator.rb
- test/proposal_subvol_test.rb
- test/support/proposal_context.rb
This solves current problem in openQA with BtrFS where parent subvolume was always set as default. 
With this patch, apparently all it is fine.
See https://trello.com/c/taJNub8F/576-fixes-to-do-openqa-passes
> Set default btrfs subvolume

- .codeclimate.yml
- README.md
- The packages can be easily updated without manual refresh
- Added `.codeclimate.yml` - disable Rubocop check, the shared config file cannot be read by CodeClimate (we run Rubocop at Travis anyway), this will fix the CC errors in the pull requests
> README - enable autorefresh for the storage-ng repo

- src/lib/y2storage/disk_size.rb
There's no code change except for the definition of #to_storage_value which was done so yardoc sees it.
> enhance documentation of DiskSize class

- test/partition_tables_test.rb
The test checks for the name of a partition which cannot be created. In other words checks for not valid data.
> - removed wrong test

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/package_handler.rb
- src/lib/y2storage/used_storage_features.rb
- test/package_handler_test.rb
Port to Storage-NG:
https://trello.com/c/yqdIek3N/606-2-handle-optional-fs-packages-correctly
https://bugzilla.suse.com/show_bug.cgi?id=1039830
> Don't insist on installing filesystem support packages that are not available in any repo (bsc#1039830)

- test/storage_class_wrapper_test.rb
It cannot be obtained automatic, as ancestor should not know about its
children, but for test it is fine to load whole namespace and all its
objects.
how output will look like:
```
Y2Storage::StorageClassWrapper
wrap_class
Y2Storage::Filesystems::Base
specifies its direct children [Y2Storage::Filesystems::BlkFilesystem, Y2Storage::Filesystems::Nfs] as downcastable
Y2Storage::Mountable
specifies its direct children [Y2Storage::Filesystems::Base, Y2Storage::BtrfsSubvolume] as downcastable
Y2Storage::Filesystems::BlkFilesystem
does not specify any downcastable class as it does not have a direct child
Y2Storage::BtrfsSubvolume
does not specify any downcastable class as it does not have a direct child
Y2Storage::LvmLv
does not specify any downcastable class as it does not have a direct child …
```
> Add test that all class wrapper properly specify downcast_to

- src/lib/y2storage/devicegraph.rb
No longer just showing two 3000+ character long strings for _expected_ and _actual_ for the proposal unit tests, but a proper diff that actually shows the problem:
``````
77) Y2Storage::GuidedProposal#propose in a PC with an empty GPT partition table not using LVM but using encryption with a separate home proposes the expected layout
Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
expected: "[[[\"disk\",\n   [[\"align_ofs\", \"0 B\"],\n    [\"block_size\", \"0.5 KiB\"],\n    [\"io_size\", \... \"16.5 KiB\"], [\"start\", \"52428783.5 KiB (50.00 GiB)\"]]]]]],\n    [\"size\", \"50 GiB\"]]]]]\n"
got: "[[[\"disk\",\n   [[\"align_ofs\", \"0 B\"],\n    [\"block_size\", \"0.5 KiB\"],\n    [\"io_size\", \... \"16.5 KiB\"], [\"start\", \"52428783.5 KiB (50.00 …
> Show properly readable diff upon failure for proposal unit tests

- src/lib/y2storage/proposal/planned_devices_generator.rb
- test/data/devicegraphs/output/empty_hard_disk_gpt_25GiB-lvm-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_25GiB-lvm.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_25GiB-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_25GiB.yml
- test/proposal_low_space_test.rb
If there is not enough disk space to satisfy all desired partition / volume sizes, now falling back to a minimum of 512 MB for swap, but keeping the maximum (by default - unless "enlarge for swap" is set) of 2 GB. It now uses a weight to get some disk space beyond the minimum: Any disk space above the cumulated minimum sizes of all planned partitions / volumes is distributed among those that have a weight set.
Right now, swap gets a weight of 100, i.e. it gets as much extra disk space as root and home together. The value is hard-coded right now. We might make it configurable some day, but right now this would just add to the complexity.
In practice all this means that while swap no longer gets its full 2 GB if disk space is low, it at least typically gets more than the minimum 512 MB; in …
> Fall back to less swap (min 512 MB) if not enough disk space for 2 GB

- src/lib/y2storage/proposal/devices_planner.rb
- src/lib/y2storage/proposal_settings.rb
- test/data/devicegraphs/output/empty_hard_disk_gpt_25GiB-lvm-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_25GiB-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-enc-lvm-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-enc-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-lvm-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_mbr_50GiB-enc-lvm-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_mbr_50GiB-enc-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_mbr_50GiB-lvm-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_mbr_50GiB-sep-home.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm-sep-home.yml
https://trello.com/c/B2Qv7y6d/639-5-storageng-proposal-adapt-to-the-situation
Now using `root_base_size` if disk space is low, i.e. when using `:min` instead of `:desired` to calculate a proposal. Continuing using `settings.home_min_size` for `:desired` which hopefully some day will be read from `control.xml` (but right now is initialized with a hard-code value of 10 GiB).
> Fall back to 3 GB /home if low disk space

- package/yast2-storage-ng.spec
Until we merge both packages back, this is needed.
> Add temporary BuildRequire for partitioner

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
documenting 3ac7b91afe2f4ba13a4295303a0c3e2c029d0f67 from #305 so that
yast2-partitioner can depend on it in https://github.com/yast/yast-partitioner/pull/26
> version + changelog

- .travis.yml
- doc/fake-devicegraphs-yaml-format.md
- src/lib/storage/patches.rb
- src/lib/y2storage/boot_requirements_strategies/zipl.rb
- src/lib/y2storage/dasd.rb
- src/lib/y2storage/fake_device_factory.rb
- src/lib/y2storage/yaml_writer.rb
- test/boot_requirements_checker_s390_test.rb
- test/boot_requirements_duplicate_test.rb
- test/proposal_scenarios_s390_test.rb
- test/yaml_writer_test.rb
- Add support for DASD type and DASD format to the YAML reader and writer
https://trello.com/c/m7N8jeE6/506-2-storageng-make-proposal-work-with-dasd
- Adapt Y2Storage API to renamed (in libstorage-ng) method/attribute names _dasd_type_ -> _type_, _dasd_format_ -> _format_
- DASD type and format are now writable (both in libstorage-ng and in the Y2Storage API)
> Add DASD type and format to YAML reader and writer

- src/lib/y2storage/partition_tables/base.rb
- src/lib/y2storage/partitionable.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- src/lib/y2storage/yaml_writer.rb
- test/y2storage/planned/assigned_space_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
PBI: https://trello.com/c/UBCLA6Qo/651-2-storageng-and-s-390-partitions-not-aligned.
Remove `Partitionable#min_grain`
> Not use min grain

- src/lib/y2storage/fake_device_factory.rb
- src/lib/y2storage/free_disk_space.rb
- src/lib/y2storage/partition_tables/base.rb
- src/lib/y2storage/partition_tables/dasd.rb
- src/lib/y2storage/planned/assigned_space.rb
- src/lib/y2storage/planned/has_size.rb
- src/lib/y2storage/proposal/partition_creator.rb
- test/data/devicegraphs/empty_dasd_50GiB.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm-sep-home.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm.yml
- test/data/devicegraphs/output/s390_dasd_zipl.yml
- test/y2storage/fake_device_factory_test.rb
- test/y2storage/planned/assigned_space_test.rb
PBI: https://trello.com/c/UBCLA6Qo/651-2-storageng-and-s-390-partitions-not-aligned.
Enforced end-alignment for last partition in a DASD partition table.
> Dasd end-alignment

- .rubocop.yml
- src/lib/y2storage/disk_analyzer.rb
- src/lib/y2storage/fake_device_factory.rb
- src/lib/y2storage/planned/partitions_distribution.rb
- src/lib/y2storage/proposal/lvm_creator.rb
- test/y2storage/proposal/lvm_creator_test.rb
- test/y2storage/proposal/partitions_distribution_calculator_test.rb
- test/y2storage/proposal_subvol_test.rb
Refinements are not used anymore.
PBI: https://trello.com/c/BWtX9ccg/548-2-remove-refinements-patches-extensions-etc-from-yast-storage-ng.
> Remove rubocop SymbolProc exception

- src/lib/y2storage/planned/has_size.rb
- test/data/devicegraphs/empty_dasd_50GiB.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm-sep-home.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm.yml
- test/data/devicegraphs/output/s390_dasd_zipl.yml
Ensure end-alignment when distributing extra space.
This should solve alignment problem detected in s380 openQA test: https://yast-openqa.suse.cz/tests/12374#step/start_install/5.
Part of PBI: https://trello.com/c/UBCLA6Qo/651-2-storageng-and-s-390-partitions-not-aligned.
> Fix alignment bug

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/filesystems/type.rb
- test/y2storage/filesystems/type_test.rb
With #335 reiserfs was dropped but it affected yast2-update not showing the legacy root partitions.
With this PR we will add support for check legacy filesystems that were valid for '/' and '/home' mount points.
> Added support for legacy filesystems (fate#323394)

- doc/dont-format-in-expert-partitioner.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/format_and_mount.rb
- src/lib/y2partitioner/sequences/filesystem_controller.rb
- src/lib/y2partitioner/widgets/btrfs_subvolumes.rb
- src/lib/y2partitioner/widgets/format_and_mount.rb
- test/y2partitioner/dialogs/format_and_mount_test.rb
- test/y2partitioner/sequences/filesystem_controller_test.rb
- test/y2partitioner/widgets/format_and_mount_test.rb
It also adjusts (and documents) some behavior when editing partitions.
Snapshots checkbox functionality manually tested with full installation.
Last step for https://trello.com/c/ytK5Yoe4/554-5-storageng-installation-to-root-subvolume
> Partitioner: checkbox to enable snapshots

- doc/boot-requirements.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- rakelib/doc_bootspecs.rake
- src/lib/y2storage/boot_requirements_strategies/uefi.rb
- test/support/boot_requirements_uefi.rb
- test/y2storage/boot_requirements_duplicate_test.rb
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1056640.
https://trello.com/c/ppQwBqN0/726-sles15-p1-1056640-build-1738-installation-with-uefi-fails-due-to-boot-efi-partition-too-small
> Avoid to reuse small efi partitions

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/partition_size.rb
- test/y2partitioner/dialogs/partition_size_test.rb
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1060864
https://trello.com/c/t5RCEg1L/729-sles15-p5-1060864-alpha-5-add-partition-with-empty-size-results-in-error-client-call-failed-with-not-a-number-typeerror
> Partitioner: fix custom size validation

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/devices_planner.rb
- src/lib/y2storage/proposal/devices_planner_strategies.rb
- src/lib/y2storage/proposal/devices_planner_strategies/legacy.rb
- src/lib/y2storage/proposal/devices_planner_strategies/ng.rb
- src/lib/y2storage/proposal_settings.rb
There are currently `:legacy` and a stub for `:ng`.
The `:legacy` code is basically a 1:1 copy of the old `devices_planner.rb`.
> separate planning strategies from DevicesPlanner into DevicesPlannerStrategies module

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/desktop/disk.desktop
https://trello.com/c/85gke1CE/745-0-storageng-missing-desktop-file-for-expert-partitioner
Directory structure and Rakefile changes taken from yast-packager, a package that does not also use the autotools. desktop files from src/desktop are automatically picked up and installed to /usr/share/applications/YaST by our default rake rules.
The .desktop file is copied verbatim from yast-storage-old.
> Added .desktop file

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_disk_proposal.rb
- src/lib/y2storage/dialogs/proposal.rb
- test/y2storage/clients/inst_disk_proposal_test.rb
- test/y2storage/dialogs/proposal_test.rb
This implements https://trello.com/c/LvwStMCI/704-1-partitioner-start-from-scratch
Easier to review in a per-commit fashion.
Manually tested in the inst-sys, see screenshots.
>  Add button to run partitioner from probed 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_issues/missing_value.rb
- src/lib/y2storage/autoinst_profile/skip_list_section.rb
- src/lib/y2storage/autoinst_profile/skip_list_value.rb
- src/lib/y2storage/autoinst_profile/skip_rule.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- test/y2storage/autoinst_profile/skip_list_section_test.rb
- test/y2storage/autoinst_profile/skip_rule_test.rb
Fixes [bsc#1065670](https://bugzilla.suse.com/show_bug.cgi?id=1065670) and logs a warning. This PR contains other minor fixes too.
> Do not crash when an unknown key is used

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/blk_devices_table.rb
Querying the end can result in wrap around so must be avoided.
Showing only start and no end is strange so also omit start.
> - do not query end of region if region is empty (bsc#1066290)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/skip_list_value.rb
- src/lib/y2storage/hwinfo_reader.rb
- test/data/hwinfo.txt
- test/y2storage/autoinst_profile/skip_list_value_test.rb
- test/y2storage/hwinfo_reader_test.rb
Here is the second part of #408, adding some missing keys that were available in SLE12. Check https://github.com/yast/yast-autoinstallation/pull/364 to see them in action.
> Add some missing skip list keys

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_proposal.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
This PR fixes partition table creation in AutoYaST (now is set to the right type). But, even more important, it also fixes space distribution in the following situation:
* no partition table exists (or profile sets `<initialize>` element to `true`)
* any partition size is set to `max` (or not set at all)
In such a scenario, the storage proposal runs out of space. There is a possible workaround: setting all partition sizes, but the user would need to take the partitions table size into account.
For the records, the problem was that the partition table was created too late (not explicitly created at all), so calculations about space distribution were just wrong.
> Fix disklabel

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/partition.rb
- src/lib/y2storage/partition_tables/dasd.rb
- src/lib/y2storage/partition_tables/gpt.rb
- test/y2storage/partition_tables/dasd_test.rb
- test/y2storage/partition_tables/gpt_test.rb
- step 1: don't break if we messed up the ids - instead, log an error and continue with a reasonable default
- step 2: map partition ids to allowed values
> handle partition ids for different partition types (bsc #1060993)

- test/y2storage/partition_tables/gpt_test.rb
- test/y2storage/partition_test.rb
This adds unit tests for the code added in #418 (and for the rest of the Partition class, as a bonus) avoiding the drop of the test coverage and, thus, restoring the balance in the force and the galaxy.
> Unit tests for Y2Storage::Partition

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/md.rb
- src/lib/y2partitioner/dialogs/md_options.rb
- src/lib/y2storage/disk_size.rb
- test/y2partitioner/actions/controllers/md_test.rb
https://trello.com/c/8mxdS9qy/765-1-sles15-p2-1065381-build-3215ppc64-openqa-test-fails-in-to-create-raid10-stderrmdadm-runarray-failed-invalid-argument
https://bugzilla.suse.com/show_bug.cgi?id=1065381
For most RAID levels now use a chunk size of 64 kiB except for some where the page size is irrelevant. 
Now no longer using a fixed list of chunk sizes, but calculating it on the fly, depending on the default chunk size. If that is less than 64 kiB, use it as the starting point.
Also, after discussing this with Arvin extended the list of chunk sizes to up to 64 MiB since this might be more efficient and thus desired by many customers.
Caveat: It turned out that DiskSize.to_s likes to use fractional numbers in some cases, so the list contains `0.5 MiB` instead of `512 MiB`. This is just …
> Avoid RAID chunk size below 64 kiB

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/partition_creator.rb
Use the safer `Partition#adapted_id` method. It fixes [bsc#1067207](https://bugzilla.suse.com/show_bug.cgi?id=1067207).
> Use Partition#adapted_id

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- src/lib/y2storage/proposal/autoinst_size.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/device_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
- test/y2storage/proposal/autoinst_size_test.rb
Set weight properly so the logical volume will grow when distributing space.
> Fix size=max for logical volumes

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_proposal.rb
- test/y2storage/autoinst_proposal_test.rb
AutoYaST did not run the space maker before falling back to using the original DevicesPlanner: https://bugzilla.suse.com/show_bug.cgi?id=1065061. So if you had a profile with an empty (or missing) `partitions` element, `use` and `initialize` would be ignored.
> Honor 'use' and 'initialize' even when no partitions are specified

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/overview.rb
- src/lib/y2storage/autoinst_profile/drive_section.rb
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/lvm_vg.rb
- src/lib/y2storage/partition_tables/base.rb
- src/lib/y2storage/partitionable.rb
- src/lib/y2storage/yaml_writer.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/planned/lvm_vg_test.rb
- test/y2storage/proposal/lvm_creator_test.rb
Last steps to implement https://trello.com/c/T8B7oRJs/769-yast2-storage-ng-do-not-rely-on-libstorage-ng-sorting-anymore
@aschnell announced its intention to drop any sorting from libstorage here https://lists.opensuse.org/yast-devel/2017-11/msg00009.html
As discussed in #454, that affects not only the collection of devices that used to be sorted by name (`Disks.all`, `Dasd.all`, etc.) but also collections within an object that used to be sorted by other criteria (partitions within a partition table will not be longer sorted by number, LVs within an VG will not be longer sorted by name, etc.)
This should prepare yast-storage-ng for such change. Manually tested by removing all the calls to `sort` in `DevicegraphImpl.h` in libstorage-ng.
>  Not longer trust any sorting coming from libstorage-ng 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/partitionable.rb
- test/y2storage/blk_device_test.rb
- test/y2storage/disk_test.rb
PBI: https://trello.com/c/X4bQOy5F/800-ship-stopper-bug-1071775-yast2-partitioner-crashes-on-test-system-system-cannot-be-installed
Bug report: https://bugzilla.suse.com/show_bug.cgi?id=1071775
> Fix efi detection

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_proposal.rb
- test/y2storage/autoinst_proposal_test.rb
* Fixes [bsc#1073307](https://bugzilla.suse.com/show_bug.cgi?id=1073307)
* When the disk does not have a partition table:
* If disklabel is defined in the profile -> it will use the given value.
* If disklabel is not defined in the profile -> it will fallback to "msdos" (like in the past).
* When the disk has a partition table:
* If the type defined in the profile (disklabel) is different -> change only if there are no partitions.
* If the type matches -> do nothing.
* If initialize is set to true -> always wipe the partition table
> AutoYaST: Improve disklabel handling

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/partitions_distribution_calculator.rb
- test/data/devicegraphs/output/windows-pc-50GiB-gpt-sep-home.yml
- test/data/devicegraphs/output/windows-pc-50GiB-gpt.yml
- test/data/devicegraphs/output/windows-pc-enc-sep-home.yml
- test/data/devicegraphs/output/windows-pc-enc.yml
- test/data/devicegraphs/output/windows-pc-gpt-enc-sep-home.yml
- test/data/devicegraphs/output/windows-pc-gpt-enc.yml
- test/data/devicegraphs/output/windows-pc-gpt-sep-home.yml
- test/data/devicegraphs/output/windows-pc-gpt.yml
- test/data/devicegraphs/output/windows-pc-mbr128-sep-home.yml
- test/data/devicegraphs/output/windows-pc-mbr128.yml
- test/data/devicegraphs/output/windows-pc-mbr256-sep-home.yml
- test/data/devicegraphs/output/windows-pc-mbr256.yml
- test/data/devicegraphs/output/windows-pc-sep-home.yml
- test/data/devicegraphs/output/windows-pc.yml
- test/data/devicegraphs/windows-pc-50GiB-gpt.yml
- test/y2storage/proposal/space_maker_test.rb
- test/y2storage/proposal_scenarios_x86_test.rb
What otherwise happens is this: our planning strategy will typically resize
an existing Windows partition *twice*. First for the root partition, then
again for the rest.
Without this patch, after the first (correct) resize, the Windows partition
will leave a free space block that appears to be bigger than can actually be
used (due to the alignment issue). As a result, the second resize would be
planned too small.
> fix miscalculation of sizes when resizing a Windows partition (bsc#1066386)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/space_maker.rb
This also includes making the exit criterion explicit even if this makes the function code so long rubocop complains.
> rewrite SpaceMaker::resize_and_delete! to be more human-readable

- package/yast2-storage-ng.changes
- src/lib/y2storage/autoinst_profile/drive_section.rb
- src/lib/y2storage/filesystems/btrfs.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/filesystems/btrfs_test.rb
Export `<enable_snapshots>` element. It solves [bsc#1073544](https://bugzilla.suse.com/show_bug.cgi?id=1073544). I am not incrementing the version number because I plan to merge another fix today and I want to avoid submitting the same package twice.
> Export enable snapshots

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/storage_manager.rb
- test/data/devicegraphs/complex-lvm-encrypt.yml
- test/y2storage/devicegraph_test.rb
- test/y2storage/storage_manager_test.rb
See https://bugzilla.suse.com/show_bug.cgi?id=1073254
yast2-bootloader and yast2-update wouldn't need any of this if libstorage-ng would save the discarded ids of each device.
I manually tested the 13.1 -> TW upgrade including the three patches (this, https://github.com/yast/yast-update/pull/91 and https://github.com/yast/yast-bootloader/pull/476) and it worked. :+1:
> Added Devicegraph#find_by_any_name (needed for bsc#1073254)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/mountable.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
- See also https://github.com/yast/yast-packager/pull/308/
- 4.0.68
> Added Mountable#persistent? (needed for bsc#1073696)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/partition.rb
- src/lib/y2partitioner/dialogs/partition_resize.rb
- src/lib/y2partitioner/dialogs/partition_size.rb
- src/lib/y2partitioner/dialogs/partition_type.rb
- src/lib/y2storage/align_policy.rb
- src/lib/y2storage/align_type.rb
- src/lib/y2storage/partition.rb
- src/lib/y2storage/partition_tables/base.rb
- src/lib/y2storage/region.rb
- test/y2partitioner/actions/controllers/partition_test.rb
- test/y2partitioner/dialogs/partition_resize_test.rb
- test/y2partitioner/dialogs/partition_size_test.rb
- test/y2partitioner/dialogs/partition_type_test.rb
- test/y2storage/partition_test.rb
During partition creation and also when resizing partitions, this implements the alignment described at https://lists.opensuse.org/yast-devel/2018-01/msg00018.html . That is, new partitions are aligned to optimal requirements (in most cases) or at least to the mandatory alignment (when region start/end are explicitly specified). This alignment is specially relevant for DASD. Same alignment logic is also applied to partitions resizing.
Thus, this fixes
* https://trello.com/c/PKzPu7mb/227-sles15-p2-1069860-sles15-beta3-yast-create-partition-failed-when-wanting-two-partitions
* https://trello.com/c/xjvk3Pdv/232-sles15-p1-1072011-build-3811-storage-ng-calculates-incorrect-values-for-parted-command-for-eckd-dasd
Done as previous work to …
> Partitioner: align created and resized partitions

- package/yast2-storage-ng.changes
- src/lib/y2storage/planned/partitions_distribution.rb
- src/lib/y2storage/proposal/partitions_distribution_calculator.rb
- test/data/devicegraphs/output/kvm_role_scenario.yml
- test/y2storage/guided_proposal_test.rb
- test/y2storage/proposal/partitions_distribution_calculator_test.rb
Unused spaces are taken into account when deciding which partitions distribution is better. Somehow definition of `gap` is changed. Previously, it was meant to be a space produced by the partitioning algorithm (for instance, putting a partition into a free space but leaving some space at the end). Now, any free space is considered a gap (no matter how it was created).
> Consider all spaces

- package/yast2-storage-ng.changes
- src/lib/y2storage/guided_proposal.rb
- test/y2storage/guided_proposal_no_disks.rb
Actually the description of #calculate_proposal is wrong. The space
calculator doesn't raise NoDiskSpaceError but Error if things fail.
Anyway, sticking to the docs and raising NoDiskSpaceError if disks are missing.
> raise exception properly when there are no disks (bsc#1057430)

- package/yast2-storage-ng.changes
- src/lib/y2partitioner/actions/controllers/lvm_vg.rb
- src/lib/y2partitioner/dialogs/blk_device_resize.rb
- src/lib/y2partitioner/dialogs/lvm_lv_size.rb
- src/lib/y2partitioner/dialogs/partition_size.rb
- src/lib/y2partitioner/size_parser.rb
- test/y2partitioner/actions/controllers/lvm_vg_test.rb
- test/y2partitioner/dialogs/blk_device_resize_test.rb
- test/y2partitioner/dialogs/lvm_lv_size_test.rb
This should make this test succeed, since "1Mb" will be considered equivalent to "1Mib" (we can't educate the whole world):
https://openqa.opensuse.org/tests/588406
> Partitioner: treat International System units as power of two

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/widgets/format_and_mount.rb
- src/lib/y2partitioner/widgets/fstab_options.rb
- src/lib/y2storage/filesystems/type.rb
- src/lib/y2storage/mountable.rb
- src/lib/y2storage/planned/can_be_formatted.rb
- src/lib/y2storage/proposal/base.rb
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-root-docker-lvm.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-root-swap.yml
- test/data/devicegraphs/output/ppc_non_power_nv-lvm.yml
- test/data/devicegraphs/output/ppc_power_nv-lvm.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm-sep-home.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm.yml
- test/data/devicegraphs/output/s390_dasd_zipl.yml
- test/data/devicegraphs/output/s390_zfcp_zipl.yml
- test/data/devicegraphs/output/windows-pc-mbr256-lvm-sep-home.yml
- test/data/devicegraphs/output/windows-pc-mbr256-lvm.yml
- test/support/proposal_context.rb
- test/y2partitioner/widgets/fstab_options_test.rb
- test/y2storage/filesystems/type_test.rb
https://trello.com/c/5zK5B9J6/94-5-betasles15-p2-1066076-installer-default-data-journaling-mode-in-ext34-differ-from-sles12
This adds fstab options (mount options to be written to /etc/fstab) to filesystems we create or mount, very much like in the old storage stack.
If the user or the application logic explicitly sets any fstab options, those are used, of course. If not, this now uses default fstab options which are different for each filesystem type: ext2/3/4, vfat, ntfs.
I extended the table that already existed for similar things that are different for each filesystem type.
In most cases it's a very simple list of strings, but there are also the Microsoft filesystems that need some locale-specific parameters such as `iocharset` and `codepage` where we need to figure out the …
> Add default fstab options

- test/y2storage/yaml_writer_test.rb
Quick (and dirty) fix for failing unit test:
https://ci.suse.de/job/yast-storage-ng-master/144/consoleFull
1) Y2Storage::YamlWriter produces yaml of a simple lvm setup
Failure/Error: expect(io.string).to eq result.join("\n") + "\n"
expected: "---\n- disk:\n    name: \"/dev/sda\"\n    size: 1 TiB\n    block_size: 0.5 KiB\n    io_size: 0 B\n  ...ipes: 1\n        file_system: ext4\n    lvm_pvs:\n    - lvm_pv:\n        blk_device: \"/dev/sda\"\n"
got: "---\n- disk:\n    name: \"/dev/sda\"\n    size: 1 TiB\n    block_size: 0.5 KiB\n    io_size: 0 B\n  ...s:\n        - iocharset=iso8859-15\n    lvm_pvs:\n    - lvm_pv:\n        blk_device: \"/dev/sda\"\n"
(compared using ==)
Diff:
@@ -15,6 +15,8 @@
size: 16 GiB
stripes: 1
file_system: ext4
+        fstab_options:
+        - iocharset=iso8859-15 …
> Disable unit test temporarily that fails only in Jenkins

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/fstab_options.rb
- test/y2partitioner/widgets/fstab_options_test.rb
This uses introspection to check the other widgets on that same dialog page which values are already handled there (both VALUES and REGEXP constants) and populates the input field only with those that are not.
Upon storing the value, it accepts all options from the user. If any of them is already handled by another widget, it will still be set, but when entering the dialog again, that widget will pick up the value and handle it.
There is no sanity checking which values are valid. The background is to avoid keeping track of every possible mount option for all types of filesystems; new ones might come without us taking notice, so we rather trust the user than our ability to keep any such tables up-to-date for all future releases.
> Implement "arbitrary options" in the partitioner's fstab options page

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/overview.rb
https://trello.com/c/dtrBS2Fq/229-1-beta7-expert-partitioner-remove-empty-screens
https://bugzilla.suse.com/show_bug.cgi?id=1078849
Disabled (commented out in the code) the empty pages for the time being:
- Crypt Files
- Device Mapper
- Unused Devices
- Mount Graph
- Settings (this one will be back soon with content)
Now it looks like this:
---------------------------------
For comparison: Before:
> Disabled (commented out) empty partitioner pages

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_drives_map.rb
- test/y2storage/proposal/autoinst_drives_map_test.rb
This change adds support to use devices names like `/dev/disk/by-label/some-label` in `drive/device` element.
> AutoYaST: use find_by_any_name

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/partition_table.rb
- src/lib/y2partitioner/actions/create_partition_table.rb
- test/y2partitioner/actions/create_partition_table_test.rb
This fixes https://trello.com/c/ahhE9izy/260-3-bsc1078721-p1-openqa-test-fails-in-partitioningfulllvm-partitions-not-deleted-after-creating-partition-table
* Fixes the bug
* Modify unit tests to actually test something meaningful
> Partitioner: fix for bsc#1078721

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/clients/storage_finish.rb
- src/lib/y2storage/clients/finish.rb
- test/y2storage/clients/finish_test.rb
Implements https://trello.com/c/dXnAZX6L/261-sles15-p1-1076183-multipathdservice-isnt-enabled-after-installation-on-multipath
Already tested manually
Bonus: update dependency on libstorage-ng to fix another reported bug
> New finish client to enable multipathd

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/add_lvm_lv.rb
- src/lib/y2partitioner/actions/add_partition.rb
- src/lib/y2partitioner/actions/controllers/lvm_vg.rb
- src/lib/y2partitioner/actions/controllers/md.rb
- src/lib/y2partitioner/actions/edit_blk_device.rb
- src/lib/y2partitioner/actions/resize_lvm_vg.rb
- src/lib/y2partitioner/actions/resize_md.rb
- src/lib/y2partitioner/actions/transaction_wizard.rb
- test/y2partitioner/actions/add_lvm_lv_test.rb
- test/y2partitioner/actions/add_partition_test.rb
- test/y2partitioner/actions/controllers/md_test.rb
- test/y2partitioner/actions/edit_blk_device_test.rb
- test/y2partitioner/actions/resize_lvm_vg_test.rb
- test/y2partitioner/actions/resize_md_test.rb
Bug reports:
* https://bugzilla.suse.com/show_bug.cgi?id=1079880
* https://bugzilla.suse.com/show_bug.cgi?id=1079573
The issue is caused because a wrong object is used inside a `DeviceGraphs#transaction`. Partitioner actions should ensure that controllers are always created with the correct device.
Note: Unit tests were not able to detect those issues. Regression tests are now added.
> Fix transaction issues

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/setup_errors_presenter.rb
- src/lib/y2partitioner/widgets/overview.rb
- src/lib/y2storage/boot_requirements_checker.rb
- src/lib/y2storage/boot_requirements_strategies/base.rb
- src/lib/y2storage/boot_requirements_strategies/legacy.rb
- src/lib/y2storage/boot_requirements_strategies/prep.rb
- src/lib/y2storage/boot_requirements_strategies/uefi.rb
- src/lib/y2storage/boot_requirements_strategies/zipl.rb
- src/lib/y2storage/setup_checker.rb
- test/y2partitioner/setup_errors_presenter_test.rb
- test/y2partitioner/widgets/overview_test.rb
- test/y2storage/boot_requirements_errors_test.rb
- test/y2storage/setup_checker_test.rb
plan is to also add all current checks in bootloader itself.
screenshot from manual testing:
and warnings still works:
> [WIP] first version of fatal errors

- src/lib/y2storage/storage_manager.rb
For https://trello.com/c/qjE8oaNh/272-failing-test-with-last-version-of-libstorage-ng.
> also copy devicegraph read from xml also to system devicegraph

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2storage/filesystems/type.rb
- src/lib/y2storage/planned/can_be_formatted.rb
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-root-docker-lvm.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-root-swap.yml
- test/y2storage/filesystems/type_test.rb
https://trello.com/c/9c9qZoIn/269-special-mount-options-for-boot-efi-bsc1080731
This is a bit of a mess; it reintroduces special handling we had in yast-storage-old for mount options for certain mount points. We had meant to leave this kind of thing behind, but it turns out we still need some of the old workarounds for some quirks or limitations of some kernel filesystem modules or low-level tools.
I tried to keep this localized in one file so anybody needing to change yet another one of those special cases doesn't need to hunt a half dozen files and a half dozen classes for all the places where this needs to be adapted.
At some points, the code may seem a little overkill, but this is meant to be extensible and, equally important, easy to understand.
The downside is that this is all in …
> Special mount option handling for certain mount paths

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/widgets/format_and_mount.rb
- test/y2partitioner/actions/controllers/filesystem_test.rb
Main PR for two cards: https://trello.com/c/FBPlQOBf/262-1-partitioner-apply-role-correctly and https://trello.com/c/EzGZXxXN/274-sles15-several-reports-irritating-mount-point-suggestions-for-existing-swap-efi-zipl
This adds three commits fixing a total of 4 bugs.
- First commit: bring back the original list of mount points instead of a fixed list
- Fixes half of [bsc#1076167](https://bugzilla.suse.com/show_bug.cgi?id=1076167) by bringing `/boot/efi' back
- Fixes [bsc#1081200](https://bugzilla.suse.com/show_bug.cgi?id=1081200) by bringing `/boot/zipl' back
- Second commit: bring back original logic for the "Mount Device" option in the roles "Operating System" and "Data".
- Fixes [bsc#1078975](https://bugzilla.suse.com/show_bug.cgi?id=1078975) and …
> Partitioner: bringing back old partitioner logic about mount points

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/widgets/fstab_options.rb
Second part of  https://trello.com/c/9c9qZoIn/269-special-mount-options-for-boot-efi-bsc1080731
This makes sure to not force mount options that should not be used for some special paths ("/", "/boot/*") back into the mount options when the user enters the "mount options" dialog in the partitioner.
For ext3/ext4, this removes the "journal" combo box, for vfat, it removes the "iocharset" combo box.
First I tried to just disable them, but this looks so unnatural and awkward that it raises a lot of questions: At least in my Qt widget style, only the combo box label is greyed out, the combo box itself is not; yet, you cannot click it, and it displays a value that is no longer applicable.
So, removing those combo boxes in just that scenario worked a lot better (and it is consistent with what we …
> Special path handling for mount options in partitioner

- package/yast2-storage-ng.changes
- src/lib/y2storage/boot_requirements_strategies/base.rb
- src/lib/y2storage/boot_requirements_strategies/legacy.rb
- src/lib/y2storage/boot_requirements_strategies/prep.rb
- src/lib/y2storage/boot_requirements_strategies/uefi.rb
- src/lib/y2storage/boot_requirements_strategies/zipl.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- src/lib/y2storage/proposal/autoinst_size_parser.rb
- src/lib/y2storage/volume_specification_builder.rb
- test/y2storage/guided_proposal_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
- test/y2storage/proposal/autoinst_size_parser_test.rb
- test/y2storage/proposal/initial_strategies/legacy_test.rb
- test/y2storage/proposal/initial_strategies/ng_test.rb
- test/y2storage/volume_specification_builder_test.rb
This PR adds support to AutoYaST to select a filesystem when it is not specified in the profile. It's still a WIP as, for instance, we should handle the "legacy" configuration.
> AutoYaST default filesystem

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/partition_table.rb
- src/lib/y2partitioner/dialogs/partition_table_type.rb
- src/lib/y2storage/partitionable.rb
- test/y2partitioner/actions/controllers/partition_table_test.rb
https://trello.com/c/3LaKjLaH/248-1-sles15-p2-1078709-build-4321storage-ng-ms-dos-is-pre-selected-when-creating-new-partition-table
https://fate.suse.com/323457
See also the discussion in the PBI:
The old default coming from libstorage-ng was MSDOS unless it wouldn't work (because it's size limited to MaxUInt32 sectors or something like that). That default is overridden for certain classes in our Ruby part which preferred GPT everywhere.
The partitioner was the only part of the code simply using the default type coming from libstorage-ng; now this changed to GPT as well.
My changes in this PR reflect that changed default (in the unit tests), and it now build-requires the latest libstorage-ng that introduced that change to make sure the unit tests don't fail.
> Default for partition table type is now GPT, no longer MSDOS

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/activate.rb
- src/lib/y2storage/callbacks/commit.rb
- src/lib/y2storage/callbacks/libstorage_callback.rb
- src/lib/y2storage/callbacks/probe.rb
- test/y2storage/callbacks/activate_test.rb
- test/y2storage/callbacks/callbacks_examples.rb
- test/y2storage/callbacks/commit_test.rb
- test/y2storage/callbacks/probe_test.rb
This implements callbacks for https://trello.com/c/lo1jjvQDv/225-2-sles15-p1-1057869-build2011storage-ng-disk-will-be-encrypted-if-change-partition-settings-twice
If the user clicks on abort the exception is still raised. That will be fixed in a separate pull request. But I wanted to ensure this to make it into RC1.
>  Better handling of errors in the callbacks 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/actions_presenter.rb
https://trello.com/c/B6Cx73jd/285-multiple-p1s-add-missing-textdomain-in-y-storage-ng
https://bugzilla.suse.com/show_bug.cgi?id=1081454
The reason why this file was not picked up by y2makepot was that all translatable messages contain `#`. But that doesn't work for `_(...)` anyway since Ruby will expand the string inside the message before the message gets to `_(...)`, so the string is not constant, so it cannot be looked up as a `msgid` in the `.po` file.
> Fixed remaining translation

- doc/installer-hacks.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/commit.rb
- src/lib/y2storage/callbacks/libstorage_callback.rb
- src/lib/y2storage/clients/inst_prepdisk.rb
- src/lib/y2storage/storage_manager.rb
- test/y2storage/callbacks/activate_test.rb
- test/y2storage/callbacks/callbacks_examples.rb
- test/y2storage/callbacks/commit_test.rb
- test/y2storage/callbacks/probe_test.rb
- test/y2storage/clients/inst_prepdisk_test.rb
- test/y2storage/storage_manager_test.rb
Improvements for https://trello.com/c/ZFRZeyzr/240-3-ruby-code-handle-errors-during-probing
- Gentle handling of "abort" during commit (the exception is not longer visible)
- Infrastructure to do the same on activate+probe (used by https://github.com/yast/yast-installation/pull/663)
- Better Popup for libstorage-ng errors
- Use "Abort Installation" button instead of simply "Abort"
- Default to continue for activate and probe. Default to abort during commit.
- Updated the installer-hacks document (related to https://github.com/yast/yast-installation/pull/663, see https://trello.com/c/LiG0TAoK/213-finish-adaptation-of-instsystemanalysis)
> Improvements when aborting on libstorage-ng errors

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/btrfs_subvolume.rb
- src/lib/y2storage/filesystems/btrfs.rb
- test/y2storage/filesystems/btrfs_test.rb
- test/y2storage/subvol_specification_test.rb
When creating btrfs subvolumes the proper hierarchy must be preserved. It's not possible to create `/foo/bar` when a subvolume `/foo/bar/xxx` already exists.
If the filesystem hasn't been created yet we can just rearrange all subvolumes to fit the new one in. For an existing filesystem there's nothing we can do except notify the user.
> ensure proper hierarchy when creating btrfs subvolumes (bsc#1078732)

- doc/boot-partition.md
- doc/boot-requirements.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_strategies/prep.rb
- src/lib/y2storage/planned/assigned_space.rb
- src/lib/y2storage/planned/partition.rb
- src/lib/y2storage/volume_specification_builder.rb
- test/support/proposed_partitions_examples.rb
- test/y2storage/boot_requirements_checker_ppc_test.rb
- test/y2storage/proposal/partitions_distribution_calculator_test.rb
- test/y2storage/proposal_scenarios_ppc_test.rb
Implements https://trello.com/c/LKmwH0cb/286-3-sles15-p1-1082468-sles15-beta7-error-during-yast-installation-bootloader-prep
- General support to enforce primary planned partitions.
- Ensures the new PReP partition suggested by BootRequirementsChecker to be primary.
- Updated documentation.
>  Ensure PReP as primary (bsc#1082468) 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/widgets/fstab_options.rb
- src/lib/y2storage/btrfs_subvolume.rb
- src/lib/y2storage/filesystems/btrfs.rb
- test/data/devicegraphs/mixed_disks_btrfs.yml
- test/y2storage/btrfs_subvolume_test.rb
- test/y2storage/filesystems/btrfs_test.rb
- test/y2storage/mount_point_test.rb
https://trello.com/c/c4V8FLoO/276-1-sles15-p1-1080408-hps-bug-sles15-beta6-installer-writes-inconsistent-fstab-entries-for-btrfs-subvolumes
https://bugzilla.suse.com/show_bug.cgi?id=1080408
When creating subvolumes or their mount points, copy _mount_by_ from the parent Btrfs.
Also, when changing _mount_by_ for a Btrfs in the expert partitioner, apply that change to all subvolumes (all that have a mount point) as well; this is the best we can do right now because we don't have much of a user interface for any more detailed settings for subvolumes.
> Consistent mount_by for subvolumes

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/can_be_formatted.rb
- test/support/proposal_context.rb
- test/y2storage/proposal/initial_strategies/ng_test.rb
- test/y2storage/proposal_subvol_test.rb
First step to fix https://trello.com/c/MSBg5L2S/304-sles15-p1-1084213-storage-ng-home-subvolume-not-created-if-user-opts-to-not-have-a-home-partition
> Fix for bsc#1084213 and bsc#1084261

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/format_and_mount.rb
https://trello.com/c/BgAmje4M/
- Only during installation (not in the installed system, not during upgrade)
- Only if creating or editing a mount point that is not to be formatted
- Only for a small number of well-known system mount points:
- /
- /usr
- /boot
...post a warning:
Upon "Yes" (keep unformatted), apply the changes and close this dialog.
Upon "No", go back and let the user choose something else (format or change mount point).
> Warn if reusing an existing system mount point in the partitioner during installation

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/resize_blk_device.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
https://trello.com/c/lD8N7IET/200-5-partitioner-show-specific-error-messages-when-resizing-partitions
This is the first line of defence: If the filesystem type doesn't support resizing at all, this is the most obvious reason; we don't need to check if other, more complex conditions are met that the user might try to fix first. 
Since a filesystem is the innermost thing that is affected by a resize, otherwise the user might get errors about
- the partition that cannot be resized for any other reason
- an encryption layer that cannot be resized
There might still be more reasons, also on the filesystem level, why resizing is currently (!) not possible. But if it can't be done for a specific filesystem type at all, we don't need to bother with anything else; this is checked here, and it is …
> Check if partition resize is possible based on filesystem type

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/filesystems/base.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/filesystems/mount_by_type.rb
- src/lib/y2storage/filesystems/nfs.rb
- test/data/devicegraphs/md-imsm1-devicegraph.xml
- test/y2storage/filesystems/blk_filesystem_test.rb
- test/y2storage/filesystems/mount_by_type_test.rb
- test/y2storage/filesystems/nfs_test.rb
See https://trello.com/c/Mz4nNca0/302-3-sles15-p1-1071454-upgrade-to-sles15-fails-if-var-is-separate and https://github.com/yast/yast-update/pull/96#issuecomment-373754382
> Methods to deal with /etc/fstab specs (part of bsc#1071454)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/lvm_vg.rb
- src/lib/y2partitioner/actions/controllers/md.rb
- src/lib/y2storage/autoinst_proposal.rb
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/disk_device.rb
- src/lib/y2storage/fake_device_factory.rb
- src/lib/y2storage/region.rb
- src/lib/y2storage/yaml_writer.rb
- test/data/devicegraphs/complex-lvm-encrypt.yml
- test/data/devicegraphs/false-swaps.yml
- test/data/devicegraphs/zero-size_disk.yml
- test/y2partitioner/actions/controllers/lvm_vg_test.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/devicegraph_test.rb
- test/y2storage/fake_device_factory_test.rb
- test/y2storage/guided_proposal_test.rb
- test/y2storage/region_test.rb
- test/y2storage/yaml_writer_test.rb
PBI: https://trello.com/c/jPe9PnBi/308-3-sles15-p1-1083887-zero-size-disks-not-able-to-find-the-scsi-disks-while-trying-to-install-sles-15-on-vmax-luns
* Devices with zero-size are excluded to be used in Proposal and Partitioner. 
* Fixed tests to avoid creation of zero-size devices or partitions.
* Adapted yaml reader/writer to properly manage zero-size devices.
* Bonus: yaml reader/writer tests are re-written in a more rspec way.
> Fix errors with zero-size devices 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/resize_blk_device.rb
- src/lib/y2storage/resize_info.rb
- test/support/proposal_context.rb
- test/y2partitioner/actions/resize_blk_device_test.rb
- test/y2partitioner/dialogs/blk_device_resize_test.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/device_test.rb
- test/y2storage/lvm_lv_test.rb
- test/y2storage/partition_test.rb
- test/y2storage/planned/can_be_resized_test.rb
- test/y2storage/proposal/autoinst_devices_creator_test.rb
- test/y2storage/proposal/space_maker_test.rb
- test/y2storage/proposal_scenarios_x86_test.rb
- test/y2storage/resize_info_test.rb
https://trello.com/c/lD8N7IET/200-5-partitioner-show-specific-error-messages-when-resizing-partitions
Blog post: https://github.com/yast/yast.github.io/issues/147#issuecomment-375342963
This PR wraps the new resize blocker reasons from libstorage-ng to provide human-readable error messages for all the individual reasons that block a resize operation: 
There might be more than one problem at the same time. We want to show the user all of them, or at least all that make sense; it's no use to show him just one, and once he managed to fix that one, he might find out that there are more, so all his efforts (which might involve data loss due to deleting partitions and/for filesystems) were still in vain.
The first part of this uses introspection to look up constants starting with `RB_` and …
> Show specific error messages when resizing partitions

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/add_md.rb
- src/lib/y2partitioner/actions/controllers/md.rb
- src/lib/y2partitioner/dialogs/blk_device_resize.rb
- src/lib/y2partitioner/dialogs/format_and_mount.rb
- src/lib/y2partitioner/filesystem_errors.rb
- src/lib/y2partitioner/widgets/md_devices_selector.rb
- src/lib/y2storage/volume_specification.rb
- test/y2partitioner/actions/controllers/md_test.rb
- test/y2partitioner/dialogs/blk_device_resize_test.rb
- test/y2partitioner/dialogs/format_and_mount_test.rb
- test/y2partitioner/filesystem_errors_test.rb
- test/y2partitioner/widgets/md_devices_selector_test.rb
- test/y2storage/volume_specification_test.rb
PBI: https://trello.com/c/pvMqokfm/321-not-planned-sles15-p1-1085131-build-4864storage-ng-there-is-no-warning-when-btrfs-root-partition-is-too-small-for-snapshot
> Add snapshots size check 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/dialogs/proposal.rb
Better handling if the storage proposal just is "No proposal possible":
https://trello.com/c/1FvORDWg/315-2-sles15-p3-1064677-build-3101-internal-error-in-installer-on-click-on-booting-in-installation-summary-after-creating-invalid-pa
This affects the automatic proposal as well as the guided setup.
The error handling was always there, but the message was not really informative: "Cannot continue" does not give the user any hint what to do. So basically this just improves the error message:
The expert partitioner has its own error handling which presents errors to the user, but the user can decide to override any error and continue regardless.
> Better error handling if no storage proposal possible

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/clients/partitioner_testing.rb
- src/lib/y2partitioner/clients/main.rb
- src/lib/y2storage/callbacks/initialize.rb
- src/lib/y2storage/exceptions.rb
- src/lib/y2storage/storage_manager.rb
- test/y2partitioner/clients/main_test.rb
- test/y2storage/callbacks/initialize_test.rb
- test/y2storage/storage_manager_test.rb
PBI: https://trello.com/c/jItiacnG/335-readd-system-wide-lock-in-libstorage-ng
Notes for reviewers:
* [These changes](https://github.com/yast/yast-ruby-bindings/pull/215) in `yast-ruby-bindings`are required for this PR.
* Clients from other packages using storage-ng do not need to be adapted. With the default callbacks, an `AbortException` is raised if the user aborts and the process will finish.
* codeclimate is complaining for a couple of methods (high complexity), but it seems difficult to improve them without a less readable way.
* Class StorageManager starts to be too large, and codeclimate also detects it. Another class to lighten up in future.
> Handle lock system

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/initial_strategies/ng.rb
- test/y2storage/proposal/initial_strategies/ng_test.rb
The behavior was intentionally implemented in a different way to what was documented at https://github.com/yast/yast-storage-ng/blob/master/doc/old_and_new_proposal.md
Now code and documentation match.
> Make disable_order affect all configurable aspects of the volume

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/filesystems/legacy_nfs.rb
- src/lib/y2storage/mount_point.rb
- test/y2partitioner/widgets/pages/nfs_mounts_test.rb
Communicate properly with the embedded yast2-nfs-client so legacy entries using `nfs4` in the vfstype field can be detected and corrected.
This depends on https://github.com/openSUSE/libstorage-ng/pull/510 (I will add the dependency as soon as that gets merged).
> Partitioner: handle legacy entries which use nfs4

- package/yast2-storage-ng.spec
- test/data/devicegraphs/nfs1.xml
- test/y2partitioner/widgets/pages/nfs_mounts_test.rb
This depends on https://github.com/openSUSE/libstorage-ng/pull/511 being merged and a new docker image being available with the new XML format.
> Removed workaround in tests

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/assigned_space.rb
- src/lib/y2storage/planned/partitions_distribution.rb
- test/data/devicegraphs/bug_1088483.yml
- test/y2storage/guided_proposal_test.rb
- test/y2storage/proposal/space_maker_test.rb
Final step for https://trello.com/c/A2IzetTP/349-2-sles15-p1-1088483-storage-ng-parted-error-about-wrong-partition-end-sector
Bonus: memoize stuff in `PartitionsDistribution` and friends. Now the testsuite is 20% faster!!
> Fix unit tests and include test for bug#1088483

- Rakefile
just small note, after upgrade of yast-rake at https://github.com/yast/yast-rake/pull/53 IBS devel project will be "Devel:YaST:SLE-15" and not "Devel:YaST:Head". But it should not affect auto-submission.
> continue submitting to SLE15 GA

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
PBI: https://trello.com/c/Xy8pySwj/362-390-bug-reopen-partitioner-settings-mount-by
Needed to use `%ifarch s390` to decide what template to use for `/etc/sysconfig/storage`. This file is needed to decide the default `mount_by` value (and other Partitioner settings).
> Make the package arch dependant

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/dialogs/partition_role.rb
- src/lib/y2partitioner/filesystem_role.rb
- test/y2partitioner/actions/controllers/filesystem_test.rb
Main PR for https://trello.com/c/P3bHR7pD/369-not-estimated-p1-1084491-build-4897-storage-openqa-test-fails-in-installationsnapshots-snapper-is-not-configured-when-lvm-encryp
> Partitioner: default value for snapper checkbox (bsc#1084491)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/main.rb
Related to PBI: https://trello.com/c/VjBb7Jxy/347-2-sles15-p3-1086892-slex15loc-yastalllangsuntranslated-modify-the-disks-confirmation-pop-up-after-finishing-changes-in-expert-pa
The partitioner should not try to save after rescanning.
> Fix rescan option

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/clients/main.rb
- test/y2partitioner/clients/main_test.rb
Partitioner was failing after confirming changes in a running system.
The bug was introduced with PR#610. See also https://trello.com/c/VjBb7Jxy/347-2-sles15-p3-1086892-slex15loc-yastalllangsuntranslated-modify-the-disks-confirmation-pop-up-after-finishing-changes-in-expert-pa
> Fix partitioner client bug

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2storage/device.rb
- src/lib/y2storage/encryption.rb
- src/lib/y2storage/md.rb
- src/lib/y2storage/mount_point.rb
- src/lib/y2storage/mountable.rb
- test/data/devicegraphs/subvolumes-and-empty-md.xml
- test/y2storage/in_etc_test.rb
PR for https://trello.com/c/bM0mB7r9/146-3-storage-ng-set-inetcfstab-inetccrypttab-and-inetcmdadm
Tested manually and it works, as can be seen here (the action for adding it to cryptab is added and, thus, the system boots):
> Allow to reuse LUKS devices and MDs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_checker.rb
- src/lib/y2storage/boot_requirements_strategies/nfs_root.rb
- src/lib/y2storage/setup_checker.rb
- test/support/boot_requirements_context.rb
- test/y2storage/boot_requirements_errors_test.rb
- test/y2storage/setup_checker_test.rb
See https://trello.com/c/F1oQeriK/377-1-sles15-p1-1090752-internal-error-undefined-method-mbrgap-for-nilnilclass
The reporter found this crash installing on NFS-root in a diskless system
Additionally, while writing the unit tests I found the boot requirement checks also misbehaved if there were local disks combined with root in NFS, just in a different way.
This PR adds fixes and unit tests for both situations.
Even after fixing the crash, the SetupChecker was still reporting this warning.
Now that should also be fixed with the latest commit (added after the first approval of this PR). Everything up to that point tested manually in a diskless system and in a disk with a local disk (in addition to the NFS mount).
BUT, at the moment of writing bootloader fails if the user decides to …
> Proper partitioner checks for root on NFS (bsc#1090752)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/summary_text.rb
- src/lib/y2storage/actions_presenter.rb
- src/lib/y2storage/clients/inst_prepdisk.rb
- src/lib/y2storage/clients/partitions_proposal.rb
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/dialogs/proposal.rb
- src/lib/y2storage/dump_manager.rb
- src/lib/y2storage/proposal/base.rb
- src/lib/y2storage/storage_manager.rb
- src/lib/y2storage/yaml_writer.rb
- test/y2storage/actions_presenter_test.rb
- test/y2storage/clients/inst_prepdisk_test.rb
- test/y2storage/dump_manager_test.rb
https://trello.com/c/hvI17ITA/155-2-storageng-log-the-final-partitioning
This will dump device and action graphs to file at appropriate places during installation and in the installed system (when the partitioner is used).
During installation, it will create a directory `storage-inst` below `/var/log/YaST2` for those files; in the installed system, it will create a directory `storage` and rotate any previous such directory to keep at most 3 old ones of them:
- storage  (for the current files)
- storage-01  (for the last older ones)
- storage-02  (for even older ones)
- storage-03  (for even older ones)
For each program start (of the partitioner), those directories are rotated.
For the installation, it's always just `storage-inst`; any previous directory by that same name will be deleted …
> Dump devicegraphs to YAML and XML

- src/lib/y2storage/boot_requirements_strategies/analyzer.rb
- src/lib/y2storage/mount_point.rb
- src/lib/y2storage/setup_checker.rb
This is just something I realized while working on https://trello.com/c/F1oQeriK/377-1-sles15-p1-1090752-internal-error-undefined-method-mbrgap-for-nilnilclass
Now that we have a `MountPoint`class, there is a clear responsible for comparing paths and there is no need to fiddle with `Pathname` everywhere.
Cleaner code and the testsuite still passes.
> Centralize path comparison in MountPoint

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/dump_manager.rb
Imo and Ivan found out (independently) that the inst-sys doesn't provide rspec/mocks, so it was necessary to change that check for mocked objects.
> Hot fix: Don't require rspec/mocks (not in inst-sys)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/mount_point.rb
- test/y2storage/mount_point_test.rb
Continuation of https://trello.com/c/yzueuWcq/256-1-propose-correct-better-mount-options-for
> Use passno=2 for extX systems mounted in non-root paths

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_disk_proposal.rb
- src/lib/y2storage/dialogs/proposal.rb
- src/lib/y2storage/dump_manager.rb
- src/lib/y2storage/yaml_writer.rb
- test/y2storage/yaml_writer_test.rb
Don't record any LUKS passwords with the DumpManager.
Recording the passwords per se was not that much of a security problem, but sending y2logs would have been.
The DumpManager was only introduced some PRs ago with yast2-storage-ng-4.0.171.
RC4 does not contain it yet; build 600 (the latest one as of 2018-05-08 10:45) still contains yast2-storage-ng-4.0.169, so no beta tester was affected.
---------------------------------
After quite some discussions in the last related PR #609, here are now some changes when and under what names those devicegraphs and actions are dumped.
In an extreme example, if a user modifies the proposal during installation quite a bit, you get something like this:
- 01-probed.xml
- 01-probed.yml
- 02-proposed.xml
- 02-proposed.yml
- 03-actions.txt
- …
> Security fix + dump devicegraph and actions at better strategic places

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/yaml_writer.rb
- test/y2storage/yaml_writer_test.rb
https://trello.com/c/w14Rh3JY/378-1-yaml-writer-inform-about-missing-stuff
For device types (more exactly: for block devices) where we don't have proper support in our YAML reader / writer, add at least a section to the YAML output that shows that there is something so the XML file can be used for more details.
Sample output:
```yaml
- disk:
name: "/dev/sdc"
size: 32 GiB
block_size: 0.5 KiB
io_size: 0 B
min_grain: 1 MiB
align_ofs: 0 B
- unsupported_device:
type: Y2Storage::DmRaid
name: "/dev/mapper/isw_ddgdcbibhd_test1"
support: unsupported in YAML - check XML
- unsupported_device:
type: Y2Storage::DmRaid
name: "/dev/mapper/isw_ddgdcbibhd_test2"
support: unsupported in YAML - check XML
- unsupported_device:
type: Y2Storage::Filesystems::Nfs
name: server:/path
support: unsupported in YAML …
```
> Rudimentary support in YAML writer for unknown device types (RAID, multipath, NFS)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- src/lib/y2storage/proposal/autoinst_size_parser.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
- test/y2storage/proposal/autoinst_size_parser_test.rb
Fixes bsc#1092414. This problem happens when the mount point is not defined and size is set to 'auto' or filesystem_type is set to :btrfs.
> Do not crash when mount point is not defined

- package/yast2-storage-ng.changes
- src/lib/y2partitioner/actions/controllers/md.rb
- src/lib/y2partitioner/dialogs/md_options.rb
- src/lib/y2storage/md.rb
- test/y2partitioner/actions/controllers/md_test.rb
PBI: https://trello.com/c/wqCTgFxw/368-1-sles15-p2-1090182-build5741storage-ng-layout-not-understood-errors-when-setting-non-default-parity-for-raid5-and-raid10
> Fix raid options

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/mount_point.rb
See https://trello.com/c/XQXJVOVl/242-5-port-yast-nfs-client-to-storage-ng
To use storage-ng in yast2-nfs-client we need a more fine-grained control on what gets mounted during a commit, so we need to control the value of the `MountPoint#active?` flag
> Expose the active flag for MountPoint 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/fstab_options.rb
- src/lib/y2storage/filesystems/type.rb
- test/y2storage/filesystems/type_test.rb
_**This supersedes https://github.com/yast/yast-storage-ng/pull/649**_
https://trello.com/c/pVvQMTRq/313-2-sles15-p3-1084867-installer-does-not-handle-xfs-label-length-limitations
This limits what a user can enter for volume labels:
- The length of the volume label
- The permitted characters
The length is provided by libstorage-ng directly with `BlkFilesystem::max_labelsize()`.
There is no such counterpart for the permitted characters, so this was added to `Filesystem::Type` on the yast-storage-ng Ruby level.
We could provide a different set of characters for each filesystem, and this is actually prepared in this PR, but so far it does what was requested in the PBI: Keep it simple.
We now restrict it to `A..Za..z0..9` and some very few special characters: `-_.` (minus, underscore, period) …
> Limit volume label length and permitted characters

- test/spec_helper.rb
- test/y2storage/dump_manager_test.rb
- This is a preparation for the upcoming `parallel_tests` support, fixes a race condition when running several tests in parallel
- Actually fixed by Ancor during the YaST workshop
- The target is SLE15-GA to less diverge from master
> Added dumper mocking to not break parallel tests

- .travis.yml
- Speed up the build by splitting the work into separate jobs
- Run "yardoc" only once (was run two times, by `yast-travis-ruby` and then by `rake check:doc` here)
- Originally the Travis build time was 8-10 minutes, with this change the build is finished in less than 4 minutes (see [this](https://travis-ci.org/yast/yast-storage-ng/builds/389591445) and [this](https://travis-ci.org/yast/yast-storage-ng/builds/389597728) build)
- See the [related change in the Docker script](https://github.com/yast/docker-yast-ruby/pull/25)
As this only touches the `.travis.yml` file which is not packaged into the final RPM it is safe to include it also in the SLE15 branch.
> Run parallel jobs at Travis

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/filesystems/btrfs.rb
- test/y2storage/filesystems/btrfs_test.rb
Fixes [bsc#https://bugzilla.suse.com/show_bug.cgi?id=1096240](https://bugzilla.suse.com/show_bug.cgi?id=1096240).
> Fix subvolumes prefix detection when creating a filesystem

- .coveralls.yml
- .gitignore
- .rspec_parallel
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/spec_helper.rb
Speed up the unit tests by running them in parallel using the [parallel_tests](https://github.com/grosser/parallel_tests) gem.
- The local speed up is about `npcu`-times, i.e. with quad core CPU the speed up is about 4x (on my machine with HT enabled the speed up is ~4.4x)
- The Travis speed up is about 1.4x (4min15s -> 3min7s), the [Travis doc](https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System) says the worker has ~1.5CPU power. That's still quite a good improvement...
- This will speed up also build in OBS, the workers use `-smp 8` or even `-smp 16` KVM option, the speed up should be significant there
- This is SLE15-GA compatible change, it does not change anything in SLE15-GA, only the SLE15-SP1/Leap15.1 will be affected
- I have …
> Run the unit tests in parallel

- package/yast2-storage-ng.spec
Tumbleweed does not define `%sle_version` (in contrast to Leap).
https://en.opensuse.org/openSUSE:Packaging_for_Leap#RPM_Distro_Version_Macros
> Compatibility fix for Tumbleweed

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/partition_size.rb
libyui's IntField widget works only with 32 bits. Since the major visible
advantage over a plain InputField are the controls allowing to
increase/decrease the value by one - which is not very helpful here - I
think it's fine to use an InputField here.
I've also changed the logic for the min/max values presented: it used to
show the first and last available blocks regardless whether these belong to
the same unused region.  This runs into the problem that in nearly all cases
you run into an error if you just confirm the defaults (for instance the min
value used to be _before_ the first partition).
Instead it now shows the default (largest) region (which is always a valid
> allow for numbers > 32 bit in region dialog (bsc#1065258)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/libstorage_callback.rb
- test/y2storage/callbacks/callbacks_examples.rb
The strings received from libstorage have ASCII-8BIT encoding which makes troubles when it contains UTF-8 characters. Processing such strings might result in the `Encoding::CompatibilityError` exception.
See https://bugzilla.suse.com/show_bug.cgi?id=1096758
> Fixed crash in the error callback when passing UTF-8 string from libstorage-ng (bsc#1096758)

- package/yast2-storage-ng.changes
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/actions/controllers/fstabs.rb
- src/lib/y2partitioner/filesystem_role.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/filesystems/btrfs.rb
- src/lib/y2storage/volume_specification.rb
- test/y2partitioner/actions/controllers/filesystem_test.rb
- test/y2partitioner/actions/controllers/fstabs_test.rb
Part of https://trello.com/c/S2PrGCQz/388-ostumbleweed-p5-1094924-partition-imported-during-installation-would-all-be-formatted-by-default
Review commit by commit.
Manually tested: works as expected.
> Manage Btrfs stuff when importing mount points

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/drive_section.rb
- src/lib/y2storage/autoinst_profile/partitioning_section.rb
- test/y2partitioner/clients/main_test.rb
- test/y2storage/autoinst_profile/partitioning_section_test.rb
Second part of https://trello.com/c/BEBfAZTf/142-1-p2-1098594-support-for-bios-defined-md-in-autoyast
It also includes a commit to add a mock that was missing in the testsuite (it was trying to fiddle with udevadm).
> AutoYaST: fix exporting of BIOS RAIDs (bsc#1098594)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/blk_device_attributes.rb
- src/lib/y2partitioner/widgets/help.rb
For https://trello.com/c/0ygAghdd/15-sles15-p3-1070570-yast-partitioner-names-the-partition-table-disk-label.
> use "Partition Table" instead of "Disk Label" (bsc#1070570)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/drive_section.rb
This fixes the bsc#1098594 regression unit test in [partitioning_section_test.rb](../tree/SLE-15-GA/test/y2storage/autoinst_profile/partitioning_section_test.rb#L105) as otherwise `drive.device` would be nil on s390.
> make bsc#1098594 regression test work on s390

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/partition_section.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
Fixes [bsc#1103113](https://bugzilla.suse.com/show_bug.cgi?id=1103113).
> Export lvm_group for MD RAID devices

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_disk_proposal.rb
- test/y2storage/clients/inst_disk_proposal_test.rb
The old fix was not working if the user went back and forth in the installer because the status was tracked in an extra instance variable, instead of checking the already existing variables that are always properly initialized.
See https://github.com/yast/yast-storage-ng/pull/697#discussion_r207894154 for details.
> Fix the check about a manual staging (bsc#1055756)

- package/yast2-storage-ng.changes
- src/lib/y2partitioner/widgets/pages/disk.rb
- src/lib/y2partitioner/widgets/pages/disks.rb
- src/lib/y2partitioner/widgets/pages/partition.rb
- src/lib/y2partitioner/widgets/pages/stray_blk_device.rb
Some stuff found during https://trello.com/c/EqN6jm0m/172-5-sles15-p3-1085134-cannot-install-when-using-xen-virtual-partitions-xvda1xvda2 that was not worth fixing in the SLE-15-GA branch due to i18n overhead.
> Partitioner: fix heading strings and comments

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned.rb
- src/lib/y2storage/planned/device.rb
- src/lib/y2storage/planned/stray_blk_device.rb
- src/lib/y2storage/proposal/autoinst_devices_creator.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- src/lib/y2storage/proposal/autoinst_drives_map.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
Main PR for https://trello.com/c/f0FOcqlx/185-5-sles15-p3-1085134-autoyast-for-xen-virtual-partitions-xvda1xvda2
For historical reasons, a system with the Xen virtual partitions `/dev/xvda1`, `/dev/xvda2` and `/dev/xvdb1` is represented in the AutoYaST profile as: 
```xml
<drive>
<device>/dev/xvda</device>
<partition>
<partition_nr>1</partition_nr>
...information about /dev/xvda1...
</partition>
<partition>
<partition_nr>2</partition_nr>
...information about /dev/xvda2...
</partition>
</drive>
<drive>
<device>/dev/xvdb</device>
<partition>
<partition_nr>1</partition_nr>
...information about /dev/xvdb1...
</partition>
</drive>
```
Where `/dev/xvda` and `/dev/xvdb` are devices that really do not exist in the system. With this changes, such creative `<drive>` sections are recognized and the …
> Process Xen virtual partitions from AutoYaST profiles

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/partitions_proposal.rb
- test/data/devicegraphs/empty_hard_disk_128MiB.yml
- test/y2storage/clients/partitions_proposal_test.rb
https://trello.com/c/1K6xCnFa/
https://bugzilla.suse.com/show_bug.cgi?id=1099762
That product's workflow doesn't use the usual storage proposal as a separate workflow step before the installation summary proposal, it uses the older client which is called at the installation summary proposal together with all the other proposals (software, bootloader, ...).
That older proposal client has largely fell out of use; it is otherwise only used for AutoYaST which has a bit different preconditions.
When it could not make any storage proposal because the disk was simply too small, it caused a crash because it tried to assign a `nil` proposal to the storage manager which gladly accepted that, but crashed when it tried to deep-copy it.
- Added unit test with a small (5 GiB) disk to check for this …
> Prevent nil:NilClass crash in Kubic if disk too small

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/dialogs/guided_setup/select_root_disk.rb
- test/support/guided_setup_context.rb
- test/y2storage/dialogs/guided_setup/select_root_disk_test.rb
- [Trello Card](https://trello.com/c/VnLlG6Lp/13-sles15-p2-1055646-storageng-guided-setup-select-hard-disks-what-to-do-with-windows)
- [Bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=1055646)
> Hide windows actions if there are no windows partitions

- package/yast2-storage-ng.changes
- test/y2partitioner/actions/controllers/filesystem_test.rb
To fix the build failure at https://build.opensuse.org/project/show/openSUSE:Factory:Staging:G
It's only failing in master (TW) because the libstorage-ng version in SLE-15 somehow hides the mistake, but I believe it's worth fixing the test also in the SLE-15-GA branch for consistency.
> Fix inconsistent test environment (and improve wording) 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/blk_device_attributes.rb
- src/lib/y2partitioner/widgets/blk_devices_table.rb
- test/y2partitioner/widgets/configurable_blk_devices_table_test.rb
- test/y2partitioner/widgets/partition_description_test.rb
> Mount point asterisk

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
This PR includes the fix reported by @benlorenz regarding issue #727.
Thanks!
> Fix reuse by partition number

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/disk_analyzer.rb
- test/y2storage/disk_analyzer_test.rb
Related to https://bugzilla.suse.com/show_bug.cgi?id=1101979
> If there is any problem during the content info detection, it will not
be considered as windows partition.
> Do not crash during the content info detection

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/has_size.rb
- src/lib/y2storage/planned/stray_blk_device.rb
- src/lib/y2storage/proposal/autoinst_devices_creator.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- test/support/storage_helpers.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/proposal/autoinst_devices_creator_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
This allows partition 0 to stand as an alias for the full disk.
> support full disk devices as lvm pv in autoyast profile (bsc#1107298)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/blk_device.rb
- src/lib/y2partitioner/actions/delete_device.rb
- src/lib/y2partitioner/actions/resize_blk_device.rb
- src/lib/y2partitioner/dialogs/blk_device_resize.rb
- src/lib/y2partitioner/immediate_unmount.rb
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/mount_point.rb
- src/lib/y2storage/storage_manager.rb
- test/y2partitioner/actions/controllers/blk_device_test.rb
- test/y2partitioner/actions/delete_partition_test.rb
- test/y2partitioner/actions/resize_blk_device_test.rb
- test/y2partitioner/dialogs/blk_device_resize_test.rb
- test/y2storage/blk_device_test.rb
PBI: https://trello.com/c/e1TpNp2Y/213-5-partitioner-handle-on-the-fly-unmounting-in-installed-system
Requires https://github.com/yast/yast-yast2/pull/817
NOTE
This PR is intentionally not merged yet. These changes should not be included as Self Update, so we are going to merge [this L3](https://trello.com/c/1icYnFLW/266-l3-sles15-1107298-autoyast-disk-directly-as-pv-doesnt-work) before. Maybe, if we are lucky, we don't get more L3s after merging the code of this PR and so it would not be included in the Self Update.
> Try to unmount devices for some actions

- src/lib/y2storage/blk_device.rb
- test/y2storage/blk_device_test.rb
This coded has been backported from `master` because it is needed to find out when a drive should be included in an (exported) AutoYaST profile.
> Backport BlkDevice#component_of

- src/lib/y2storage/planned/can_be_md_member.rb
- src/lib/y2storage/planned/disk.rb
- src/lib/y2storage/planned/partition.rb
- src/lib/y2storage/planned/stray_blk_device.rb
- src/lib/y2storage/proposal/autoinst_devices_creator.rb
- src/lib/y2storage/proposal/autoinst_disk_device_planner.rb
- test/y2storage/planned/can_be_md_member_test.rb
This PR extends #754 so a disk can be used as a MD RAID too. In the image below you can see a `raid0` which uses `5GiB` from `vda1` and the whole `vdb` disk (20GiB).
> Allow to use disk as a RAID member

- src/lib/y2storage/proposal/autoinst_disk_device_planner.rb
- test/y2storage/proposal/autoinst_disk_device_planner_test.rb
Fix support to reuse a Xen virtual partition as a RAID member. It looks like a weird case,
but it is rather easy to support it.
> Support to use a Xen virtual partition as a RAID member

- package/yast2-storage-ng.changes
- src/lib/y2partitioner/actions/create_partition_table.rb
For ms-dos partition tables the default minimal_mbr_gap setting of 1 MiB
prevents creating partitions in the expert partitioner starting at a lower
value (via the region dialog).
Note this is not an issue with gpt, there you can already do this.
> lower minimal mbr gap size to allow creating unaligned partitions

- package/yast2-storage-ng.changes
- src/lib/y2storage/partition_id.rb
Rather add 'Partition' explicitly if really needed. This way it's possible
to use the partition type in texts consistently.
The understanding is that 'XXX partition' and 'partition of type XXX' should
both be legible terms.
> do not include 'Partition' in partition type names

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/actions_presenter.rb
- test/y2storage/actions_presenter_test.rb
Replace a newline `\n` in a compound action with the proper HTML line break `<br>` to show a newline where one is meant to be.
See also the example actions in https://github.com/openSUSE/libstorage-ng/pull/585 :
Create bcache /dev/bcache0 on /dev/sda (2.00 TiB) for /data with ext4
/dev/bcache0 is cached by /dev/sdf (128.00 MiB)
Create encrypted bcache /dev/bcache1 on /dev/sdb (512.00 GiB) for /home with xfs
/dev/bcache1 is cached by /dev/sdg (160.00 MiB)
Create RAID6 /dev/md0 (1023.75 GiB) for /data with ext4
from /dev/sda (512.00 GiB), /dev/sdb (512.00 GiB), /dev/sdc (512.00 GiB), /dev/sdd (512.00 GiB)
> Support for compound actions with newlines

- src/lib/y2storage/proposal/partition_killer.rb
- src/lib/y2storage/proposal/space_maker.rb
First step for https://trello.com/c/DVQH3p2n/397-8-bug1057436-improve-confusing-spacemaker-strategy-fate325885-preserve-irst-partitions-in-guided-proposal
This basically implements what is described at https://github.com/yast/yast-storage-ng/blob/master/doc/space_maker_improve_strategy.md
Please don't be too picky about name or level of documentation of internal methods. The next step would be to adapt them in order to support IRST and similar stuff.
It's much easier to review commit by commit.
> SpaceMaker: refactor the code to be more flexible

- test/y2partitioner/actions/controllers/fstabs_test.rb
- test/y2partitioner/dialogs/md_edit_devices_test.rb
This PR fixes the test suite to avoid aleatory segmentation faults like [this](https://build.suse.de/build/Devel:YaST:Head/SUSE_SLE-15-SP1_GA/s390x/yast2-storage-ng/_log) in OBS and IBS.
The problem was produced because some tests were using an instance of a devicegraph that no longer exists, so it could produce a segmentation fault when the ruby garbage collector takes place. 
Each case is explained in the code.
> Fix segmentation fault in unit tests

- doc/boot-requirements.md
- doc/the-boot-partition-and-me.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- rakelib/doc_bootspecs.rake
- src/lib/y2storage/boot_requirements_strategies/analyzer.rb
- src/lib/y2storage/boot_requirements_strategies/base.rb
- src/lib/y2storage/boot_requirements_strategies/legacy.rb
- src/lib/y2storage/boot_requirements_strategies/uefi.rb
- src/lib/y2storage/filesystems/type.rb
- src/lib/y2storage/partition_tables/msdos.rb
- src/lib/y2storage/partitionable.rb
- test/support/boot_requirements_context.rb
- test/y2storage/boot_requirements_checker_aarch64_test.rb
- test/y2storage/boot_requirements_checker_x86_test.rb
- test/y2storage/boot_requirements_duplicate_test.rb
- test/y2storage/boot_requirements_errors_test.rb
- test/y2storage/boot_requirements_strategies/analyzer_test.rb
- test/y2storage/disk_test.rb
- test/y2storage/proposal_scenarios_x86_test.rb
WIP
- some test cases are not yet adapted
- the 'whole disk' case gives the wrong warning (due to default = gpt): https://github.com/yast/yast-storage-ng/pull/788/commits/3637f8c8c8a9c21176f5ac4c216bfe9cfe435c79
The logic in the boot requirements check for legacy is a bit broken. So I start by putting things straight.
In the legacy (non-efi) case, using ms-dos partition table, in
https://github.com/yast/yast-storage-ng/blob/master/doc/boot-requirements.md
the entire 'with too small MBR gap' - section can go. It's basically the same as the 'mbr gap too small' part of the lvm/encryption case. I don't see why proposing /boot to embed grub is sometimes good and sometimes bad.
The code now consistently proposes a /boot partition if the mbr gap is too small. No error is raised. This should have …
> fix boot requirements: legacy

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_disk_proposal.rb
- src/lib/y2storage/clients/partitions_proposal.rb
- src/lib/y2storage/dialogs/guided_setup.rb
- test/y2storage/clients/inst_disk_proposal_test.rb
- test/y2storage/clients/partitions_proposal_test.rb
- test/y2storage/dialogs/guided_setup_test.rb
Installation summary links to storage client instead of Expert Partitioner directly. Moreover, the Guided Setup wizard can be now canceled, see https://bugzilla.suse.com/show_bug.cgi?id=1121442.
PBI: https://trello.com/c/53IEUxrB/577-susecaas-platform-4-p2-1099485-caasp-specific-partitioning-warning-dialog-missing-in-storage-ng
~~Requires this be merged: https://github.com/yast/yast-yast2/pull/886~~
> Link to storage client

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/used_storage_features.rb
- test/y2storage/used_storage_features_test.rb
For https://trello.com/c/OkmGMBQG/632-sle15-sp1-1122781-p1-installer-throws-error-message-after-selection-of-multipath-disk-on-sles-15-sp1-beta2.
> do not include nil in package list of used storage features for FC devices (bsc#1122781)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/partitions_distribution_calculator.rb
- src/lib/y2storage/proposal/space_maker.rb
- test/data/devicegraphs/output/windows-pc-50GiB-gpt-sep-home.yml
- test/data/devicegraphs/output/windows-pc-50GiB-gpt.yml
- test/data/devicegraphs/output/windows-pc-enc-sep-home.yml
- test/data/devicegraphs/output/windows-pc-enc.yml
- test/data/devicegraphs/output/windows-pc-gpt-enc-sep-home.yml
- test/data/devicegraphs/output/windows-pc-gpt-enc.yml
- test/data/devicegraphs/output/windows-pc-gpt-sep-home.yml
- test/data/devicegraphs/output/windows-pc-gpt.yml
- test/data/devicegraphs/output/windows-pc-sep-home.yml
- test/data/devicegraphs/output/windows-pc.yml
See https://trello.com/c/0ZARc9rP/602-1-bug1057436-chapter-two-avoid-two-passes-if-not-needed
Review by commit.
The **second commit** adapts the test in a way that is equivalent to the adaptations found in https://github.com/yast/yast-storage-ng/pull/822. That's because this pull request mitigates the effect of some problems of the original `PartitionsDistributionCalculator.#resizing_size` that are fixed in that other PR. To be precise, this "hides" the following problems described in the other pull request
- Windows partitions are reduced 1 extra MiB if there is some space in the disk. That is done just in case, even if there is no real misalignment to fix. With two passes, the first resizing introduced that space, so the second one added the extra MiB.
- When there is a free space >1MiB …
> SpaceMaker: avoid two passes if not needed (bug#1057436) 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/free_disk_space.rb
- src/lib/y2storage/partition.rb
- src/lib/y2storage/planned/assigned_space.rb
- src/lib/y2storage/planned/partitions_distribution.rb
- src/lib/y2storage/proposal/partitions_distribution_calculator.rb
- test/data/devicegraphs/windows-pc-gpt-with-gap.yml
- test/data/devicegraphs/windows_resizing1.yml
- test/data/devicegraphs/windows_resizing2.yml
- test/y2storage/proposal/partitions_distribution_calculator_test.rb
- test/y2storage/proposal/space_maker_test.rb
This basically implements https://trello.com/c/gdXTlipJ/288-bug1057436-chapter-three-better-calculation-of-resize-windows
With this, the tests at #816 are all green, which means:
- The resizing calculation is not longer confused by other (probably useless) spaces in the disk. This used to have catastrophic consequences.
- When resizing a Windows with a misaligned end (quite common in GPT), we don keep the misalignment. Instead, we take the opportunity to fix it and avoid the gap.
In addition, the remaining test (most adaptations were done already in #825) is now adapted to the new (more correct) behavior because:
- Windows partitions are not always reduced 1 extra MiB just in case. Only when there is a real misalignment to fix.
- With the previous behavior, when there was a free space …
> Windows better resize

- doc/boot-requirements.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_strategies/uefi.rb
- test/spec_helper.rb
- test/support/proposed_partitions_examples.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/boot_requirements_checker_aarch64_test.rb
- test/y2storage/boot_requirements_checker_raspi_test.rb
- test/y2storage/boot_requirements_checker_x86_test.rb
- test/y2storage/disk_analyzer_test.rb
- test/y2storage/filesystems/btrfs_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
- test/y2storage/subvol_specification_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1119318
https://trello.com/c/vjCvQuGp/650-1-sles15-sp1-p2-1119318-installer-suggest-way-too-big-uefi-esp
The UEFI ESP partition was considered much too large on aarch64. Small flash storage (16 GiB SD cards etc.) are quite common for RasPI, and using 512 MiB on such a device only for the ESP consumes a considerable part of the available storage already.
Limit the size of that partition to the minimum on that architecture.
> Limit ESP to min size on aarch64 (bsc#1119318)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/bcache.rb
Some setters have been removed from libstorage-ng because `bcache` command has no way to make permanent changes for such attributes (`writeback_percent` and `sequential_cutoff`).
* https://trello.com/c/sdR0Hwi3/607-2-use-the-new-bcache-command-instead-of-make-bcache
* https://fate.suse.com/325346
This PR simply adapts the ruby wrappers by removing the setters.
> Remove bcache setters

- .github/pull_request_template.md
- Having a pull request template should make the pull requests unified and easier to write.
- It's just a suggested template, feel free add/remove some parts as you need or edit the texts.
- For example some pull requests do not need any screenshot so just remove that section.
- Let's try it in this repository and see how it works. We can later add it to all YaST repositories or drop it if it does not work as expected. :stuck_out_tongue_closed_eyes: 
The rendered template looks like this:
----
*Short description of the original problem.*
- *Bugzilla link*
- *openQA link*
- *Links to other related pull requests*
*Short description of the fix.*
*If the fix affects the UI attach some screenshots here.*
> Added a Pull Request Template

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/clients/main.rb
- test/y2partitioner/clients/main_test.rb
See https://trello.com/c/deksXijN/671-3-sles15-sp1-p1-1123837-error-popup-shown-twice-followed-by-an-unhandled-exception
> Partitioner: abort gracefully in installed system (bsc#1123837)

- .codeclimate.yml
- The CodeClimate checks are too strict.
- https://trello.com/c/JtowjQ61
- Disable the checks which are done also by Rubocop (with less strict limits)
- I kept the duplication checks which are not supported by Rubocop
- None, let's see how the CC will evaluate the code and how the metrics change...
> Disable most checks at CodeClimate

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/add_bcache.rb
- src/lib/y2partitioner/actions/delete_bcache.rb
- src/lib/y2partitioner/dialogs/bcache.rb
- src/lib/y2partitioner/widgets/bcache_add_button.rb
- test/y2partitioner/actions/add_bcache_test.rb
- test/y2partitioner/dialogs/bcache_test.rb
- test/y2partitioner/widgets/bcache_add_button_test.rb
Bcache devices can be created without an associated caching set. In fact, this is a recommended practice if you are thinking about using bcache later. The idea is to setup all your slow devices as bcache backing devices without a cache, and you can choose to add a caching device later.
The Expert Partitioner needs to be adapted to allow bcache creation without a caching set.
- https://jira.suse.de/browse/SLE-4329
- https://trello.com/c/GMjxjMJC/654-3-allow-to-create-a-bcache-without-cset
The widget to select the caching set now has a new option: "Without caching". 
* Added unit tests.
* Manually tested.
Option to not select caching device
Error when there are no suitable backing devices
Added help
> Allow to create bcache without caching set

- test/data/devicegraphs/dasd_50GiB.yml
- test/data/devicegraphs/empty_dasd_50GiB.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm-sep-home.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm.yml
- test/data/devicegraphs/output/s390_dasd_zipl.yml
- test/y2partitioner/actions/create_partition_table_test.rb
- test/y2partitioner/widgets/blk_device_edit_button_test.rb
- test/y2partitioner/widgets/pages/system_test.rb
- test/y2storage/autoinst_profile/skip_list_value_test.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/boot_requirements_checker_s390_test.rb
- test/y2storage/boot_requirements_strategies/analyzer_test.rb
- test/y2storage/dasd_test.rb
- test/y2storage/hwinfo_reader_test.rb
- test/y2storage/partition_tables/dasd_test.rb
- test/y2storage/partition_test.rb
- test/y2storage/proposal_scenarios_s390_test.rb
Unrealistic device name in unit tests make unit tests more difficult to understand.
Use realistic device names.
> use realistic device name for DASD

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/raid_options_section.rb
- test/y2storage/autoinst_profile/raid_options_section_test.rb
The device_order was so far not saved in the AutoYaST profile during cloning.
- https://bugzilla.suse.com/show_bug.cgi?id=1083542
Save the device_order.
> save device_order for MD RAIDs in AutoYaST profile

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/dialogs/guided_setup/base.rb
- src/lib/y2storage/dialogs/guided_setup/select_disks.rb
- test/y2storage/dialogs/guided_setup/select_disks_test.rb
The screen to select the disks to run the Guided Setup is unusable if there are more than 20 disks to choose from. See
| nCurses       | Qt           |
| ------------- |-------------|
| ![current-curses-30](https://gist.githubusercontent.com/ancorgs/67dcd8a52debd95496137a1cd5bacf6f/raw/734b565d7757b79f47f94f504051f25fcbbe2395/current-curses-30.png) | ![current-qt-30](https://gist.githubusercontent.com/ancorgs/67dcd8a52debd95496137a1cd5bacf6f/raw/734b565d7757b79f47f94f504051f25fcbbe2395/current-qt-30.png) |
In addition, we wanted to take the opportunity to improve the descriptions of the disk. For example, there is nothing to identify external disks like USB.
- [bsc#1123688](https://bugzilla.suse.com/show_bug.cgi?id=1123688) about unusable screen with many disks
- [Gist discussing the …
> Guided Setup: improve disk selection screen

- doc/bcache.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/overview.rb
- src/lib/y2storage/bcache.rb
- src/lib/y2storage/devicegraph_sanitizer.rb
- test/y2storage/bcache_cset_test.rb
- test/y2storage/bcache_test.rb
- test/y2storage/devicegraph_sanitizer_test.rb
https://trello.com/c/f1pcGKbD/673-3-bcache-in-non-x8664-systems
https://jira.suse.de/browse/SLE-4329
Bcache is only really supported (on the kernel and upstream tools side) on a limited range of platforms. Currently, this is only the x86_64 architecture.
Right after probing, check if bcache is in use (i.e. if there is an existing bcache device).
Probing is safe since this only uses external tools like the `blkid` command and checks for `/sys` etc. paths that the kernel generated.
If there is an existing bcache, but we don't fully support bcache on that architecture, post a warning, but let the user proceed anyway.
This is implemented via the DevicegraphSanitizer which is run over the probed devicegraph to check for problems. Now a new error class for bcache is added if any bcache device …
> Limit Bcache Support to x86_64 Arch

- package/yast2-storage-ng.changes
The fix in #799 listed the correct bug ID in the git commit but the wrong one in the RPM changelog.  I noticed this when I updated a Leap 15.0 machine and the summary for the wrong bug was shown in the patch info.
PR for master branch forthcoming, as it doesn't seem possible to submit both branches at once.
> Fix bug # for 4.0.215 changelog.

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/y2partitioner/actions/add_bcache_test.rb
- test/y2partitioner/actions/delete_bcache_test.rb
- test/y2partitioner/actions/edit_blk_device_test.rb
- test/y2partitioner/dialogs/bcache_test.rb
- test/y2partitioner/widgets/bcache_add_button_test.rb
- test/y2partitioner/widgets/bcache_device_description_test.rb
- test/y2partitioner/widgets/bcache_modify_button_test.rb
- test/y2partitioner/widgets/device_buttons_set_test.rb
- test/y2partitioner/widgets/pages/bcache_test.rb
- test/y2partitioner/widgets/pages/bcaches_test.rb
- test/y2partitioner/widgets/pages/system_test.rb
- test/y2storage/blk_device_test.rb
- test/y2storage/devicegraph_test.rb
Unit tests fail on arch other than x86_64 because there is no more bcache support there.
Now forcing mocking arch to x86_64 for those unit tests that depend on bcache things; otherwise `fake_scenario` will get an exception _probed devicegraph not sanitized_.
> Force mocking x86_64 architecture for unit tests that depend on bcache

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/md.rb
- src/lib/y2storage/proposal/autoinst_md_planner.rb
- test/y2storage/autoinst_proposal_md_test.rb
- test/y2storage/planned/md_test.rb
The device order for MD RAIDs was not handled by AutoYaST during installation.
https://bugzilla.suse.com/show_bug.cgi?id=1083542
Handle the device order during installation.
- Extended unit test
> handle device_order for MD RAIDs during installation

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/dialogs/guided_setup/select_disks.rb
- src/lib/y2storage/dialogs/guided_setup/select_filesystem/base.rb
- src/lib/y2storage/dialogs/guided_setup/select_root_disk.rb
- src/lib/y2storage/dialogs/guided_setup/select_scheme.rb
There were no help texts yet in the _guided setup_.
- Trello: https://trello.com/c/iCjvewN0/
- Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1121801
Manually tested with the proposal test client:
```
/sbin/yast2 ./proposal_testing.rb ../../test/data/devicegraphs/windows-pc.yml
```
(or any other suitable YAML or XML devicegraph)
If there are Windows partitions that can be resized, this can contain two more lines that refer to the resize options.
This is a bit lame; in particular, it does not explain the pros and cons of the different filesystem types. It also does not explain why and when a user would want a separate /home partition and the pros and cons of Btrfs snapshots.
The problem with that is that those widges are created quite dynamically, depending on the settings on …
> Help Texts for Guided Setup

- test/y2partitioner/actions/controllers/bcache_test.rb
- test/y2partitioner/actions/edit_bcache_test.rb
- test/y2partitioner/ui_state_test.rb
- test/y2partitioner/widgets/bcache_edit_button_test.rb
- test/y2storage/devicegraph_test.rb
Bcache tests require arch to be mocked as x86.
* Related to https://trello.com/c/cQo16PQ5/672-editing-an-in-memory-bcache-device-devices-and-cache-mode
* https://jira.suse.de/browse/SLE-4329
Mock arch where it is needed.
- Unit tests
> Add missing arch mocking for bcache tests

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/configure.rb
- src/lib/y2partitioner/widgets/reprobe.rb
- src/lib/y2partitioner/widgets/rescan_devices_button.rb
- test/support/partitioner_reprobe_examples.rb
- test/y2partitioner/widgets/configure_test.rb
When executed on an already installed system (i.e. not in installation), the Partitioner of storage-ng does not contain any way to activate pre-existing but inactive LUKs device.
The old partitioner (pre-ng) didn't executed an activation by default either, but it offered two ways of activating such device so it could be mounted or used in any other way.
1) The user can click on "Edit" for an encrypted partition and then, in the first screen of the Edit wizard, select to mount the existing file-system. In that case, the next step of the Edit wizard consists on asking the password and activating the existing LUKS.
2) There is also a general option "Provide Crypt Passwords" that is available in  "Configure..." just alongside the similar "Configure Multipath" also used to activate inactive …
> Partitioner: button to activate crypt devices

- test/y2storage/fake_device_factory_test.rb
With new ruby 2.6, testsuite has started to fail randomly. Such random failures use to indicate that some tests are using objects that should not be there (e.g., a discarded `devicegraph`). When that happens, the test fails if the ruby Garbage Collector is called before accessing to such objects.
Most likely ruby 2.6 has introduced any change with the GC, or simply the order of tests is now different (we have created new test files). Those could be the reasons why the test failure appears now and not before.  
Fix testsuite to use correct objects.
> Fix testsuite

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/pages/bcaches.rb
- test/y2partitioner/widgets/pages/bcaches_test.rb
The Expert Partitioner shows the bcache devices, but  there is no way to see all the caching set devices. 
- https://jira.suse.de/browse/SLE-4329
- https://trello.com/c/NbiTkMzT/689-1-tab-to-display-the-bcache-csets
The Bcache section of the Expert Partitioner has now two tabs instead of the list of bcache devices. The first tab (with the label `Bcache Devices`) shows the former list of bcache devices. The second tab (with label `Caching Set Devices`) lists all existing caching sets.
- Added unit tests
> Add tab for caching set devices

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- test/y2partitioner/actions/controllers/filesystem_test.rb
Insonsistency with old partitioner which keeps old label if just refformating fs.
- https://bugzilla.suse.com/show_bug.cgi?id=1087229
lets keep label even when reformat filesystem.
> Preserve old filesystem label (bsc##1087229)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2storage/dialogs/guided_setup/select_root_disk.rb
- src/lib/y2storage/dialogs/guided_setup/select_scheme.rb
- test/y2partitioner/actions/controllers/filesystem_test.rb
- test/y2partitioner/dialogs/btrfs_subvolume_test.rb
- test/y2partitioner/widgets/overview_test.rb
- test/y2storage/dialogs/guided_setup/select_root_disk_test.rb
- test/y2storage/disk_test.rb
- test/y2storage/filesystems/btrfs_test.rb
- test/y2storage/partition_test.rb
This is about bringing back a convenience function in the partitioner:
When adding an ESP (EFI System Partition), the partitioner should automatically suggest `/boot/efi` as the mount point.
- Trello: https://trello.com/c/qatyxSB8/
- Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1088120
Refactored the one other similar special case into a new function _suggested_mount_path_ in the controller class of that partitioner dialog.
This now automatically suggests a mount point _swap_ for swap filesystems and _/boot/efi_ for ESPs.
Please notice that this is unconditional whether or not the system currently uses EFI boot (which is consistent with the behaviour of creating a new ESP): The user might be in the process of setting up the system for EFI boot for which he will need the ESP.
This …
> Suggest /boot/efi as Mount Point for ESP in Partitioner

- package/yast2-storage-ng.changes
- src/lib/y2storage/autoinst_profile/partition_section.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
When cloning a system with GPT, AutoYaST still generating
> <partition_type>primary</partition_type>
However, this attribute does not make sense when dealing with GPT partition tables.
- https://bugzilla.suse.com/show_bug.cgi?id=1115751
- https://trello.com/c/9ZIgDgWF
Do not export it when the partition belongs to a GPT partition table.
- Also tested manually
> Do not export the partition_type attribute when belongs to GPT

- Rakefile
We were ignoring the rake check about valid changelog entries. That was introduced when yast-storage-ng was a prototype, but it makes no sense anymore now that is an official package that must adhere to YaST standards.
Just remove the line specifying to skip the changelog checks.
> Don't skip the changelog check anymore

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/filesystem_role.rb
The filesystem roles in partitioner were not being translated due a wrongly placed `textdomain`.
- https://bugzilla.suse.com/show_bug.cgi?id=1127756
Move the `textdomain` to the `initialize` method.
| Before | After |
|--------|-------|
| ![unfixed_filesytem_role_selection](https://user-images.githubusercontent.com/1691872/53747767-e7b89f00-3e9b-11e9-8d48-7e82bb656735.png) | ![fixed_filesystem_role_selection](https://user-images.githubusercontent.com/1691872/53747778-eedfad00-3e9b-11e9-87a3-90b28e8a18c8.png) |
> Fix missing translations in partitioner

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/partition_table_type.rb
- src/lib/y2storage/callbacks/libstorage_callback.rb
- src/lib/y2storage/devicegraph_sanitizer.rb
- src/lib/y2storage/dialogs/guided_setup/select_root_disk.rb
There were a missing translation an a "can't modify frozen String" crash.
- https://bugzilla.suse.com/show_bug.cgi?id=1125006
- https://bugzilla.suse.com/show_bug.cgi?id=1127181
Simply fix those errors.
> Avoid to crash when frozen String and fix missing translation

- src/lib/y2partitioner/dialogs/partition_table_type.rb
Fix translation, using a `%s` flag instead a `%{device_name}`
Discussed in IRC
> \<dgdavid> ancorgs: I regret to check that you were right :( --> https://github.com/yast/yast-translations/commit/a764fd40804ed07bd56de51359309791749c2c3e#diff-f567bd0448f631420a03b5f26ea184baR1542
> \<ancorgs> dgdavid: yes, that was another argument I forgot to use: keeping the old string that was already translated in yast-storage
> \<ancorgs> it all summarize to the same. In I18n stuff, be conservative
> \<ancorgs> if we keep the old string, it will be translated already in all languages
> \<dgdavid> ancorgs: do you think I should do a new PR changing the %{device_name} by %s ?
> \<ancorgs> dgdavid: yes. It's two minutes for us. And will safe 5 minutes for each translator
Using a @lslezak words from other …
> Fix translation using flag instead named parameter

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/blk_device_resize.rb
- test/y2partitioner/dialogs/blk_device_resize_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1124146
https://trello.com/c/OUo0x3S3/
In the partitioner, when the user changed an existing partition to be formatted and then immediately clicked on "resize", there would be a crash with a libstorage exception.
The code tried to call `detect_size_info` on the filesystem, but that filesystem did not yet exist in the probed/system devicegraph.
Now also checking if the planned filesystem is the same as the existing one or if it is new.
Manual test on my workstation with "yast2 disk" and a USB stick.
Changed the existing VFAT filesystem to ext4 and then hit _Resize_.
> Prevent crash if resizing a newly formatted filesystem

- package/yast2-storage-ng.changes
- src/lib/y2storage/autoinst_profile/partition_section.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
In #860 was introduced a too much specific checking to decide if the `partition_type` attribute should be exported when cloning.
See the @ancorgs' [comment](https://github.com/yast/yast-storage-ng/pull/860#discussion_r264133770)
Use the PartitionTable API.
> Improve the logic to decide when exports partition_type attribute

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/icons.rb
- src/lib/y2partitioner/widgets/blk_devices_table.rb
- src/lib/y2partitioner/widgets/configure.rb
- src/lib/y2partitioner/widgets/pages/bcache.rb
- src/lib/y2partitioner/widgets/pages/bcaches.rb
- src/lib/y2partitioner/widgets/pages/btrfs.rb
- src/lib/y2partitioner/widgets/pages/device_graph.rb
- src/lib/y2partitioner/widgets/pages/devices_table.rb
- src/lib/y2partitioner/widgets/pages/disk.rb
- src/lib/y2partitioner/widgets/pages/lvm_lv.rb
- src/lib/y2partitioner/widgets/pages/lvm_vg.rb
- src/lib/y2partitioner/widgets/pages/md_raid.rb
- src/lib/y2partitioner/widgets/pages/nfs_mounts.rb
- src/lib/y2partitioner/widgets/pages/partition.rb
- src/lib/y2partitioner/widgets/pages/settings.rb
- src/lib/y2partitioner/widgets/pages/stray_blk_device.rb
- src/lib/y2partitioner/widgets/pages/summary.rb
- src/lib/y2partitioner/widgets/pages/system.rb
Some icons used by the Expert Partitioner are not provided (neither by [yast-theme](https://github.com/yast/yast-theme/tree/master/icons/hicolor/scalable/apps) nor by [libyui-qt](https://github.com/libyui/libyui-qt/tree/master/src/icons)): *fcoe*, *xpram*, *dasd* and *zfcp* icons are missing. As consequence, the *Configure* menu button does not show the icon for some of its options, see the following screenshot:
* Related to https://bugzilla.suse.com/show_bug.cgi?id=1122174
* https://trello.com/c/IcPWJBUW/817-3-missing-icons-in-partitioner-configure
* [old_icons.tar.gz](https://github.com/yast/yast-storage-ng/files/2960648/old_icons.tar.gz)
* https://github.com/libyui/libyui-qt/pull/101
@hellcp has provided [svg version](https://github.com/libyui/libyui-qt/pull/101) for the missing icons. …
> Add missing icons

- src/lib/y2storage/filesystems/type.rb
- test/data/devicegraphs/btrfs_bcache.xml
- test/data/devicegraphs/dasd1.xml
- test/data/devicegraphs/md-imsm1-devicegraph.xml
- test/data/devicegraphs/output/empty_dasd_fba_gpt-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-root-docker-lvm.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-root-swap.yml
- test/data/devicegraphs/output/ppc_power_nv-lvm.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm-sep-home.yml
- test/data/devicegraphs/output/s390_dasd_zipl-lvm.yml
- test/data/devicegraphs/output/s390_dasd_zipl.yml
- test/data/devicegraphs/output/s390_zfcp_zipl.yml
- test/data/devicegraphs/output/windows-pc-mbr256-lvm-sep-home.yml
- test/data/devicegraphs/output/windows-pc-mbr256-lvm.yml
- test/data/devicegraphs/partitioned_btrfs_bcache.xml
- test/y2storage/filesystems/type_test.rb
https://trello.com/c/Ys1c4kVI
https://bugzilla.suse.com/show_bug.cgi?id=1122867
Some mount options that we always added are now default:
- ext2/3/4: `acl` and `user_xattr`
Remove them from the default options that we write to /etc/fstab.
No change log entry and no version bump because this will have to wait for merging until SLE-15-SP1 is branched off, and we don't want any unnecessary merge conflicts and problems with the change log check scripts in OBS complaining about change log entries out of chronological sequence.
> Don't add mount options that are default (ext2/3/4: acl, user_xattr)

- src/lib/y2partitioner/widgets/format_and_mount.rb
- src/lib/y2storage/partition_id.rb
- test/y2storage/partition_id_test.rb
https://trello.com/c/uJDzzpFV/
_No corresponding bug_
Partition IDs (types) were not sorted in any meaningful way in the partitioner.
Introduced a sort order on the Ruby level of that type (enum which is imported and mapped from libstorage-ng).
We now have a table in the Ruby code for the desired sort order and a spaceship operator (`<=>`) that uses that table so the normal Ruby `sort` function can be used:
https://github.com/yast/yast-storage-ng/pull/872/files#diff-ecc44dd40509958fa302edf2358c7f8fR60
Of course the partitioner still only shows those types that are actually applicable, not just every value of that enum.
Values that are not in that sort order table are sorted at the end.
This is for SLE-15 SP2. We need to wait until we have a branch for SLE-15 SP1, so for now there is no …
> Sort Partition IDs Logically

- src/lib/y2storage/disk_analyzer.rb
- src/lib/y2storage/existing_filesystem.rb
- src/lib/y2storage/partition.rb
- src/lib/y2storage/partitionable.rb
- test/support/proposal_context.rb
- test/y2storage/existing_filesystem_test.rb
- test/y2storage/partition_test.rb
**IMPORTANT NOTE**: this PR is going to be merged into *pre-SLE-15-SP2* branch. That branch will not be merged into master until *SLE-15-SP1* is branched. Before merging *pre-SLE-15-SP2* branch, a new entry should be added to the changelog (describing all changes provided by *pre-SLE-15-SP2* branch) and the version number should be bumped to *4.2.0*.
The class `ExistingFilesystem` is the responsible of mounting an existing filesystem and inspecting its content to get some information, e.g., the name of the installed OS, the content of the fstab file, etc. But *libstorage-ng* offers its own mechanism to detect a Windows system, and `DiskAnalyzer` class directly ask to *libstorage-ng* to check if a filesystem contains a Windows. But everything related to a filesystem inspection should be …
> Move windows system detection

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/spec_helper.rb
- test/y2partitioner/actions/add_bcache_test.rb
- test/y2partitioner/actions/controllers/bcache_test.rb
- test/y2partitioner/actions/delete_bcache_test.rb
- test/y2partitioner/actions/edit_bcache_test.rb
- test/y2partitioner/actions/edit_blk_device_test.rb
- test/y2partitioner/dialogs/bcache_test.rb
- test/y2partitioner/ui_state_test.rb
- test/y2partitioner/widgets/bcache_add_button_test.rb
- test/y2partitioner/widgets/bcache_device_description_test.rb
- test/y2partitioner/widgets/bcache_edit_button_test.rb
- test/y2partitioner/widgets/bcache_modify_button_test.rb
- test/y2partitioner/widgets/device_buttons_set_test.rb
- test/y2partitioner/widgets/pages/bcache_test.rb
- test/y2partitioner/widgets/pages/bcaches_test.rb
- test/y2partitioner/widgets/pages/system_test.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
- test/y2storage/autoinst_proposal_bcache_test.rb
- test/y2storage/bcache_cset_test.rb
- test/y2storage/bcache_test.rb
- test/y2storage/blk_device_test.rb
- test/y2storage/devicegraph_sanitizer_test.rb
- test/y2storage/devicegraph_test.rb
- test/y2storage/proposal/autoinst_bcache_planner_test.rb
- test/y2storage/proposal/autoinst_devices_creator_test.rb
- test/y2storage/proposal/bcache_creator_test.rb
The `DevicegraphSanitizer` complains when Bcache is used with an architecture different to *x86_64*. In unit tests, architecture has to be mocked to avoid test failures when the tests are executed in another architecture. This has demonstrated to be quite error prone. With new tests involving Bcache, OBS will fail when generating the package for other architectures if you forget mocking the architecture.
Errors for Bcache should be mocked in general, and only unmocked when needed.
* Follow-up of https://trello.com/c/WYoMDTMZ/852-bsc1129787-bootrequirementschecker-fails-to-determine-the-boot-disk
* https://bugzilla.suse.com/show_bug.cgi?id=1129787
Errors for Bcache are generally mocked. Architecture mocking is also removed from unit tests that don't require it anymore.
> Fix bcache tests

- test/y2storage/autoinst_proposal_bcache_test.rb
Architecture mocking was dropped for tests involving Bcache, but we went too far for an autoyast test where mocking is still needed.
* PR dropping architecture mocking: https://github.com/yast/yast-storage-ng/pull/880
Bring back architecture mocking for a autoyast test.
* All unit tests have been run by simulating a ppc arch and all of them are green now.
NOTE FOR REVIEWERS: version number and changelog are not modified because previous PR and these changes will be manually submitted together (no SR yet).
> Mock architecture for autoyast test

- test/y2storage/existing_filesystem_test.rb
The unit tests are failing in architectures other than x86. For example in [aarch64](https://build.opensuse.org/package/live_build_log/openSUSE:Factory:ARM/yast2-storage-ng/standard/aarch64), [armv7](https://build.opensuse.org/package/live_build_log/openSUSE:Factory:ARM/yast2-storage-ng/standard/armv7l) and [armv6](https://build.opensuse.org/package/live_build_log/openSUSE:Factory:ARM/yast2-storage-ng/standard/armv6l).
- See bugzilla: [bsc#1130957](http://bugzilla.suse.com/show_bug.cgi?id=1130957)
Mock also the architecture when mocking the Windows presence
> Fix unit tests in ARM architecture (bsc#1130957)

- doc/autoyast.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_issues/list.rb
- src/lib/y2storage/autoinst_profile/drive_section.rb
- src/lib/y2storage/autoinst_profile/partition_section.rb
- src/lib/y2storage/autoinst_profile/partitioning_section.rb
- src/lib/y2storage/planned.rb
- src/lib/y2storage/planned/devices_collection.rb
- src/lib/y2storage/planned/md.rb
- src/lib/y2storage/planned/nfs.rb
- src/lib/y2storage/proposal/autoinst_devices_creator.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- src/lib/y2storage/proposal/autoinst_drives_map.rb
- src/lib/y2storage/proposal/autoinst_nfs_planner.rb
- src/lib/y2storage/proposal/nfs_creator.rb
- test/support/storage_helpers.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
- test/y2storage/autoinst_profile/partitioning_section_test.rb
- test/y2storage/autoinst_proposal_nfs_test.rb
- test/y2storage/planned/devices_collection_test.rb
- test/y2storage/proposal/autoinst_devices_creator_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
- test/y2storage/proposal/autoinst_drives_map_test.rb
- test/y2storage/proposal/autoinst_nfs_planner_test.rb
- test/y2storage/proposal/nfs_creator_test.rb
In SLE-12, AutoYaST supported installation over NFS. The way to indicate NFS drives in the AutoYaST profile is not documented at all, but it can be achieved by giving a *\<device\>* inside the *\<partition\>* section. This invalidates the profile because *\<partition\>* cannot contain a *\<device\>*, but it works in SLE-12.
Storage-ng has no support for installing over NFS with AutoYaST, so the *\<device\>* hack should be brought back again.
* https://bugzilla.suse.com/show_bug.cgi?id=1130256
* https://trello.com/c/x4LYDnwe/865-3-l3-important-bug-1130256-autoyast-for-a-nfs-root-fails-at-partitioning
Add support for installing over NFS as before, that is, by specifying a device inside the partition section. Such device contains the NFS share in which to install.
NOTE: exporting NFS is not …
> Add support for NFS in AutoYaST

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/initial_guided_proposal.rb
- src/lib/y2storage/proposal/settings_generator/base.rb
- src/lib/y2storage/proposal_settings.rb
- test/y2storage/initial_guided_proposal_test.rb
- test/y2storage/proposal/settings_generator/legacy_test.rb
- test/y2storage/proposal/settings_generator/ng_test.rb
- test/y2storage/proposal_settings_test.rb
Initial settings are not being restored before each proposal attempt because
> `Yast.deep_copy` is quite a fail that only copies one level, leaving the second level as references instead of copies. — [extracted from Ancor's comment](https://github.com/yast/yast-storage-ng/pull/889#discussion_r271681321)
See also, 
- https://bugzilla.suse.com/show_bug.cgi?id=1130392
- https://trello.com/c/KJpkiH4P/889-1130392-storage-disabled-volumes-stay-disabled-during-proposal-process
~~Overwrite the [`ProposalSettings#dup`](https://github.com/yast/yast-storage-ng/compare/SLE-15-SP1...feature/bsc-1130392-fix-reset-proposal-settings?expand=1#diff-30d4c4c7ff63d32d4f2fa075e77d3290R209)~~ Added a [`ProposalSettings#deep_copy`](https://github.com/yast/yast-storage-ng/pull/889/files#diff-30d4c4c7ff63d32d4f2fa0 …
> Fix resetting proposal settings

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_issues/list.rb
- src/lib/y2storage/autoinst_profile/drive_section.rb
- src/lib/y2storage/autoinst_profile/partition_section.rb
- src/lib/y2storage/autoinst_profile/partitioning_section.rb
- src/lib/y2storage/boot_requirements_checker.rb
- src/lib/y2storage/planned.rb
- src/lib/y2storage/planned/devices_collection.rb
- src/lib/y2storage/planned/md.rb
- src/lib/y2storage/planned/nfs.rb
- src/lib/y2storage/proposal/autoinst_devices_creator.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- src/lib/y2storage/proposal/autoinst_drives_map.rb
- src/lib/y2storage/proposal/autoinst_nfs_planner.rb
- src/lib/y2storage/proposal/nfs_creator.rb
- test/support/storage_helpers.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
- test/y2storage/autoinst_profile/partitioning_section_test.rb
- test/y2storage/autoinst_proposal_nfs_test.rb
- test/y2storage/planned/devices_collection_test.rb
- test/y2storage/proposal/autoinst_devices_creator_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
- test/y2storage/proposal/autoinst_drives_map_test.rb
- test/y2storage/proposal/autoinst_nfs_planner_test.rb
- test/y2storage/proposal/nfs_creator_test.rb
Backporting PR https://github.com/yast/yast-storage-ng/pull/884.
NOTE: in SLE-15-GA, AutoYaST base code is slightly different to SP1 and master. For example, bcache is not supported at all. This PR backports https://github.com/yast/yast-storage-ng/pull/884 but adapting the code as needed.
> Backport (GA): Add support for NFS in AutoYaST

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/drive_section.rb
- src/lib/y2storage/autoinst_profile/partition_section.rb
- src/lib/y2storage/autoinst_profile/partitioning_section.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- src/lib/y2storage/proposal/autoinst_nfs_planner.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
- test/y2storage/autoinst_profile/partitioning_section_test.rb
- test/y2storage/autoinst_proposal_nfs_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
- test/y2storage/proposal/autoinst_nfs_planner_test.rb
NFS drives are specified in the AutoYaST profile by an "undocumented" option. That is, by defining a drive with a "/dev/nfs" device, and then, each partition defines a NFS share, e.g.:
```
<drive>
<device>/dev/nfs</device>
<partitions>
<partition>
<mount>/</mount>
<device>server:path</device>
</partition>
</partitions>
</drive>
```
The <partition> section contains a <device> attribute. This is quite unexpected, because a <partition> section cannot contain a <device>. In fact, the AutoYaST profile does not validate.
The support for importing this kind of drives was already implemented in [here](https://github.com/yast/yast-storage-ng/pull/890). But now we have to find a better way for defining NFS drives and be able to import/export this new format.
Note: currently, old format cannot be …
> Add support for NFS in Autoyast (new format)

- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/widgets/btrfs_subvolumes_table.rb
This PR does not solve a specific problem. Instead, simply removes
* A [quite confusing comment](https://github.com/yast/yast-storage-ng/commit/ac181fb3516bcdbea57c9eaf140d781ed1a730af) that we found while working on  https://github.com/yast/yast-storage-ng/pull/897. It could be interpreted in two ways
- It is describing an old behavior and clarifying that it is no longer available in the new Partitioner, or 
- It is a forgotten note which should have been removed [when the `BlkDeviceRestorer` was included](https://github.com/yast/yast-storage-ng/commit/6b22232d69100a6b8428774399a85198047af3b6).
In case of the first interpretation, it seems to be not necessary nowadays. For the second one, it is simply a comment that must be removed.
* A [leftover …
> Remove dead code

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/pages/bcaches.rb
Some strings in the Partitioner are not being displayed in the correct language
- https://bugzilla.suse.com/show_bug.cgi?id=1126822
Adding missing calls to `textdomain` in the widgets' constructors.
- Tested manually with the RC2 ISO and the file modified by hand.
See bug report for screenshots of the failure.
> Textdomain 1126822 sp1

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/main.rb
- src/lib/y2partitioner/ui_state.rb
- src/lib/y2partitioner/widgets/device_button.rb
- src/lib/y2partitioner/widgets/device_menu_button.rb
- src/lib/y2partitioner/widgets/overview.rb
- test/y2partitioner/ui_state_test.rb
> In the old partitioner is possible to open and collapse branches of the tree and it remains as it is set.
However, 
> in the new one (the tree) is always fully extended, with no collapsed branch.
- https://trello.com/c/dVI060Q3/206-3-partitioner-remember-the-state-of-the-tree-at-least-branches-closed-by-the-user
Based on method proposed by @jreidinger in https://github.com/yast/yast-yast2/pull/734 and [holding a reference to the `OverviewPagerTree` in `UIState`](https://github.com/yast/yast-storage-ng/blob/9a1a5e07830498724d1487617bec7586734d6d82/src/lib/y2partitioner/dialogs/main.rb#L65), it is now possible to query and save open items of the tree [to preserve their state between instances](https://github.com/yast/yast-storage-ng/blob/9a1a5e07830498724d1487617bec7586734d6d82/src/lib/y2p …
> [Partitioner] Remember the tree state

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/actions/edit_btrfs.rb
- src/lib/y2partitioner/dialogs/btrfs_options.rb
- src/lib/y2partitioner/dialogs/format_and_mount.rb
- src/lib/y2partitioner/filesystem_errors.rb
- src/lib/y2partitioner/widgets/btrfs_options.rb
- src/lib/y2partitioner/widgets/filesystem_options.rb
- src/lib/y2partitioner/widgets/format_and_mount.rb
- src/lib/y2partitioner/widgets/pages/btrfs.rb
- src/lib/y2partitioner/widgets/pages/btrfs_filesystems.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- test/y2partitioner/actions/edit_btrfs_test.rb
- test/y2partitioner/dialogs/btrfs_options_test.rb
- test/y2partitioner/widgets/btrfs_options_test.rb
- test/y2partitioner/widgets/pages/btrfs_test.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
Currently, the button for editing a Btrfs filesystem opens a dialog to manage its subvolumes. The button should open a dialog for editing the filesystem options, similar to the dialog for editing a block device.
* https://jira.suse.de/browse/SLE-3877
* https://trello.com/c/Icti2ZBT/947-3-partitioner-editing-btrfs-filesystems
Now, the edit button opens a dialog to edit the Btrfs filesystem. The dialog allows to set the mount point, mount options, configure subvolumes, and enable/disable snapshots (this last only for root during installation).
- Added unit tests
> Edit Btrfs filesystems

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/blk_devices_table.rb
- src/lib/y2partitioner/widgets/configurable_blk_devices_table.rb
- src/lib/y2partitioner/widgets/fstab_selector.rb
- src/lib/y2partitioner/widgets/pages/system.rb
- src/lib/y2storage/partition.rb
- test/data/devicegraphs/efi_not_mounted.yml
- test/y2partitioner/widgets/pages/system_test.rb
- test/y2storage/partition_test.rb
According to ["BtrFS in partitioner" document](https://github.com/yast/yast-storage-ng/blob/master/doc/btrfs_in_partitioner.md) document, column "Fs Type" does not have sense any more and the value for "Type" must be change to fullfill requirements described in ["Partitioner with multidevice BTRFS" gist](https://gist.github.com/joseivanlopez/06e92d5784da7efad7a6feeeb8e2eac6).
Part of https://trello.com/c/BUuCsg5A/945-2-partitioner-new-type-column-and-multi-device-btrfs-in-general-list
* Removed the "Fs Type" column
* Changed the content of "Type" column
- Tested manually using the _partitioner_testing_ client.
<details>
<summary>Click to show/hide</summary>
---
| Partitioner using the `yast.xml` file attached in the linked gist | …
> Use new "Type" column

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/ui_state.rb
- src/lib/y2partitioner/widgets/bcache_add_button.rb
- src/lib/y2partitioner/widgets/configure.rb
- src/lib/y2partitioner/widgets/device_button.rb
- src/lib/y2partitioner/widgets/device_menu_button.rb
- src/lib/y2partitioner/widgets/execute_and_redraw.rb
- src/lib/y2partitioner/widgets/import_mount_points_button.rb
- src/lib/y2partitioner/widgets/lvm_vg_add_button.rb
- src/lib/y2partitioner/widgets/md_add_button.rb
- src/lib/y2partitioner/widgets/overview.rb
- src/lib/y2partitioner/widgets/rescan_devices_button.rb
- test/y2partitioner/ui_state_test.rb
- test/y2partitioner/widgets/overview_test.rb
In theory, the Partitioner should start with all the sections (like "Hard Disks", "Volume Management", etc.) open by default, so the first level of devices is visible.
But when a section was initially empty and the first device was added, the section remained closed. That's wrong. When the very first device is added, the default behavior (open displaying the first level of devices) should be applied.
The wrong behavior can be seen at
https://openqa.opensuse.org/tests/920618#step/partitioning_full_lvm/51
Reported as [bsc#1133686](https://bugzilla.suse.com/show_bug.cgi?id=1133686)
Trello: https://trello.com/c/XYcpfC8F/957-ostumbleweed-p5-1133686-partitioner-misbehavior-of-tree-sections-that-were-initially-empty
In addition, while fixing this we noticed the status of the tree was not saved …
> Partitioner: fix behavior of tree sections that were initially empty

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/blk_devices_table.rb
- test/y2partitioner/widgets/pages/system_test.rb
After merge #911, we realized that it contained below undesired behaviors
* It was displaying a wrong icon for a Btrfs multidevice filesystem _(because it was using the default one)_.
* It was using a wrong device name for a multidevice filesystem.
* It was displaying the label for a device which is part of a multidevice.
* It was displaying the mount point for a device which is part of a multidevice.
* It was displaying the unfinished "PV of" string in certain situation, when the VG does not have a basename (yet).
Fix all of them.
<details>
<summary>Click to show/hide</summary>
---
| Before |
|-------|
| ![Screenshot_opensusetumbleweed_2019-04-30_14:58:55](https://user-images.githubusercontent.com/1691872/56970250-a58ba100-6b5e-11e9-915d-789f992f0ee7.png) |
| After |
| …
> Fix "Type" column

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/blk_device.rb
- src/lib/y2partitioner/actions/delete_btrfs.rb
- src/lib/y2partitioner/actions/delete_device.rb
- src/lib/y2partitioner/actions/edit_blk_device.rb
- src/lib/y2partitioner/ui_state.rb
- src/lib/y2partitioner/widgets/device_buttons_set.rb
- src/lib/y2partitioner/widgets/device_delete_button.rb
- src/lib/y2partitioner/widgets/pages/btrfs.rb
- src/lib/y2partitioner/widgets/pages/btrfs_filesystems.rb
- src/lib/y2storage/disk_analyzer.rb
- src/lib/y2storage/mountable.rb
- test/data/devicegraphs/btrfs2-devicegraph.xml
- test/y2partitioner/actions/delete_btrfs_test.rb
- test/y2partitioner/actions/edit_blk_device_test.rb
- test/y2partitioner/ui_state_test.rb
- test/y2partitioner/widgets/device_buttons_set_test.rb
We found that treating the deletion and edition of multi-device Btrfs just like any other filesystem leaded to problems and inconsistencies. For example.
- Starting point: a Btrfs over sda1 and sdb1
- The user edits sda1 and marks it to be formatted as ext4. That deletes the Btrfs.
- The user uses sdb1 for something else (let's say LVM)
- The user edits sda1 again and chooses "Do not format"
In the regular case, "do not format" means keeping the filesystem that is currently in sda1 in the `system` devicegraph (i.e. in the real disk). But that cannot be done because a multi-device filesystem cannot be restored from the `system` devicegraph to the `current` one (first of all, sdb1 is not available anymore.
Trello card: https://trello.com/c/DdttqbRR/956-2-button-to-delete-multi-device-btrfs …
> Partitioner: button to delete btrfs and pop-up to protect multi-device filesystems

- package/yast2-storage-ng.spec
- Missing URL tag in the spec file
- https://bugzilla.suse.com/show_bug.cgi?id=1097956
- The tag has been added
- Additionally I have used `spec-cleaner` to fix the other potential issues and to reformat the spec file
It's recommended to review each commit separately, the first change was done automatically by the `spec-cleaner` tool, then I fixed small regressions and finally added the missing URL.
> Reformatted spec, added URL tag (bsc#1097956)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- test/y2storage/proposal/autoinst_disk_device_planner_test.rb
AutoYaST fails when trying to reuse a non-formatted partition as-is (i.e. without formatting it). By definition, it means AutoYaST can hardly be used to reuse BIOS BOOT partitions.
- See https://bugzilla.suse.com/show_bug.cgi?id=1134330
This fixes two issues:
- First of all, the "missing reusable filesystem" issue was always reported twice due to a code duplication.
- More important, this avoids false positives when reporting such error. If the partition is not intended to be mounted and no filesystem type is specified, is probably ok if the partition to be reused is not currently formatted.
- Regression unit test added
Review commit by commit, it makes more sense.
> Fix bug#1134330 in SLE-15-GA

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/blk_device.rb
- src/lib/y2partitioner/actions/edit_blk_device.rb
- src/lib/y2partitioner/actions/resize_blk_device.rb
- src/lib/y2partitioner/dialogs/blk_device_resize.rb
- src/lib/y2storage/lvm_pv.rb
- src/lib/y2storage/resize_info.rb
- test/y2partitioner/actions/controllers/blk_device_test.rb
- test/y2partitioner/actions/edit_blk_device_test.rb
- test/y2partitioner/actions/resize_blk_device_test.rb
- test/y2partitioner/dialogs/blk_device_resize_test.rb
- test/y2storage/lvm_pv_test.rb
NOTE FOR REVIEWERS: failing test is because this PR requires [this changes](https://github.com/openSUSE/libstorage-ng/pull/646) be merged. But this PR could be already reviewed anyway.
The Expert Partitioner does not allow to resize a device when the device is being used by a multi-device Btrfs filesystem. It shows a message about device in use.
* https://jira.suse.de/browse/SLE-3877
* https://trello.com/c/mB6C51ir/973-3-libstorage-ng-resize-btrfs-with-multiple-devices
* Requires this changes: https://github.com/openSUSE/libstorage-ng/pull/646
First of all, libstorage-ng has been adapted to allow resizing multi-device Btrfs, see https://github.com/openSUSE/libstorage-ng/pull/646. In the Expert Partitioner, the "device in use" message has been suppressed  when the device belongs to a …
> Resize multi-device Btrfs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- test/y2storage/proposal/autoinst_disk_device_planner_test.rb
Bug#1134330 was fixed for SLE-15-GA and verified by the reporter at #922. Merging to other branches is still missing.
This merges #922 into SLE-15-SP1
https://trello.com/c/mimudxBQ/987-l3-sled15-1134330-ay-on-nvme-disks-could-not-find-a-reusable-filesystem
> Merge bugfix for bug#1134330 into SLE-15-SP1

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- test/y2storage/proposal/autoinst_disk_device_planner_test.rb
Bug#1134330 was fixed for SLE-15-GA and verified by the reporter at #922. Merged into SLE-15-SP1 by #928. Merging to master is still missing.
This merges #922 into master
https://trello.com/c/mimudxBQ/987-l3-sled15-1134330-ay-on-nvme-disks-could-not-find-a-reusable-filesystem
> Merge bugfix for bug#1134330 into master

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/lvm_vg.rb
- src/lib/y2storage/proposal/autoinst_devices_creator.rb
- src/lib/y2storage/proposal/devicegraph_generator.rb
- src/lib/y2storage/proposal/devices_planner_strategies/base.rb
- src/lib/y2storage/proposal/devices_planner_strategies/ng.rb
- src/lib/y2storage/proposal/lvm_helper.rb
- src/lib/y2storage/proposal/partitions_distribution_calculator.rb
- src/lib/y2storage/proposal/phys_vol_calculator.rb
- src/lib/y2storage/proposal/phys_vol_strategies/base.rb
- src/lib/y2storage/proposal/phys_vol_strategies/use_available.rb
- src/lib/y2storage/proposal/phys_vol_strategies/use_needed.rb
- src/lib/y2storage/proposal/space_maker.rb
- src/lib/y2storage/proposal_settings.rb
- src/lib/y2storage/volume_specification.rb
- test/data/control_files/separate_vgs.xml
- test/y2storage/planned/lvm_vg_test.rb
- test/y2storage/proposal/lvm_helper_test.rb
- test/y2storage/proposal/partitions_distribution_calculator_test.rb
- test/y2storage/proposal_separate_vgs_test.rb
For SUSE Manager we want the storage proposal to work in a different way than the regular (open)SUSE.
There will be a new `separate_vgs` setting to indicate the proposal must allocate some volumes as a LVM logical volume in its own separate dedicated volume group.
In the control file, some volumes will have a new attribute `separate_vg_name` to indicate they can be allocated like that. The rest of the <partitioning> section of control.xml would stay as it is now.
* See [description of the feature](https://gist.github.com/ancorgs/c7c9d7ccd3feb38b3f40e85d58e4a671) from the UI perspective.
* See [card describing the feature](https://trello.com/c/aIAbysbE/)
* See [PBI for this first step](https://trello.com/c/k5ZZNKdJ/)
This PBI includes some previous refactoring needed to implement this …
> Proposal: support for separate VGs

- src/lib/y2storage/proposal/phys_vol_strategies/base.rb
- test/data/control_files/separate_vgs.xml
The test coverage for #931 was intentionally simplistic since it makes little sense to test all the small details before getting feedback. Unfortunately that leaded to a bug been overlooked. The proposal managed to succeed when combining the "system" VG with some dedicated ones just by a matter of luck (and producing a clearly sub-optimal solution). It was in fact getting confused about some PVs.
Fix the PV detection to have into account the case of many planned VGs.
> Separate vg fixes

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/fstabs.rb
- test/y2partitioner/actions/controllers/fstabs_test.rb
The Expert Partitioner has a feature to import mount points from the fstab file of a previous installation. When an imported fstab entry points to a multi-device Btrfs in the previous system, the multi-device filesystem is not restored in the new system being installed. Instead of that, a single-device Btrfs is created.  
* https://trello.com/c/50a33VHa/1084-ostumbleweed-p5-1137997-expert-partitioner-import-multi-device-btrfs-mount-points
* https://bugzilla.suse.com/show_bug.cgi?id=1137997
Now on, the multi-device Btrfs is re-created in the new system when importing the mount point.
- Added unit tests
<details>
<summary>Show screenshots</summary>
* Storage layout from the initial proposal:
* Importing mount points from a previous system with multi-device Btrfs:
* Result …
> Import mount point from multi-device Btrfs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_space_maker.rb
- src/lib/y2storage/proposal/partition_killer.rb
- test/data/devicegraphs/lvm-two-disks.yml
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/proposal/autoinst_space_maker_test.rb
The Guided Proposal and AutoYaST use the `PartitionKiller` to remove partitions. When the `PartitionKiller` is told to delete a partition, it removes such partition and all the related partitions. For example, when the specified partition is a LVM PV, the rest of PVs are removed too. And something similar happens when the partition belongs to a MD RAID or to a multi-device Btrfs.
Such behavior may be useful for the Guided Proposal, but it could be a problem for AutoYaST, see https://github.com/yast/yast-storage-ng/pull/923. So, for the case of AutoYaST, the `PartitionKiller` 
should remove only the indicated partitions and nothing else.
* https://trello.com/c/9AZD9sn6/1054-2-autoyast-storage-ng-avoid-collateral-casualties-of-partitionkiller
* Related PR: …
> AutoYaST: only delete indicated partitions

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/nfs.rb
- test/y2storage/planned/nfs_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1136272
https://trello.com/c/FQAyxSFk/
Crash with "internal error" because of a typo in the filesystem type.
Fixed the typo.
> AutoYaST: Fixed typo in filesystem type that caused a crash

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/nfs.rb
- test/y2storage/planned/nfs_test.rb
_**This merges PR #939 from the SLE-15-SP1 branch to master**_
https://bugzilla.suse.com/show_bug.cgi?id=1136272
https://trello.com/c/FQAyxSFk/
Crash with "internal error" because of a typo in the filesystem type.
Fixed the typo.
- ~~[ ] SLE-15-SP1~~ _Done_
> AutoYaST: Fixed typo in filesystem type that caused a crash (master)

- test/y2storage/dialogs/guided_setup/widgets/disk_selector_test.rb
The submit request for #936 failed because of `test/y2storage/dialogs/guided_setup/widgets/disk_selector_test.rb`, which is using real `VolumeSpecification` objects. In consequence, it needs to create a test instance of `StorageManager` first.
- https://build.opensuse.org/package/live_build_log/YaST:Head/yast2-storage-ng/openSUSE_Tumbleweed/x86_64
```
[  157s]   1) Y2Storage::Dialogs::GuidedSetup::Widgets::DiskSelector#content contains an item per candidate disk
[  157s]      Failure/Error: Y2Storage::VolumeSpecification.new(vol_features.merge("mount_point" => "swap")),
[  157s]        #<InstanceDouble(::Storage::Arch) (anonymous)> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one …
```
> Fix the test of DiskSelector widget

- doc/old_and_new_proposal.md
This PR simply adds some basic documentation for those options/elements related to separate LVM Volume Groups added in previous PRs
* https://github.com/yast/yast-storage-ng/pull/931 - Proposal: support for separate VGs
- partitioning / proposal / `separate_vgs`
- partitioning / volume / `separate_vg_name`
* https://github.com/yast/yast-storage-ng/pull/936 - SUMA guided setup
- partitioning / proposal / `allocate_volume_mode`
> Add some documentation for new separate LVM VG options

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/initial_guided_proposal.rb
- test/support/storage_helpers.rb
- test/y2storage/devicegraph_test.rb
- test/y2storage/disk_analyzer_test.rb
- test/y2storage/initial_guided_proposal_test.rb
- test/y2storage/reusing_efi_test.rb
While executing the manual tests of the new SUMA proposal (see [the blog post for details](https://lizards.opensuse.org/2019/07/16/suse-manager-guided-setup/)) I realized it was possible for the initial proposal (the one that is auto-calculated before the user has executed the Guided Setup) to enter an infinite loop.
While debugging that, I also noticed there is a chance for the initial proposal to apply the settings `xxx_delete_mode=all` wrongly.
More details about the nature of both bugs in the comments of the corresponding regression unit tests.
Stop the excessive caching of the internal SpaceMaker object (to fix the infinite loop) and of the cleaned devicegraph (to fix the other problem).
- Added new unit tests with descriptions of the original problems
> Fix caching in the initial proposal

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/btrfs_devices.rb
- src/lib/y2partitioner/actions/controllers/lvm_vg.rb
- src/lib/y2partitioner/blk_device_restorer.rb
- test/data/devicegraphs/trivial_btrfs.yml
- test/y2partitioner/blk_device_restorer_test.rb
The BlkDeviceRestorer tries to add a device that already exists.
- https://bugzilla.suse.com/show_bug.cgi?id=1142669
Do not try to add a device that already exists.
The selected devices in the dialog for LVM VGs and btrfses are sorted by name now.
> fixed exception when removing devices from btrfs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/lvm_lv.rb
- src/lib/y2storage/proposal/autoinst_bcache_creator.rb
- src/lib/y2storage/proposal/autoinst_devices_creator.rb
- src/lib/y2storage/proposal/autoinst_vg_planner.rb
- test/y2storage/autoinst_proposal_bcache_test.rb
- test/y2storage/proposal/autoinst_bcache_creator_test.rb
- test/y2storage/proposal/autoinst_devices_creator_test.rb
- test/y2storage/proposal/autoinst_vg_planner_test.rb
AutoYaST does no support to create a Bcache without a caching device. And a Bcache over a LVM LV is not supported either.
* https://bugzilla.suse.com/show_bug.cgi?id=1139783
* https://trello.com/c/jcmHbDNT/1190-3-osdistribution-p5-1139783-lvm-lv-cannot-be-used-as-bcache-cache-device-and-possibly-backing-device
* Added AutoYaST support for creating a Bcache without a caching device.
* Added AutoYaST support for creating a Bache over a LVM PV (for both: caching and backing).
* Error message when the AutoYaST profile does not specify a valid backing device for a Bcache.
NOTE: setting the cache mode fails when the backing device is a LVM LV, see https://bugzilla.suse.com/show_bug.cgi?id=1139948 
* Added unit tests
* Tested manually
<details>
<summary>
Show/hide screenshots
</summary>
Bcache …
> AutoYaST: fix Bcache creation

- doc/btrfs_in_partitioner.md
Adding the group quotas to the list of Btrfs features we need to take into account when rethinking the UI for managing Btrfs subvolumes.
For more details, see the discussion at https://jira.suse.com/browse/SLE-7742
> Doc: document impact of Btrfs quotas in the Partitioner

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_prepdisk.rb
https://bugzilla.suse.com/show_bug.cgi?id=1136463
Files in `/run` are needed also in the target system during installation.
That's basically [bnc#717321](https://bugzilla.suse.com/show_bug.cgi?id=1136463) but again for storage-ng.
Bind-mount `/run` into target system.
https://bugzilla.suse.com/show_bug.cgi?id=717321
Same issue in SLE12, fixed in old storage stack.
https://github.com/yast/yast-storage/blob/SLE-12-SP5/src/clients/inst_prepdisk.rb#L143-L166
Tested manually.
> bind-mount /run from inst-sys to target system during install (bsc#1136463)

- package/yast2-storage-ng.changes
- src/lib/y2partitioner/actions/controllers/encryption.rb
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/actions/filesystem_steps.rb
- src/lib/y2partitioner/dialogs/encryption.rb
- src/lib/y2partitioner/widgets/encrypt_password.rb
- test/y2partitioner/actions/controllers/encryption_test.rb
- test/y2partitioner/dialogs/encryption_test.rb
- test/y2partitioner/keep_original_filesystems_test.rb
- test/y2partitioner/widgets/encrypt_password_test.rb
Editing a block device that already contains an encryption layer has some problems, described at
https://trello.com/c/qeSZSCxQ/1244-5-partitioner-fix-behavior-when-selecting-deselecting-encryption-checkbox
This PR specifically targets the following problems:
- If the password was already provided, editing again looses it and asks for a new password. That will become a bigger problem soon, since we plan to add more types of encryption (random, pervasive, maybe LUKS2) each of them with their own arguments. Having to re-enter the type and all the arguments would be even a better PITA than it's today.
- If there is already a existing encryption in the system (e.g. a LUKS2 one created with other tool), it cannot be reused. This will also become a bigger problem soon with pervasive encryption, …
> Improve behavior when editing encrypted devices

- doc/boot-requirements.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_strategies/analyzer.rb
- src/lib/y2storage/boot_requirements_strategies/base.rb
- src/lib/y2storage/boot_requirements_strategies/legacy.rb
- src/lib/y2storage/boot_requirements_strategies/prep.rb
- test/support/boot_requirements_context.rb
- test/y2storage/boot_requirements_checker_ppc_test.rb
- test/y2storage/boot_requirements_checker_x86_test.rb
- test/y2storage/boot_requirements_errors_test.rb
- test/y2storage/boot_requirements_strategies/analyzer_test.rb
Add warning if `/boot` is luks2 encrypted as grub does only support luks1.
Warning added. 
This also implies that the proposal will go for a separate `/boot` partition if `/` is on luks2.
- manual integration testing
- unit tests
Note:
> I've added only two tests for LUKS2 in the proposal (to see if it results in a  `/boot` partition). It's my impression the boot requirements document would quite blow up otherwise.
> add warning if /boot is on a luks2 encrypted partition

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/encryption.rb
- src/lib/y2partitioner/dialogs/encryption.rb
- src/lib/y2partitioner/widgets/encrypt.rb
- src/lib/y2partitioner/widgets/encrypt_method_options.rb
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/device.rb
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/encryption.rb
- src/lib/y2storage/encryption_method.rb
- src/lib/y2storage/encryption_processes/base.rb
- src/lib/y2storage/encryption_processes/luks1.rb
- src/lib/y2storage/encryption_processes/pervasive.rb
- src/lib/y2storage/encryption_processes/secure_key.rb
- src/lib/y2storage/encryption_processes/secure_key_volume.rb
- src/lib/y2storage/encryption_processes/swap.rb
- src/lib/y2storage/luks.rb
- src/lib/y2storage/storage_manager.rb
- test/data/lszcrypt/no_devs.txt
- test/data/lszcrypt/ok.txt
- test/data/zkey/list-dasdc1.txt
- test/data/zkey/list-no-dasdc1.txt
- test/y2partitioner/actions/controllers/encryption_test.rb
- test/y2partitioner/widgets/encrypt_method_options_test.rb
- test/y2storage/encryption_method_test.rb
- test/y2storage/encryption_processes/luks1_test.rb
- test/y2storage/encryption_processes/swap_test.rb
- test/y2storage/pervasive_encryption_test.rb
- test/y2storage/storage_manager_test.rb
Allow to encrypt volumes using pervasive encryption via the Partitioner.
- https://www.ibm.com/support/knowledgecenter/linuxonibm/liaaf/lnz_r_dccnt.html
- https://jira.suse.com/browse/SLE-7376
- https://trello.com/c/HKaDMPL6/1297-5-pervasive-encryption-partitioner
Implemented a new PERVASIVE_LUKS2 encryption method.
That method is exposed in the Partitioner when the system has at least one online Crypto Express cryptographic coprocessor configured in CCA mode and the needed tools installed.
Otherwise (most users on earth) nothing changes.
This is how it looks in the partitioner, including the help.
and
It works and it generates secure keys like the ones showed here.
As you can see, the devices are registered by id if possible.
If a key already exists for the volume, then it's reused …
> Pervasive encryption

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/partition_section.rb
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- src/lib/y2storage/proposal/autoinst_vg_planner.rb
- test/data/devicegraphs/autoyast_drive_examples.yml
- test/data/devicegraphs/lvm-two-vgs.yml
- test/data/devicegraphs/windows-linux-free-pc.yml
- test/y2storage/autoinst_issues/shrinked_planned_devices_test.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/partition_test.rb
- test/y2storage/planned/can_be_formatted_test.rb
- test/y2storage/proposal/autoinst_devices_creator_test.rb
- test/y2storage/proposal/autoinst_disk_device_planner_test.rb
Many things were broken regarding the usage of UUID in AutoYaST. For details, see [comment#9 at bsc#1148477](https://bugzilla.suse.com/show_bug.cgi?id=1148477#c9).
In the SLE-15-SP1 case:
- It was failing to reuse partitions and LVs finding them by their UUID. There was simply no code for that.
- It failed if the UUID was specified in the profile for a new file system. Setting such UUID was never intended to work, but AutoYaST should not fail.
See also https://trello.com/c/XibWb5sb/1335-2-ostumbleweed-p5-1148477-build-20190824-installation-fails-on-setting-uuid-of-btrfs
Use the `uuid` property to find devices to be reused and ignore the `uuid` property in any other case.
Better review commit by commit.
See also https://github.com/SUSE/doc-sle/pull/483
- Added new unit tests
- Removed some …
> AutoYaST: fixes related to UUID (bsc#1148477)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/partition_section.rb
- src/lib/y2storage/proposal/autoinst_btrfs_planner.rb
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- src/lib/y2storage/proposal/autoinst_vg_planner.rb
- test/data/devicegraphs/autoyast_drive_examples.yml
- test/data/devicegraphs/lvm-two-vgs.yml
- test/data/devicegraphs/windows-linux-free-pc.yml
- test/y2storage/autoinst_issues/shrinked_planned_devices_test.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/partition_test.rb
- test/y2storage/planned/can_be_formatted_test.rb
- test/y2storage/proposal/autoinst_btrfs_planner_test.rb
- test/y2storage/proposal/autoinst_devices_creator_test.rb
- test/y2storage/proposal/autoinst_disk_device_planner_test.rb
Follow-up of #976, this time for master. For details, see [comment#9 at bsc#1148477](https://bugzilla.suse.com/show_bug.cgi?id=1148477#c9).
This is about the problems affecting master (15.2 and TW):
- It was failing to reuse partitions and LVs finding them by their UUID. There was simply no code for that.
- It failed if the UUID was specified in the profile for a new file system. Setting such UUID was never intended to work, but AutoYaST should not fail.
- It was exporting the UUID when cloning a system, which triggered the mentioned failure.
See also https://trello.com/c/XibWb5sb/1335-2-ostumbleweed-p5-1148477-build-20190824-installation-fails-on-setting-uuid-of-btrfs
Use the `uuid` property to find devices to be reused, do not export the `uuid` property when cloning to a profile and …
> AutoYaST: extended fixes related to UUID (bsc#1148477)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/crypttab.rb
- src/lib/y2storage/encryption_method/protected_swap.rb
- src/lib/y2storage/encryption_method/secure_swap.rb
- src/lib/y2storage/encryption_method/swap.rb
- src/lib/y2storage/encryption_processes/base.rb
- src/lib/y2storage/encryption_processes/luks1.rb
- src/lib/y2storage/encryption_processes/pervasive.rb
- src/lib/y2storage/encryption_processes/secure_key.rb
- src/lib/y2storage/encryption_processes/volatile.rb
- test/data/zkey/list-no-sector-size.txt
- test/y2storage/crypttab_test.rb
- test/y2storage/encryption_processes/pervasive_test.rb
- test/y2storage/encryption_processes/secure_key_test.rb
- test/y2storage/encryption_processes/volatile_test.rb
Set the encryption sector size according to the underlying device.
* If it is 4k or bigger, set the sector-size to 4k for performance reasons.
* If it is smaller than 4k, just do the default (do not set any sector size).
> Set encryption sector size from the underlying device

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/encrypt_method_options.rb
- src/lib/y2storage/boot_requirements_strategies/analyzer.rb
- src/lib/y2storage/boot_requirements_strategies/base.rb
- src/lib/y2storage/boot_requirements_strategies/zipl.rb
- src/lib/y2storage/fake_device_factory.rb
- test/data/devicegraphs/s390_luks2.yml
- test/y2storage/boot_requirements_strategies/analyzer_test.rb
- test/y2storage/boot_requirements_strategies/zipl_test.rb
Fixes https://trello.com/c/JqMeJJbq/1353-1-avoid-false-warning-about-booting-from-luks2-in-s390.
This PR contains the version bump: https://github.com/yast/yast-storage-ng/pull/984.
> Fix encrypted grub warning

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/partitioning_section.rb
- src/lib/y2storage/proposal/autoinst_devices_planner.rb
- src/lib/y2storage/proposal/autoinst_drives_map.rb
- test/y2storage/autoinst_profile/partitioning_section_test.rb
- test/y2storage/proposal/autoinst_devices_planner_test.rb
Treat CT_DMMULTIPATH as an alias to CT_DISK.
* https://trello.com/c/wd3xE1Wq/1349-3-compatibility-and-documentation-for-autoyastmultipath
> AutoYaST: CT_DMMULTIPATH handling

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/encryption_processes/pervasive.rb
- src/lib/y2storage/encryption_processes/secure_key.rb
- test/y2storage/encryption_processes/pervasive_test.rb
- test/y2storage/encryption_processes/secure_key_test.rb
- test/y2storage/pervasive_encryption_test.rb
The secure key creation fails if the block device does not exist yet.
The secure key is first created without the device information and later the device information is added to the secure key.
- Updated and added unit tests.
> fix creation of secure key for new partitions (bsc#1154267)

- src/lib/y2storage/encryption_method/swap.rb
The system does not prevent hibernation when encrypting swap with a volatile encryption method.
* https://trello.com/c/gDP5eXqK/1397-2-clarify-hibernation-behavior-if-a-volatile-encryption-is-used
Document the behavior.
> Add comment about hibernation with encrypted swap

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/drive_section.rb
- src/lib/y2storage/autoinst_profile/partition_section.rb
- test/data/devicegraphs/root_md_raid.yml
- test/data/devicegraphs/root_partitioned_md_raid.yml
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
When exporting a Btrfs multidevice filesystem, the filesystem related information will be repeated for each component. For instance, the list of subvolumes will appear in all `<partition>` elements which are part of the Btrfs filesystem. See [bsc#1148578](https://bugzilla.suse.com/show_bug.cgi?id=1148578).
Additionally, this PR prevents exporting the `enable_snapshots` element when the `drive` section does not contain the root filesystem. The reason for this change is that snapshots will be applied [only to the root filesystem](https://github.com/yast/yast-storage-ng/blob/master/src/lib/y2storage/proposal/autoinst_drive_planner.rb#L163), so it does not make sense in any other drive.
> AutoYaST: avoid repeating filesystem elements for Btrfs multidevice filesystems

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_proposal.rb
- test/y2storage/autoinst_proposal_test.rb
`Y2Storage::AutoinstProposal` receives now the proposal settings. The idea is that, instead of using `Y2Storage::ProposalSettings.new_for_current_product`, it can receive a customized one.
Needed for https://github.com/yast/yast-autoinstallation/pull/544.
> AutoYaST: inject proposal settings

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/disk_device.rb
- src/lib/y2storage/encryption.rb
- src/lib/y2storage/filesystems/base.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/lvm_lv.rb
- src/lib/y2storage/mount_point.rb
- src/lib/y2storage/mountable.rb
- src/lib/y2storage/partition.rb
- src/lib/y2storage/planned/can_be_formatted.rb
- test/data/devicegraphs/btrfs-multidevice-over-partitions.xml
- test/data/devicegraphs/encrypted_partition.xml
- test/data/devicegraphs/mixed_disks_btrfs.yml
- test/y2partitioner/actions/controllers/filesystem_test.rb
- test/y2storage/encryption_test.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
- test/y2storage/mount_point_test.rb
Systemd should be able to distinguish when an encrypted device is based on a network-based storage device and, thus, can only be initialized after the network is up. In some cases that detection fails (for example network block device based mounts, such as iSCSI), and systemd gets stuck before initializing the network waiting for the device to be available.
Recently, SLE and openSUSE Leap has incorporated support for specifying the option `_netdev` in the crypttab file. With such option, systemd will recognize the encrypted device as network-based and will only try to activate it after setting up the network. That's analogous to the corresponding `_netdev` option in fstab that has been already there for quite some time and that can be used to defer when a device is mounted.
For it to work …
> Add _netdev option to fstab and crypttab when needed (jsc#SLE-7687)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/package_handler.rb
- test/y2storage/package_handler_test.rb
During installation, YaST was not always marking for installation all the packages needed by the storage stack.
It happened because YaST was checking which packages were already installed and skipping them. That makes sense when yast2-storage-ng is running in an already installed system, but makes no sense during installation. The packages where not being added to the software proposal of the target system if they where available in the inst-sys.
- https://bugzilla.suse.com/show_bug.cgi?id=1151148
- https://openqa.opensuse.org/tests/1091600/modules/await_install/steps/136
- https://trello.com/c/LxzOqypU/1352-ostumbleweed-p2-1151148-live-installation-fails-because-yast-does-not-install-storage-feature-packages
Skip the check for already installed packages when running during the …
> Fix wrong check about installed packages (bsc#1151148)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/devicegraph_sanitizer.rb
- test/spec_helper.rb
- test/y2storage/devicegraph_sanitizer_test.rb
Under certain scenarios, the root mount point could be probed as inactive (which does not make sense). One situation where this happens is when the user executes a snapshot rollback and the system has not been rebooted yet. In that case, */etc/fstab* and */proc/mounts* files would contain something like the following:
~~~
$ cat /etc/fstab
/dev/sda1  /  btrfs  defaults  0  0
$ cat /proc/mounts
dev/sda1 / btrfs rw,relatime,space_cache,subvolid=268,subvol=/@/.snapshots/1/snapshot 0 0
~~~
Note that subvolid 268 in */proc/mounts* entry is the Id of the default subvolume before the rollback process. The new default subvolume would have a different Id, and for that reason, the root mount point is probed as inactive (there is no entry in */proc/mounts* for root with the new default subvolume Id). …
> Error message for inactive root

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/mount_point.rb
- test/y2storage/mount_point_test.rb
The ESP - the boot partition used for booting an EFI system - has been configured to not being fscked on boot. That leads to error messages on boot in case the filesystem has not been unmounted properly.
https://bugzilla.suse.com/show_bug.cgi?id=1135523
In `etc/fstab` **passno** now is set to `2` for something that is mounted as `/boot/efi`
I did no extra check if the filesystem really is VFAT for that partition since this is a requirement of the EFI standard anyway and should be - and surely is - checked elsewhere.
> Set passno to 2 for the ESP (bsc#1135523)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/guided_proposal.rb
As reported in [bug#1154070](https://bugzilla.suse.com/show_bug.cgi?id=1154070), the initial storage proposal, before the user has had any chance to select the disks, is very slow in SLE 15 for SAP in systems with many disks (40 in the case of the report). That's a consequence of SLE for SAP using LVM by default, which is much slower than the partition-based proposal.
This limits that initial attempt to the first 10 disks on the system in all cases, not only SLE for SAP. To be honest, in any system with so many disks it's kind of expected the user will run the Guided Setup or the Expert Partitioner anyways (the possibilities for the automatic initial proposal to match user expectations with so many disks is almost zero).
Tested manually. With 10 disks the calculation is much, much faster.
> Speed up initial proposal on systems with many disks

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/encryption.rb
- src/lib/y2storage/mount_point.rb
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-enc-sep-home.yml
- test/data/devicegraphs/output/empty_hard_disk_gpt_50GiB-enc.yml
- test/data/devicegraphs/output/multi-linux-pc-enc-sep-home.yml
- test/data/devicegraphs/output/multi-linux-pc-enc.yml
- test/data/devicegraphs/output/multi-linux-pc-gpt-enc-sep-home.yml
- test/data/devicegraphs/output/multi-linux-pc-gpt-enc.yml
- test/data/devicegraphs/output/windows-linux-multiboot-pc-enc-sep-home.yml
- test/data/devicegraphs/output/windows-linux-multiboot-pc-enc.yml
- test/data/devicegraphs/output/windows-linux-multiboot-pc-gpt-enc-sep-home.yml
- test/data/devicegraphs/output/windows-linux-multiboot-pc-gpt-enc.yml
- test/data/devicegraphs/output/windows-pc-enc-sep-home.yml
- test/data/devicegraphs/output/windows-pc-enc.yml
- test/data/devicegraphs/output/windows-pc-gpt-enc-sep-home.yml
- test/data/devicegraphs/output/windows-pc-gpt-enc.yml
- test/y2storage/blk_device_test.rb
- test/y2storage/encryption_test.rb
- test/y2storage/fake_device_factory_test.rb
When an encryption device is created in YaST (by means of either the storage proposal or manually with the Expert Partitioner), the device mapper name for the new device is generated from the udev id of the underlying device (e.g., "cr_ccw-0XAF5E-part2"). When booting, a message is prompted like this:
~~~
"Please enter passphrase for disk cr_ccw-0XAF5E-part2!"
~~~
But it is difficult to know what device this refers when there are several encrypted devices in the system. More user-friendly names should be used for encryption devices. 
* https://bugzilla.suse.com/show_bug.cgi?id=1125774
* https://trello.com/c/MR24HhqL/1486-2-research-p4-1125774-sles-15-sp1-beta3-improve-naming-of-crypt-devices-in-the-passphrase-prompt
Now on (and similar to what the old storage stack did), the mount point …
> Improve encryption names

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/guided_proposal.rb
As reported in [bug#1154070](https://bugzilla.suse.com/show_bug.cgi?id=1154070), the initial storage proposal, before the user has had any chance to select the disks, is very slow in SLE 15 for SAP in systems with many disks.
In #988 a limit of 10 disks was introduced for that first attempt in order to speed up the calculation. But some reports indicate that limit could not be enough to keep the proposal under a reasonable time threshold in some specially complex situations.
Lower the limit to only 5 disks. After all, users with more than 5 disks will very likely dismiss the initial proposal and use the Guided Setup or the Expert Partitioner. So trying so hard to find a good proposal is often just wasting time.
> Speed up even more initial proposal on systems with many disks

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/activate.rb
- src/lib/y2storage/dialogs/callbacks/activate_luks.rb
- test/support/devices_planner_context.rb
- test/y2storage/callbacks/activate_test.rb
- test/y2storage/dialogs/callbacks/activate_luks_test.rb
NOTE FOR REVIEWERS: unit tests require https://github.com/openSUSE/libstorage-ng/pull/688 to pass.
When a LUKS needs to be activated, the user is prompted to give the encryption password. But the popup only shows the encryption UUID, making very difficult to identify the device when the systems contains several encrypted devices. 
* Part of https://trello.com/c/MR24HhqL/1486-2-research-p4-1125774-sles-15-sp1-beta3-improve-naming-of-crypt-devices-in-the-passphrase-prompt
* Related to https://bugzilla.suse.com/show_bug.cgi?id=1125774
* Requires https://github.com/openSUSE/libstorage-ng/pull/688
Now on, the activation popup also shows the name of the underlying device.
- Unit tests adapted.
<details>
<summary>Show/Hide</summary>
</details>
> Improve callback for LUKS activation

- src/lib/y2storage/encryption.rb
Encryption names were improved here https://github.com/yast/yast-storage-ng/pull/1006 to take into account the mount point when possible, for example:
~~~
mount point: / => cr_root
mount point: /foo/bar => cr_foo_bar
~~~
But indirectly used encrypted devices (e.g., an encrypted LVM PV) could also have more user-friendly names. For example, when an encrypted LVM PV is added to the volume group "vg0", the encryption name could be `cr_vg0`. Similarly, it could be improved for encrypted devices used by a MD Raid, Bcache or Bcache caching set. 
* Related to https://bugzilla.suse.com/show_bug.cgi?id=1125774
Adapting encryption names for indirectly used encrypted devices could be tricky and it requires to take several implications into account. Some comments are added to the code, but the …
> Add comment about possible encryption improvements

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/libstorage_callback.rb
- test/y2storage/callbacks/callbacks_examples.rb
stderr of some programs can be so long that it does not fit on the screen and so it is useless for users.
- https://bugzilla.suse.com/show_bug.cgi?id=1085468
Use shared functionality to [wrap text](https://github.com/yast/yast-yast2/blob/6bc7bd9f1ef03f783ed269cd59174fe9e8a25c78/library/general/src/lib/ui/text_helpers.rb#L34).
- Unit tests included.
before:
after:
> Wrapping error

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_drives_map.rb
- test/y2storage/proposal/autoinst_drives_map_test.rb
If you want to use multipath through AutoYaST, you need to specify the multipath device name in the `device` element. Sometimes, it might be more convenient to use one of its wires. For instance, let's say that you use a multipath device that is accessible through `/dev/sda` and `/dev/sdb`. Instead of using `/dev/mapper/WHATEVER-MP-NAME`, you might want to just use `/dev/sda` (or `/dev/sdb`).
See [bsc#1159081](https://bugzilla.suse.com/show_bug.cgi?id=1159081) for further details.
This PR adds support to use the wire instead of the full multipath device name. Basically, it checks whether the specified device is part of a multipath one. In that case, it will consider the multipath device. Otherwise, it will apply the default logic (searching for the disk device where it belongs).
- Added a …
> AutoYaST: specify a multipath device through one of its wires

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/devices_planner_strategies/ng.rb
- test/y2storage/proposal/devices_planner_strategies/ng_test.rb
As described in [bug#1075990](https://bugzilla.suse.com/show_bug.cgi?id=1075990), there is a corner-case in which the max size for a volume is not properly calculated. Check the bug report for details.
Make sure `max_size` is always used when `max_size_lvm` is not there, even if the value must be increased by sizes coming from other volumes via `fallback_max_size_lvm`.
This includes a preliminary commit to organize the code a little bit better, so it's MUCH easier to review commit by commit.
Added a new unit test with the situation described in the bug.
> Enhance behavior of fallback_max_size_lvm (bsc#1075990)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/blk_devices_table.rb
- src/lib/y2storage/device.rb
- test/y2partitioner/test_helper.rb
- test/y2partitioner/widgets/btrfs_devices_selector_test.rb
- test/y2partitioner/widgets/lvm_vg_devices_selector_test.rb
- test/y2partitioner/widgets/md_devices_selector_test.rb
- test/y2partitioner/widgets/pages/bcaches_test.rb
- test/y2partitioner/widgets/pages/disks_test.rb
- test/y2partitioner/widgets/pages/lvm_test.rb
- test/y2partitioner/widgets/pages/lvm_vg_test.rb
- test/y2partitioner/widgets/pages/md_raids_test.rb
- test/y2partitioner/widgets/pages/system_test.rb
So far devices in tables were sorted alphabetical when the user selected sorting by name or size. That does not give good results. Now the sorting is done better, e.g. numerical for size.
Also see libyui/libyui#156.
> Improved sorting by device name and size in tables

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/partition_id.rb
- test/y2storage/partition_id_test.rb
NOTE FOR REVIEWERS: tests require https://github.com/openSUSE/libstorage-ng/pull/691.
Partition Id names are defined for both: libstorage-ng and yast2-storage-ng. But now on, libstorage-ng provides a public method to get the name of a partition id.
* Part of https://trello.com/c/QsLIaeYN/1519-tw-leap-151-storage-ng-inconsistent-partition-type-display
* Requires https://github.com/openSUSE/libstorage-ng/pull/691
New method `Storage.partition_id_name` is used instead of defining own names.
- Unit tests updated.
<details>
<summary>Show/Hide</summary>
</details>
> Unify partition id names

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/format_and_mount.rb
- src/lib/y2storage/filesystems/base.rb
- src/lib/y2storage/filesystems/type.rb
- src/lib/y2storage/mountable.rb
Now that libstorage-ng can represent BitLocker in the devicegraph it is possible to try to mount it in the expert partitioner.
Disallow mounting of BitLocker in the expert partitioner using the new ```supports_mount?``` function from libstorage-ng.
> disallow to mount BitLocker

- doc/boot-requirements.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/mkfs_options.rb
- src/lib/y2partitioner/widgets/mkfs_optiondata.rb
- src/lib/y2partitioner/widgets/mkfs_options.rb
- src/lib/y2partitioner/widgets/mkfs_optionvalidator.rb
- src/lib/y2storage/arch.rb
- test/support/proposed_partitions_examples.rb
- test/y2partitioner/actions/controllers/lvm_vg_test.rb
- test/y2partitioner/widgets/mkfs_optiondata_test.rb
- test/y2partitioner/widgets/mkfs_optionvalidator_test.rb
- test/y2storage/disk_test.rb
- test/y2storage/proposal_scenarios_s390_test.rb
The dialog with format options for XFS allowed invalid options:
- Invalid block size (bsc#1111668)
- Invalid inode size
- Extended checks for block and inode size.
- Unit tests
- https://trello.com/c/tUOAy26G/1568-2-sles15-sp1-1111668-build-662-installation-fails-to-mount-partition-when-define-16384-as-block-size-for-xfs
- https://bugzilla.suse.com/show_bug.cgi?id=1111668
> extended checks for XFS format options

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/bin/mask-systemd-units
- src/lib/y2storage/inhibitors/mdadm_auto_assembly.rb
- test/y2partitioner/clients/main_test.rb
systemd has removed some links for programs in /usr/bin to /sbin. So the paths YaST uses are gone.
Also a script did not use absolute paths. Seems as if this was not noticed during the "YaST hardening".
Use the paths that still exist and use absolute paths.
- Adapted unit test
- https://bugzilla.suse.com/show_bug.cgi?id=1160890
- https://trello.com/c/3Y9HSV8m/3830-tw-p2-1160890-stop-using-sbin-udevadm-and-other-symlinks
> use correct and absolute paths to some external programs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/filesystems/base.rb
- src/lib/y2storage/filesystems/type.rb
- test/y2storage/filesystems/base_test.rb
- test/y2storage/filesystems/type_test.rb
Partitions with BitLocker were not treated as Windows. One notable consequence of that is that BitLocker partitions could be removed by the storage proposal even when the user instructed YaST to not modify Windows.
Treat partitions with BitLocker as Windows.
https://trello.com/c/urYYuPsW/1562-3-detecting-bitlocker-part-of-bug1159318-expert-partitioner-let-me-resize-bitlocker-partition-cause-data-lost
> treat partitions with BitLocker as Windows

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/help.rb
- src/lib/y2partitioner/widgets/pages/nfs_mounts.rb
- src/lib/y2partitioner/yast_nfs_client.rb
- src/lib/y2storage/filesystems/legacy_nfs.rb
- src/lib/y2storage/filesystems/nfs.rb
- src/lib/y2storage/mount_point.rb
- test/y2partitioner/widgets/pages/nfs_mounts_test.rb
The NFS client (yast2-nfs-client) can be used standalone or through the Partitioner. But the behaviour is not exactly the same in both cases.
With the standalone mode:
* All nfs shares are deleted and created again.
* Current unmounted shares are mounted after saving the changes, even though the nfs entry is not edited.
* Current shares that are not included in the fstab are written to fstab after saving the changes.
With the Expert Partitioner:
* Only edited entries are modified after saving.
* Current unmounted shares are mounted only if their server or path change.
* Current shares that are not included in the fstab are written to fstab only if their server or path change.
Related bugs:
* https://bugzilla.suse.com/show_bug.cgi?id=1006815
* …
> Improve integration of NFS client

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/ui_state.rb
- src/lib/y2partitioner/widgets/pages/system.rb
- test/y2partitioner/ui_state_test.rb
- test/y2partitioner/widgets/pages/system_test.rb
The [system overview page](https://github.com/yast/yast-storage-ng/blob/master/src/lib/y2partitioner/widgets/pages/system.rb) does not include the [`DeviceButtonSet`](https://github.com/yast/yast-storage-ng/blob/master/src/lib/y2partitioner/widgets/device_buttons_set.rb) at the bottom of the devices table. And... there is no arguable reason for it :)
* Trello: https://trello.com/c/cyWuac6k
* Fate: https://fate.suse.com/318196
To use those dynamic (and useful) buttons also on that page.
To make the changes fully consistent with the rest of Partitioner _pages_, the second buttons row has been realigned to the right. Now, all pages follows the same pattern: contextual actions closest to the table and aligned to the left and general actions below but aligned to the right.
* Added small unit …
> Show the dynamic buttons set in the main table of devices

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/dialogs/guided_setup/select_scheme.rb
At some point, the Guided Setup started to look like this in ncurses:
Note the different width of the "Password" and "Verify Password" fields.
Reported as https://bugzilla.suse.com/show_bug.cgi?id=1161202
Enlarge both fields to use the whole width of the form. With that, the fields look longer than before. The change affects both Qt and ncurses views (see screenshots below), but it should be more solid, regarding internationalization, than hardcoding a (minimal) size.
Fixed ncurses view:
Qt also changed:
> Guided Setup: enforce width of password fields (bsc#1161202)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/resize_blk_device.rb
- test/y2partitioner/actions/resize_blk_device_test.rb
We had a bug report where a user shrunk a partition with BitLocker on it (which caused data loss since BitLocker was not detected).
The data loss is now prevented by two changes:
- BitLocker is detected (other PRs)
- A warning is presented to the user when trying to resize a device which seems to be empty (this PR).
- Added a new unit test.
- https://bugzilla.suse.com/show_bug.cgi?id=1159318
- https://trello.com/c/CEJP4jFv/1575-1-warn-when-resizing-empty-partitions-2nd-part-of-bug1159318-expert-partitioner-let-me-resize-bitlocker-partition-cause-data-loss
- https://trello.com/c/urYYuPsW/1562-3-detecting-bitlocker-part-of-bug1159318-expert-partitioner-let-me-resize-bitlocker-partition-cause-data-lost
> added warning before resizing block devices which were probed empty

- package/yast2-storage-ng.changes
During resolving the merge conflict the order of entries was mixed up. Changing timezone to fix this.
> change time to please tools

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/partition_id.rb
The partitioner was crashing with some locales (Russian and French, according to the report) when trying to display some partition IDs.
- https://bugzilla.suse.com/show_bug.cgi?id=1161442
The problem was that the result of this libstorage-ng function call was being passed directly to Ruby's `#format`.
```ruby
Storage.partition_id_name(id)
```
But, as we learned some time ago, we should enforce the encoding of all strings coming from libstorage-ng before trying to process them. Normally, that's done by `StorageClassWrapper`. But that, of course, does not cover direct calls to libstorage-ng like the one above.
Enforce the encoding for the mentioned string.
- Tested manually (in Russian)
> Fix 1161442

- doc/user-stories/expert-partitioner.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/popup.rb
- src/lib/y2partitioner/widgets/fstab_options.rb
- src/lib/y2storage/filesystems/type.rb
- test/y2partitioner/widgets/fstab_options_test.rb
Some dialogs do not fit on small screens, neither ncurses nor qt UI.
- https://trello.com/c/YWiwQnng/1580-3-leap-151-p3-1135723-installation-fstab-options-window-extended-below-screen-bottom-on-1280x800-screen
- https://bugzilla.suse.com/show_bug.cgi?id=1135723
- https://bugzilla.suse.com/show_bug.cgi?id=1161651
Drop some obsolete options:
- noatime (likely not use often since relatime is the default for years)
- acl and xattrs (default for years; not supported for UDF)
Replace the five radio buttons for the mount by method by a combobox.
User can still enable options using the text field for arbitrary options.
- Adapted unit test.
> reduce size of dialogs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/bin/mask-systemd-units
The mask-systemd-units did not mask swap units of systemd. Thus systemd could mount swaps while YaST was running causing failures when YaST tries to mount swaps.
- https://trello.com/c/BDMvJros/1570-3-sles15-sp2-p5-1152545-error-re-creating-plain-encryption
- https://bugzilla.suse.com/show_bug.cgi?id=1152545
Also mask/unmask swap units (by not filtering them out).
> also mask swap units in mask-systemd-units

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/used_storage_features.rb
When user tries to encrypt a swap partition using YaST the error message "Command not found: "/sbin/cryptsetup…" appears instead of a request to install that package.
libstorage suggests UF_PLAIN_ENCRYPTION for encrypting swap, but the package requirement for that feature was missing in yast-storage-ng. So the package `cryptsetup` was not installed before commiting the changes.
- [bsc#1160773](https://bugzilla.suse.com/show_bug.cgi?id=1160773)
Added package requirement for `cryptsetup` to UF_PLAIN_ENCRYPTION in yast-storage-ng.
By this opportunity removed the obsolete feature UF_CRYPT_TWOFISH which libstorage does not use any more.
> Added package requirement for UF_PLAIN_ENCRYPTION (bsc#1160773)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/delete_partitions.rb
- test/y2partitioner/actions/delete_partitions_test.rb
The "Delete all" button in the "Partitions" tab of any partitionable device failed when there were logical partitions involved.
- https://bugzilla.suse.com/show_bug.cgi?id=1162290
The Partitioner got the list of all partitions in the device and then iterated over that list deleting each. But after having deleted the extended partitions, the logical partitions were not longer there. Still, the Partitioner tried to delete the not-longer-existent partitions because they were in its list.
Simply use the method `PartitionTables:Base#delete_all_partitions` that already have all that into account.
- Tested manually also
> Partitioner: fix button to delete all partitions (bsc#1162290) 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/clients/main.rb
- src/lib/y2partitioner/dialogs/commit.rb
- src/lib/y2partitioner/widgets/commit_actions.rb
- src/lib/y2storage/callbacks/commit.rb
- src/lib/y2storage/storage_manager.rb
- test/y2partitioner/clients/main_test.rb
- test/y2partitioner/dialogs/commit_test.rb
- test/y2partitioner/widgets/commit_actions_test.rb
When using the Expert Partitioner in an already installed system, the last screen is a summary about all the actions to apply. But once this summary is accepted, the Expert Partitioner is automatically closed, and there is no hint about what is happening under the hood. Were all the changes correctly applied? Has it already finished? Or is it still working? No way to know.
* https://bugzilla.suse.com/show_bug.cgi?id=1135366 
* https://trello.com/c/Xpjm7Kdr/1579-5-1135366-ux-issue-when-applying-changes-with-expert-partitioner
The old Partitioner had an extra dialog after the summary to show the progress of the changes being applied to the system. A similar dialog has been brought back.
These changes require the new progress bar widget defined here …
> Add commit progress dialog

- package/yast2-storage-ng.changes
#1031 introduced a wrong version number in the changelog.
To say "sorry" :sweat_smile:  and fix it.
> Fix wrong version in the changelog file

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/btrfs_raid_level.rb
- test/y2partitioner/actions/controllers/btrfs_devices_test.rb
libstorage gained support for btrfs RAID levels RAID1C3 and RAID1C4. That makes the testsuite here fail. 
Add minimal support for btrfs RAID levels RAID1C3 and RAID1C4.
- Extended unit test.
> added texts for RAID1C3 and RAID1C4

- test/data/devicegraphs/empty-md_raid.yml
- test/y2storage/proposal_raid_test.rb
This test shows the behavior SLE-15-SP1 had when making a proposal on top of a software RAID.
This is unfortunately broken in master (SLE-15-SP2), as reported in [bug#1161331](https://bugzilla.suse.com/show_bug.cgi?id=1161331).
> Test to demostrate bsc#1161331 is not present in SP1

- package/yast2-storage-ng.changes
The changed introduced in #1042 failed at Jenkins with our beloved error: "_Stopping, missing new bugzilla or fate entry in the *.changes file. e.g. bnc#<number> or fate#<number>_"
Just add some numbers that are traceable by our build service bots.
> Added references to changelog for the bots

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/edit_blk_device.rb
- test/y2partitioner/actions/edit_blk_device_test.rb
Some block devices cannot used as block devices (e.g., DASD devices). Therefore, these devices cannot be directly formatted, but the Expert Partitioner does not prevent it.
* https://bugzilla.suse.com/show_bug.cgi?id=1163597
* https://trello.com/c/NsJWnEWd/1651-sles15-sp2-p2-1163597-partitioner-allows-to-install-on-an-unpartitioned-dasd
A new error was added to the action for editing block devices. Now, an error popup is shown when the user tries to edit a device that cannot be used as block device.
Note that `BootRequirementsChecker` was working correctly and some warnings were generated when a DASD device was directly formatted for root. See screenshots.
<details>
<summary>Show/Hide</summary>
* New error
* `BootRequirementsChecker` was showing …
> Add not usable as block device error

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_strategies/analyzer.rb
- test/data/devicegraphs/empty-md_raid.yml
- test/y2storage/proposal_raid_test.rb
In order to support S130/S140/S150 controllers (and also to be more compatible with the old storage), when a software RAID is completely empty (not formatted and not partitioned), it will be considered as a candidate device for the storage proposal.
As proven by #1043, in SLE-15-SP1 that resulted in a proposal that locates the `/boot/efi` partition inside the software RAID. Although that can be a bit controversial, Dell was happy with this behavior (their S130/S140/S150 controllers has indeed proven to be able to boot the resulting setup) and nobody has complained.
But in TW and in the beta versions of SLE-15-SP2, the proposal tries to locate the `/boot/efi` partitions directly in one of the physical disks and that leaded to an infinite loop.
This pull request:
- Merges #1043, so we …
> Proposal: honor root_device also when is a software RAID (bsc#1161331)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/edit_blk_device.rb
- src/lib/y2partitioner/widgets/device_buttons_set.rb
- src/lib/y2partitioner/widgets/pages/disk.rb
- test/y2partitioner/actions/edit_blk_device_test.rb
- test/y2partitioner/widgets/device_buttons_set_test.rb
- test/y2partitioner/widgets/pages/disk_test.rb
Some block devices cannot be used as block devices (e.g., DASD devices). Therefore, these devices cannot be directly formatted, but the Expert Partitioner does not prevent it.
* https://bugzilla.suse.com/show_bug.cgi?id=1163597
* https://trello.com/c/NsJWnEWd/1651-sles15-sp2-p2-1163597-partitioner-allows-to-install-on-an-unpartitioned-dasd
A solution was already proposed in the PR https://github.com/yast/yast-storage-ng/pull/1045, but now a more convenient approach is implemented. The buttons for editing a device are hidden (i.e., when the device cannot be used as block device) instead of showing an error popup.
- Added a new unit tests
<details>
<summary>Show/Hide</summary>
* Before:
* After:
</details>
> Hide edit button for DASD devices

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/partition_killer.rb
- test/y2storage/proposal/space_maker_test.rb
When a planned device needs to be created out of the candidate devices, the SpaceMaker entered an infinite loop. See [bug#1161331](https://bugzilla.suse.com/show_bug.cgi?id=1161331) (and also [bug#1161678](https://bugzilla.suse.com/show_bug.cgi?id=1161678)) and https://trello.com/c/6FDBka8e/.
After having merged #1046, devices should never be planned out of the candidate devices, so the error cannot affect users anymore. But the SpaceMaker was still not fixed and it could still enter in the infinite loop if the proposal changes in the future.
This is the commit that opened the door for the infinite loops in SpaceMaker: https://github.com/yast/yast-storage-ng/commit/c61035961a06e5301f0b0d3c51392d0252f531d5
It changed the semantic of `PartitionKiller#disks`. Originally, that was only …
> Fix a bug preventing some partitions to be deleted (bsc#1161331)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/libstorage_callback.rb
- src/lib/y2storage/callbacks/probe.rb
- src/lib/y2storage/exceptions.rb
- src/lib/y2storage/package_handler.rb
- src/lib/y2storage/storage_manager.rb
- src/lib/y2storage/used_storage_features.rb
- test/y2storage/callbacks/probe_test.rb
- test/y2storage/used_storage_features_test.rb
For https://trello.com/c/ae4cAtFe/1573-5-improve-probing-when-there-are-missing-tools.
Probing can fail if programs are missing.
Allow user to install missing packages.
- Added a new unit test.
See trello card.
> allow to install packages needed for probing

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/mount_point.rb
- src/lib/y2storage/mountable.rb
- test/y2storage/blk_device_test.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
- test/y2storage/mount_point_test.rb
This module has some logic to obtain the most reasonable mount by option. See https://github.com/yast/yast-storage-ng/pull/985. That logic is kind of duplicated by *yast2-bootloader* module, see https://github.com/yast/yast-bootloader/blob/master/src/lib/bootloader/udev_mapping.rb#L110.
But *yast2-storage-ng* does not offer a proper public API to get the preferred mount by option.
* https://trello.com/c/TyCrUgrP/1401-use-the-suitablemountby-mechanism-in-yast-bootloader
New API methods have been added to obtain the preferred mount by option and the associated udev path of the device: `Mountable#preferred_mount_by`, `BlkDevice#path_for_mount_by`.
See also https://github.com/yast/yast-bootloader/pull/591.
* Added new unit tests
> Add methods for preferred mount by

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/encryption.rb
- src/lib/y2partitioner/widgets/apqn_selector.rb
- src/lib/y2partitioner/widgets/encrypt.rb
- src/lib/y2partitioner/widgets/encrypt_method_options.rb
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/encryption.rb
- src/lib/y2storage/encryption_method/pervasive_luks2.rb
- src/lib/y2storage/encryption_processes/apqn.rb
- src/lib/y2storage/encryption_processes/base.rb
- src/lib/y2storage/encryption_processes/pervasive.rb
- src/lib/y2storage/encryption_processes/secure_key.rb
- test/data/lszcrypt/three-apqns.txt
- test/y2partitioner/actions/controllers/encryption_test.rb
- test/y2partitioner/widgets/apqn_selector_test.rb
- test/y2partitioner/widgets/encrypt_method_options_test.rb
- test/y2partitioner/widgets/encrypt_password_test.rb
- test/y2storage/blk_device_test.rb
- test/y2storage/encryption_method_test.rb
- test/y2storage/encryption_processes/apqn_test.rb
- test/y2storage/encryption_processes/pervasive_test.rb
- test/y2storage/encryption_processes/secure_key_test.rb
- test/y2storage/pervasive_encryption_test.rb
When a device is going to be encrypted with pervasive encryption (s390), a new secure key is generated for the device (if there is none yet). By default, this new secure key will be generated for all adapters/domains available in the system. But this could fail when the adapters/domains are set with different master keys. In that case, only adapters using the same master key should be taken into account for generating the new secure key.  
* https://jira.suse.com/browse/IBM-495?focusedCommentId=974832&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-974832
* https://trello.com/c/KwTmeWhi/1587-5-sle-7376-pervasive-encryption-second-round-specifying-the-apqns
Now, the dialog for pervasive encryption allows to select APQNs when a new secure key is going to be …
> Select APQNs for a new secure key

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/drive_section.rb
- test/data/devicegraphs/md_raid_lvm.yml
- test/y2storage/autoinst_profile/drive_section_test.rb
As seen in [bsc#1159201](https://bugzilla.suse.com/show_bug.cgi?id=1159324), AutoYaST omits the `<partitions>` list when cloning an unpartitioned RAID that does not have partitions nor a file system. It may happen that the RAID is used as part of another device (e.g., as part of an LVM volume group).
Additionally, while debugging the issue, I have found that the `<disklabel>` element was not set.
This PR fixes both problems, setting the `<disklabe>` to the appropriate value and exporting the `<partitions>` section when the RAID device is used.
- https://bugzilla.suse.com/show_bug.cgi?id=1159324
- Trello card: https://trello.com/c/lLRXuABJ/1673-3-sles15-sp1-p5-1159201-autoyast-does-not-get-encrypted-setup-with-a-unusual-partition-scheme
> bsc#1159201: export unpartitioned RAID when used for another device (LVM, RAID, bcache)

- test/y2partitioner/widgets/commit_actions_test.rb
Tests are failing in IBS/OBS. We have reproduced the problem by running the tests in a given order.
Thanks to @joseivanlopez who spotted the problem.
> Fix CommitActions tests

- src/lib/y2storage/proposal/autoinst_space_maker.rb
- test/y2storage/autoinst_proposal_system0_test.rb
- test/y2storage/proposal/autoinst_space_maker_test.rb
Given a system where there is already an LVM VG named (e.g., `system`), if you
try to reinstall using a new VG with the same name, it might happen that
AutoYaST modifies the wanted name (like `system0`) to avoid *colliding* with the
old name. It does not make sense, as you do not want to keep the old one.
- [bsc#1115749](https://bugzilla.suse.com/show_bug.cgi?id=1115749)
The problem happens when you are using a full disk as a PV (it will not happen
when using partitions). The reason is that `AutoinstSpaceMaker` will not have
full disks into account, even when you have set the `use` to `all`.
Additionally, this PR also fixes the reusing of Bcache devices when, for some reason, the user does not mark the caching/backing devices to be reused.
> AutoYaST: modify the LVM VG name only when really needed

- src/lib/y2storage/package_handler.rb
During implementation of #1060, an obsolete require was left behind.
Remove the obsolete require. The dependency is not longer true (removing it was in fact one of the goals of the refactoring) and the required file is not longer there (unless you have an old version of yast2-storage-ng installed).
> Remove obsolete require

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_issues.rb
- src/lib/y2storage/autoinst_issues/conflicting_attrs.rb
- src/lib/y2storage/proposal/autoinst_disk_device_planner.rb
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- src/lib/y2storage/proposal/autoinst_md_planner.rb
- src/lib/y2storage/proposal/autoinst_vg_planner.rb
- test/support/autoinst_devices_planner_bcache.rb
- test/support/autoinst_devices_planner_conflicts.rb
- test/y2storage/autoinst_issues/conflicting_attrs_test.rb
- test/y2storage/proposal/autoinst_disk_device_planner_test.rb
[bsc#1165907](https://bugzilla.suse.com/show_bug.cgi?id=1165907) revealed a problem when setting two mutually exclusive options in an AutoYaST partition section. In that case, setting the `lvm_group` and `raid_name` caused `libstorage-ng` to crash.
There are a few elements that determine how is the device going to be used: `mount`, `raid_name`, `lvm_name`, `btrfs_name`, `bcache_backing_for` and `bcache_caching_for`. The truth is that all those elements should be exclusive.
Now, if more than one of those attributes are present, AutoYaST will select just one and ignore the rest. For the time being, the logic is pretty simple (just a matter of precedence), but in the future, we might consider a smarter mechanism.
The PR contains some unit tests and I have tried the changes manually. …
> AutoYaST: warn about conflicting elements

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/yaml_writer.rb
- test/y2storage/yaml_writer_test.rb
Working on https://github.com/openSUSE/libstorage-ng/pull/709 I noticed that the `nocow` btrfs attribute is not written correctly into YAML, resulting in invalid YAML files.
It stored the value as string (`'true'`) instead of as `true`.
> write nocow attribute correctly into YAML

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/clone_partition_table.rb
- test/data/devicegraphs/mixed_disks_clone.yml
- test/y2partitioner/actions/controllers/clone_partition_table_test.rb
The YaST Partitioner offers an option to clone the partition table from one device to others. During that action the Partitioner tries to only offer destination devices that make sense. That means they have to be as least as big as the source device, they have to have the same topology, etc.
Unfortunately, the Partitioner didn't check the block size of the devices, which must also match in order for the cloning to be possible.
- https://bugzilla.suse.com/show_bug.cgi?id=1166363
- https://trello.com/c/b9VsyvXH/1702-2-sle15-sp2-1166363-cloning-a-partition-table-with-different-sector-sizes-runs-into-an-internal-error
After verifying that is perfectly possible for two devices with different block sizes to have identical `Topology` objects in libstorage-ng, I created this pull request that …
> Check block sizes when cloning partitions (bsc#1166363) 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_strategies/analyzer.rb
- test/y2storage/boot_requirements_strategies/analyzer_test.rb
The installer allows to proceed even when `/boot` is explicitly or implicitly mounted in a [bcache](https://bcache.evilpiepirate.org/) formatted partition.
However, the installed system is not able to boot.
- https://trello.com/c/KK7xbNps
- https://bugzilla.suse.com/show_bug.cgi?id=1165903
- Related to https://github.com/yast/yast-storage-ng/pull/944
To show an alert when `/boot` will be mounted in a bcache.
<details>
<summary>Click to show/hide</summary>
---
</details>
> Fix the /boot in bcache detection

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/filesystems/mount_by_type.rb
- src/lib/y2storage/luks.rb
- src/lib/y2storage/md.rb
- src/lib/y2storage/mount_point.rb
- test/y2storage/blk_device_test.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
Recently yast2-booloader was modified to not contain the logic about what is the best file path to reference a file, but to delegate that calculation to yast2-storage-ng. See https://github.com/yast/yast-bootloader/pull/591
Unfortunately, the logic implemented in that pull request is not really a direct translation of the previous one. If the device contains no filesystem (for example, PReP partitions and bios_boot ones), the logic implemented in https://github.com/yast/yast-bootloader/pull/591 fallbacks immediately to use the kernel device name.
In fact, the API offered by yast2-storage-ng only contained method to get the preferred name for `BlkFilesystem` objects, but not for `BlkDevice` objects themselves. Moreover, the distinction was not so clear and the method …
> Add preferred_name to BlkDevice and BlkFilesystem (needed for bsc#1166096)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/fillup/sysconfig.storage-yast2-storage-ng.common
- src/lib/y2partitioner/widgets/commit_actions.rb
- src/lib/y2storage/clients/finish.rb
- src/lib/y2storage/clients/inst_disk_proposal.rb
- src/lib/y2storage/sysconfig_storage.rb
- src/lib/y2storage/used_filesystems.rb
- test/y2storage/used_filesystems_test.rb
With the rewrite of yast2-storage it did no longer write the used filesystems to USED_FS_LIST in /etc/sysconfig/storage. AFAIS this has no further consequences.
- https://bugzilla.suse.com/show_bug.cgi?id=1161533
The list is written again.
- Added a new unit test.
> reanimate saving USED_FS_LIST (bsc#1161533)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/filesystems/blk_filesystem.rb
- test/y2storage/encryption_test.rb
- test/y2storage/mount_point_test.rb
YaST adds the `_netdev` fstab option to all network-based file-systems. In the case of the root file-system that can be a problem. Copy&pasting the explanation directly from [the bugzilla entry](https://bugzilla.suse.com/show_bug.cgi?id=1165937):
_Adding `_netdev` for rootfs in /etc/fstab should not be necessary and it confuses systemd for the time being._
_It's not necessary because the main description of rootfs should be given through the kernel command line via "root*=" options. These options are parsed by the fstab generator, which should generate the correct dependencies especially if these options specify a remote root._
_OTOH `_netdev` is obviously not available until the rootfs is mounted._
_The entry in fstab for '/' is used but only to apply the final mount options, and it's …
> Do not propose the _netdev option for the root filesystem (bsc#1165937)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/storage_manager.rb
- test/y2storage/storage_manager_test.rb
This sequence of steps in the Partitioner leaded to a crash:
- Delete a partition containing a filesystem
- Reprobe
- Delete a partition containing a filesystem (not necessarily the same)
The problem was an outdated `Y2Storage::StorageManager.instance.system` pointing to a devicegraph that had been already killed by libstorage-ng.
The possibility to access to `Storage.system` (in addition to `probed` and `staging`) was added to `Y2Storage::StorageManager` in #725. But, although the libstorage-ng documentation specifies that reprobing invalidates the three devicegraphs `probed`, `system` and `staging`, the memoization of the latter was not being cleared up.
- Report for SLE-15-SP2: https://bugzilla.suse.com/show_bug.cgi?id=1168325
- …
> Refresh the system devicegraph when reprobing (bsc#1168325)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/activate.rb
- src/lib/y2storage/storage_env.rb
- test/y2storage/callbacks/activate_test.rb
- test/y2storage/storage_env_test.rb
If the system has many LUKS devices users do not like to have to cancel activation several times during upgrade.
- https://bugzilla.suse.com/show_bug.cgi?id=1162545
Allow to disable LUKS activation by setting the environment variable YAST_ACTIVATE_LUKS=0.
- Added a new unit test.
> allow to disable LUKS activation (bsc#1162545)

- package/yast2-storage-ng.spec
The **CONTRIBUTING.md** file was removed (#1076) from the repository but the file is still referenced in the spec file
Remove the file from the spec file
> Remove CONTRIBUTING.md from the spec file

- doc/vfat-notes.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/fstab_options.rb
- src/lib/y2storage/filesystems/type.rb
- test/data/devicegraphs/output/raspi_empty.yml
- test/data/devicegraphs/output/raspi_firmware.yml
- test/y2storage/filesystems/type_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1161771
- and also revisiting https://bugzilla.suse.com/show_bug.cgi?id=1080731
- https://trello.com/c/vBCU6H1R
TL;DR: VFAT mounts with `iocharset=utf8` are implicitly case-sensitive. There's a separate `utf8` option (without `iocharset=`) that is to be used instead. `utf8` is case-insensitve in some limited fashion which is good enough to avoid the `EFI` spelling ambiguity that caused [bsc#108073]( https://bugzilla.suse.com/show_bug.cgi?id=108073).
The goal is to avoid `iocharset=utf8` in favor of `utf8`.
This also changes the defaults of `iocharset` and `codepage` for newly created vfat filesystems to "" (empty) if the default encoding and code page are used. This has the advantage that entering the fstab option dialog no longer adds …
> rework VFAT mount option handling (bsc#1161771)

- Rakefile
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/guided_proposal.rb
- src/lib/y2storage/initial_guided_proposal.rb
- src/lib/y2storage/proposal/partitions_distribution_calculator.rb
- src/lib/y2storage/volume_specifications_set.rb
- test/data/control_files/suma_multidisk.xml
- test/data/devicegraphs/many_disks.yml
- test/y2storage/initial_guided_proposal_multidisk_first_test.rb
- test/y2storage/proposal_scenarios_multidisk_role_test.rb
This replaces #1080 (I messed up with git)
Review commit by commit, all of them make sense on their own and contain descriptive messages.
This pull request would kickstart the SLE-15-SP2 branch, so it also includes a commit to adapt the Rakefile.
Quite some time ago, we implemented several configuration options for the storage proposal to enable the creation of the `suma_multidisc_role` for SUSE Manager Server (see https://github.com/yast/skelcd-control-suse-manager-server/pull/15).
Apart from the three new options (`allocate_volume_mode`, `separate_vgs` and `delete_resize_configurable`) introduced to change how the Guided Setup works, we also added the option `multidisk_first` to influence the initial proposal (the one that is calculated before the user has had any chance to influence …
> Speed up the initial proposal, specially for suma_multidisc_role

- package/yast2-storage-ng.changes
- src/lib/y2storage/boot_requirements_strategies/base.rb
- test/y2storage/boot_requirements_errors_test.rb
The `SetupChecker` is considering some clear `warnings` as `errors`.
- https://trello.com/c/QSNRwq5E/1742-1-relax-boot-related-errors-make-them-warnings
<details>
<summary>Click to show/hide more details</summary>
---
Extracted from Trello card description:
> The `SetupChecker` contains two levels of errors:
> 
> - `errors` for things that really make impossible for the installation process to continue. Basically missing mountpoint for "/" and similar disasters. The user simply cannot press "next" in the Partitioner if an error is reported.
> - `warnings` for stuff that can lead to a non-supported and/or non-bootable system but should not interrupt the installation process. For those power users that know what they are doing.
> 
> Things like the lack of a `/boot/efi` partition in the EFI …
> Relax SetupChecker errors

- Dockerfile
- The `Dockerfile` was not adapted when branching SP2 (at that time the image did not exist)
- Adapt it :wink:
> Adapt Dockerfile for SLE15-SP2

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/encryption.rb
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/device.rb
- src/lib/y2storage/encryption.rb
- test/y2storage/in_etc_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1118977
- https://trello.com/c/jtojel4R
New encrypted volumes are added to `/etc/crypttab` (even when not mounted).
There are two issues:
1. The default value for `in_etc` is true for newly created encrytpted volumes.  Since the `#update_etc_status` method ensures the status can't be set to false when it was originally true, this unavoidably creates an initial crypttab entry.
To avoid this, set the `in_etc` flag to false explicitly for freshly created encrypted volumes.
2. The `#update_etc_status` method is called when you switch between mounting/not mounting in the fstab dialog.
But when encryption had just been enabled, the encrypted device does not yet exist in the device tree. It's created only after going through the password dialog.
This …
> update /etc/crypttab status properly (bsc#1118977)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/encryption.rb
- test/y2storage/encryption_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1168465
- https://trello.com/c/01yaT7SA
The new crypttab option `x-initrd.attach` should be added for filesystems that are attached in the initrd.
See [crypttab(5)](https://www.freedesktop.org/software/systemd/man/crypttab.html).
Add this option for newly created filesystems mounted at `/` and all filesytems with `x-initrd.mount` fstab option.
> add x-initrd.attach option to crypttab if needed (bsc#1168465)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/resize_info.rb
The message for a new resize blocking reason is missing.
- https://github.com/openSUSE/libstorage-ng/pull/744
Add the message.
> added translation for new resize blocking reason

- doc/lvm.md
First step to implement correct support in YaST for all the LVM types/features that are currently detected by libstorage-ng.
See https://trello.com/c/P5XUCPLo/1879-3-follow-up-of-new-lvm-types-check-possible-impact-in-the-proposal-and-or-expert-partitioner-and-or-offline-upgrade
> Document current status of LVM in the Partitioner

- doc/lvm.md
There was a recurrent mistake in `lvm.md`. [Stripped != striped](https://grammarist.com/usage/stripedstriping-vs-strippedstripping/).
Simply fix it!
> Fix recurrent typo

- .cirrus.yml
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/storage_feature.rb
With NVMeOF devices the NVMe tools in the package nvme-cli are needed.
Install the tools if libstorage-ng reports the new feature UF_NVME.
- https://trello.com/c/QIyuWNgI/1911-5-sles15-sp2-p2-1172866-nvme-cli-not-installed-when-root-is-an-nvme-device
- https://bugzilla.suse.com/show_bug.cgi?id=1172866
> install nvme-cli if NVMe devices are present

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_proposal.rb
- src/lib/y2storage/proposal_settings.rb
- test/y2storage/autoinst_proposal_test.rb
- test/y2storage/proposal_settings_test.rb
AutoYaST proposal falls back to the guided proposal when no partitions are indicated in the AutoYaST profile. This fallback only performs two tries at most: with max and desired device sizes. For example, it does not try with every candidate disk as possible boot disk.
Because of that, the boot disk is always fixed to the default disk reported by the "Boot Requirements Checker" (first disk as general default), making the installation impossible when the boot disk does not belong to the list of candidates devices.
This bug becomes very evident when the AutoYaST profile does not include the first disk as possible candidate disk:
~~~
<partitioning config:type="list">
<drive>
<device>/dev/sdc</device>
<disklabel>gpt</disklabel>
<initialize config:type="boolean">true</initialize> …
> AutoYaST delegates to initial proposal

- doc/lvm.md
The document `doc/lvm.md` describes the current status of the LVM support in the Partitioner. It was taken as starting point for this task: https://trello.com/c/pZPp5aIN/1824-3-lvm-and-partitioner-fix-found-problems
Now that the task is (mainly) done, the document is outdated.
Additionally, the outcome of this other task was only documented in Trello, which is wrong since Trello is only used to coordinate the work, but should never be the only source for any information.
https://trello.com/c/P5XUCPLo/1879-3-follow-up-of-new-lvm-types-check-possible-impact-in-the-proposal-and-or-expert-partitioner-and-or-offline-upgrade
Update the document with the new status, which is of course much better than the previous one, and with new sections describing the behavior of the partitioning proposal …
> Update lvm.md after the latest fixes in that area

- doc/lvm.md
- package/yast2-storage-ng.changes
- src/lib/y2partitioner/widgets/lvm_lv_attributes.rb
- src/lib/y2storage/lvm_lv.rb
- test/y2storage/lvm_lv_test.rb
As documented in [doc/lvm.md](https://github.com/yast/yast-storage-ng/blob/47201dfdb855d468ba735ffe46bf16544002eea0/doc/lvm.md),
> the partitioner UI reports correctly the number of stripes, **but reports 0.00B for the stripes size**.
for thin and mirror LVs.
<sub>Related to https://github.com/yast/yast-storage-ng/pull/1105</sub>
* Manage the #stripe_size method in `Y2Storage::LvmLv` instead of forwarding it directly to libstorage-ng.
* Do not display the stripe size in the overview when it is zero.
| Mirror LV | Thin LV |
|-|-|
| ![mirror_lv](https://user-images.githubusercontent.com/1691872/87782269-1ed9e700-c82a-11ea-9263-adc5f385f07f.png) | ![thin_lv](https://user-images.githubusercontent.com/1691872/87782288-24cfc800-c82a-11ea-989e-826ae19 …
> Partitioner: fix reported stripe size

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/can_be_formatted.rb
- test/y2storage/proposal_separate_vgs_test.rb
The proposals contain logic to avoid creating Btrfs subvolumes if their mount points are shadowed by any other filesystem. But that was not working properly for roles using `separate_vgs` in the configuration of the proposal.
So far, that setting is used only by the following SUSE Manager roles: `suma_multidisc_role` and `suma_retail_multidisc_role`. When one of such roles was selected, the proposal created a separate `/srv` LVM logical volume in its own dedicated volume group... but also a `/srv` subvolume for the root filesystem. That, of course, caused problems.
- https://bugzilla.suse.com/show_bug.cgi?id=1174475
- https://trello.com/c/b2NAhJzv/1990-susemanager-41-p5-1174475-srv-mountpoint-is-declared-twice-in-etc-fstab
Make sure the detection of shadowed subvolumes also has into …
> Detect subvolumes shadowed by a separate_vg (bug#1174475)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_proposal.rb
- src/lib/y2storage/proposal/base.rb
- test/y2storage/autoinst_proposal_test.rb
`Y2Storage::AutoinstProposal` provides a method called `#failed?`. It returns true when it was not possible to calculate a devicegraph for the system that can satisfy the provided AutoYaST profile.
SLES15-SP2 Installer for SAP Business ONE relies on such method to implement its own storage proposal.
But when `AutoinstProposal` found a critical error while matching `<drive>` sections in the profile with devices in the system (for example, it didn't find a disk that was supposed to be there), the proposal was indeed not calculated... but `#failed?` returned false instead of true.
- https://bugzilla.suse.com/show_bug.cgi?id=1174469
- https://trello.com/c/FSrfXADT/1992-2-sle15-sp2-p2-1174469-yast-storage-error-in-copytostaging
- A gist with some extra information about stuff discussed in the …
> Fix bug when AutoinstProposal find no devices (bsc#1174469) 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_space_maker.rb
- test/y2storage/autoinst_proposal_system0_test.rb
- test/y2storage/proposal/autoinst_space_maker_test.rb
Backport of https://github.com/yast/yast-storage-ng/pull/1056 as [suggested in the bug report](https://bugzilla.suse.com/show_bug.cgi?id=1115749#c14).
Given a system where there is already an LVM VG named (e.g., `system`), if you try to reinstall using a new VG with the same name, it might happen that AutoYaST modifies the wanted name (like `system0`) to avoid *colliding* with the old name. It does not make sense, as you do not want to keep the old one.
- [bsc#1115749](https://bugzilla.suse.com/show_bug.cgi?id=1115749)
The problem happens when you are using a full disk as a PV (it will not happen when using partitions). The reason is that `AutoinstSpaceMaker` will not have full disks into account, even when you have set the `use` to `all`.
Additionally, this PR also fixes the reusing of …
> [bsc#1115749]  AutoYaST: modify the LVM VG name only when really needed

- package/yast2-storage-ng.changes
- src/lib/y2storage/proposal/autoinst_space_maker.rb
Merge #1117 into SP2. It adds a line to the changes log that was omitted in the original #1056 and it should have been added in the #1057.
> Merge SLE-15-SP1 into SLE-15-SP2

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/bcache_options_section.rb
- src/lib/y2storage/autoinst_profile/btrfs_options_section.rb
- src/lib/y2storage/autoinst_profile/drive_section.rb
- src/lib/y2storage/autoinst_profile/partition_section.rb
- src/lib/y2storage/autoinst_profile/partitioning_section.rb
- src/lib/y2storage/autoinst_profile/raid_options_section.rb
- test/y2storage/autoinst_issues/issues_presenter_test.rb
- test/y2storage/autoinst_profile/bcache_options_section_test.rb
- test/y2storage/autoinst_profile/btrfs_options_section_test.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
- test/y2storage/autoinst_profile/raid_options_section_test.rb
The new error reporting mechanism and the <ask-list> features use different syntax to point to a specific element in a profile (`partitioning,0,partitions,1` vs `drives [1] > partitions [2]`).
Use the same syntax that the ask-list. This PR relies on https://github.com/yast/yast-yast2/pull/1090.
> [AutoYaST] Fix profile element paths

- src/lib/y2partitioner/widgets/bcache_edit_button.rb
- src/lib/y2partitioner/widgets/blk_device_edit_button.rb
- src/lib/y2partitioner/widgets/btrfs_edit_button.rb
- src/lib/y2partitioner/widgets/device_delete_button.rb
- src/lib/y2partitioner/widgets/device_resize_button.rb
- src/lib/y2partitioner/widgets/lvm_lv_add_button.rb
- src/lib/y2partitioner/widgets/lvm_lvs_delete_button.rb
- src/lib/y2partitioner/widgets/lvm_vg_resize_button.rb
- src/lib/y2partitioner/widgets/overview.rb
- src/lib/y2partitioner/widgets/pages/lvm.rb
- src/lib/y2partitioner/widgets/pages/system.rb
- src/lib/y2partitioner/widgets/partition_add_button.rb
- src/lib/y2partitioner/widgets/partition_move_button.rb
- src/lib/y2partitioner/widgets/partition_table_add_button.rb
- src/lib/y2partitioner/widgets/partitions_delete_button.rb
- src/lib/y2partitioner/widgets/used_devices_edit_button.rb
- test/y2partitioner/dialogs/device_graph_test.rb
- test/y2partitioner/dialogs/settings_test.rb
- test/y2partitioner/dialogs/summary_popup_test.rb
- test/y2partitioner/widgets/device_graph_with_buttons_test.rb
- test/y2partitioner/widgets/overview_test.rb
- test/y2partitioner/widgets/visual_device_graph_test.rb
The tree options *Device Graphs*, *Installation Summary* and *Settings* were moved from the left tree to the new menu bar. Now, having a first level in the tree with everything hanging on it simply does not make sense. We can remove the outer nesting of the left tree, so the first level would be "Hard disks", "Volume Management", etc.
See https://github.com/yast/yast-storage-ng/blob/master/doc/partitioner_ui.md#agreed-plan-so-far for a sketch of the expected result.
* Related to: https://bugzilla.suse.com/show_bug.cgi?id=1175489
* PBI: https://trello.com/c/9fXaJujC/2044-2-partitioner-left-tree-less-nesting
The first level was removed.
Note: ruby 2.7 deprecates the usage of last argument as keyword parameters. Because that, we start to see a lot warnings like this:
~~~
warning: Using the …
> Reduce tree nesting

- src/lib/y2partitioner/dialogs/main.rb
- src/lib/y2partitioner/ui_state.rb
- src/lib/y2partitioner/widgets/main_menu_bar.rb
- src/lib/y2partitioner/widgets/menus/add.rb
- src/lib/y2partitioner/widgets/menus/base.rb
- src/lib/y2partitioner/widgets/menus/configure.rb
- src/lib/y2partitioner/widgets/menus/device.rb
- src/lib/y2partitioner/widgets/menus/extra.rb
- src/lib/y2partitioner/widgets/menus/go.rb
- src/lib/y2partitioner/widgets/menus/modify.rb
- src/lib/y2partitioner/widgets/menus/system.rb
- src/lib/y2partitioner/widgets/menus/view.rb
The previous version of the Partitioner menu bar was intentionally incomplete since it was just a proof of concept.
After some meetings and discussions (see, for example, [this mail thread](https://lists.opensuse.org/yast-devel/2020-09/msg00004.html)) we have agreed on the general approach the menu should follow.
This pull request implements a first version of that menu, in which all possible Partitioner actions are represented in the most consistent way we have been able to come up with.
With all the options that were below the system table, plus two extra entries to quit (with and without saving).
With a few generic actions for the device currently selected in the table. We are considering to call it "Edit", since its a more common term for a menu. But "edit" has another historical …
> First version of a menu bar with all the entries

- src/lib/y2partitioner/dialogs/main.rb
The `Expert Partitioner` title does not allow to put the recently added menu bar at the very top.
* Part of https://trello.com/c/dT7X5aC1/2045-menu-layout-rendering-improvements
Do not display the `Expert Partitioner` heading anymore.
| Installer | Running System |
|-|-|
|  ![Screenshot_tw_2020-09-16_17:10:04](https://user-images.githubusercontent.com/1691872/93364866-faf24c00-f840-11ea-84b7-fb577f4ce936.png) |  ![93351630-dd69b600-f831-11ea-9300-a2248e153047](https://user-images.githubusercontent.com/1691872/93364951-18271a80-f841-11ea-88b7-78d701536cc8.png) |
Some adjustments were necessary in order to not keep reserving space for the Wizard heading. See below PRs for more details 
* https://github.com/yast/yast-yast2/pull/1098
* …
> Remove heading from partitioner dialog

- src/lib/y2partitioner/dialogs/bcache_csets.rb
- src/lib/y2partitioner/dialogs/device_graph.rb
- src/lib/y2partitioner/dialogs/settings.rb
- src/lib/y2partitioner/dialogs/summary_popup.rb
- src/lib/y2partitioner/widgets/configurable_blk_devices_table.rb
- src/lib/y2partitioner/widgets/menus/view.rb
- src/lib/y2partitioner/widgets/pages/bcaches.rb
- test/y2partitioner/dialogs/bcache_csets_test.rb
A menu bar is being added to the Expert Partitioner. We are taking the opportunity for improving some other parts, for example the Bcache presentation. Right now, the Bcache page contains two tabs, one to list the Bcache devices and a second one to list the Bcache Caching Sets. This last tab is only informative (no actions can be done over the Bcache Caching Sets). Note that this is the only general page with two tabs. For example, Hard Disk, LVM, etc have no tabs. For a matter of homogeneity, it would be better to remove the tabs in this Bcache page and show that information as a popup by using an option of the new menu bar. 
* Part of PBI: https://trello.com/c/NITXJRBE/2055-menu-driven-interface-finish-it
Removed tabs in the Bcache page and added a new option in the menu bar that opens …
> Bcache Caching Sets popup

- src/lib/y2partitioner/widgets/btrfs_filesystems_table.rb
- src/lib/y2partitioner/widgets/columns/device.rb
- src/lib/y2partitioner/widgets/overview_tab.rb
- src/lib/y2partitioner/widgets/pages/bcache.rb
- src/lib/y2partitioner/widgets/pages/btrfs.rb
Part of the dirty prototype at `partitioner-ui-03`: make the sections for Bcache and Btrfs work in a more similar way to others.
> Ui 03 fix btrfs and bcache

- src/lib/y2partitioner/widgets/main_menu_bar.rb
- src/lib/y2partitioner/widgets/menus/modify.rb
This is part of the prototype we are building in the `partitioner-ui-03` branch. A couple of images is worth a thousand words (well, or at least a hundred).
> Adapt the draft of the menus to partitioner-ui-03

- src/lib/y2partitioner/widgets/blk_devices_table.rb
- src/lib/y2partitioner/widgets/overview_tab.rb
- src/lib/y2partitioner/widgets/pages/bcache.rb
- src/lib/y2partitioner/widgets/pages/bcaches.rb
- src/lib/y2partitioner/widgets/pages/disk.rb
- src/lib/y2partitioner/widgets/pages/disks.rb
- src/lib/y2partitioner/widgets/pages/lvm.rb
- src/lib/y2partitioner/widgets/pages/lvm_vg.rb
- src/lib/y2partitioner/widgets/pages/md_raid.rb
- src/lib/y2partitioner/widgets/pages/md_raids.rb
- src/lib/y2partitioner/widgets/pages/system.rb
Part of the dirty prototype at `partitioner-ui-03`: add nested tables.
This requires these other changes to work:
* https://github.com/libyui/libyui/pull/171
* https://github.com/libyui/libyui-qt/pull/132
* https://github.com/yast/yast-ycp-ui-bindings/pull/55
* https://github.com/yast/yast-yast2/pull/1099
> Nested tables

- src/lib/y2partitioner/widgets/columns/device.rb
Part of the dirty prototype at `partitioner-ui-03`: use basenames for nested devices.
> Use short names

- src/lib/y2partitioner/widgets/overview.rb
- src/lib/y2partitioner/widgets/pages/bcache.rb
- src/lib/y2partitioner/widgets/pages/bcaches.rb
- src/lib/y2partitioner/widgets/pages/btrfs.rb
- src/lib/y2partitioner/widgets/pages/devices_table.rb
- src/lib/y2partitioner/widgets/pages/disk.rb
- src/lib/y2partitioner/widgets/pages/lvm_vg.rb
- src/lib/y2partitioner/widgets/pages/md_raid.rb
- src/lib/y2partitioner/widgets/pages/nfs_mounts.rb
- src/lib/y2partitioner/widgets/pages/stray_blk_device.rb
- src/lib/y2partitioner/widgets/pages/system.rb
Part of the dirty prototype at `partitioner-ui-03`: remove titles from list pages and add nesting in used devices/physical volumes.
The "Used Devices" tab for Bcache is not using nesting because it is not clear how to do it. Right now, this tab is showing both: caching and backing device.
> Remove titles and add nesting in used devices

- src/lib/y2partitioner/ui_state.rb
- src/lib/y2partitioner/widgets/blk_device_edit_button.rb
- src/lib/y2partitioner/widgets/partition_add_button.rb
- test/y2partitioner/ui_state_test.rb
This is part of the on-going process to reorganize the Partitioner UI into the branch *partitioner-ui-02*.
This PR modifies `UIState` avoiding it to memorize the latest tab when we go back to a previous visited page. With new UI, the first tab will be always the default one. For example, a MD RAID will have two tabs: *Overview Device* and *Used Devices*. *Overview Device* will always be the landing tab when go to the page of a specific MD. The *Used Devices* tab will only be automatically open when we are managing the used devices.
> Partitioner: remove tab state

- src/lib/y2partitioner/widgets/menus/add.rb
- src/lib/y2partitioner/widgets/menus/device.rb
- src/lib/y2partitioner/widgets/menus/modify.rb
- test/y2partitioner/widgets/menus/add_test.rb
- test/y2partitioner/widgets/menus/examples.rb
- test/y2partitioner/widgets/menus/matchers.rb
- test/y2partitioner/widgets/menus/modify_test.rb
This is part of the on-going process to reorganize the Partitioner UI into the branch *partitioner-ui-02*.
This PR makes the *Device* and *Add* menus completely functional by calling the proper action for every item of the menus.
> Partitioner: add menu actions

- src/lib/y2partitioner/widgets/columns/type.rb
- src/lib/y2partitioner/widgets/menus/add.rb
- src/lib/y2partitioner/widgets/menus/device.rb
- src/lib/y2partitioner/widgets/menus/modify.rb
- test/y2partitioner/widgets/columns/type_test.rb
- test/y2partitioner/widgets/menus/modify_test.rb
This is part of the on-going process to reorganize the Partitioner UI into the branch *partitioner-ui-02*.
This PR:
* Avoids some rubocop complaints by using metaprogramming.
* Adds some missing actions to the *Device->Delete* menu. 
* Uses a better wording in the Type column for the Bcache caching and backing devices.
> Partitioner: improvements

- test/y2partitioner/widgets/main_menu_bar_test.rb
- test/y2partitioner/widgets/menus/examples.rb
- test/y2partitioner/widgets/menus/matchers.rb
- test/y2partitioner/widgets/menus/system_test.rb
- test/y2partitioner/widgets/menus/view_test.rb
This is part of the on-going process to reorganize the Partitioner UI into the branch `partitioner-ui-02`.
This PR adds some missing unit tests.
> Partitioner: tests for the menus System and View

- src/lib/y2partitioner/actions/add_lvm_vg.rb
- src/lib/y2partitioner/actions/add_md.rb
- src/lib/y2partitioner/actions/controllers/add_partition.rb
- src/lib/y2partitioner/actions/controllers/btrfs_devices.rb
- src/lib/y2partitioner/actions/controllers/lvm_lv.rb
- src/lib/y2partitioner/actions/controllers/lvm_vg.rb
- src/lib/y2partitioner/actions/controllers/md.rb
- src/lib/y2partitioner/ui_state.rb
- src/lib/y2partitioner/widgets/main_menu_bar.rb
- src/lib/y2partitioner/widgets/menus/add.rb
- src/lib/y2partitioner/widgets/menus/device.rb
- src/lib/y2partitioner/widgets/menus/modify.rb
- test/y2partitioner/actions/controllers/lvm_lv_test.rb
- test/y2partitioner/widgets/main_menu_bar_test.rb
- test/y2partitioner/widgets/menus/add_test.rb
- test/y2partitioner/widgets/menus/modify_test.rb
This is part of the on-going process to reorganize the Partitioner UI into the branch `partitioner-ui-02`.
The "Add" and "Device" menus act on the device currently selected in the table. But it was failing in several situations:
- With a completely empty devicegraph, no device is ever selected and the menu bar was always empty.
- When clicking in a section with no elements (eg. clicking "RAID") there is no selected device (empty table), so the menu still referenced to the selected device in the previous table.
- When the process of adding a new device was canceled, the temporary new device (that didn't exist anymore after cancelling) was considered as the current one. Producing a crash when any action was selected in the menu.
- When managing NFS, all the menu entries were always enabled. …
> More robust menus

- src/lib/y2partitioner/widgets/pages/md_raid.rb
- test/y2partitioner/widgets/pages/md_raid_test.rb
The page of a MD RAID is creating the Overview tab with a wrong pager, making it to fail when double-clicking over a device to open the popup with the description.
Part of: https://trello.com/c/NITXJRBE/2055-8-menu-driven-interface-finish-it.
Create the overview tab with the correct page.
* Adapted unit tests
> Fix md page

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/probe.rb
- src/lib/y2storage/storage_env.rb
- test/y2storage/callbacks/probe_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1177332
**This is the PR against SLE-15-SP1**
https://trello.com/c/rjFULQ97/
Some third-party storage software like the Veritas Volume Manager use a disk label (partitioning scheme) that we don't support in libstorage-ng and yast-storage-ng. In this particular case, they use a Sun disk label for disks below 2 TB, and GPT above that size.
When starting the YaST partitioner, libstorage-ng detects the unsupported disk label and reports it as an error. That error is displayed in an error pop-up dialog, and the user can choose to continue anyway (in which case that disk is treated as if it were empty, i.e. no partitions are shown).
In this particular case, the customer had 29 disks and found the sheer number of reported errors overwhelming. They wanted …
> L3 Veritas Volume Manager: Allow to Ignore Probe Errors

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/probe.rb
- src/lib/y2storage/storage_env.rb
- test/y2storage/callbacks/probe_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1177332
**This is the merges the original SLE-15-SP1 PR to SLE-15-SP2**
https://trello.com/c/rjFULQ97/
Some third-party storage software like the Veritas Volume Manager use a disk label (partitioning scheme) that we don't support in libstorage-ng and yast-storage-ng. In this particular case, they use a Sun disk label for disks below 2 TB, and GPT above that size.
When starting the YaST partitioner, libstorage-ng detects the unsupported disk label and reports it as an error. That error is displayed in an error pop-up dialog, and the user can choose to continue anyway (in which case that disk is treated as if it were empty, i.e. no partitions are shown).
In this particular case, the customer had 29 disks and found the sheer number of reported errors …
> L3 Veritas Volume Manager: Allow to Ignore Probe Errors (SLE-15-SP2)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/probe.rb
- src/lib/y2storage/storage_env.rb
- test/y2storage/callbacks/probe_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1177332
**This merges the original SLE-15-SP1 PR via the SLE-15-SP2 branch to master**
https://trello.com/c/rjFULQ97/
Some third-party storage software like the Veritas Volume Manager use a disk label (partitioning scheme) that we don't support in libstorage-ng and yast-storage-ng. In this particular case, they use a Sun disk label for disks below 2 TB, and GPT above that size.
When starting the YaST partitioner, libstorage-ng detects the unsupported disk label and reports it as an error. That error is displayed in an error pop-up dialog, and the user can choose to continue anyway (in which case that disk is treated as if it were empty, i.e. no partitions are shown).
In this particular case, the customer had 29 disks and found the sheer number of …
> L3 Veritas Volume Manager: Allow to Ignore Probe Errors (master)

- package/yast2-storage-ng.changes
#1157 is failing in Jenkins because `jsd#XXX` is not recognized as a reference to Jira anymore.
Use `jsc#XXXX` instead.
> Fix Jira references in changelog

- doc/boot-requirements.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_strategies/uefi.rb
- src/lib/y2storage/volume_specification_builder.rb
- test/data/devicegraphs/output/raspi_empty.yml
- test/data/devicegraphs/output/raspi_firmware.yml
- test/support/proposed_partitions_examples.rb
- test/y2storage/volume_specification_builder_test.rb
The installer was proposing a `/boot/efi` partition in which both the size and FAT size were subject to improvement.
First of all, we were proposing a partition with a size between 256MiB and 500MiB. The reason for such minimum was that in Advanced Format 4K Native drives (4-KB-per-sector), a FAT32 file-system cannot work properly on smaller partitions.
But we were not enforcing the FAT size to 32. We were delegating the decision of the FAT size to `mkfs.vfat`. Turns out that, for whatever reason, that tool only uses FAT32 for partitions equal or bigger than 512MiB... which we were never creating by default.
As a result, our `/boot/efi` partition was always FAT16. The EFI standard recommends FAT32 when possible.
On the other hand, some people claim that 256 MiB is too big as a minimum …
> Revisit the size and format of the proposed /boot/efi

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/menus/modify.rb
https://trello.com/c/MRJhR5x6/2080-1-partitioner-disable-menu-entries-from-device-and-add-when-an-nfs-device-is-selected
The NFS page in the partitioner is really only an embedded version of the NFS client module. It does not fit into the scheme of thinge in the partitioner, in particular not how menus and menu actions work. That NFS client module/page uses its own buttons; it really only pretends to be a part of the partitioner.
Disable menu actions that won't with NFS.
On the NFS page, all menu items that would cause trouble are already disabled.
That leaves the "All Devices" page where some actions in the "Device" menu were still enabled:
- Edit
- Show Details
- Delete
This PR disables them.
The user has to go to the NFS page to perform those actions via buttons in the embedded NFS …
> Disable "Device" Menu Items for NFS Shares

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/btrfs_subvolume.rb
- src/lib/y2partitioner/dialogs/import_mount_points.rb
- src/lib/y2partitioner/widgets/fstab_selector.rb
- test/spec_helper.rb
- https://trello.com/c/GZXM36ty
- https://bugzilla.suse.com/show_bug.cgi?id=1130822
A `textdomain` declaration is per *class* which means there were several cases of having several classes in a file and only one of them declaring the text domain.
Also added detecting a missing textdomain during unit testing (using https://github.com/yast/yast-ruby-bindings/pull/230/).
> Add `textdomain` to fix untranslated error messages

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_prepdisk.rb
- test/y2storage/clients/inst_prepdisk_test.rb
https://trello.com/c/fhCSVHzi/2149-2-tw-1174029-yast2-depends-on-efi-vars
https://bugzilla.suse.com/show_bug.cgi?id=1174029
When we are done creating parititons and filesystems during installation, we mount system mounts such as `/dev`, `/proc`, `/sys`, `/run` to the newly created target system so it can later be used correctly in a `chroot` environment.
On EFI systems, that also includes the EFI variables in `/sys/firmware/efi/efivars` (a separate filesystem / kernel table).
On some platforms (arm64) that is only half-implemented, however: They do use EFI, but there is no support (yet) for the special _efivarfs_ filesystem that is used to read and write EFI variables directly via that system mount.
So attempting to mount that  `/sys/firmware/efi/efivars` filesystem fails, an exception is …
> Improved Error Handling for Mounting efivars

- src/lib/y2partitioner/actions/controllers/btrfs_subvolume.rb
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/dialogs/btrfs_subvolume.rb
- src/lib/y2partitioner/widgets/btrfs_filesystems_table.rb
- src/lib/y2partitioner/widgets/btrfs_options.rb
- src/lib/y2partitioner/widgets/btrfs_quota.rb
- src/lib/y2partitioner/widgets/columns.rb
- src/lib/y2partitioner/widgets/columns/btrfs_exclusive.rb
- src/lib/y2partitioner/widgets/columns/btrfs_referenced.rb
- src/lib/y2partitioner/widgets/columns/btrfs_rfer_limit.rb
- src/lib/y2partitioner/widgets/columns/disk_size.rb
- src/lib/y2partitioner/widgets/columns/size.rb
- src/lib/y2partitioner/widgets/format_and_mount.rb
- src/lib/y2partitioner/widgets/help.rb
- src/lib/y2storage/btrfs_subvolume.rb
- test/y2partitioner/actions/controllers/btrfs_subvolume_test.rb
- test/y2partitioner/actions/controllers/filesystem_test.rb
- test/y2partitioner/dialogs/btrfs_subvolume_test.rb
- test/y2partitioner/widgets/btrfs_filesystems_table_test.rb
- test/y2partitioner/widgets/btrfs_options_test.rb
- test/y2partitioner/widgets/btrfs_quota_test.rb
- test/y2partitioner/widgets/columns/btrfs_exclusive_test.rb
- test/y2partitioner/widgets/columns/btrfs_referenced_test.rb
- test/y2partitioner/widgets/columns/btrfs_rfer_limit_test.rb
- test/y2partitioner/widgets/columns/size_test.rb
We want to add support for Btrfs quotas to the Partitioner. See [Jira entry SLE-7742](https://jira.suse.com/browse/SLE-7742)
This is the second part of https://trello.com/c/Ypt6X2VA/2118-3-partitioner-support-for-btrfs-quotas (the first part was #1163).
- In the form to edit a Btrfs file system (not to be confused with the form to edit a block device), a new "Enable Subvolumes Quota" is added. <details><summary>Click here to see two screenshots about it</summary>![quota1](https://user-images.githubusercontent.com/3638289/99694671-f8a0ae00-2a8c-11eb-9ca2-c27e5c0779ef.png)
</details>
- In the form to edit a Btrfs subvolume, a "Limit Size" widget is added. <details><summary>Click here to see two screenshots about it</summary>![quota3](https://user-images.githubusercontent.com/3638289/99694682 …
> Add Btrfs quotas to the Partitioner UI

- src/lib/y2partitioner/actions/controllers/btrfs_subvolume.rb
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/dialogs/btrfs_subvolume.rb
- src/lib/y2partitioner/widgets/device_table_entry.rb
- src/lib/y2storage/btrfs_subvolume.rb
- src/lib/y2storage/filesystems/btrfs.rb
- src/lib/y2storage/planned/can_be_formatted.rb
- src/lib/y2storage/shadower.rb
- test/y2partitioner/actions/controllers/btrfs_subvolume_test.rb
- test/y2partitioner/actions/delete_btrfs_subvolume_test.rb
- test/y2partitioner/dialogs/btrfs_subvolume_test.rb
- test/y2partitioner/widgets/device_table_entry_test.rb
- test/y2storage/btrfs_subvolume_test.rb
- test/y2storage/filesystems/btrfs_test.rb
- test/y2storage/shadower_test.rb
This is a follow-up of https://github.com/yast/yast-storage-ng/pull/1160.
In SLE and openSUSE, a "@" Btrfs subvolume is used as kind of prefix for the rest of subvolumes in the root file system. All subvolumes proposed in the control file should be created as children of "@". Moreover, the path of all the subvolumes should start with "@/", for example:
~~~
top level
|-- @
|-- @/home
|-- @/var
|-- @/.snapshots
|-- @/.snapshots/1/snapshot
|-- @/.snapshots/2/snapshot
~~~
This was designed so to make the snapshots rollback easier, see https://www.spinics.net/lists/linux-btrfs/msg44611.html (although having a prefix is not necessary at all. What really eases to rollback snapshots is the fact of having different subvolumes for root, home, etc).
The Expert Partitioner should be able to recognize …
> Fix subvolumes prefix

- src/lib/y2partitioner/actions/add_tmpfs.rb
- src/lib/y2partitioner/actions/edit_tmpfs.rb
- src/lib/y2partitioner/dialogs/tmpfs.rb
- src/lib/y2partitioner/widgets/fstab_options.rb
- src/lib/y2partitioner/widgets/menus/add.rb
- src/lib/y2partitioner/widgets/menus/modify.rb
- src/lib/y2partitioner/widgets/tmpfs_buttons.rb
- src/lib/y2partitioner/widgets/tmpfs_options.rb
- src/lib/y2storage/filesystems/base.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- test/y2partitioner/actions/add_tmpfs_test.rb
- test/y2partitioner/actions/edit_tmpfs_test.rb
- test/y2partitioner/dialogs/tmpfs_test.rb
- test/y2partitioner/widgets/fstab_options_test.rb
- test/y2partitioner/widgets/menus/add_test.rb
- test/y2partitioner/widgets/menus/modify_test.rb
- test/y2partitioner/widgets/tmpfs_buttons_test.rb
- test/y2partitioner/widgets/tmpfs_options_test.rb
This replaces #1176 
In SLE 12 (with old yast2-storage) AutoYaST was able to import/export tmpfs file systems. Moreover, the Expert Partitioner included a section for the tmpfs file systems. Both features are missing in SLE 15.
- https://jira.suse.com/browse/SLE-16313
- PBI: https://trello.com/c/JRECcir9/2134-5-tmpfs-in-the-partitioner-and-autoyast
As a follow-up to #1179, this pull request adds the possibility to create tmp filesystem and to edit the existing ones.
See screenshots below.
- Added unit tests.
- Tested manually with the `partitioner_testing` client.
> Partitioner: actions to add and edit tmpfs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/y2partitioner/widgets/overview_test.rb
OBS build is failing after including these changes https://github.com/yast/yast-storage-ng/pull/1182, see https://build.opensuse.org/request/show/852869.
Some unit tests were properly adapted.
> Fix unit tests

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/quit_partitioner.rb
- src/lib/y2partitioner/device_graphs.rb
- src/lib/y2partitioner/dialogs/main.rb
- test/y2partitioner/actions/quit_partitioner_test.rb
- test/y2partitioner/device_graphs_test.rb
- test/y2partitioner/dialogs/main_test.rb
- test/y2partitioner/dialogs/summary_test.rb
In some cases, the Expert Partitioner is showing the "Summary" step even though nothing was modified.
* https://bugzilla.suse.com/show_bug.cgi?id=1179829
There was a problem with the condition to decide whether to show the "Summary". The idea was to show the Summary only if any device was edited. To decide that, a devicegraph comparison was used (`initial != current`). But such comparison takes into account the userdata. So, two devicegraphs with the same devices but different user data would be different.
Because that, when a devicegrah has Btrfs subvolumes, the userdata of Btrfs is filled in the *current* devicegraph to save its `subvolumes_prefix`. This was making *current* to be different to *initial*.
Now on, the Summary is shown only if there is any action to perform during the …
> Partitioner: only show summary when needed

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/overview.rb
- src/lib/y2partitioner/widgets/summary_text.rb
- src/lib/y2storage/actiongraph.rb
- src/lib/y2storage/clients/inst_disk_proposal.rb
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/package_handler.rb
- test/y2partitioner/widgets/overview_test.rb
- test/y2storage/actiongraph_test.rb
- test/y2storage/devicegraph_test.rb
Sometimes yast2-storage-ng decides that some packages need to be installed. But there was room for improvement at least in two situations:
- [bsc#1065588](https://bugzilla.suse.com/show_bug.cgi?id=1065588): During installation, all potentially needed packages were added to the software proposal as mandatory ones, which implies the users cannot install the system if they decide to deselect the packages for installation at a later point (ie. in the "Software" section of the installation summary).
- [bsc#1168077](https://bugzilla.suse.com/show_bug.cgi?id=1168077): In an already installed system, the Partitioner calculated the packages to install based on the content of the system after performing all the changes, instead of calculating that based on the actions the Partitioner was going to …
> Improve installation of packages

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/devicegraph.rb
- test/y2storage/devicegraph_test.rb
The problem described on [bsc#1179590](https://bugzilla.suse.com/show_bug.cgi?id=1179590) was caused because deleting a Btrfs subvolume in the devicegraph was not triggering the corresponding deletion of its qgroups.
That was fixed in libstorage-ng by adding the qgroups to the REMOVE view. See https://github.com/openSUSE/libstorage-ng/pull/787
But that didn't fix the problem in all possible situations because `Devicegraph#remove_with_dependants` was not honoring the REMOVE view.
This PR fixes `remove_with_dependants` to use the REMOVE view when descending the hierarchy.
Now that libstorage-ng has the concept of the REMOVE view, maybe we can get rid of `#remove_with_dependants` if we move some of its logic (eg. the fact that deleting a VG should invalidate all its PVs) to that view, …
> Use the REMOVE view in remove_with_dependants

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- test/y2storage/proposal/autoinst_disk_device_planner_test.rb
If `<quotas>` element is set to `false`, AutoYaST disables the quotas no matter whether the `referenced_limit` is specified for some subvolume.
Related to #1186.
> AutoYaST: disable quotas when <quotas> is set to false

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/planned/can_be_formatted.rb
- test/y2storage/guided_proposal_test.rb
As requested in [jsc#SLE-17081](https://jira.suse.com/browse/SLE-17081), it would be desirable that YaST bootloader sets the `resume=` kernel parameter following a similar convention to the one followed to reference devices in `/etc/fstab`. Very often, that convention is using the UUID of the swap device. 
The truth is that YaST bootloader already tries to honor that convention but, in many situation it simply cannot do it because the swap devices are not yet created at the point in time in which the YaST Bootloader proposal calculates the value of the `resume=` parameter. That means the UUID is still unknown. As a result, the proposal falls back to using another method other than the UUID to reference the swap device.
This has also been reported as …
> Pre-generate uuid for swap (jsc#SLE-17081)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/btrfs_subvolume.rb
- src/lib/y2partitioner/dialogs/btrfs_subvolume.rb
- test/y2partitioner/actions/controllers/btrfs_subvolume_test.rb
- test/y2partitioner/actions/edit_btrfs_subvolume_test.rb
- test/y2partitioner/dialogs/btrfs_subvolume_test.rb
The YaST Partitioner didn't allow the users to modify the path of those subvolumes that already existed on the disk.
But it allowed to modify the path of those subvolumes that existed only in the devicegraph so far. In order to make that possible, the corresponding subvolume was deleted from the devicegraph and re-created.
That had undesired effects, like causing the removal of all the children subvolumes every time a subvolume was modified (even if the path was not altered). That's described in [bsc#1180182](https://bugzilla.suse.com/show_bug.cgi?id=1180182) (which is a spin-off of [bsc#1179590](https://bugzilla.suse.com/show_bug.cgi?id=1179590)).
Simply, do not allow to modify the path of a subvolume that already exists in the devicegraph. libstorage-ng doesn't offer a safe way of doing …
> Partitioner: do not allow to modify the path of Btrfs subvolumes (bsc#1180182)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/filesystems/mount_by_type.rb
- src/lib/y2storage/luks.rb
- src/lib/y2storage/md.rb
- src/lib/y2storage/mount_point.rb
- src/lib/y2storage/mountable.rb
- test/y2storage/blk_device_test.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
- test/y2storage/mount_point_test.rb
See [SLE-17081](https://jira.suse.com/browse/SLE-17081) (which is a follow-up of [bsc#1177926](https://bugzilla.suse.com/show_bug.cgi?id=1177926) and closely related to [bsc#1169874](https://bugzilla.suse.com/show_bug.cgi?id=1169874)).
Ideally, all components of the installer should use the same identification method (`uuid` vs `by-id` vs `by-path` vs...) to reference storage devices in different parts of the system like the bootloader parameters or the `/etc/fstab` file. But the bootloader setup (mostly `resume=` parameter) is not following the same identification method used for configuring the storage setup (mostly `fstab`).
That happens because the logic from yast2-storage-ng to determine which is the most convenient and stable device name is somehow duplicated in yast2-bootloader. …
> Add `#preferred_name` to BlkDevice and BlkFilesystem

- doc/boot-partition.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_strategies/base.rb
- src/lib/y2storage/boot_requirements_strategies/uefi.rb
- test/y2storage/boot_requirements_errors_test.rb
- test/y2storage/reusing_efi_test.rb
The automatic partitioning proposal never creates an EFI system partition (ESP) that is smaller than a certain size (128 MiB) at the time of writing. That's fine so far.
But there are two other situations in which the same minimal size is applied and that's causing problems to some users:
- When the automatic partitioning proposal is deciding whether a pre-existing ESP should be reused instead of proposing a brand new one.
- If the Expert Partitioner was used to create a custom ESP.
So the min size is ok for brand new EFI partitions suggested by the installer, but it should not be used to discard partitions in other scenarios.
See the detailed discussion here: #1194. 
See also (restricted access): https://trello.com/c/eAdUReCf/2236-2-do-not-use-the-efi-minimal-size-to-discard-partitions …
> Do not use the ESP minimal size to discard partitions

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/add_btrfs_subvolume.rb
- src/lib/y2partitioner/actions/controllers/btrfs_subvolume.rb
- test/y2partitioner/actions/controllers/btrfs_subvolume_test.rb
When creating a new subvolume and the "Size Limit" checkbox is marked, the subvolume is created without the indicated limit.
* https://bugzilla.suse.com/show_bug.cgi?id=1181205
Fix controller to take into account the limit option.
* Added new unit tests
* Tested manually with *partitioner_testing* client
> Partitioner: Fix subvolume dialog

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/pages/disk.rb
- test/y2partitioner/widgets/pages/disk_test.rb
In the Expert Partitioner, when going to the "Used Devices" tab of a MD BIOS RAID, the list does not contain the devices used by the MD.
* https://bugzilla.suse.com/show_bug.cgi?id=1181300
The devices used by the MD are included in the list of used devices. 
* Added a new unit test.
* Tested manually with the *partitioner_testing* client.
> Partitioner: Fix used devices tab

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/drive_section.rb
- test/y2storage/autoinst_profile/drive_section_test.rb
There are several situations in the AutoYaST profile in which the `<partition>` subsection within a given `<drive>` section does not really represent a partition, but it contains general information about the drive itself. For example, when the drive contains a disklabel set to the value "none" or when the drive represents an NFS or btrfs filesystem.
In those cases, the corresponding entry in the left tree of the AutoYaST UI should read "Partition (Drive)" instead of just "Partition". That was happening for drives with the disklabel "none", but not for drives of type `CT_NFS` or `CT_BTRFS`.
Fixed the method used to get the so-called "master" partition section (that is, the partition section that actually is meant to describe the whole drive). Now the tree looks as expected.
Tested …
> AutoYaST UI: improved visualization of some partition sections

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/bcache.rb
- src/lib/y2partitioner/actions/controllers/btrfs_devices.rb
- test/y2partitioner/actions/controllers/bcache_test.rb
- test/y2partitioner/actions/controllers/btrfs_devices_test.rb
https://bugzilla.suse.com/show_bug.cgi?id=1170044
Some special kinds of LVM logical volumes (thin pools and cache pools) cannot be used as base for a bcache (nor backing or caching device) or for a Btrfs filesystem, because those logical volumes are not block devices.
But the Partitioner was not making any distinction, so they were offered in the UI just like any other logical volume. Of course, that leaded to problems at a later point if the user selected any of them to be part of any bcache or btrfs.
In both cases, check the `Storage::BlkDevice#usable_as_blk_device?` method offered by libstorage-ng to distinguish those devices that, despite being represented as an instance of `BlkDevice`, are not really block devices in the full sense.
Added new unit tests
> Partitioner: do not offer LVM pools for bcache and btrfs (bsc#1170044)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/blk_devices_table.rb
- src/lib/y2partitioner/widgets/btrfs_filesystems_table.rb
- src/lib/y2partitioner/widgets/configurable_blk_devices_table.rb
- src/lib/y2storage/btrfs_subvolume.rb
- test/y2partitioner/actions/controllers/encryption_test.rb
- test/y2partitioner/widgets/btrfs_filesystems_table_test.rb
- test/y2partitioner/widgets/configurable_blk_devices_table_test.rb
- test/y2partitioner/widgets/encrypt_method_options_test.rb
- test/y2partitioner/widgets/encrypt_password_test.rb
- test/y2storage/blk_device_test.rb
- test/y2storage/boot_requirements_strategies/analyzer_test.rb
- test/y2storage/boot_requirements_strategies/zipl_test.rb
- test/y2storage/clients/partitions_proposal_test.rb
- test/y2storage/package_handler_test.rb
To avoid the situation in which a filesystem with many subvolumes (specially snapshots) hides other devices (eg. subsequent disks), we decided to display some branches of all tables of devices collapsed by default. But the original criteria to decide whether a given branch should be initially opened or closed was pretty simplistic - just collapsing branches with more than 10 elements. That turned to be inconvenient in many cases like the one reported at [bsc#1181464](https://bugzilla.suse.com/show_bug.cgi?id=1181464): a single disk with many partitions... in which all the interesting information (the list of partitions) is hidden by default.
By default, only collapse branches that contain Btrfs snapshots. Except for the tables in the Btrfs section of the Partitioner, in which everything …
> Partitioner: only collapse by default Btrfs with snapshots

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/configurable_blk_devices_table.rb
- src/lib/y2partitioner/widgets/main_menu_bar.rb
- src/lib/y2partitioner/widgets/overview.rb
- test/y2partitioner/widgets/configurable_blk_devices_table_test.rb
- test/y2partitioner/widgets/main_menu_bar_test.rb
As explained [in this ML thread](https://lists.opensuse.org/archives/list/yast-devel@lists.opensuse.org/thread/X6OWMUXFWUPKA4R6EB33AIXJDH23R362/), the new interface of the Partitioner ([summarized here](https://github.com/yast/yast-storage-ng/pull/1157)) is causing confusion in some of our traditional users.
After discarding the implementation of a more advanced help dialog that could provide a more guided experience (see [this other ML thread](https://lists.opensuse.org/archives/list/yast-devel@lists.opensuse.org/thread/B6VANW7DAYBZ6ZIYX5HOW3LHYZK2EE4G/)), I tried to just extend the current help texts.
The goal is to provide enough details to make the new menu-driven approach obvious without going too much into details so the information still fits in a regular help pop-up with no …
> Partitioner: improved help

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/disk.rb
- src/lib/y2storage/encryption.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/lvm_lv.rb
- src/lib/y2storage/multi_disk_device.rb
- src/lib/y2storage/partition.rb
- test/y2storage/encryption_test.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
- test/y2storage/mount_point_test.rb
See [bsc#1176140](https://bugzilla.suse.com/show_bug.cgi?id=1176140).
YaST adds `_netdev` to the default mount options of all file systems that are placed on network-based disks.
Turns out that adding `_netdev` when not really needed is counterproductive and can cause ordering cycles in the systemd units. That's something that would need a more general solution, likely implemented in the systemd side.
On the other hand, YaST considers that all iSCSI and FCoE disks are network-based and, thus, their mount points could need the `_netdev` option. But turns out that is not true, many iSCSI and FCoE drivers can actually initialize the disks and make the corresponding block device available to the operating system before the network is fully configured.
Do not blindly trust the data transport …
> Use the driver to decide whether _netdev is needed

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/fstab_options.rb
- test/y2partitioner/widgets/fstab_options_test.rb
In the Expert Partitioner, when editing the fstab options of a file system, the text field to give a label is not shown.
https://bugzilla.suse.com/show_bug.cgi?id=1183220
Fix bug in method that checks whether a file system supports a label.
* Added new unit tests
* Tested manually with *partitioner_testing* client.
> Partitioner: allow to define the filesystem label

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/confirm_recursive_delete.rb
The _recursive deletion_ confirm dialog includes a question mark icon it its heading which
* is vertically cut-off, and
* **should not be there** (_ALL icons in dialogues should have been removed a long time ago_, https://bugzilla.suse.com/show_bug.cgi?id=1182497#c8)
- https://bugzilla.suse.com/show_bug.cgi?id=1183088
Drop it.
| Before | After |
|-|-|
| ![dialog_using_the_question_mark_icon](https://user-images.githubusercontent.com/1691872/110716467-260d9500-81ff-11eb-9ab7-ffc69a8f2fca.png) | ![dialog_not_using_the_question_mark_icon](https://user-images.githubusercontent.com/1691872/110716508-3887ce80-81ff-11eb-98c9-a215becf57c1.png) |
> Remove question mark icon

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/lvm_lv.rb
- src/lib/y2partitioner/actions/controllers/lvm_vg.rb
- src/lib/y2partitioner/dialogs/blk_device_resize.rb
- src/lib/y2partitioner/dialogs/lvm_lv_size.rb
- src/lib/y2partitioner/widgets/lvm_vg_devices_selector.rb
- src/lib/y2storage/callbacks/check.rb
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/lvm_lv.rb
- src/lib/y2storage/lvm_pv.rb
- src/lib/y2storage/lvm_vg.rb
- src/lib/y2storage/proposal/lvm_creator.rb
- src/lib/y2storage/storage_manager.rb
- test/data/devicegraphs/lvm_several_pvs.yml
- test/y2partitioner/actions/controllers/lvm_lv_test.rb
- test/y2partitioner/actions/controllers/lvm_vg_test.rb
- test/y2partitioner/dialogs/blk_device_resize_test.rb
- test/y2partitioner/dialogs/lvm_lv_size_test.rb
- test/y2partitioner/widgets/lvm_vg_devices_selector_test.rb
- test/y2storage/callbacks/check_test.rb
- test/y2storage/devicegraph_test.rb
- test/y2storage/lvm_lv_test.rb
- test/y2storage/lvm_vg_test.rb
- test/y2storage/proposal/lvm_creator_test.rb
- test/y2storage/storage_manager_test.rb
When a striped logical volume is going to be created, its size should be multiple of the physical extend size. Moreover, its resulting number of physical extents should be multiple of the number of stripes. Otherwise, *lvcreate* command will round the number of extents of the new logical volume up to make it multiple of the number of stripes. This could lead to a number of extents that exceeds the number of free extents from the volume group. 
* https://bugzilla.suse.com/show_bug.cgi?id=1180723
Now on, the size of the new striped volume is rounded-down to make the number of extents multiple of the number of stripes. This is done by the Expert Partitioner and also by the storage proposal when a new logical volume is created . Note that the size of the logical volume is also rounded when …
> Improve LVM striped volumes support

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/lvm_lv_size.rb
- src/lib/y2partitioner/widgets/lvm_vg_devices_selector.rb
After merging https://github.com/yast/yast-storage-ng/pull/1212, unit tests started failing in IBS for SLE-15-SP3, but it worked fine in OBS for Factory. The error was produced because a private method is called over *self*, which raises an exception with ruby < 2.7, see:
* https://bugs.ruby-lang.org/issues/16123
*  https://bugs.ruby-lang.org/issues/11297
* https://blog.saeloun.com/2019/12/24/ruby-2-7-allows-calling-a-private-method-with-self.html
Avoid direct calls of private methods over *self* to make it work in both: SLE-15-SP3 (ruby 2.5) and TW.
> Avoid error when using self

- Rakefile
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/bin/mask-systemd-units
- src/lib/bidi_markup.rb
- src/lib/y2partitioner/bidi.rb
- src/lib/y2partitioner/widgets/columns/base.rb
- src/lib/y2partitioner/widgets/columns/device.rb
- src/lib/y2partitioner/widgets/columns/mount_point.rb
- src/lib/y2partitioner/widgets/tabs.rb
- src/lib/y2partitioner/yard_links.rb
- test/data/devicegraphs/bidi.yml
- test/y2partitioner/test_helper.rb
- test/y2partitioner/widgets/columns/device_test.rb
- test/y2partitioner/widgets/columns/mount_point_test.rb
In Arabic, the device table displays `/dev/sda1` as `dev/sda1/`
- https://bugzilla.suse.com/show_bug.cgi?id=1128091
Use [Unicode BiDi formatting characters](https://www.unicode.org/reports/tr9/#Directional_Formatting_Codes) in the source (creating a machine "translation" of the string).
Disabled for TUI: libyui-ncurses does not handle the BiDi characters well, truncating the strings. TUI does not have the general RTL direction anyway.
If you start off with a JEOS and only install the bare minimum of packages needed to test this, you may end up seeing dotted box characters in place of the BiDi controls. Installing *noto-sans-fonts.rpm* helps.
<table>
<tr><td>before</td><td>after</td></tr>
<tr><td>
</td><td>
</td>
</tr></table>
> Display pathnames correctly in a Right-to-Left context (bsc#1128091)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/menus/modify.rb
In the Partitioner, the **'Change Used Devices'** menu item is not translatable.
- https://bugzilla.suse.com/show_bug.cgi?id=1185060
- https://trello.com/c/s7kg1VMD/2471-1-sle15-sp3-1185060-untranslated-text-change-used-devices-in-device-menu-in-partitioner
Make it translatable.
> Make  'Change Used Devices' menu item translatable (bsc#1185060)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/filesystems/blk_filesystem.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1186268
- https://trello.com/c/gNgBB1Qh
When looking up device names from fstab, check against all possible variants (udev symlinks).
> try harder matching device names (bsc#1186268)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/can_be_formatted.rb
- test/y2storage/planned/can_be_formatted_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1186298
- https://trello.com/c/I08exOoV
If a filesystem is both marked as read-only and explicitly includes `ro` in its fstab option list, it should not end up with `ro` twice in its fstab entry.
De-duplicate fstab options.
Receive counts in `include` seem to be a rather recent rspec feature (3.10, it seems); so replacing `include().once` with something weird to make the tests work in travis.
> ensure mount options are not doubled (bsc#1186298)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/desktop/org.opensuse.yast.Disk.desktop
Related to [bsc#1187270](https://bugzilla.opensuse.org/show_bug.cgi?id=1187270).
See [the original issue](https://github.com/yast/yast-users/pull/303) in the yast2-users module.
> bsc#1187270: fix control center tooltip

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/desktop/org.opensuse.yast.Disk.desktop
Related to [bsc#1187270](https://bugzilla.opensuse.org/show_bug.cgi?id=1187270).
See #1224 (SLE-15-SP2) and [the original issue](https://github.com/yast/yast-users/pull/303) in the yast2-users module.
> bsc#1187270: fix control center tooltip (SLE-15-SP3)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/desktop/org.opensuse.yast.Disk.desktop
Related to [bsc#1187270](https://bugzilla.opensuse.org/show_bug.cgi?id=1187270).
See #1225 (SLE-15-SP2) and [the original issue](https://github.com/yast/yast-users/pull/303) in the yast2-users module.
> bsc#1187270: fix control center tooltip (master)

- test/y2storage/planned/can_be_formatted_test.rb
The unit tests are failing with the version of RSpec currently available in SLE-15-SP4.
The test was introduced (in a way that was actually compatible with old versions of RSpec) in #1222, which was a pull request against the SLE-15-SP3 branch. But when merging that into the master branch (#1223), an extra commit 62f3f49b2d85 was introduced to use the most modern syntax introduced in RSpec 3.10.
Now that we are submitting the master branch of the repository to the SP4 project in the build system (which includes RSpec 3.7), that modern syntax turns to be a problem.
Reverted commit 62f3f49b2d85 so the more compatible test is used again. Now the test looks the same in SLE-15-SP3 and in master.
> Improve RSpec compatibility

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/device_finder.rb
- src/lib/y2storage/disk_analyzer.rb
- test/y2storage/disk_analyzer_test.rb
The storage proposal looks for the devices that can be used for the installation (a.k.a. *candidate disks*). A device is considered a *candidate disk* if it fulfills some conditions. For example, the devices containing a repository  for the installation are discarded as *candidate disks*. The URI of the installation repositories (e.g., *hd:/?device=/dev/disk/by-id/mmc-EB1QT_0xd948672b-part2*) are analyzed to determine whether a device contains a repository. The devices indicated in the URI are not used as *candidate disks*. 
The URI of the repository can point to a device by the kernel name or by one of the udev symlinks. In the last case, the device could not be found if *libstorage-ng* does not provide that udev name (note that *libstorage-ng* filters some udev names). As result, the …
> Improve detection of candidate disks

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
The menu option "View --> Device Graphs" is not shown if *libyui-qt-graph* package is not installed. yast2-storage-ng should recommend such a package. 
* https://bugzilla.suse.com/show_bug.cgi?id=1191109 
Recommends to install *libyui-qt-graph*, but only if *libyui-qt* is already installed.
* See https://documentation.suse.com/sbp/all/single-html/SBP-RPM-Packaging/index.html#sec-weak-dependencies
> Recommends libyui-qt-graph

- package/yast2-storage-ng.changes
- src/lib/y2storage/dialogs/guided_setup/helpers/disk.rb
- src/lib/y2storage/disk.rb
- src/lib/y2storage/disk_device.rb
- src/lib/y2storage/guided_proposal.rb
- test/support/guided_setup_context.rb
- test/y2storage/dialogs/guided_setup/helpers/disk_test.rb
Commit 41d4ae7a98824290b5 introduced a check to know whether a disk is an SD/MMC card. But it did it as part of the method `#types_for_is`. That implies such circumstance is checked too often. Not only when the caller wants to know whether the disk is an SD card... but basically every time the nature of the device is checked with any purpose.
The information about the disk being an SD card or not is not present in the devicegraph, it needs an extra check with hwinfo. During normal operation, the result of the calls to hwinfo are cached, so it doesn't have a big impact. But in the testsuite, where nothing is cached, the impact is huge. It multiplies x5 the execution time of the testsuite.
Move the check to a separate method, so the hwinfo call is only executed when the caller really wants …
> Move the check for SD cards to a separate method

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_vg_planner.rb
- src/lib/y2storage/proposal/lvm_creator.rb
- test/y2storage/proposal/autoinst_vg_planner_test.rb
- test/y2storage/proposal/lvm_creator_test.rb
AutoYaST ignores the `pesize` element.
- [bsc#1192124](https://bugzilla.suse.com/show_bug.cgi?id=1192124)
Initialize the `extent_size` according to the `pesize` when planning the LVM volume group.
- *Tested manually* (in process)
> bsc#1192124: AutoYaST does not honor the `pesize` element

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_vg_planner.rb
- src/lib/y2storage/proposal/lvm_creator.rb
- test/y2storage/proposal/autoinst_vg_planner_test.rb
- test/y2storage/proposal/lvm_creator_test.rb
This PR merges #1242 into `SLE-15-SP3`.
AutoYaST ignores the `pesize` element.
- [bsc#1192124](https://bugzilla.suse.com/show_bug.cgi?id=1192124)
Initialize the `extent_size` according to the `pesize` when planning the LVM volume group.
> bsc#1192124: AutoYaST does not honor the pesize element

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/autoinst_vg_planner.rb
- src/lib/y2storage/proposal/lvm_creator.rb
- test/y2storage/proposal/autoinst_vg_planner_test.rb
- test/y2storage/proposal/lvm_creator_test.rb
This PR merges #1243 into `master`.
AutoYaST ignores the `pesize` element.
- [bsc#1192124](https://bugzilla.suse.com/show_bug.cgi?id=1192124)
Initialize the `extent_size` according to the `pesize` when planning the LVM volume group.
>  bsc#1192124: AutoYaST does not honor the pesize element

- src/lib/y2storage/dialogs/proposal.rb
The Ruby gettext crashes when the comments are *inside* the n_() call, calling `rake pot` failed with this error:
```
/usr/lib64/ruby/gems/2.5.0/gems/gettext-3.2.5/lib/gettext/po_entry.rb:305:in `format':
This POEntry is a kind of plural but the msgid_plural property is nil. msgid:
<p>The device %s is a Dell BOSS drive.</p> (GetText::POEntry::NoMsgidPluralError)
```
Move the comments outside the `n_()` call.
The `rake pot` now does not crash and the generated `storage.pot` file contains
the text also with the comment:
```
#. TRANSLATORS: %s is a linux device name (eg. /dev/sda) (singular),
#. or a list of comma-separated device names (eg. "/dev/sda, /dev/sdb") (plural)
#: src/lib/y2storage/dialogs/proposal.rb:150
#, c-format
msgid "<p>The device %s is a Dell BOSS drive.</p>"
msgid_plural …
```
> Fixed plural string comments

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/libstorage_callback.rb
- test/y2storage/callbacks/callbacks_examples.rb
The installer has lost a specific error message when the same LVM **P**hysical **V**olume is found in several devices, which might means there are multipath devices in the system but multipath support is disabled. See screenshots below:
| SLE-15-GA | SLE-15-SP1 | openSUE TW |
| - | - | - |
| ![sle-15-ga-lvm-failed](https://user-images.githubusercontent.com/1691872/142013862-244695d6-0c6e-4938-a915-a16eedba177a.png) | ![sle-15-sp1-lvm-failed](https://user-images.githubusercontent.com/1691872/142013901-9476ab05-c047-4424-b730-94eac0cb1639.png) | ![openSUSE-TW-lvm-failed](https://user-images.githubusercontent.com/1691872/142013922-126c2172-15dd-4a77-b5e0-0ace7f0d341d.png) |
| lvm2 2.02.177-5.11.x86_64 | lvm2 2.02.180-10.16.x86_64 | lvm2 2.03.12-3.2.x86_64 |
* https://trello.com/c/jFw6d1l4/ …
> [SLE-15-SP1] Fix duplicate PV error detection with disabled multipath

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/libstorage_callback.rb
- test/y2storage/callbacks/callbacks_examples.rb
> The installer has lost a specific error message when the same LVM Physical Volume is found in several devices, which might means there are multipath devices in the system but multipath support is disabled
See https://github.com/yast/yast-storage-ng/pull/1247 for reading the full story.
* Tested manually via driver update (SLE-15-SP2)
| Error | Details |
|-|-|
| ![sle15sp2-multipath-pv-fixed-dud](https://user-images.githubusercontent.com/1691872/142250364-6456505d-3d63-4760-8d90-04ff78408eae.png) | ![sle15sp2-multipath-pv-details-fixed-dud](https://user-images.githubusercontent.com/1691872/142250395-4740f7ae-c533-47d3-80aa-450b651ed042.png) |
> [SLE-15-SP2] Fix duplicate PV error detection with disabled multipath

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/callbacks/libstorage_callback.rb
- test/y2storage/callbacks/callbacks_examples.rb
> The installer has lost a specific error message when the same LVM Physical Volume is found in several devices, which might means there are multipath devices in the system but multipath support is disabled
See https://github.com/yast/yast-storage-ng/pull/1247 for reading the full story.
* Tested manually via driver update (SLE-15-SP3)
| Error | Details |
|-|-|
| ![sle15sp3-multipath-pv-fixed-dud](https://user-images.githubusercontent.com/1691872/142254835-3bf0b8d2-e814-49dc-bcfe-c9e06cca2a66.png) | ![sle15sp3-multipath-pv-details-fixed-dud](https://user-images.githubusercontent.com/1691872/142254846-63d2ffea-6e4d-4e84-9be6-9c7f477ca195.png) |
> [SLE-15-SP3] Fix duplicate PV error detection with disabled multipath

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
> The installer has lost a specific error message when the same LVM Physical Volume is found in several devices, which might means there are multipath devices in the system but multipath support is disabled
See https://github.com/yast/yast-storage-ng/pull/1247 for reading the full story.
> Fix duplicate PV error detection with disabled multipath

- doc/boot-requirements.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_strategies/analyzer.rb
- src/lib/y2storage/encryption_method/base.rb
- src/lib/y2storage/encryption_processes/luks.rb
- src/lib/y2storage/encryption_processes/pervasive.rb
- src/lib/y2storage/planned/can_be_encrypted.rb
- test/support/boot_requirements_uefi.rb
- test/y2storage/boot_requirements_checker_ppc_test.rb
- test/y2storage/boot_requirements_checker_s390_test.rb
- test/y2storage/boot_requirements_checker_x86_test.rb
- test/y2storage/boot_requirements_strategies/analyzer_test.rb
`BootRequirementsChecker` was already adapted to deal with LUKS2 encryption at https://github.com/yast/yast-storage-ng/pull/964.
But the [boot-requirements.md](https://github.com/yast/yast-storage-ng/blob/master/doc/boot-requirements.md) document we always use to reflect how the proposals (both the Guided Proposal and the AutoYaST one) work was only updated in a couple of not-so-visible sections back then. Due to that, we even overlooked that `BootRequirementsChecker` already supported LUKS2-based scenarios.
On the other hand, while checking that everything worked as expected, I found that `BootRequirementsChecker` assumed that both the guided proposal and the AutoYaST one used always LUKS1. That is currently true for the guided proposal but not for the AutoYaST one. The AutoYaST property …
> Document and fix BootRequirementsChecker for LUKS2

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/encrypt_method_options.rb
A typo in a UI message.
Typo fixed. (I also slightly reworded the message below.)
- Not tested but trivial, I guess
> encrypt: Fix UI message typo, loose->lose

- package/yast2-storage-ng.changes
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/hwinfo_disk.rb
- src/lib/y2storage/hwinfo_reader.rb
- test/y2partitioner/widgets/lvm_vg_devices_selector_test.rb
- test/y2storage/autoinst_profile/skip_list_value_test.rb
- test/y2storage/blk_device_test.rb
- test/y2storage/encryption_test.rb
- test/y2storage/hwinfo_reader_test.rb
- test/y2storage/mount_point_test.rb
`Y2Storage::HWInfoReader` used to return `OpenStruct` objects (for devices that are known to hwinfo) or `nil` (for not found devices). That left too much to be done in the side of the caller.
The underlying `OpenStruct` objects are now encapsulated in objects of the new class `Y2Storage::HWInfoDisk`. To ensure backwards compatibility, the new class is a subclass of `OpenStruct`, but it offers additional information like proper default values in some well-known cases, like multi-valued attributes.
In addition `HWInfoReader` does not longer return nil for unknown devices, but an empty `HWInfoDisk` object.
Unit tests adapted
> HWInfoReader: always return HWInfoDisk objects

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/confirm_recursive_delete.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1193326
- Let's use the same button IDs in all Yes/No popups to make testing via libyui REST API easier
> Unify the Yes/No popup button IDs (bsc#1193326)

- doc/netdev.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/mount_point.rb
- src/lib/y2storage/mountable.rb
- src/lib/y2storage/proposal/devicegraph_generator.rb
- test/y2storage/devicegraph_test.rb
- test/y2storage/encryption_test.rb
- test/y2storage/mount_point_test.rb
- test/y2storage/proposal_mount_options_test.rb
YaST proposes the mount option "_netdev" in those scenarios when it's needed for the system to boot properly. But that's a task that comes with some challenges:
- If the "_netdev" option is needed but omitted, the system will have problems to boot.
- If the "_netdev" option is added to a mount point for which is not needed, the system will have problems to boot.
- The criteria to determine if "_netdev" is needed depends on:
- the mount point path
- the driver used by the device(s) supporting such a mount point
- which other mount points are based on the same device(s)
- what dracut is going to do regarding initrd generation
So far, YaST used to add "_netdev" if needed to the list of default options proposed for every new mount point. This is a problem because that decision is not …
> Adjust _netdev only in the GuidedProposal (jsc#SLE-20535)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/arch.rb
- test/y2storage/arch_test.rb
- https://trello.com/c/ZWMQnKom
- https://bugzilla.suse.com/show_bug.cgi?id=937067
EFI detection code is all over the place. Consolidate in one spot. As libstorage-ng is using this as well - rely on libstorage-ng.
- add `Y2Storage::Arch.efibootmgr?` method
- `Y2Storage::Arch.efiboot?` takes `LIBSTORAGE_EFI` and `/etc/install.inf::efi` settings into account
- `Y2Storage::StorageManager.arch` is initialized  taking `LIBSTORAGE_EFI` and `/etc/install.inf::efi` settings into account
`#efibootmgr?` and `#efiboot?` are independent and do not rely on each other (`#efiboot? == false` does not imply `#efibootmgr? == false`, for example). This is how it works in libstorage-ng and the sematics are kept here.
- https://github.com/openSUSE/libstorage-ng/pull/846
> use libstorage-ng to determine whether efibootmgr is available (bsc#937067)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/devices_planner.rb
- src/lib/y2storage/volume_specification.rb
- test/y2storage/proposal/devices_planner_test.rb
- test/y2storage/volume_specification_test.rb
The installation control file now allows to indicate mount options, see https://github.com/yast/yast-installation-control/pull/115. The storage proposal needs to be adapted to take the given mount options into account.
* https://trello.com/c/NITXJzLx/1745-3-mount-options-for-a-volume-in-the-partitioning-section-of-controlxml
Add support for mount options to the storage proposal. Default mount options are still used if the control file does not contain *<mount_options>*. 
Note: the term to refer to mount options lack of consistency through the code and UI:
* `VolumeSpecification#mount_options`
* `Planned::Device#fstab_options`
* `MountPoint#mount_options`
* Device Overview Dialog: "Mount Options"
* Edit device dialog: "Fstab Options" 
* AutoYaST profile: `<fstopt>`
* Control file: …
> Mount options from control file

- doc/efi.md
- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
Follow-up to https://github.com/yast/yast-storage-ng/pull/1256:
- https://trello.com/c/ZWMQnKom
- https://bugzilla.suse.com/show_bug.cgi?id=937067
Document UEFI detection and handling.
> document UEFI handling (bsc#937067)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/can_be_encrypted.rb
- src/lib/y2storage/proposal/autoinst_bcache_planner.rb
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- src/lib/y2storage/proposal/autoinst_md_planner.rb
- src/lib/y2storage/proposal/autoinst_partitioner.rb
- src/lib/y2storage/proposal/autoinst_space_maker.rb
- test/data/devicegraphs/gpt_encryption.yml
- test/y2storage/autoinst_proposal_bcache_test.rb
- test/y2storage/autoinst_proposal_md_test.rb
- test/y2storage/autoinst_proposal_test.rb
As reported at [bsc#1193450](https://bugzilla.suse.com/show_bug.cgi?id=1193450), it currently seems to be impossible to keep the original file-system when reusing an existing software RAID with AutoYaST. AutoYaST always formats the MD again.
While investigating the fix, we found two other problems:
- Bcache devices that are directly formatted (without a partition table) are affected by a very similar problem, they are also always re-formatted when reused even if `<format>` is `false` in the profile.
- Reusing devices that were already encrypted was buggy. Under certain circumstances, when the profile specified that a new encryption should be created (replacing the previous one), it was possible to end up with a double-encrypted system (a LUKS directly on top of another LUKS).
Turns out …
> AutoYaST fixes for reusing encrypted devices and RAIDs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/can_be_encrypted.rb
- src/lib/y2storage/proposal/autoinst_bcache_planner.rb
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- src/lib/y2storage/proposal/autoinst_md_planner.rb
- src/lib/y2storage/proposal/autoinst_partitioner.rb
- src/lib/y2storage/proposal/autoinst_space_maker.rb
- test/data/devicegraphs/gpt_encryption.yml
- test/y2storage/autoinst_proposal_bcache_test.rb
- test/y2storage/autoinst_proposal_md_test.rb
- test/y2storage/autoinst_proposal_test.rb
This is a merge of #1266 into SLE-15-SP3.
The reporter of [bsc#1193450](https://bugzilla.suse.com/show_bug.cgi?id=1193450) confirmed that fix worked as expected for SLE-15-SP2, so it's time to merge it into SP3 and master.
> SP3 merge of AutoYaST fixes for reusing encrypted devices and RAIDs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/can_be_encrypted.rb
- src/lib/y2storage/proposal/autoinst_bcache_planner.rb
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- src/lib/y2storage/proposal/autoinst_md_planner.rb
- src/lib/y2storage/proposal/autoinst_partitioner.rb
- src/lib/y2storage/proposal/autoinst_space_maker.rb
- test/data/devicegraphs/gpt_encryption.yml
- test/y2storage/autoinst_proposal_bcache_test.rb
- test/y2storage/autoinst_proposal_md_test.rb
- test/y2storage/autoinst_proposal_test.rb
This is a merge of #1266 into master (future SLE-15-SP4)
For the corresponding merge to SLE-15-SP3, see #1268.
The reporter of [bsc#1193450](https://bugzilla.suse.com/show_bug.cgi?id=1193450) confirmed that fix worked as expected for SLE-15-SP2.
> SP4 (master) merge of AutoYaST fixes for reusing encrypted devices and RAIDs

- src/lib/y2storage/volume_specification_builder.rb
- test/support/proposed_partitions_examples.rb
In a PPC system with a disk that reports an optimal I/O size of 16 MiB, YaST will create a PReP partition of that size (creating an smaller one would imply a missaligned end). That's perfectly fine, since recent IBM's firmware can deal with "big" PReP partitions like that. But the firmware can be wrongly configured with some settings that limit the size of the PReP partition it accepts.
The problem was reported by some SUSE customers and the situation was clarified. The technical details and the procedure to configure the firmware were documented at [bsc#1192448](https://bugzilla.suse.com/show_bug.cgi?id=1192448), including the text of a TID (Technical Information Document) that will be soon be published through the usual SUSE channels.
Add enough pointers in the boot requirements …
> Improve documentation for PReP

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/storage_manager.rb
- test/y2storage/storage_manager_test.rb
When a standalone client (e.g., yast2-bootloader in a running system) performs the probing and find issues, the report introduced in https://github.com/yast/yast-storage-ng/pull/1248 is shown. However, the standalone module continues anyway when the user decides to abort.
* https://bugzilla.suse.com/show_bug.cgi?id=1193749
* https://trello.com/c/9YjFdL0a/2774-3-yast2-bootloader-and-maybe-others-does-not-abort-in-probing-issues (internal link)
<details>
<summary>Click to show/hide some examples</summary>
---
<table>
<tr>
<th>yast-bootloader</th>
<th>yast-rear</th>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/1691872/146373046-3339d758-2008-45d5-8d40-dadefd812648.mp4
</td>
<td>
https://user-images.githubusercontent.com/1691872/146373104-fda7cb28-bbff-4b9f-a8ed-0d72720ee3ed.mp4 …
> Allow abort, even from standalone modules, when probing finds issues

- test/spec_helper.rb
- test/y2storage/clients/manual_test_test.rb
The manual testing client introduced at #1274 depends on yast2-installation being installed on the machine in order to execute the AutoYaST "simulation". That's perfectly fine since that client (specially when testing AutoYaST) is a developer-oriented tool.
But we don't want to introduce a hard dependency from yast2-storage-ng to yast2-installation.
On the other hand, we want the `ManualTest` client to be covered by some unit tests. Since those unit tests are executed while building the package... we have a chicken and egg problem.
Mock all the components from yast2-installation used during the unit test for `Y2Storage::Clients::ManualTest`
> Mock yast-installation classes and modules in tests

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/installation/console/plugins/luks2_checkbox.rb
- src/lib/y2storage/storage_env.rb
- test/installation/console/plugins/luks2_checkbox_test.rb
- test/spec_helper.rb
Activating the experimental LUKS2 support added in #1245 is quite tricky:
- You need to remember the quite long `YAST_LUKS2_AVAILABLE` variable name
- If you forget to set it before starting YaST then you have to reboot the installation and start again :thinking: 
- Once set you cannot change it later
Add an checkbox in the YaST expert console, that makes the setting easily accessible and it can be changed even during installation.
This is a perfect use case why I introduced the YaST expert console.
- Use the `Ctrl+Alt+Shift+C` (in Qt) or `Ctrl+D Shift+C` (in ncurses) keyboard shortcut to activate the expert console
- First show the default encryption options
- Then activate the YaST expert console and enable LUKS2
- Show the encryption options again, now with the LUKS2 …
> Added YaST Console checkbox for enabling LUKS2 support

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/configure_actions.rb
- src/lib/y2storage/callbacks/activate.rb
- src/lib/y2storage/dialogs/callbacks/activate_luks.rb
- src/lib/y2storage/luks.rb
- test/y2partitioner/actions/configure_actions_test.rb
- test/y2storage/callbacks/activate_test.rb
- test/y2storage/dialogs/callbacks/activate_luks_test.rb
When there are several encrypted devices, the user is asked to provide the password for every one. This could be very annoying when the user is only interested on activating some of the encrypted devices.
* https://bugzilla.suse.com/show_bug.cgi?id=1162545
Improve the *activate callback* used for requesting a LUKS password during the activation. The dialog was simplified (less text) and an option was added for skipping the activation of the rest of devices. This is a conservative change that does not cover all possible use cases:
* [Covered ] Many encrypted devices and the user wants to activate none.
* [Partially covered] Many encryption devices and the user only wants to activate some of them.
* The user still has to skip devices one by one until reaching the devices on interest.
* …
> Improve LUKS activation

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/spec_helper.rb
- test/y2partitioner/widgets/btrfs_devices_selector_test.rb
- test/y2partitioner/widgets/columns/format_test.rb
- test/y2partitioner/widgets/columns/size_test.rb
- test/y2partitioner/widgets/device_buttons_set_test.rb
- test/y2partitioner/widgets/pages/nfs_mounts_test.rb
- test/y2storage/boot_requirements_duplicate_test.rb
- test/y2storage/dialogs/guided_setup/select_scheme_test.rb
- test/y2storage/encryption_method_test.rb
- RSpec verifying doubles are not enabled in the tests
- That can hide some possible problems
- Enable verifying doubles in `test/spec_helper.rb`
- Fix reported issues
- Additionally fixed missing mock for reading the NFS configuration. Originally it read the real configuration from the system including the firewalld configuration which displays a PolicyKit popup asking for the `root` password on my system.
- See https://github.com/yast/yast-ruby-bindings/pull/281 for the new mocking helper
- Updated unit tests
> Enable RSpec verifying doubles

- package/yast2-storage-ng.changes
- src/lib/y2partitioner/widgets/description_section/filesystem.rb
- test/y2partitioner/widgets/description_section/filesystem_test.rb
As part of improving the integration with *yast2-nfs-client* (see https://github.com/yast/yast-storage-ng/pull/1283), it was decided to always show *defaults* instead of an empty string when the NFS has no mount options. This is done everywhere, namely lists and forms. But there was one more place: the popup to show the details of a device (*Device -> Show Details* menu option). 
Use *defaults* in the device details when there are no mount options. 
* Added unit test
* Tested manually
> Improve show details for NFS devices 

- package/yast2-storage-ng.changes
- src/lib/y2storage/storage_manager.rb
- test/y2storage/storage_manager_test.rb
An installation repo can be provided from a local disk by using *install=* boot option (e.g., *install=hd:/isos/tw.iso*). YaST mounts the device containing the local repository. If *libstorage-ng* has to unmount such a device (e.g., because the mount point of the repo device was edited in the Expert Partitioner), then the unmount action fails. Note that *libstorage-ng* would try to unmount the device by using a device path as the device would be mounted under the installation mount point (e.g., */mnt/var/adm/mount/AP_0xppFmPE*).
Always release all installation sources before probing. With that, *libstorage-ng* will never try to unmount the device. Note that YaST Packager will mount the source devices again under demand, for example, when the installation starts.  Also note that this is …
> Release sources before probing

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/filesystems/blk_filesystem.rb
- test/y2storage/filesystems/blk_filesystem_test.rb
When an **fstab** first field entry contains quotes surrounding the **UUID** or **label** then the filesystem match fails and do not find any filesystem for the given device.
- https://bugzilla.suse.com/show_bug.cgi?id=1197692
Modify the Regexp for matching device names using **UUID** or **labels** surrounded by quotes.
> Allow quotes when matching fstab device entries

- src/lib/y2storage/filesystems/blk_filesystem.rb
- src/lib/y2storage/luks.rb
- test/y2storage/luks_test.rb
It just extend #1291 improving the **Regexp** for matching the **fstab** first field entry where needed. 
Version increase is not needed as I have not submitted the changes yet.
> Modify fstab entry match Regexp

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/dialogs/fstab_options.rb
- src/lib/y2partitioner/dialogs/import_mount_points.rb
- src/lib/y2partitioner/dialogs/mkfs_options.rb
- src/lib/y2partitioner/dialogs/partition_table_clone.rb
- src/lib/y2partitioner/widgets/fstab_options.rb
- src/lib/y2partitioner/widgets/mkfs_options.rb
Some dialogs in the partitioner have a *Help* button that pops up an empty window.
- https://bugzilla.suse.com/show_bug.cgi?id=1194274
- https://trello.com/c/22Mos13d
These fixes work via a method of a base class of all these dialogs, [Y2Partitioner::Dialogs::Popup#set_help_text](https://github.com/yast/yast-storage-ng/blob/SLE-15-SP4/src/lib/y2partitioner/dialogs/popup.rb#L100).
A better fix would be to use a common mechanism of CWM+Wizard:
Wizard.SetHelpText relying on existence of a widget with Id(:WizardDialog)
but that is risky for SLE15-SP4
Tested manually.
For easier testing, the dialogs are:
- MkfsOptions "Format Options"
Add Partition, Next, Next, Options, Help
- FstabOptions "Fstab Options"
Add Partition, Next, Next, Mount Device, Fstab Options, Help
- ImportMountPoints "Import …
> Fix empty help in some Partitioner dialogs (bsc#1194274)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/storage_feature.rb
Recently support for the NILFS2 file-system was introduced in libstorage-ng. As a result, a new value was introduced for the so-called "storage features". See https://github.com/openSUSE/libstorage-ng/pull/874
yast-storage-ng contains a unit test to detect that situation and stop building when a new unknown feature is introduced. As expected, the unit test is failing now.
Adapt yast-storage-ng to correctly handle the new support for NILFS2, requesting the corresponding package if NILFS2 is used in the system and the package is available.
> Recognize new libstorage-ng feature for NILFS2

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/encryption_type.rb
https://bugzilla.opensuse.org/show_bug.cgi?id=1199832
Unit tests fail after a new enum was added in libstorage-ng for _bitlocker_.
```
[  122s] Failures:
[  122s] 
[  122s]   1) Y2Storage::EncryptionType#to_human_string for all the possible values of the library returns the translated string
[  122s]      Failure/Error: expect(value.to_human_string).to be_a(::String)
[  122s] 
[  122s]      RuntimeError:
[  122s]        Unhandled encryption type '#<Y2Storage::EncryptionType bitlocker>'
[  122s]      # ./src/lib/y2storage/encryption_type.rb:74:in `to_human_string'
[  122s]      # ./test/y2storage/encryption_type_test.rb:29:in `block (5 levels) in <top (required)>'
[  122s]      # ./test/y2storage/encryption_type_test.rb:28:in `each'
[  122s]      # …
```
> Fixed Build Failure because of new "bitlocker" Enum

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/blk_device.rb
- src/lib/y2storage/filesystems/mount_by_type.rb
- src/lib/y2storage/mount_point.rb
Libstorage-ng introduces new types for mount_by which causes failure in test suites and also other code is not adapted for it.
- [bsc#1202225](https://bugzilla.suse.com/show_bug.cgi?id=1202225)
- https://trello.com/c/Xz60ksqP/3042-p1-yast-storage-ng-broken-due-to-new-mount-bys-on-libstorage-ng
- https://github.com/openSUSE/libstorage-ng/pull/893
- original pr with alternative  solution https://github.com/yast/yast-storage-ng/pull/1306
Adapt a code to skip newly added ones as there is no request to support them.
- *Adapted unit tests*
> New mountby2

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/y2storage/partition_tables/msdos_test.rb
This was changed in libstorage-ng https://github.com/openSUSE/libstorage-ng/pull/900
Before that, `ms_dos_ptable.partition_id_supported?(Y2Storage::PartitionId::UNKNOWN)` returned false. Now it returns true.
The change is actually safe for the current code-base of yast-storage-ng (see below), but it broke the unit tests we intentionally have in place to detect changes in the libstorage-ng API (so we can manually check if there is any problematic implication).
Just adapt the test to the new behavior of libstorage-ng. We verified the change is safe because:
- `PartitionTables::Base#supported_partition_ids` already filters UNKNOWN out. Among other things, that already guarantees UNKNOWN is never offered as an option in the UI.
- Calls to …
> Adapt test to behavior change in libstorage-ng

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/y2storage/clients/manual_test_test.rb
- https://bugzilla.opensuse.org/show_bug.cgi?id=1204871 "- [Staging] rubygem-rspec-* 3.12 breaks various yast modules build"
- see https://github.com/yast/yast-yast2/pull/1279 for details
> Fix hash vs keyword arguments in RSpec expectations (bsc#1204871)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/overview.rb
- src/lib/y2storage/dialogs/proposal.rb
- src/lib/y2storage/setup_checker.rb
- src/lib/y2storage/setup_errors_presenter.rb
- src/lib/y2storage/with_security_policies.rb
- test/y2partitioner/widgets/overview_test.rb
- test/y2storage/dialogs/proposal_test.rb
- test/y2storage/setup_checker_test.rb
- test/y2storage/setup_errors_presenter_test.rb
YaST installer is now able to validate whether a setup fulfills the installation requirements of the DISA STIG security policy, see https://github.com/yast/yast-security/pull/128. Some of those checks affect to the storage setup. But neither Guided Setup nor Expert Partitioner are performing checks for the enabled security policy.  
* Part of
* https://trello.com/c/SqFGWTyB/3044-build-a-basic-initial-api-for-the-stig-checker
* https://jira.suse.com/browse/PM-3526
* Requires: https://github.com/yast/yast-security/pull/128
Perform policy checks and show issues in both the storage proposal dialog and the Expert Partitioner. Note that a policy can be enabled by default with the `YAST_SECURITY_POLICY` boot parameter, for example `YAST_SECURITY_POLICY=stig`.
NOTE: this will be merged after …
> Security policy checks

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/encryption.rb
- src/lib/y2partitioner/widgets/description_section/blk_device.rb
- src/lib/y2partitioner/widgets/pbkdf_selector.rb
- src/lib/y2storage.rb
- src/lib/y2storage/boot_requirements_strategies/analyzer.rb
- src/lib/y2storage/boot_requirements_strategies/base.rb
- src/lib/y2storage/encryption.rb
- src/lib/y2storage/encryption_method/luks2.rb
- src/lib/y2storage/encryption_processes/luks.rb
- src/lib/y2storage/pbkd_function.rb
- src/lib/y2storage/planned/can_be_encrypted.rb
- src/lib/y2storage/planned/lvm_vg.rb
- src/lib/y2storage/proposal/devices_planner.rb
- src/lib/y2storage/proposal/lvm_helper.rb
- src/lib/y2storage/proposal_settings.rb
- test/support/boot_requirements_context.rb
- test/y2partitioner/widgets/description_section/blk_device_test.rb
- test/y2partitioner/widgets/pbkdf_selector_test.rb
- test/y2storage/encryption_method_test.rb
- test/y2storage/pbkd_function_test.rb
- test/y2storage/proposal_luks2_x86_test.rb
The `GuidedProposal` (and its variants) is the component responsible of calculating a good storage layout to install the system. So far it's used:
- By YaST to calculate the initial storage proposal
- By YaST if the option "Guided Setup" is used in the partitioning screen
- By AutoYaST if any of the options for [automatic partitioning](https://documentation.suse.com/sles/15-SP4/html/SLES-all/cha-configuration-installation-options.html#CreateProfile-Automatic-Partitioning) or for [guided partitioning](https://documentation.suse.com/sles/15-SP4/html/SLES-all/cha-configuration-installation-options.html#CreateProfile-Guided-Partitioning) is used
- By the current prototypes of D-Installer
For many reasons outlined in [this bugzilla comment](https://bugzilla.suse.com/show_bug.cgi?id=1185291#c1) …
> Support for LUKS2 in the GuidedProposal

- package/yast2-storage-ng.changes
- src/lib/y2storage/proposal/lvm_helper.rb
- src/lib/y2storage/proposal_settings.rb
- test/data/devicegraphs/output/windows-linux-lvm-noreuse-lvm-sep-home.yml
- test/data/devicegraphs/output/windows-linux-lvm-noreuse-lvm.yml
- test/y2storage/proposal/lvm_helper_test.rb
- test/y2storage/proposal_scenarios_x86_test.rb
For historical reasons, YaST tries to reuse existing LVM volume groups when making a proposal.
That behavior can be very confusing in many situations. Some of the associated problems and historical factors are described here:
https://trello.com/c/Ib7QC298/19-proposal-strategy-for-reusing-stuff-in-proposal-bug1091998-and-others
Now `Y2Storage::GuidedProposal` is also used by D-Installer and we don't want to follow the YaST approach for reusing stuff. Since D-Installer represents a new playground, we don't need to play by the old rules and expectations.
Introduce a new setting into `Y2Storage::ProposalSettings` that will be used only by D-Installer (for the time being) and that will inhibit the mechanism to reuse existing LVM volume groups.
Added unit tests. Backwards compatibility ensured …
> [Proposal] New setting to not reuse LVM volume groups

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/blk_device.rb
This is for SLE-15 SP4.
https://bugzilla.suse.com/show_bug.cgi?id=1200975
In some cases, Dell BOSS NVMe drives were not correctly identified and shown as such to the user.
Extended the regular expression for the check.
https://bugzilla.suse.com/show_bug.cgi?id=1200975#c87
Merge to _master_:
_to do_
> Correctly Identify Dell BOSS Storage Devices

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/equal_by_instance_variables.rb
- src/lib/y2storage/proposal_settings.rb
- src/lib/y2storage/secret_attributes.rb
- src/lib/y2storage/subvol_specification.rb
- src/lib/y2storage/volume_specification.rb
- test/y2storage/equal_by_instance_variables_test.rb
- test/y2storage/filesystems/btrfs_test.rb
- test/y2storage/proposal/settings_generator_test.rb
- test/y2storage/proposal_settings_test.rb
- test/y2storage/secret_attributes_test.rb
Ruby 3.2 yast2-storage-ng sometimes fails to build, diff in Marshal.dump
- https://bugzilla.suse.com/show_bug.cgi?id=1208259
- https://trello.com/c/jRe5bWVE/3249-ostumbleweed-1206419-staging-ruby-keyword-parameters-yast-stack-fails-to-build-against-ruby-32
The failing test means to check that a new `ProposalSettings` is in fact equal to the original one, and does so by dumping and reloading the two objects with `Marshal`. It fails in case the two objects differ in the order in which their instance variables were assigned.
Instead of using `Marshal`, add `ProposalSettings#==`.
Do it by introducing a simple module, `EqualByInstanceVariables`, including it in that class and a couple of others that are used by it.
Gory details: everything I've learned about equality in Ruby along the way, …
> Ruby 3.2 yast2-storage-ng sometimes fails to build, diff in Marshal.dump 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/guided_proposal.rb
- test/y2storage/guided_proposal_test.rb
Changing the candidate device in the D-Installer to a non-existing device caused a crash `undefined method 'partition_table' for nil:NilClass`:
```
/usr/share/YaST2/lib/y2storage/guided_proposal.rb:274:in `block in candidate_devices_with_empty_partition_table': undefined method `partition_table' for nil:NilClass; caused by 1 sender=:1.0 -> dest=org.opensuse.DInstaller.Storage serial=12 reply_serial= path=/org/opensuse/DInstaller/Storage1; interface=org.opensuse.DInstaller.Storage1.Proposal.Calculator; member=Calculate error_name=; caused by 3 sender=:1.4 -> dest=:1.0 serial=36 reply_serial=12 path=; interface=; member= error_name=org.freedesktop.DBus.Error.Failed (DBus::Error)
```
- Added a `nil` check
- Added a new unit test, the code now raises `Y2Storage::NoDiskSpaceError` instead of …
> Fixed crash in the proposal code (bsc#1209523)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/columns/type.rb
- src/lib/y2storage/blk_device.rb
- test/y2storage/blk_device_test.rb
Some things has changed regarding BOSS devices manufactured by Dell. That leaded to the creation of [bug#1200975](https://bugzilla.suse.com/show_bug.cgi?id=1200975).
From the discussions in the bug report, we identified two things that could be improved in the YaST side.
1. The regexp to detect a Dell BOSS disk needs to be updated. Originally Dell stated that all BOSS devices would contain the string "DELLBOSS" as part of the model (https://jira.suse.com/browse/SLE-17578). Looks like that's not true anymore. According to a comment at the mentioned [bug#1200975](https://bugzilla.suse.com/show_bug.cgi?id=1200975), the new criteria is "_the model string will always have both Dell and BOSS in some order_".
2. For a typical disk, the column "Type" in the Expert Partitioner is computed as …
> [SP5] Improve display of Dell BOSS

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/dialogs/guided_setup/helpers/disk.rb
- test/y2storage/dialogs/guided_setup/helpers/disk_test.rb
Described and discussed at https://bugzilla.suse.com/show_bug.cgi?id=1209588
The screen of the Guided Setup used to select the target disk(s) shows some information about each disk to make it possible to identify them.
But deciding which information to display is VERY tricky:
- YaST interface is designed to fit perfectly in text mode with 80 columns and 24 lines. That implies a lot of text and space economy.
- Many systems contains dozens of disks.
- Although some advanced users may appreciate details about the model of the disk or the controller, those are long and complex strings that are meaningless for most users.
- ...and many other considerations...
As a reasonable compromise, YaST displays the following information for each disk:
- The device name
- The total size
- The list of …
> Guided Setup: display a hint for disks with sensible transports

- package/yast2-storage-ng.changes
- src/lib/y2storage/proposal/devices_planner.rb
- src/lib/y2storage/proposal/partitions_distribution_calculator.rb
- src/lib/y2storage/proposal/space_maker.rb
- src/lib/y2storage/volume_specification.rb
- test/data/devicegraphs/output/agama-basis-distributed.yml
- test/data/devicegraphs/output/agama-basis-lvm-distributed.yml
- test/data/devicegraphs/output/agama-basis-lvm-separate_boot.yml
- test/data/devicegraphs/output/agama-basis-lvm-several_disks.yml
- test/data/devicegraphs/output/agama-basis-lvm-single_disk.yml
- test/data/devicegraphs/output/agama-basis-separate_boot.yml
- test/data/devicegraphs/output/agama-basis-single_disk.yml
- test/data/devicegraphs/windows_disks.yml
- test/support/proposal_context.rb
- test/y2storage/proposal/space_maker_test.rb
- test/y2storage/proposal_agama_basis_test.rb
We are re-using the YaST `GuidedProposal` at Agama (to be precise, we use `MinGuidedProposal` which is identical but ignores `desired_size` and performs only one attempt with the minimum).
The `GuidedProposal` can find the best location for every requested volumes within a set of candidate devices. It also allows to specify that a given volume must be placed in a specific disk. But turns out it was not able to do both things at the same time!
If a setting called `allocate_volume_mode` was set to `auto` (which is the default), assignations of volume to specific disks were ignored and the proposal freely allocated all the volumes within the designated candidate devices. If `allocate_volume_mode` was set to `device` then the proposal calculated the candidate devices as the sum of all devices …
> Adaptations to have more flexible proposal (useful for Agama)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_prepdisk.rb
- src/lib/y2storage/storage_manager.rb
Agama uses the *inst_prepdisk* client to perform the required storage actions. That client calls to the storage commit action, which uses the default commit callbacks from YaST to report the errors.
Agama needs to provide its own callbacks, see https://github.com/openSUSE/agama/pull/558.
Allows to pass commit callbacks to the *inst_prepdisk* client.
> Add commit callbacks to inst_prepdisk

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/guided_proposal.rb
- src/lib/y2storage/proposal/space_maker.rb
- src/lib/y2storage/proposal/space_maker_actions.rb
- src/lib/y2storage/proposal/space_maker_actions/auto_strategy.rb
- src/lib/y2storage/proposal/space_maker_actions/base.rb
- src/lib/y2storage/proposal/space_maker_actions/bigger_resize_strategy.rb
- src/lib/y2storage/proposal/space_maker_actions/delete.rb
- src/lib/y2storage/proposal/space_maker_actions/list.rb
- src/lib/y2storage/proposal/space_maker_actions/shrink.rb
- src/lib/y2storage/proposal/space_maker_actions/wipe.rb
- src/lib/y2storage/proposal/space_maker_prospects/base.rb
- src/lib/y2storage/proposal/space_maker_prospects/delete_partition.rb
- src/lib/y2storage/proposal/space_maker_prospects/list.rb
- src/lib/y2storage/proposal/space_maker_prospects/resize_partition.rb
- src/lib/y2storage/proposal/space_maker_prospects/wipe_disk.rb
- src/lib/y2storage/proposal_settings.rb
- src/lib/y2storage/proposal_space_settings.rb
- test/data/devicegraphs/irst-windows-linux-gpt.yml
- test/y2storage/proposal/space_maker_bigger_resize_test.rb
- test/y2storage/proposal/space_maker_test.rb
The traditional behavior of `Y2Storage::Proposal::SpaceMaker` is coupled to the options offered by YaST in that regard. Somehow summarized in this screenshot.
But for Agama we want to offer other options.
First of all, we want to stop making a difference for partitions of type Windows/Linux/other. The criteria for classifying a partition in one group or the other is not so clear.
On the other hand, we want to make it possible for Agama to specify any of the four modes described at [storage_ui.md](https://github.com/openSUSE/agama/blob/master/doc/storage_ui.md). That is:
- Delete everything in the disk(s).
- Resize existing partition(s).
- Do not modify existing partition(s).
- Custom, with the user specifying what to do with every individual partition in the affected disks: resize it, …
> New strategy for SpaceMaker

- package/yast2-storage-ng.changes
In my previous PR #1337 I copied from a previous entry the format of the reference to the github issue. But that's not the format recognized by the OBS and Jenkins cops.
That made the CI run fail. See https://ci.opensuse.org/job/yast-yast-storage-ng-master/464/console
Use the right format, not only for my new entry but also for the previous one I copied.
> Fix format of references to GitHub at changelog

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/dasd.rb
Agama needs to show the Bus Id of a DASD in order to help to indentify the device, see https://github.com/openSUSE/agama/pull/578. 
Add `#bus_id` to `Dasd` class.
> Add bus_id for DASD

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/widgets/fstab_options.rb
**This is for _SLE-15-SP4_**. The merge to _SLE-15-SP5_ and _master_ / _Factory_ will follow.
**L3:** https://bugzilla.suse.com/show_bug.cgi?id=1211337
https://trello.com/c/0ASTpHRy
Trying to change the volume label of a mounted Btrfs or swap partition in the YaST partitioner fails with an error message
_Setting label of btrfs on /dev/sda2 (57.50 GiB) to root Unexpected situation found in the system._
The "Details" button shows
_Caught signal #127: "/sbin/btrfs filesystem label '/dev/sda2' 'root'_
which is scary and confusing and does not give the user any hint what's actually wrong.
In the case of a root Btrfs, it even hangs later because subvolumes cannot be mounted.
Even though some filesystem types do support changing the volume label while mounted, in our context this has …
> Prevent setting the Volume Label for a Mounted Btrfs or Swap

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/filesystem.rb
- src/lib/y2partitioner/widgets/fstab_options.rb
**This is the merge of #1341  to _master_ / _Factory_.**
**L3:** https://bugzilla.suse.com/show_bug.cgi?id=1211337
https://trello.com/c/JvuZVVU3
Trying to change the volume label of a mounted Btrfs or swap partition in the YaST partitioner fails with an error message
_Setting label of btrfs on /dev/sda2 (57.50 GiB) to root Unexpected situation found in the system._
The "Details" button shows
_Caught signal #127: "/sbin/btrfs filesystem label '/dev/sda2' 'root'_
which is scary and confusing and does not give the user any hint what's actually wrong.
In the case of a root Btrfs, it even hangs later because subvolumes cannot be mounted.
Even though some filesystem types do support changing the volume label while mounted, in our context this has implications with the subvolumes. Handling the …
> Prevent setting the Volume Label for a Mounted Btrfs or Swap [master]

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal_settings.rb
- test/y2storage/proposal_settings_test.rb
We want to make it possible for the Common Criteria role to provide an encryption password, so the partitioning proposal uses encryption by default.
And we want to do so in the less intrusive possible way, since we want the change to land at already released branches like 15.4 and 15.5.
On the one hand, we implemented https://github.com/yast/system-role-common-criteria/pull/10, to make the Common Criteria role dialog ask for the encryption password and store it at the field `encryption` of the `ProductFeatures`.
On this pull request, we make sure the storage `GuidedProposal` honors the mentioned field. The storage proposal already took all its default settings from the `ProductFeatures`, but encryption was not previously considered because it makes no sense to define a given password for …
> Honor proposal encryption from ProductFeatures

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_disk_proposal.rb
- src/lib/y2storage/clients/partitions_proposal.rb
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/package_handler.rb
- src/lib/y2storage/storage_feature.rb
- test/y2storage/devicegraph_test.rb
- test/y2storage/package_handler_test.rb
- test/y2storage/storage_features_list_test.rb
_This is for SLE-15-SP4 / **MicroOS 5.3** and **MicroOS 5.4**_.
A merge to _SLE-15-SP5_ and _master_ / _Factory_ will follow.
https://bugzilla.suse.com/show_bug.cgi?id=1212452
https://trello.com/c/T9nqET80/
On an system with a multipath storage setup, the reboot after the installation failed. It turned out that the _multipath-tools_ package was not installed.
A regular SLE-15-SPx or Leap 15.x or Tumbleweed installation uses the _inst_disk_proposal_ client in the installation workflow which at its end determines which storage features (e.g. Btrfs, XFS, LVM, multipath) are used and adds the software packages that are needed for those technologies to the pool of packages that are going to be installed.
But MicroOS has a different installation workflow, and it doesn't use that default …
> Ensure adding Storage Support Software Packages for MicroOS [SLE-15-SP4]

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_disk_proposal.rb
- src/lib/y2storage/clients/partitions_proposal.rb
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/package_handler.rb
- src/lib/y2storage/proposal_settings.rb
- src/lib/y2storage/storage_feature.rb
- test/y2storage/devicegraph_test.rb
- test/y2storage/package_handler_test.rb
- test/y2storage/proposal_settings_test.rb
- test/y2storage/storage_features_list_test.rb
_This is the merge to **SLE-15-SP5** of #1346 ._
https://bugzilla.suse.com/show_bug.cgi?id=1212452
https://trello.com/c/T9nqET80/
On an system with a multipath storage setup, the reboot after the installation failed. It turned out that the _multipath-tools_ package was not installed.
A regular SLE-15-SPx or Leap 15.x or Tumbleweed installation uses the _inst_disk_proposal_ client in the installation workflow which at its end determines which storage features (e.g. Btrfs, XFS, LVM, multipath) are used and adds the software packages that are needed for those technologies to the pool of packages that are going to be installed.
But MicroOS has a different installation workflow, and it doesn't use that default _inst_disk_proposal_ client at all; instead, it uses a custom _partitions_proposal_ …
> Ensure adding Storage Support Software Packages for MicroOS [SLE-15-SP5]

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_disk_proposal.rb
- src/lib/y2storage/clients/partitions_proposal.rb
- src/lib/y2storage/devicegraph.rb
- src/lib/y2storage/package_handler.rb
- src/lib/y2storage/proposal_settings.rb
- src/lib/y2storage/storage_feature.rb
- test/y2storage/devicegraph_test.rb
- test/y2storage/package_handler_test.rb
- test/y2storage/proposal_settings_test.rb
- test/y2storage/storage_features_list_test.rb
_This is the merge to **master / Factory / TW** of #1350 ._
https://bugzilla.suse.com/show_bug.cgi?id=1212452
https://trello.com/c/T9nqET80/
On an system with a multipath storage setup, the reboot after the installation failed. It turned out that the _multipath-tools_ package was not installed.
A regular SLE-15-SPx or Leap 15.x or Tumbleweed installation uses the _inst_disk_proposal_ client in the installation workflow which at its end determines which storage features (e.g. Btrfs, XFS, LVM, multipath) are used and adds the software packages that are needed for those technologies to the pool of packages that are going to be installed.
But MicroOS has a different installation workflow, and it doesn't use that default _inst_disk_proposal_ client at all; instead, it uses a custom …
> Ensure adding Storage Support Software Packages for MicroOS [master] 

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/partition_section.rb
- src/lib/y2storage/encryption.rb
- src/lib/y2storage/encryption_method/luks2.rb
- src/lib/y2storage/planned/can_be_encrypted.rb
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- test/y2storage/autoinst_profile/partition_section_test.rb
- test/y2storage/autoinst_proposal_encryption_test.rb
AutoYaST does not officially support LUKS2 or setting any of its advanced options.
In fact, preliminary support for LUKS2 was added to YaST at SLE-15-SP4 targeting only the interactive installation. That's explained at the description of #1245. Since there was no feedback about it, the feature was not developed any further.
As a consequence, LUKS2 works partially in AutoYaST if the boot argument `YAST_LUKS2_AVAILABLE` is used during installation. But there is no way to configure via AutoYaST some of the parameters than can be tweaked in the UI (like the PBKDF or the LUKS2 label). LUKS2 support for AutoYaST is not even officially documented.
But some SUSE customers want to configure LUKS2 devices during installation using AutoYaST, tweaking some of the luksFormat parameters. Even on …
> AutoYaST (SLE-15-SP6): support for advanced LUKS(2) settings

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/raid_options_section.rb
- src/lib/y2storage/md_level.rb
libstorage-ng and YaST used to lack support for the RAID level "linear". That leaded to errors during probing in a system with such RAIDs. See [bsc#1215022](https://bugzilla.suse.com/show_bug.cgi?id=1215022).
To fix the problem, support for a new `MdLevel::LINEAR` was added to libstorage-ng. But yast2-storage-ng needs the corresponding adaptations to the new MD level.
To be precise, we want YaST to stop failing in presence of such a RAID, but we don't want to add support to create new ones.
This targets SLE-15-SP4, only as a fix for the reported bug.
Adds the code needed to recognize the new level added to libstorage-ng, so probing works and the RAIDs are properly represented (eg. in the Expert Partitioner).
This also adds basic handling at AutoYaST. Basically preventing the …
> Support probing of linear RAIDs

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/raid_options_section.rb
- src/lib/y2storage/md_level.rb
This is a merge to the SLE-15-SP5 branch of #1354. That pull request was already tested, approved and verified to work by the reporter.
> Support probing of linear RAIDs (SP5)

- test/spec_helper.rb
- test/y2storage/hwinfo_reader_test.rb
The testsuite used to run in around 2-4 minutes in my personal system.
We have always known that we should be more aggressive mocking calls to `hwinfo` and some libstorage-ng operations (mostly those that result in calls to `udevadm --settle`). But even without that mocking, the situation was still acceptable.
Recently things became MUCH worse. Now the testsuite is much slower. I was not able to find what caused it. No luck bisecting the changes in the repository, so I guess the problem is somewhere else (some combination of changes in libstorage-ng or another YaST package, Ruby, the Tumbleweed kernel, udev and whatnot).
Even if the source of the recent slow-down is still there, I decided to introduce the long-overdue mocking for `hwinfo` in order to mitigate the problem.
Now the …
> Speed-up tests a bit in systems with slow hwinfo

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/devices_planner.rb
- src/lib/y2storage/proposal_settings.rb
- test/data/devicegraphs/autoyast_drive_examples.yml
- test/y2storage/proposal_swap_reuse_test.rb
Currently YaST’s guided storage proposal reuses any available swap, even if that swap is not in the candidate devices.
That’s the traditional behavior inherited from the SLE-12 times. Although it has been reported as confusing at https://bugzilla.suse.com/show_bug.cgi?id=1175535 and https://bugzilla.suse.com/show_bug.cgi?id=1215639 .
It’s still not decided which possibilities we want to use regarding re-use of partitions at Agama. But while we decide what to do in Agama, the current behavior of reusing swap is confusing because it’s not clear what is happening looking at the UI.
This implements a new setting at `ProposalSettings` to fine-tune swap reusing at the `GuidedProposal`. It has three possible values:
- `:any` Current behavior. For keeping compatibility in YaST.
- `:none` Simply …
> Add internal setting to configure swap reusing in GuidedProposal

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/storage_feature.rb
https://bugzilla.suse.com/show_bug.cgi?id=1219804
Build failure with latest libstorage-ng:
```
13) Y2Storage::StorageFeature.all contains one entry for each feature from libstorage-ng
Failure/Error: expect(described_class.all.map(&:to_sym)).to contain_exactly(*constants)
expected collection contained:  [:UF_BCACHE, :UF_BCACHEFS, :UF_BITLOCKER, :UF_BTRFS, :UF_DASD, :UF_DMRAID, :UF_EXFAT, :UF_EXT2, :UF_E..._ENCRYPTION, :UF_PMEM, :UF_QUOTA, :UF_REISERFS, :UF_SNAPSHOTS, :UF_SWAP, :UF_UDF, :UF_VFAT, :UF_XFS]
actual collection contained:    [:UF_BCACHE, :UF_BITLOCKER, :UF_BTRFS, :UF_DASD, :UF_DMRAID, :UF_EXFAT, :UF_EXT2, :UF_EXT3, :UF_EXT4,..._ENCRYPTION, :UF_PMEM, :UF_QUOTA, :UF_REISERFS, :UF_SNAPSHOTS, :UF_SWAP, :UF_UDF, :UF_VFAT, :UF_XFS]
the missing elements were:      [:UF_BCACHEFS]
``` …
> Fix Build Failure: New libstorage-ng enum

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/lvm_helper.rb
- src/lib/y2storage/proposal_settings.rb
- src/lib/y2storage/storage_env.rb
- test/y2storage/storage_env_test.rb
https://jira.suse.com/browse/PED-6407
The Storage Proposal in SLE 15 allows for creating a layout based on LVM. For historical reasons, it tries to reuse the existing LVM volume group for new installations. This sometimes produces a non-optimal, non-logical or even confusing disk setup.
linuxrc option to disable lvm reuse
> Handling of YAST_REUSE_LVM linuxrc option

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/widgets/columns/filesystem_label.rb
- src/lib/y2partitioner/widgets/columns/type.rb
- src/lib/y2storage/device_description.rb
- src/lib/y2storage/filesystem_label.rb
- test/y2partitioner/widgets/columns/filesystem_label_test.rb
- test/y2partitioner/widgets/columns/type_test.rb
- test/y2storage/device_description_test.rb
- test/y2storage/filesystem_label_test.rb
The partitioner implements some logic to generate the content of the columns (e.g., for generating the descrition of the device, the label of a file system, etc). Such information is useful for other projects like Agama, but reusing that logic is not possible as it is because it is directly implemented in the partitioner columns (UI stuff).
Extract the logic for generating useful information to separate classes, making possible to reuse it. 
* Unit tests adapted.
* Tested manually
> Extract device description and filesystem label

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/data/devicegraphs/autoyast_drive_examples.yml
- test/data/devicegraphs/dos_lvm.yml
- test/data/devicegraphs/dos_lvm_boot_partition.yml
- test/data/devicegraphs/lvm-striped-lvs.yml
- test/data/devicegraphs/lvm-two-disks.yml
- test/data/devicegraphs/lvm_with_bios_boot.yml
- test/data/devicegraphs/lvm_with_boot.yml
- test/data/devicegraphs/prep_lvm.yml
- test/data/devicegraphs/trivial_lvm.yml
- test/data/devicegraphs/trivial_lvm_and_other_partitions.yml
https://bugzilla.suse.com/show_bug.cgi?id=1221222
Build failure of yast-storage-ng with the latest SWIG bindings.
The unit tests use `DiskSize::unlimited` in the YAML files for many test scenarios for LVs, and that results in a value -1 which clashes with the libstorage function prototype that expects `unsigned long long` for `create_lvm_lv()`.
Obviously SWIG decides at runtime (!) which C++ function to call, and now the checks appear to be stricter: A -1 worked well until this version; it had obviously converted it to the bit pattern of the expected unsigned type, in this case resulting in 16 EiB - 1. Now that doesn't work anymore.
Don't use _unlimited_ for LVM LVs in the YAML fake device graphs; that's unrealistic and not possible in real life anyway.
This fix is limited purely to unit …
> Fix unlimited-sized fake device graphs (bsc#1221222)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/partitions_distribution_calculator.rb
- test/y2storage/proposal_agama_advanced_test.rb
When the `GuidedProposal` uses the `:bigger_resize` strategy for making space, it receives a list of potential resize actions.
Combining LVM with a separate boot disk, it may happen that the list of resize actions include actions on partitions of the boot disks that are not needed, because there is already enough free space in the booting disk without resizing any partition.
Sometimes, that leaded to an exception in the algorithm of `Proposal::PartitionsDistributionsCalculator`.
Take the corner case into account and return a zero in the value for "missing size" (there is no need to resize).
> Fix total size

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/data/devicegraphs/autoyast_drive_examples.yml
- test/data/devicegraphs/dos_lvm.yml
- test/data/devicegraphs/dos_lvm_boot_partition.yml
- test/data/devicegraphs/lvm-striped-lvs.yml
- test/data/devicegraphs/lvm-two-disks.yml
- test/data/devicegraphs/lvm_with_bios_boot.yml
- test/data/devicegraphs/lvm_with_boot.yml
- test/data/devicegraphs/prep_lvm.yml
- test/data/devicegraphs/trivial_lvm.yml
- test/data/devicegraphs/trivial_lvm_and_other_partitions.yml
This is a backport of PR #1375 to **SLE-15-SP6**.
https://bugzilla.suse.com/show_bug.cgi?id=1221222
Build failure of yast-storage-ng with the latest SWIG bindings.
The unit tests use `DiskSize::unlimited` in the YAML files for many test scenarios for LVs, and that results in a value -1 which clashes with the libstorage function prototype that expects `unsigned long long` for `create_lvm_lv()`.
Obviously SWIG decides at runtime (!) which C++ function to call, and now the checks appear to be stricter: A -1 worked well until this version; it had obviously converted it to the bit pattern of the expected unsigned type, in this case resulting in 16 EiB - 1. Now that doesn't work anymore.
Don't use _unlimited_ for LVM LVs in the YAML fake device graphs; that's unrealistic and not possible in …
> Fix unlimited-sized fake device graphs (bsc#1221222)  [SLE-15-SP6 Backport]

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/device_description.rb
- test/y2storage/device_description_test.rb
- The device labels in Agama do not include the encryption status
- In YaST it is OK because it has a dedicated column with encryption status
- In Agama we would like to have the status included directly in the label
- Adapt the code to include the encryption status in the label
- The encryption status is included only when explicitly requested. That allows to keep the backward compatibility with YaST and show it only in Agama.
- See related https://github.com/openSUSE/agama/pull/1155
> Optionally include the encryption status in the device description

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/boot_requirements_strategies/analyzer.rb
- src/lib/y2storage/proposal/space_maker_actions/bigger_resize_strategy.rb
- src/lib/y2storage/proposal_space_settings.rb
- test/y2storage/proposal/space_maker_bigger_resize_test.rb
- test/y2storage/proposal_agama_advanced_test.rb
- test/y2storage/proposal_agama_reuse_test.rb
**IMPORTANT:** This should be merged in sync with https://github.com/openSUSE/agama/pull/1164, which includes the needed adaptations in the Agama side to keep everything consistent.
The `:bigger_resize` strategy was added to give Agama a more fine-grained control of the actions to be performed by the SpaceMaker.
But we found several inconsistencies in the way we originally defined `:bigger_resize`.
Before this change, the SpaceMaker strategy expected a list like this.
- For non-partitioned disks (for example, disks directly formatted or acting as LVM PV) it expected one of the following actions:
- none (ie. keep the content)
- `:delete` or `:force_delete` (ie. wipe the content).
- For partitions it expected one of the following:
- none (ie. keep the partition as-is),
- `:delete or …
> Improve the :bigger_resize SpaceMaker strategy

- package/yast2-storage-ng.changes
- src/lib/y2storage/device_description.rb
- test/y2storage/device_description_test.rb
The description of an encrypted physical volume is wrong: *PV of system* instead of *Encrypted PV of system*.
Fix `ProductDescription`.
* Added new unit test
* Tested manually
> Fix device description of encrypted PV

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/proposal/devices_planner.rb
- test/y2storage/proposal_agama_reuse_test.rb
This bug at Agama was reported https://github.com/openSUSE/agama/issues/1339
Turns out the root of the error was an uncaught exception at the GuidedProposal caused because YaST was trying to adjust the sizes of the root device to fulfill the Btrfs-related settings... but such a device was a disk instead of an LV or partition.
Added the same guard we have in other parts of `DevicesPlanner` (eg. `adjust_sizes`).
- Tested manually with Agama. It solves the reported bug.
> Fix a bug when formatting a full disk as Btrfs with snapshots

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/autoinst_profile/drive_section.rb
Agama calculates an AutoYaST proposal from a given JSON config file. Such a config file is a direct conversion from XML to JSON. This implies that some symbol attributes (e.g., [type](https://doc.opensuse.org/projects/autoyast/#id-1.9.5.2.10.8.7.4) from *drive* section) are converted to string (JSON does not support symbols).
The AutoYaST proposal code works fine with strings instead of symbols, for example for the fileystem type, encryption method, etc. Except for the `type` attribute, which must be a symbol.
Ensure the *type* attribute is a symbol when importing a hash. 
Required by https://github.com/openSUSE/agama/pull/1471.
> Fix drive section

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/storage_feature.rb
**This is for SLE-15-SP6.** A merge to SLE-15-SP7 and _master_ / _Factory_ will follow.
https://bugzilla.suse.com/show_bug.cgi?id=1187854
https://trello.com/c/N7gz5WP0
When determining what additional software packages are needed for a storage operation, e.g. in the expert partitioner, we still requested the old _exfat-utils_ instead of the newer _exfatprogs_.
This can be relevant if the user wants to format e.g. a USB stick with the ExFAT filesystem, and the support package for that filesystem is not yet installed.
Add _exfatprogs_ to the list of needed packages for the storage operations, not _exfat-utils_.
libstorage-ng has been using the binary from _exfatprogs_ for quite a while already. But the user had to make sure manually that this package was installed.
- Merge to SLE-15-SP7: …
> Use the newer exfatprogs instead of exfat-utils [SLE-15-SP6]

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/free_disk_space.rb
- src/lib/y2storage/partition.rb
- src/lib/y2storage/planned/assigned_space.rb
- src/lib/y2storage/planned/can_be_resized.rb
- src/lib/y2storage/planned/has_size.rb
- src/lib/y2storage/planned/partition.rb
- src/lib/y2storage/proposal/partition_creator.rb
- src/lib/y2storage/proposal/space_maker.rb
- src/lib/y2storage/proposal/space_maker_actions/bigger_resize_strategy.rb
- src/lib/y2storage/proposal/space_maker_actions/shrink.rb
- src/lib/y2storage/proposal_space_settings.rb
- src/lib/y2storage/space_actions.rb
- src/lib/y2storage/space_actions/base.rb
- src/lib/y2storage/space_actions/delete.rb
- src/lib/y2storage/space_actions/resize.rb
- test/y2storage/partition_test.rb
- test/y2storage/planned/assigned_space_test.rb
- test/y2storage/planned/can_be_resized_test.rb
- test/y2storage/planned/partition_test.rb
- test/y2storage/proposal/space_maker_bigger_resize_test.rb
- test/y2storage/proposal_agama_advanced_test.rb
- test/y2storage/proposal_agama_basis_test.rb
- test/y2storage/proposal_agama_reuse_test.rb
Agama allows to specify what to do with the existing partitions during installation in a quite flexible way. That includes deleting, deleting if needed or resizing (both shrinking and growing) within certain min and max sizes.
The initial support for that is implemented at https://github.com/openSUSE/agama/pull/1599
This pull request includes all the changes needed to make that implementation possible.
> Improvements to allow more flexible resize of partitions (needed by Agama)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/storage_feature.rb
**This the merge of #1389 into SLE-15-SP7.**
https://bugzilla.suse.com/show_bug.cgi?id=1187854
https://trello.com/c/N7gz5WP0
When determining what additional software packages are needed for a storage operation, e.g. in the expert partitioner, we still requested the old _exfat-utils_ instead of the newer _exfatprogs_.
This can be relevant if the user wants to format e.g. a USB stick with the ExFAT filesystem, and the support package for that filesystem is not yet installed.
Add _exfatprogs_ to the list of needed packages for the storage operations, not _exfat-utils_.
libstorage-ng has been using the binary from _exfatprogs_ for quite a while already. But the user had to make sure manually that this package was installed.
-Original PR for SLE-15-SP6: #1389 
- Merge to _master_ / _Factory_: …
> Use the newer exfatprogs instead of exfat-utils [SLE-15-SP7]

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/storage_feature.rb
**This the merge of #1389 / #1390 into _master_ / _Factory_.**
https://bugzilla.suse.com/show_bug.cgi?id=1187854
https://trello.com/c/N7gz5WP0
When determining what additional software packages are needed for a storage operation, e.g. in the expert partitioner, we still requested the old _exfat-utils_ instead of the newer _exfatprogs_.
This can be relevant if the user wants to format e.g. a USB stick with the ExFAT filesystem, and the support package for that filesystem is not yet installed.
Add _exfatprogs_ to the list of needed packages for the storage operations, not _exfat-utils_.
libstorage-ng has been using the binary from _exfatprogs_ for quite a while already. But the user had to make sure manually that this package was installed.
- Original PR for SLE-15-SP6: #1389 
- Merge to …
> Use the newer exfatprogs instead of exfat-utils [master]

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/can_be_encrypted.rb
- src/lib/y2storage/planned/lvm_vg.rb
- src/lib/y2storage/proposal/autoinst_partitioner.rb
- src/lib/y2storage/proposal/devicegraph_generator.rb
- src/lib/y2storage/proposal/lvm_helper.rb
- src/lib/y2storage/proposal/partitions_distribution_calculator.rb
- src/lib/y2storage/proposal/phys_vol_calculator.rb
- src/lib/y2storage/proposal/resize_phys_vol_calculator.rb
- src/lib/y2storage/proposal/space_maker.rb
- src/lib/y2storage/proposal/space_maker_actions/auto_strategy.rb
- src/lib/y2storage/proposal/space_maker_actions/list.rb
- src/lib/y2storage/proposal/space_maker_prospects/list.rb
- test/y2storage/proposal/partitions_distribution_calculator_test.rb
- test/y2storage/proposal/space_maker_bigger_resize_test.rb
- test/y2storage/proposal/space_maker_lvm_test.rb
- test/y2storage/proposal/space_maker_test.rb
We want to offer new possibilities with the so-called AgamaProposal (that will be used to implement all the features described at [this document](https://github.com/agama-project/agama/blob/master/doc/auto_storage.md).
For that we need a more powerful SpaceMaker that can automatically calculate physical volumes for an arbitrary number of LVM volume groups extended over different sets of disks.
This pull request generalizes the existing SpaceMaker to gain that capability and to be less coupled with the traditional YaST GuidedProposal.
Original API
```ruby
class Y2Storage::Proposal::SpaceMaker
def initialize(disk_analyzer, settings); end
def provide_space(original_graph, planned_partitions, lvm_helper); end
def prepare_devicegraph(original_graph, planned_partitions = []); end
end
```
New …
> Changes to allow automatic generation of LVM PVs at the AgamaProposal

- doc/boot-partition.md
/boot/zipl/active_devices.txt won't be updated anymore by *_configure tools after applying patches from bsc#1216257
*Short description of the original problem.*
- *Bugzilla link*
- *openQA link*
- *Links to other related pull requests*
*Short description of the fix.*
*If the fix affects the UI attach some screenshots here.*
> Doc: remove incorrect documentation about /boot/zipl/active_devices.txt

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- test/y2partitioner/widgets/pages/disks_test.rb
There is a wrong test in which no value was passed to the `#include` matcher. This raises an error with *rspec-expectations 3.13.2*.
https://github.com/rspec/rspec-expectations/blob/838952dc1416c943e7933684c47249a77481e7f5/Changelog.md
3.13.2 / 2024-08-20
Bug Fixes:
Raise an error when passing no arguments to the include matcher. (Eric Mueller, #1479)
Fix tests by using correct data and passing a value to `#include`.
- Updated unit test.
> Fix bsc#1233095

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/inst_prepdisk.rb
In agama where is systemd root is mounted as sharable and it affects also default for nested mounts. Result is that default mount bind is also sharable. As consequence systemd credentials creates under /run its own mount point when user login and this mount point is as long busy as long user is logged in. Result is that /mnt cannot be clearly unmounted.
trello card: https://trello.com/c/4YxqRmZF/3944-3-agama-could-not-umount-mnt-run-after-the-installation-systemd-creds
lwn article about topic: https://lwn.net/Articles/689856/
Make mount --bind explcitely private to avoid propagation of mount points.
> explicitelly mount /mnt/run as private to avoid mount point propagations

- package/yast2-storage-ng.changes
Convert timestamp to UTC
to make parsing unambiguous.
Without this change, osc build mis-parsed this as another date
which breaks reproducible builds
> Convert timestamp to UTC

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
https://bugzilla.suse.com/show_bug.cgi?id=1235598
Package or dist upgrades may lead to confusion what Ruby version to use and break YaST.
Require bindings for the current Ruby version
> Require libstorage bindings for the current Ruby version (bsc#1235598)

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2partitioner/actions/controllers/encryption.rb
- src/lib/y2storage/autoinst_profile/partition_section.rb
- src/lib/y2storage/planned/can_be_encrypted.rb
- src/lib/y2storage/proposal/autoinst_drive_planner.rb
- test/y2storage/autoinst_proposal_encryption_test.rb
Recently was added support for PAES-encrypted volumes but only selecting the apqns and key type to be used manually.  Therefore, would be nice to be able to select the apqns and key type through the AutoYaST profile.
- https://trello.com/c/Ffc1JCwe
Added AutoYaST support for selecting in the profile the APQNs and the pervasive encryption key type to be used.
- Added unit test
> AutoYaST part of pervasive encryption

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/manual_test.rb
- src/lib/y2storage/device.rb
- src/lib/y2storage/device_finder.rb
- src/lib/y2storage/storage_env.rb
- src/lib/y2storage/storage_manager.rb
- test/y2storage/clients/manual_test_test.rb
- test/y2storage/device_test.rb
- test/y2storage/storage_env_test.rb
- test/y2storage/storage_manager_test.rb
To ease development of Agama, it would be really useful to have a way to fake the storage setup using a devicegraph stored in a file.
Introduce two new environment variables that will be honored by yast-storage-ng:
- YAST_TEST_MODE limits the access to the system. YaST will create a test libstorage-ng instance instead of real one and will not try to read information from the system when asked for resize information or when searching a device.
- YAST_DEVICEGRAPH_FILE allows to specify a mocked devicegraph.
- Tested manually during Agama development
- Unit tests adapted and expanded
> Add env variables to enforce test mode

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/clients/finish.rb
- src/lib/y2storage/resize_info.rb
- src/lib/y2storage/storage_manager.rb
- test/y2storage/clients/finish_test.rb
- test/y2storage/storage_manager_test.rb
It was decided that lvm2 should use system/devices feature by default in all (open)SUSE distributions (openSUSE Tumbleweed, SLES 16 and Leap 16).
Libstorage-ng was already adapted to handle that, but some adaptations were still missing in the installer.
- https://jira.suse.com/browse/PED-7355
- https://jira.suse.com/browse/PED-12241
- Ensure libstorage-ng generates the corresponding files if it considers they are missing.
- Copy the files to the target system at the end of installation.
- Tested manually at Tumbleweed (YaST) :heavy_check_mark: 
- Tested manually at SLES 16 (Agama) :heavy_check_mark: 
- Added unit tests
[This change](https://github.com/openSUSE/libstorage-ng/pull/1022) that was very recently introduced at libstorage-ng and needed the corresponding adaptation at YaST (we …
> Manage /etc/lvm/devices

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/disk_analyzer.rb
Agama needs to check whether a device (drive or MD RAID) can be used as candidate for installation, but the method is private.
Needed for https://github.com/agama-project/agama/pull/2338.
Make `DiskAnalyzer#candidate_device?` public.
> Make #candidate_device? public

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/disk_analyzer.rb
Agama needs to check whether a software RAID can be used as candidate for installation according to the current YaST heuristics, but the method is private.
Needed for https://github.com/agama-project/agama/pull/2388
Extract some logic to a new `DiskAnalyzer#candidate_software_raid?` public method.
> New public function to check whether a software RAID is candidate for installation

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/disk.rb
- test/y2storage/mount_point_test.rb
- test/y2storage/proposal_mount_options_test.rb
The name of the iSCSI driver is wrong, which makes the method `#systemd_remote?` to wrongly report false for an iSCSI device. As side effect, the _netdev option is never added.
Related to https://bugzilla.suse.com/show_bug.cgi?id=1244935. 
Use correct driver name.
> Fix iSCSI driver name

- package/yast2-storage-ng.changes
- package/yast2-storage-ng.spec
- src/lib/y2storage/planned/can_be_encrypted.rb
- test/y2storage/planned/can_be_encrypted_test.rb
- test/y2storage/proposal/autoinst_devices_creator_test.rb
Agama fails to calculate a storage proposal if the configuration specifies that a disk that initially contained partitions must be directly encrypted and formatted as a whole.
Do doubt pre-existing partitions should be destroyed as part of the process, but Agama struggles with that.
The problem does not happen if the disk is formatted but not encrypted.
Handle the situation in `CanBeEncrypted` in the same what that it was already handled at `CanBeFormatted`. That is, removing descendants of the devicegraph before proceeding.
- Tested manually in an Agama instance
> Prevent failure when encrypting a partitionable (bsc#1246970)
